### ISSUE TITLE
Potential bug in the Splitting Rules and Request for a related hyperparameter

### ISSUE THREAD

**Issue by DPanknin** [grf-labs/grf#1002]
Dear developers,

in RegressionSplittingRule.cpp (and probably some other files) you indirectly calculate the splitting objective in terms of the variable "decrease", which should be positive whenever the split leads to a reduced objective. Accordingly, you stop splitting, when best_decrease <= 0.

For now let us assume (imbalance_penalty = 0.) to simplify my argument.
In the calculation of the decrease it says:

double decrease = sum_left * sum_left / weight_sum_left + sum_right * sum_right / weight_sum_right;

which is always > 0 (as long as there is any variation in the labels-which is common especially in the case of regression).
And so, your procedure splits, until some other boundary condition (such as too small number of samples in the leaf) are violated.

My suggestion is that the line should instead read:

double decrease = - sum_node * sum_node / weight_sum_node + sum_left * sum_left / weight_sum_left + sum_right * sum_right / weight_sum_right;

Now, basically the difference seems marginal, i.e., since the additional term is a constant at that point. However I came across this when playing around with a positive convergence threshold, call it "splittingThreshold" for now:
It is meant to stop the splitting procedure in a node, whenever
(best_decrease <= splittingThreshold), where (splittingThreshold >= 0).

The idea behind it is (again from regression) that a decreasing training error does not necessarily imply a decreasing generalization error. And so I would like to ask, whether you would consider to add "splittingThreshold" with whatever name (and default value (splittingThreshold = 0.0) to your library.

Thank you,
Danny

**Comment by erikcs** [comment]
Thank you for the suggestion @DPanknin. As you say, the effective stopping criteria is min_node_size or variants of that, the reason for not stopping when the leaf is pure (all Y the same) is mentioned briefly in #415 - i.e. it is optimizing for an unintended use case (zero overlap). On "generalization error", one way GRF addresses this is with "honest subsampling" as described in https://arxiv.org/pdf/1510.04342.pdf

For a derivation of the CART splitting rule used in GRF you can have a look here: https://grf-labs.github.io/grf/DEVELOPING.html#tree-splitting-algorithm. The role of the "imbalance" parameters are briefly discussed here https://grf-labs.github.io/grf/REFERENCE.html#selecting-balanced-splits. Please let us know if there's anything you find unclear.

**Comment by erikcs** [comment]
Closing for now due to lack of activity.

Please feel free to open if you have more suggestions, or if you would like to share some benchmarks (there are some examples in the experiments\ folder).
