### ISSUE TITLE
Large inconsistency between grf and other models

### ISSUE THREAD

**Issue by formulah** [grf-labs/grf#1003]
I have a RCT data set with about 10,000+ observations and 50+ covariates, and I am trying to estimate the ATE and compare the estimates from a couple of models. The models I use are:

1. GRF (using the average_treatment_effect function)
2. Propensity score matching, in which I estimate the propensity score function of being treated and match each control unit with the closest treated unit (using the Matchit R package)
3. Linear model in which the covariates are control variables

However, the point estimates are very different: GRF gives 0.010 with a standard error of 0.021; propensity score matching gives 0.224 with a standard error of 0.051; the linear model gives 0.136 with a standard error of 0.036. From my past experience, this inconsistency seems unusual - different methods often yields quite consistent estimates, but it is not the case here. 

In general, why would there be huge differences between those estimates?

**Comment by erikcs** [comment]
Hi @formulah, those methods will not necessarily give the same result. If (3) is misspecified, it will be different from (1), see https://github.com/grf-labs/grf/issues/619#issuecomment-588346718 for an example.

**Comment by erikcs** [comment]
(and the reasoning is the same for (2) - the model for the propensity score might be misspecified, the binary W example at the end of #619 would not be estimated well with a logistic regression)
