### ISSUE TITLE
grf 2.0 Cython compatibility

### ISSUE THREAD

**Issue by crflynn** [grf-labs/grf#1004]
Hey @erikcs . Thanks for pointing out the 2.0 release with changes. I've begun updating skgrf and for the most part it has been pretty straightforward. The updates to the Data class have been beneficial (I'm now able to run without using a special C++ wrapper for numpy), and the changes have been minimal with respect to the bindings interface. There is one small issue that is preventing me from upgrading:

You can see from this [CI run](https://github.com/crflynn/skgrf/pull/61/checks?check_run_id=2948984358) that Cython fails to compile the python extension because of a variable name collision in the grf namespace in two of the strategy files. I believe this is because Cython requires includes of cpp files in addition to headers for C++ extensions, whereas internally here I think you would only include header files. When I change the name of one of these variables locally, it compiles fine, and all of the tests pass.

Here is the Cython compilation output indicating the error.
```
      In file included from skgrf/grf.cpp:949:
      skgrf/./grf/src/prediction/InstrumentalPredictionStrategy.cpp:35:19: error: redefinition of ‘const size_t grf::NUM_TYPES’
         35 | const std::size_t NUM_TYPES = 7;
            |                   ^~~~~~~~~
      In file included from skgrf/grf.cpp:943:
      skgrf/./grf/src/prediction/CausalSurvivalPredictionStrategy.cpp:30:19: note: ‘const size_t grf::NUM_TYPES’ previously defined here
         30 | const std::size_t NUM_TYPES = 2;
            |                   ^~~~~~~~~
      error: command 'gcc' failed with exit status 1
```

Now, I'm not a Cython or C++ expert, but I've tried various things like excluding cpp files from cython extension includes, but I don't think it's possible to build an extension without them. If it's not too much trouble I'd like to request modifying these variable names, and making a patch release. This should enable compilation using Cython.

**Comment by erikcs** [comment]
Thanks @crflynn - that is a very old typo! You are right, those two should be class member variables instead. My Cython is a bit rusty, but I made a comment in https://github.com/crflynn/skgrf/pull/61 wondering if it is still possible to make it work, getting them compiled as separate translation units as the R extension does, which shouldn't give a name collision.

**Comment by crflynn** [comment]
The suggested workaround seems to work. I'll leave this open in case you intend to address the naming issue. Thanks!

**Comment by erikcs** [comment]
Yes, thanks, we will rename them (just letting the 2.0.0 release linger for a while first).
