### ISSUE TITLE
The parameter min.node.size of causal_forest does not perform as expected,am I using it in the wrong way?

### ISSUE THREAD

**Issue by liuweie** [grf-labs/grf#1005]
**Description of the question**
    The  GRF reference  mentions that set the parameter min.node.size to a number(for example 10)  when grow a causal forest, a node will contain at least min.node.size treated samples, and also at least that many control samples. Here is the link: https://grf-labs.github.io/grf/REFERENCE.html#selecting-balanced-splits
    However, when I practice, I found that the avg_W value of some leaf nodes is 0 （W is a binary variable, which can only take 0 or 1）, which means that the samples of this leaf node are all control samples。In this way, the treatment effect of the leaf node cannot be calculated。
    I really hope someone can help me solve this problem.Am I use it in the wrong way ? I have been stuck in this problem for two days。Thanks

**GRF version**
2.0.0

**Comment by erikcs** [comment]
Hi @liuweie, GRF uses honest subsampling (https://grf-labs.github.io/grf/REFERENCE.html#honesty-honestyfraction-honestypruneleaves) by default, meaning that the separate "estimation leaf" might in fact contain zero treated samples.

**Comment by liuweie** [comment]
> Hi @liuweie, GRF uses honest subsampling (https://grf-labs.github.io/grf/REFERENCE.html#honesty-honestyfraction-honestypruneleaves) by default, meaning that the separate "estimation leaf" might in fact contain zero treated samples.

Got it ! Thanks very much!
