### ISSUE TITLE
Inaccurate calculation of avg_Y and avg_W found in causal_survival_forest()

### ISSUE THREAD

**Issue by yingwu2017** [grf-labs/grf#1010]
**Description of the bug**
I'm using the ACTG175 data to fit a causal survival forest as the paper [https://arxiv.org/abs/2001.09887](url) did in the HIV data analysis part. I obtain a forest and  plot the first tree in the forest:
![t1](https://user-images.githubusercontent.com/29743463/125602490-c98bda67-a188-4237-905b-d985f11413d0.png)

According to the printout, the average Y and average W of the leaf node is 859.65 and 0.53 respectively. However, when I extract the leaf samples of this node and compute the average Y and average W on my own, I found my results are quite different:
![微信图片_202107141748441](https://user-images.githubusercontent.com/29743463/125602549-b95948dc-98d3-499e-bf58-023e0d88fd56.png)

I also calculate both values on the estimation samples and get this:
![微信图片_202107141748442](https://user-images.githubusercontent.com/29743463/125602585-946c0a4c-fa91-4c41-bc5b-128856decb5f.png)

None of these results are in line with the values given in the first printout.
 I do not know if I misunderstand the outputs of the tree or there is indeed something wrong with the code? Actually, I also found a similar issue in the trained forest given in the examples at [https://grf-labs.github.io/grf/reference/causal_forest.html](url) 

**Steps to reproduce**
```
# load package and data
library('survival')
library(grf)
library(dplyr)
data(ACTG175)

# reconstruct and recode the data
actg <- ACTG175[ACTG175$arms %in% c(1,3), ] # pick data from arm1 and arm3
actg$treat <- as.integer(actg$arms==1) # recode treatment and control
# recode survival time and censoring indicator
actg$cens= as.integer(actg$days>1000) 
actg[actg$days>1000,'days'] <- 1000

# use the following 12 vars to fit the forest
vars <- c('age','wtkg','karnof','cd40',"cd80","gender","homo","race","symptom","hemo","drugs",'str2')

# calculate the mtry parameter
p <- length(vars)
ceil <- sqrt(p)+20 %>% ceiling()
mtry <- min(p,ceil)

# fit the forest
cs.forest <- causal_forest(X=actg[vars],Y = actg$days, 
              W = actg$treat, D = actg$cens,
              min.node.size = 15, mtry = mtry,num.trees = 2000, seed = 2021)
# output the average Y and W of that leaf node.
t1 <- get_tree(cs.forest,1);t1 

# extract the entire samples and the leaf samples used for t1
total.samples <- t1$drawn_samples
leaf.samples <- cs.forest$`_leaf_samples`[[1]]
est.smaples <- set.diff(total.samples, leaf.samples)

# calculate the leaf average of Y and W  
actg$days[leaf.samples] %>% mean()
actg$treat[leaf.samples]%>% mean()

# calculate the averages on the estimation samples
actg$days[est.samples] %>% mean()
actg$treat[est.samples]%>% mean()
```

**GRF version**
2.0.0

**Comment by erikcs** [comment]
Hi @yingwu2017, sorry, I think I am misunderstanding your example:`causal_survival_forest` doesn't plot any leaf info except node size, do you mean `causal_forest`:

```
cs.forest <- causal_forest(X=actg[vars],Y = actg$days, 
                           W = actg$treat,
                           min.node.size = 15, mtry = mtry,num.trees = 2000, seed = 2021)
t1 <- get_tree(cs.forest,1)
mean(cs.forest$W.orig[t1$nodes[[2]]$samples])
mean(cs.forest$Y.orig[t1$nodes[[2]]$samples])
plot(t1)
```
(anything prefixed with `_` in the forest object signifies an internal data structure that may not behave as expected)

**Comment by yingwu2017** [comment]
Hi,@ .

**Comment by yingwu2017** [comment]
Hi, @erikcs, thanks for your quick reply! Yes, I intended to use causal_forest( ). Please forgive my carelessness. I think I now see why my calculation of the avg_Y and avg_W (of a given leaf node) is different from yours. I expect the following codes to yield exactly the same leaf samples for leaf node 2, first tree of cs.forest, however, they do not:
```
# my way to extract the leaf samples
cs.forest$`_leaf_samples`[[1]][[2]]  
# your way to extract the leaf samples
t1$nodes[[2]]$samples
```
So if the second code yields the true leaf samples, what about the first code? I'm confused.

**Comment by erikcs** [comment]
```cs.forest$`_leaf_samples`[[1]][[2]]``` stores samples in 0-indexed C++, it may also not necessarily give samples corresponding to that node index because of pruning (see the argument `honesty.prune.leaves`), so it is not a right or robust way to get any information.

On a related note, there is a utility function for getting node membership from a test set `X` here: https://grf-labs.github.io/grf/reference/get_leaf_node.html

**Comment by yingwu2017** [comment]
Ok, I got it. Thanks a lot!
