### ISSUE TITLE
test_calibration referred as using held out data when using in-sample data

### ISSUE THREAD

**Issue by MichaelLLi** [grf-labs/grf#1019]
**Description of the bug**

The description and summary of the test_calibration function in grf says that it utilizes best linear fit using forest predictions on **held-out** data.  However, looking at the source code, the regression runs with the target Y as (forest$Y.orig - forest$Y.hat), which is the full original data that was utilized to train the causal forest in the first place, which would mean it is in-sample testing. Am I mis-interpreting the meaning of held-out data here?

**Steps to reproduce**

Running test_calibration() on any trained causal forest. 

**GRF version**

2.0.1

**Comment by erikcs** [comment]
Hi, the predictions from [predict(forest, newdata=NULL)](https://grf-labs.github.io/grf/reference/predict.causal_forest.html) are out of bag, which is what `using the forest prediction (on held-out data)` refers to here.

**Comment by MichaelLLi** [comment]
I see, thank you!
