### ISSUE TITLE
Doubly-robust scores for multi_arm_causal_forest is incorrect

### ISSUE THREAD

**Issue by halflearned** [grf-labs/grf#1020]
@erikcs and I found the following error in  `get_scores.multi_arm_causal_forest`.

The expression for the IPW denominator, computed [here](https://github.com/grf-labs/grf/blob/6eb10e8c5404f6f010c4329d4f7b93ed8b5dc070/r-package/grf/R/get_scores.R#L259) is only valid for the case of two arms, and incorrect for the case of multiple arms. This [gist](https://gist.github.com/halflearned/f481693b4583d823830509f198b5261a) shows that the error affects the coverage of estimates based on this method.

I ran additional simulations and it seems that the implementation of `policytree::double_robust_scores` is correct. A correct version of this method should satisfy:

```{r}
mgrf <- multi_armed_causal_forest(X, Y, W)
pt.scores <- policytree::double_roubust_scores(mgrf)  # AIPW scores for E[Y(w)] for w = 1, ... K
mgrf.scores <- get_scores(mgrf). # AIPW scores for E[Y(w)] - E[Y(1)] for w = 2, ..., K
pt.scores[,-1] - pt.scores[,1] == mgrf.scores 
```

**Comment by erikcs** [comment]
This is fixed in #1021. Leaving this issue open until the next CRAN release.
