### ISSUE TITLE
Treatment propensities take values very close to 0 or 1

### ISSUE THREAD

**Issue by lpereirasantos** [grf-labs/grf#1024]
Hi,

I'm using the  multi_arm_causal_forest function, and I'm havind the bug:

"Estimated treatment propensities take values very close to 0 or 1 meaning some estimates may not be well identified."

Could you indicate some literature or some way to deal with this problem?

I'm using a database with 800k observations and close to 300k it has a propensity below 0.5 or above 0.95.

Thaks

**Comment by halflearned** [comment]
Hi @lpereirasantos, that's not a bug. 

It means that, for some covariate values, your data falls overwhelmingly in the treatment group (propensities close to 1) or  in the control group (propensities close to 0). This prevents you from being able to accurately estimate causal effects. Consider, for example, an experiment in which all treated observations are old, and all control observations are young. In that case, you can't compare young-treated to young-control or old-treated to old-control, and therefore you can't disentangle the effect of age from the effect of the treatment.

As the warning says, you probably need to change your estimand. See [Crump, Richard K., V. Joseph Hotz, Guido W. Imbens, and Oscar A. Mitnik. 2009](https://dash.harvard.edu/bitstream/handle/1/3007645/imbens_addressing.pdf;jsessionid=DCC62F5E158B7F64B1271E8A921D31EE?sequence=2) for some alternatives.

**Comment by lpereirasantos** [comment]
Thanks a lot!

Em qui., 29 de jul. de 2021 às 00:03, Vitor Hadad ***@***.***>
escreveu:

**Comment by lpereirasantos** [comment]
Dear Grf-Labs/Grf,
Dear Vitor,

I know this is not a bug, but rather statistical issues.
I would still like to know your opinion:

When I use the average_treatment_effect function, if I just subsample
observations that have a propensity score in a certain range ([0.05; 0.05],
for example), is this an acceptable procedure from an estimation point of
view?

Thanks again!

Em qui., 29 de jul. de 2021 às 09:45, Leandro Pereira dos Santos <
***@***.***> escreveu:

**Comment by swager** [comment]
Yes -- it's a reasonable approach (although you won't be targeting the ATE anymore). One paper that discusses this approach and its implications is the following:

Crump, R. K., Hotz, V. J., Imbens, G. W., & Mitnik, O. A. (2009). Dealing with limited overlap in estimation of average treatment effects. Biometrika, 96(1), 187-199.

**Comment by lpereirasantos** [comment]
Thanks a lot!

Em qui., 29 de jul. de 2021 às 15:21, Stefan Wager ***@***.***>
escreveu:
