### ISSUE TITLE
Recommendations for quantile regression?

### ISSUE THREAD

**Issue by kochbj** [grf-labs/grf#1028]
Hi all,

Thanks for such a great tool. I have a really naive question. Do you guys have any recommended practices or metrics for evaluating the fit of a quantile forest? I can't find a lot online.

EDIT: Some follow up questions. Why is there no support for tuning or variance estimates of quantile forests? Which of the nine R implementations is equivalent to the transform done by GRF?

Thanks again for your time,
B

**Comment by erikcs** [comment]
Hi @kochbj, one way could be using the quantile scoring function psi from section 5 in https://arxiv.org/pdf/1610.01271.pdf, but @swager and @jtibshirani may have other suggestions.

Currently not all forest have every single feature implemented. causal/instrumental/quantile are GRFs.
