### ISSUE TITLE
Variable_importance() function in GRF

### ISSUE THREAD

**Issue by njawadekar** [grf-labs/grf#1030]
Hello,
I am writing because I am trying to better understand how the **variable_importance()** function works behind the scenes in the GRF package (Version 2.0.2). I am particularly interested in using this function on a causal_forest object in order to determine the covariates that were most important for the "heterogeneities of treatment effects" that exist within a sample.

Generally speaking, I understand that "variable importance factor" in random forests can be computed in a variety of ways, and that one common way (particularly in a typical random forest for prediction) is through calculating, for each covariate, the average node impurity decrease across each of the times that covariate was used to split data in any of the trees in the forest, weighted by the proportion of the trees that utilized that covariate. This is known as "Mean Decrease Impurity importance (MDI)". And then, whichever variable had the highest weighted-average decrease in node impurity across each of its splits would receive the highest variable importance factor value in the output.

My questions related to this are:

(1) How exactly is variable_importance in GRF calculated when it is run on a causal_forest object, and what is the rationale behind it? Based on the available [documentation](https://cran.r-project.org/web/packages/grf/grf.pdf), it seems that the **variable_importance** function doesn't capture something like a weighted "mean increase in heterogeneity," and instead it only seems to sum the number of times each particular covariate was used for a split, before applying some kind of weight to it - is that correct?

(2) What exactly is this weight (described in # 1)? In other words, does it similarly weight by the proportion of trees that utilized that covariate in at least one of its splits?

(3) If the variable_importance() function in GRF indeed doesn't exactly capture each covariate's average mean increase in heterogeneities across each of its splits (with increase in heterogeneity defined within criterion specified in [Athey & Imbens 2016](https://www.pnas.org/content/113/27/7353)), is there any alternative function in GRF that would allow me to calculate this type of variable importance function?

Thank you in advance!

**Comment by erikcs** [comment]
Hi @njawadekar. 

1) Yes, it is a simple weighted sum of how many times feature i was split on at each depth in the forest. 
2) It's the [decay.exponent](https://grf-labs.github.io/grf/reference/variable_importance.html) argument, used to weight the simple  [split_frequencies](https://grf-labs.github.io/grf/reference/split_frequencies.html)
3) The criterion for splitting Xj's in a causal forest is (20) in https://arxiv.org/pdf/1610.01271.pdf
