### ISSUE TITLE
bug? average_treatment_effect seed not working for continuous treatments

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#1032]
**Description of the bug**
It seems that the `seed` argument in the `causal_forest` function does not work if the treatment is continuous. See the reproduced example below:

**Steps to reproduce**
```
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rnorm(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
c.forest <- causal_forest(X, Y, W, seed=2)
```

```
> average_treatment_effect(c.forest)
 estimate   std.err 
0.5332316 0.1056678 
> average_treatment_effect(c.forest)
 estimate   std.err 
0.5392227 0.1065802 
> average_treatment_effect(c.forest)
 estimate   std.err 
0.5315766 0.1066203 
```
The results is different every time I call the average_treatment_effect function, despite of the fact that the `seed` argument is set.  I have tried and it seems that the problem fades away if the treatment is binary.

**GRF version**
`2.0.0` or `2.0.2`

**Comment by erikcs** [comment]
Hi @ginward, 

from [average_treatment_effect](https://grf-labs.github.io/grf/reference/average_treatment_effect.html) on continuous W:
>Computing the average partial effect is somewhat more involved, as the relevant doubly robust scores require an estimate of Var[Wi | Xi = x]. By default, we get such estimates by training an auxiliary forest; however, these weights can also be passed manually by specifying debiasing.weights.

You can supply `debiasing.weights` or use R's `set.seed` before:

```R
library(grf)
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rnorm(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
c.forest <- causal_forest(X, Y, W, seed=2)


variance_forest <- regression_forest(X, (W - c.forest$W.hat)^2,
                                     num.trees = 500)
V.hat <- predict(variance_forest)$predictions
debiasing.weights <- (W - c.forest$W.hat) / V.hat
average_treatment_effect(c.forest, debiasing.weights = debiasing.weights)
# estimate   std.err 
# 0.4123974 0.1179730

set.seed(1)
average_treatment_effect(c.forest)
# estimate   std.err 
# 0.4133290 0.1150927 
set.seed(1)
average_treatment_effect(c.forest)
# estimate   std.err 
# 0.4133290 0.1150927 
```

**Comment by ginward** [comment]
I see. Is it possible to add the seed argument to the auxiliary forest training?

**Comment by ginward** [comment]
> Hi @ginward,
> 
> from [average_treatment_effect](https://grf-labs.github.io/grf/reference/average_treatment_effect.html) on continuous W:
> 
> > Computing the average partial effect is somewhat more involved, as the relevant doubly robust scores require an estimate of Var[Wi | Xi = x]. By default, we get such estimates by training an auxiliary forest; however, these weights can also be passed manually by specifying debiasing.weights.
> 
> You can supply `debiasing.weights` or use R's `set.seed` before:
> 
> ```r
> library(grf)
> n <- 500
> p <- 10
> X <- matrix(rnorm(n * p), n, p)
> W <- rnorm(n, 1, 0.5)
> Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
> c.forest <- causal_forest(X, Y, W, seed=2)
> 
> 
> variance_forest <- regression_forest(X, (W - c.forest$W.hat)^2,
>                                      num.trees = 500)
> V.hat <- predict(variance_forest)$predictions
> debiasing.weights <- (W - c.forest$W.hat) / V.hat
> average_treatment_effect(c.forest, debiasing.weights = debiasing.weights)
> # estimate   std.err 
> # 0.4123974 0.1179730
> 
> set.seed(1)
> average_treatment_effect(c.forest)
> # estimate   std.err 
> # 0.4133290 0.1150927 
> set.seed(1)
> average_treatment_effect(c.forest)
> # estimate   std.err 
> # 0.4133290 0.1150927 
> ```

Do I have to call set.seed every time before calling average_treatment_effect then?

**Comment by erikcs** [comment]
Yes, that is the same behavior average_partial_effect/best_linear_projection has had for several versions now.  `debasing.weights` except for `seed` was from https://github.com/grf-labs/grf/pull/615#discussion_r380324198, but if there is user interest, another way could be to for example store the original forest training seed and use that in the variance_forest (@grf-labs).

**Comment by erikcs** [comment]
Closing this for now, unless @ginward and/or anyone in @grf-labs feels very strongly about implementing a different workaround

**Comment by erikcs** [comment]
This is changed in #1070, thanks for reporting @ginward
