### ISSUE TITLE
The COVARIATES in causal_forest function must be renamed as integers? 

### ISSUE THREAD

**Issue by sudonghua91** [grf-labs/grf#1042]
Hello,

Can I ask one question here? 

When we input causal_forest, do we have to rename the X variables (i.e. covariates) to be **integers**? That is, the X variables are called 1,2,3,...rather than the original names such as female, grade, age, education...?  That is a concern for me and I wish someone can give me a hand. Thanks!

**Comment by erikcs** [comment]
Hi @sudonghua91, the colnames of X can be any valid R name, integer or string.

**Comment by sudonghua91** [comment]
@erikcs  Thanks, Erik.
