### ISSUE TITLE
The difference between continuous treatment and binary treatment.

### ISSUE THREAD

**Issue by yang9198** [grf-labs/grf#1043]
What's the difference between the meaning of tau(x) obtained by continuous treatment and binary treatment? Is there any literature related to continuous treatment?

**Comment by erikcs** [comment]
Hi @yang9198,

https://grf-labs.github.io/grf/reference/average_treatment_effect.html:
> In the case of a causal forest with continuous treatment, we provide estimates of the average partial effect, i.e., E[Cov[W, Y | X] / Var[W | X]].

Continuous treatment effects in the potential outcome framework are discussed in https://www.math.mcgill.ca/dstephens/PSMMA/Articles/HIrano-Imbens-2004.pdf. 

Newer ML papers on continuous treatment effects are for example @klosins's https://arxiv.org/abs/2104.10334, or https://arxiv.org/pdf/2004.03036.pdf

**Comment by yang9198** [comment]
> Hi @yang9198,
> 
> https://grf-labs.github.io/grf/reference/average_treatment_effect.html:
> 
> > In the case of a causal forest with continuous treatment, we provide estimates of the average partial effect, i.e., E[Cov[W, Y | X] / Var[W | X]].
> 
> Continuous treatment effects in the potential outcome framework are discussed in https://www.math.mcgill.ca/dstephens/PSMMA/Articles/HIrano-Imbens-2004.pdf.
> 
> Newer ML papers on continuous treatment effects are for example @klosins's https://arxiv.org/abs/2104.10334, or https://arxiv.org/pdf/2004.03036.pdf

Is there a detailed derivation process of average partial effect (E[Cov[W, Y | X] / Var[W | X]]) in generalized random forest?

**Comment by erikcs** [comment]
See \hat \beta_1 in https://en.wikipedia.org/wiki/Regression_analysis

**Comment by yang9198** [comment]
> See \hat \beta_1 in https://en.wikipedia.org/wiki/Regression_analysis

So, the average partial effect estimated in grf is based on a partial linear model (Y=\theta T+g(X)+\varepsilon)，i.e., it is assumed that Y is linearly related to the continuous treatment variable T? 
There is a formal inference theory for the fully nonparametric causal effects of continuous variables in https://arxiv.org/pdf/2004.03036.pdf. Is there any corresponding code in grf that can be implemented?

**Comment by erikcs** [comment]
Yes, however the \theta coefficient is x-specific, i.e GRF is an algorithm to find forest weights that solves that partially linear model in a neighborhood where ideally the X's are "similar" (in the sense that their coefficient estimates are similar): see section 6 in https://arxiv.org/pdf/1610.01271.pdf (note the 6.1.1 paragraph on local centering: this is the default option in causal_forest, also known as the "R-learner" here https://arxiv.org/pdf/1712.04912.pdf).

**Comment by yang9198** [comment]
> Yes, however the \theta coefficient is x-specific, i.e GRF is an algorithm to find forest weights that solves that partially linear model in a neighborhood where ideally the X's are "similar" (in the sense that their coefficient estimates are similar): see section 6 in https://arxiv.org/pdf/1610.01271.pdf (note the 6.1.1 paragraph on local centering: this is the default option in causal_forest, also known as the "R-learner" here https://arxiv.org/pdf/1712.04912.pdf).

Why GRF can be used to estimate \beta_{t} \equiv \mathbb{E}[Y(t)]=\iint g(t, X, \varepsilon) d F_{X \varepsilon} and \theta_{t} \equiv \partial \beta_{t} / \partial t_{1} (define the partial (or marginal) effect of the first component of the continuous treatment T at t=\left(t_{1}, \ldots t_{d_{t}}\right)^{\prime} to be the partial derivative \theta_{t} \equiv \partial \beta_{t} / \partial t_{1}) in https://arxiv.org/pdf/2004.03036.pdf? 
The potential outcome here is a nonparametric nonseparable model: Y=g(T, X, \varepsilon), while is a partially linear model: Y=\theta T+g(X)+\varepsilon in GRF.
