### ISSUE TITLE
Where is psi(.)?

### ISSUE THREAD

**Issue by federiconuta** [grf-labs/grf#1044]
Hi all,

my question is more about the interpretation of grf. In particular I am curious on how I can recover the psi(.) form that is described in the paper on grf through the R code. Usually, I would say E[Y|X]=b0(X)*W_i+b1*X is a quite general form for linear scenarios in which we are interested in estimating b0(X). But as far as I have understood from the paper, E[Y|X] can assume a quite general form, psi(.). Should I decide psi(.) in advance before doing:

`tau.forest <- causal_forest(X, Y, W)`
? If not, how is it determined?

Thank you,

Federico

**Comment by erikcs** [comment]
Hi @federiconuta, the scoring function psi is what defines the different forest types and their implementation in GRF (with some exceptions), there is nothing for the the user to specify.  For example, the scoring function for causal forest is in 6.1 in https://arxiv.org/pdf/1610.01271.pdf, for instrumental forest see 7.1 in https://arxiv.org/pdf/1610.01271.pdf ("via moment functions ..."), and for causal survival forest 10 in https://arxiv.org/pdf/2001.09887.pdf

**Comment by federiconuta** [comment]
@erikcs  thank you for the reply. Sorry I cannot see equations 6.1 and 7.1 in the pdf that you send. Do you mean (6) and (7)?
So basically psi is already defined?  SO why do you distinguish between conditional mean case in the paper for instance (where theta(x) is mu(x))?

**Comment by erikcs** [comment]
> @erikcs thank you for the reply. Sorry I cannot see equations 6.1 and 7.1 in the pdf that you send. Do you mean (6) and (7)?
> So basically psi is already defined? �SO why do you distinguish between conditional mean case in the paper for instance (where theta(x) is mu(x))?

No, paragraph 6.1, end of first sentence.

Centering with E[Y|X] and E[W|X] is discussed in 6.1.1 in the following paragraph. This "residual-on-residual" scoring function turns out to be quite useful in general and have a separate paper here https://arxiv.org/pdf/1712.04912.pdf which generalizes it (section 6 has a section showing some examples, roughly speaking subtracting en estimate of E[Y|X) may let the forest place splits on variables that are more likely to effect tau(x) than just the main effect Y)

**Comment by federiconuta** [comment]
@erikcs  thank you very much for the clarifications. Just in order to be more concrete and to make sure I have understood properly I will provide an example entirely based on the paper. In paragraph 2.1, you show the results for regression trees whose aim is to predict E[Y|X]. In this case, psi depends on mu(X) and is defined as Y_i-mu(X). 
In the case of causal forests (paragraph 6.1) psi (if I understood correctly) is defined as Y_i - b(X)*W_i-c(X). Now, psi(.) is given for causal forests as you highlighted above. The difference between regression forests and causal forests "in terms of psi(.)" is the fact that in causal forests psi(.) is defined in terms of a treatment variable W_i (which by def. defines beta(X) as ATE). Am I correct or I did not get something right?

Thank you again,

Federico

**Comment by erikcs** [comment]
Yes, for causal forest the scoring function psi is that of the regression Y = c(x) + b(x) W.

**Comment by federiconuta** [comment]
Perfect. Thank you very much @erikcs
