### ISSUE TITLE
Longitudinal data with treatment starting in the middle for some individuals

### ISSUE THREAD

**Issue by johabel** [grf-labs/grf#1045]
Hi all,

I have 24 months of data for individuals. In months 1-12, nobody was treated with an experimental manipulation. In months 13-24, 50% of individuals were treated, the rest remained untreated. I want to analyze the data longitudinally because I have time-varying covariates.

I have two questions:

**A. How best to specify the causal forest?**
Which of the following options makes the most sense? Or are there other - better - options?
1. Run the causal forest on the entire data set, including the first 12 months in which everyone was untreated. As mentioned at https://github.com/grf-labs/grf/issues/532, I cluster for individuals and include a time count variable (1, 2, 3, ..., 24) as a covariate. However, this causal forest quickly violates the overlap assumption - I assume because months 1-12 perfectly predict the control group?
2. Run the causal forest only on months 13-24, again clustering for individuals and including a time count variable. However, this way I'm losing information on the pre-treatment values of the DV.
3. Run 12 individual causal forests for months 13-24, then pool the tau-hats in a data set to analyze sources of heterogeneity. I've seen this approach in the literature. However, I don't fully understand the rationale for doing it this way.

**B. How to specify a linear model to examine sources of heterogeneity in the treatment effect**
Some of my covariates are time-varying, some are time-invariant at the level of individuals, and some are time-invariant at a higher level (individuals are nested in organizations). So my data has a three-level structure.

When regressing tau-hat on my covariates to examine sources of heterogeneity, I think it is rather clear that I should cluster the SEs the same way I clustered during the estimation of the causal forest.  However, should I also include random effects for (a) individuals and/or (b) organizations? Seeing that the causal forest did not account for such random effects (?), I'm wondering if specifying them would be wrong.

Thanks very much for any help!!!

Best

Johannes

**Comment by erikcs** [comment]
@johabel, I'm so sorry for managing to completely miss this issue (for 2 years (!)). Am closing this hoping you've figured this out yourself, if not you'd have to provide more details as it's not completely clear to me what you are doing. There are plenty of papers that apply causal forests to time-settings where you could substitute the outcome variable for a differenced outcome variable, https://arxiv.org/abs/1905.11622 is a good reference for this approach.
