### ISSUE TITLE
Local entering and applications

### ISSUE THREAD

**Issue by federiconuta** [grf-labs/grf#1046]
Hi all,

so I have noticed the following part of the grf code (I have put in capital letters the point in which my question emerges):
P.s. I highlight the questions in bold for sake of clarity.

``` 
# In some examples, pre-fitting models for Y and W separately may
# be helpful (e.g., if different models use different covariates X).
# In some applications, one may even want to get Y.hat and W.hat
# using a completely different method (e.g., boosting).
#WHY? DOES IT DEAL WITH LOCAL CENTERING?

# Generate new data.
n <- 4000
p <- 20
X <- matrix(rnorm(n * p), n, p)
TAU <- 1 / (1 + exp(-X[, 3]))
W <- rbinom(n, 1, 1 / (1 + exp(-X[, 1] - X[, 2])))
Y <- pmax(X[, 2] + X[, 3], 0) + rowMeans(X[, 4:6]) / 2 + W * TAU + rnorm(n)

forest.W <- regression_forest(X, W, tune.parameters = "all")
W.hat <- predict(forest.W)$predictions

forest.Y <- regression_forest(X, Y, tune.parameters = "all")
Y.hat <- predict(forest.Y)$predictions

forest.Y.varimp <- variable_importance(forest.Y)

# Note: Forests may have a hard time when trained on very few variables
# (e.g., ncol(X) = 1, 2, or 3). We recommend not being too aggressive
# in selection.
selected.vars <- which(forest.Y.varimp / mean(forest.Y.varimp) > 0.2)

tau.forest <- causal_forest(X[, selected.vars], Y, W,
                            W.hat = W.hat, Y.hat = Y.hat,
                            tune.parameters = "all")

# Check whether causal forest predictions are well-calibrated.
test_calibration(tau.forest)
```

As far as I understood, the reported scenario is the "local centering case".
**Basically, the main question is: why (and in which cases) do we need local centering?**
In the paper (version of 2018), when local centering is discussed (paragraph 6.1.1), equation (21) is shown. Then, the following sentence is displayed "Thus if we locally center the Yi and the Wi before running our forest, the estimator
(19) has the potential to be robust to confounding effects even when the weights \alpha_i(x) are not sharply concentrated around x."
So cases are:

1. \alpha_i(x) are NOT sharply concentrated around x and there are confounders X -->  such confounders are eliminated by W_i and Y_i through demeaning and hence we have robustness (**correct?**);
2. \alpha_i(x) are sharply concentrated around x and there are confounders X -->  **should we assume, in this case, that confounders do not represent a problem?** 

**The second question is: if by default Y.hat=NULL (W.hat=NULL) means that the E[Y|X] (E[W|X]) is computed separately, why the comment says "In some examples, pre-fitting models for Y and W SEPARATELY may be helpful (e.g., if different models use different covariates X)." but then Y.hat and W.hat are in fact estimated separately and specified in the command causal_forest()?** I mean did you just wanted to show how "NULL" worked and de facto:

```
tau.forest <- causal_forest(X[, selected.vars], Y, W,
                            W.hat = W.hat, Y.hat = Y.hat,
                            tune.parameters = "all")
```

is the same as:

```
tau.forest <- causal_forest(X[, selected.vars], Y, W,
                            W.hat = NULL, Y.hat = NULL,
                            tune.parameters = "all")
```

Finally, if the above is correct and the code refers to local centering, how does it relate to the case where "e.g., if different models use different covariates X"? I mean, I cannot see why/if robustness to confounders implies also robustness to the fact that different models use different covariates. **Does causal_fores always estimate equation (21) of the paper rather than (19)? Or it depends on whether I specify Y.hat=NULL and W.hat=NULL (in which case I estimate (19)) or not NULL (in which case I estimate (21))?**

Thank you,

Federico

**Comment by erikcs** [comment]
> Does causal_fores always estimate equation (21) of the paper rather than (19)? Or it depends on whether I specify Y.hat=NULL and W.hat=NULL (in which case I estimate (19)) or not NULL (in which case I estimate (21))?

Causal forest by default estimates (21), when Y.hat and W.hat equals NULL. When these are NULL they are estimated separately with two regression forests.
