### ISSUE TITLE
Will consistency hold for correlated data in honest regression_forest?

### ISSUE THREAD

**Issue by ellenxtan** [grf-labs/grf#1048]
Hi, I was wondering if I have correlated (X_i, y_i) pairs, will Theorem 3.1 still holds for consistency in the asymptotic properties of random forests in the causal forest paper? Thanks so much!
![image](https://user-images.githubusercontent.com/38412452/135003967-f6ef326c-7721-4897-8a43-54af23dc3378.png)

**Comment by erikcs** [comment]
Hi @ellenxtan there are very many correlation structures. making a general statement which takes all of these into account is probably not feasible. "mild" departures from IID is probably innocuous, you would have to look in the proof details yourself...
