### ISSUE TITLE
Support for time-varying covariates in causal survival forests? 

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#1060]
Is there any support for time-varying covariates in causal survival forests, such as the `survival` package in R does here: 

https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf

**Comment by erikcs** [comment]
There are no built in estimators for panel data in GRF, but there are various ways one can adopt GRF if you have repeated observations with the same covariate values, see for example section 6 in https://arxiv.org/abs/1905.11622 ("CF-time/state learner") or ch2 in https://pure.au.dk/portal/files/198663023/Nicolaj_Mu_hlbach_PhD_dissertation.pdf
