### ISSUE TITLE
Very small variance estimates in Local Linear Forest Model

### ISSUE THREAD

**Issue by rjames6023** [grf-labs/grf#1062]
**Description of the bug**
I am fitting a Local Linear Forest (LLF) model to a dataset with just 3 variables and the predictions from the LLF model look reasonable. However, I am surprised that the variance estimates associated with the LLF model predictions are very small. For example my average prediction is approximately 0.379 while the average variance estimate is approximately 4.327e-05. I wonder if anyone could provide an insight into whether or not this variance estimate looks reasonable or if I have made a mistake in fitting/using the LLF model?

As a reference, I also ran a Nadaraya Watson kernel regression elsewhere that gives similar point predictions but is associated with average variance estimates of around 0.011 and for the quantity that I am using the LLF to predict I also have available a simplified analytic expression which also gives reasonably similar point predictions and variance estimates to the Nadaraya Watson estimator. 

**Steps to reproduce**
I have attached training/testing data files and below is a short R script that should give an example. 

library('grf')
library('readxl')
train_data = as.matrix(read_excel('C://Users//Robert James//Dropbox (Sydney Uni)//train_data.xlsx'))
train_y = train_data[1:nrow(train_data),1]
train_X = train_data[1:nrow(train_data),2:4]
test_X = as.matrix(read_excel('C://Users//Robert James//Dropbox (Sydney Uni)//test_data.xlsx'))

#Fit a LL forest model 
LL_forest_object = ll_regression_forest(train_X, train_y,
                                        num.trees = 4000,
                                        min.node.size = 100,
                                        enable.ll.split = TRUE,
                                        seed = 1234)
results.llf.var = predict(LL_forest_object, test_X, estimate.variance = TRUE)
y_hat = results.llf.var$predictions
V_y_hat = results.llf.var$variance.estimates

print(mean(y_hat))
print(mean(V_y_hat))

**GRF version**
I am using version 1.2.0
[test_data.xlsx](https://github.com/grf-labs/grf/files/7509961/test_data.xlsx)
[train_data.xlsx](https://github.com/grf-labs/grf/files/7509962/train_data.xlsx)

**Comment by erikcs** [comment]
Hi @rjames6023, your ll_regression_forest invocation looks perfectly reasonable. The pointwise GRF [variance estimates](https://grf-labs.github.io/grf/REFERENCE.html#variance-estimates) are based on measures of "within and across" variation  of tree predictions, if your data has very high/easy signal leading all the ~4k trees to split very similarity, it is reasonable to expect the pointwise variance estimates can be small (you can look at trees with get_tree).
