### ISSUE TITLE
Average_ Treatment _ effect

### ISSUE THREAD

**Issue by ZaidHattab** [grf-labs/grf#1063]
Hello, 

I am facing an issue in using the average_treatment_effect function for instrumental forest. It works, but each time I run it, it gave a different value. For example, 
**F1=instrumental_forest (X,Y,D,Z,seed=133)
average_treatment_effect(F1) 
ate=5  , se = 2 
average_treatment_effect(F1)
ate= 6 , se = 1.7** 

Is there any solution for this issue please ? 

Thank you

**Comment by erikcs** [comment]
Hi @ZaidHattab, from the [average_treatment_effect](https://grf-labs.github.io/grf/reference/average_treatment_effect.html) argument description for IV forest:

>compliance.score | Only used with instrumental forests. An estimate of the causal effect of Z on W, i.e., Delta(X) = E[W \| X, Z = 1] - E[W \| X, Z = 0], which can then be used to produce debiasing.weights. If not provided, this is estimated via an auxiliary causal forest.

to get the same results (for the CF estimating the compliance scores) you can do `set.seed` before calling `average_treatment_effect`. (related issue: #1032)

**Comment by ZaidHattab** [comment]
Many thanks for your help @erikcs 
Thing are more clear now. To make sure, would you please let me know if the below is correct ?
**library(grf)
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <-  rbinom(n, 1, 0.5)
Z <-  rbinom(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
instrument.forest =instrumental_forest (X,Y,W,Z,seed=133)
c.forest <- causal_forest(X, Y, W, seed=2)
variance_forest <- regression_forest(X, (W - c.forest$W.hat)^2, num.trees = 500)
V.hat <- predict(variance_forest)$predictions
debiasing.weights <- (W - c.forest$W.hat) / V.hat
compliance.score <- causal_forest(X, W, Z, seed=2)
average_treatment_effect(instrument.forest , debiasing.weights = debiasing.weights, compliance.score=compliance.score )**

**Comment by erikcs** [comment]
Yes, you can also do:

```
set.seed(133)
average_treatment_effect(F1)
```
and always get the same estimate

**Comment by erikcs** [comment]
This is changed in #1070, thanks for reporting @ZaidHattab
