### ISSUE TITLE
Causal survival forest survival function estimate

### ISSUE THREAD

**Issue by mparanjpe96** [grf-labs/grf#1069]
Hello,
I am trying to use the Causal survival forest prediction function. It seems that the function predict.causal_survival_forest is returning tau(X) = E[Y(1) - Y(0) | X = x] where E[Y] is the expected survival time = integral(survival function) 

I would like to return the survival function so I can compute the probability of survival beyond time t. 

Is there a way to get the survival function? 

Thanks!
Manish

**Comment by erikcs** [comment]
Hi @mparanjpe96, this functionality is being added now (#1055). We can ping you when it is available in the development version.

**Comment by mparanjpe96** [comment]
> Hi @mparanjpe96, this functionality is being added now (#1055). We can ping you when it is available in the development version.

Thats very much appreciated, thank you!!

**Comment by erikcs** [comment]
#1055 is merged into master now if you wish to beta test the bleeding edge development version

**Comment by mparanjpe96** [comment]
Thank you so much! I will let you know the outcome and if I run into any problems! 

Best,
Manish

**Comment by mnose** [comment]
Hi, 
I am working on the application of the causal survival forest and would like to report the outcome by the survival probability or hazard ratio. 

I try to install the development version from source using devtools (devtools::install_github("grf-labs/grf", subdir = "r-package/grf") and Rtools40. For some reason, I am getting the attached error and cannot install after it runs some time.  I have no problem installing other development versions from the GitHub, so not sure what is the problem. Any guidance would be appreciated
[GitHub_grf_error.txt](https://github.com/grf-labs/grf/files/7613844/GitHub_grf_error.txt)
.

**Comment by erikcs** [comment]
Here is the latest tar.gz attached you can install with R CMD INSTALL
[grf_2.0.2c4a69b9.tar.gz](https://github.com/grf-labs/grf/files/7619408/grf_2.0.2c4a69b9.tar.gz)

(devtools on windows doesn't work with grf https://grf-labs.github.io/grf/DEVELOPING.html#note-for-windows-users)

**Comment by mnose** [comment]
Thank you! It works well.
