### ISSUE TITLE
Will test_calibration() support instrumental forest in the future? 

### ISSUE THREAD

**Issue by yujias424** [grf-labs/grf#1078]
Hi all,

I am curious about whether the test_calibration() can support instrumental forest in the near future? It seems that there isn't any well-established approach that can help evaluate the quality of the instrumental forest estimates yet.

Many Thanks!

**Comment by erikcs** [comment]
Hi @yujias424, no future additions are planned for test_calibration. We do however have a new metric in works (#1086) which provides an "easy/interpretable" measure of HTEs on a test set, and which works with IV forest.
