### ISSUE TITLE
Splitting Rules

### ISSUE THREAD

**Issue by watkilj** [grf-labs/grf#1082]
I am looking for your multi_regression_forest splitting rule as a mathematical formula. I've read the source code "MultiRegressionSplittingRule.h" and "MultiRegressionSplittingRule.cpp" but the calls within that code refer to another function "find_best_split" which seem to be a dead end on source code that I can find. What is the exact splitting rule for the multi_regression_forest?

**Comment by erikcs** [comment]
See https://grf-labs.github.io/grf/DEVELOPING.html#tree-splitting-algorithm 

>For multivariate CART sum_left^2 and sum_right^2 becomes the squared L2 norm.
