### ISSUE TITLE
`get_forest_weights` considerably slower than `predict.quantile_forest`

### ISSUE THREAD

**Issue by nicolagnecco** [grf-labs/grf#1085]
Thanks for your package!

I am facing the following issue. The `get_forest_weights` documentation says that during normal prediction, the weights are computed as an intermediate step towards producing estimates. Therefore, I would expect that calling the function `get_forest_weights` would be roughly as fast as calling `predict.quantile_forest`. However, I observe that `get_forest_weights` is significantly slower than `predict.quantile_forest` (see `reprex` below).  

Do you know why this is the case?

Thank you!

**Steps to reproduce**
``` r
library(grf)
library(bench)

# Generate data.
n <- 500
ntest <- 2000
p <- 4
X <- matrix(rnorm(n * p), n, p)
X.test <- matrix(0, ntest, p)
X.test[, 1] <- seq(-2, 2, length.out = ntest)
Y <- X[, 1] * rnorm(n)

# Train a quantile forest.
q.forest <- quantile_forest(X, Y, quantiles = c(0.1, 0.5, 0.9))

# Compare predict.quantile_forest with get_forest_weights
bench::mark(
  grf:::predict.quantile_forest(q.forest, X.test, quantiles = c(0.1, 0.9)),
  get_forest_weights(q.forest, newdata = X.test),
  check = FALSE
)
#> # A tibble: 2 x 6
#>   expression                                                                 min
#>   <bch:expr>                                                               <bch>
#> 1 grf:::predict.quantile_forest(q.forest, X.test, quantiles = c(0.1, 0.9)) 207ms
#> 2 get_forest_weights(q.forest, newdata = X.test)                           678ms
#> # … with 4 more variables: median <bch:tm>, `itr/sec` <dbl>,
#> #   mem_alloc <bch:byt>, `gc/sec` <dbl>
```

<sup>Created on 2022-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**GRF version**
 grf_2.0.2

**Comment by erikcs** [comment]
Hi @nicolagnecco,

Good question, the threading strategy in those two functions are different :
```
> system.time(predict(q.forest, X.test, quantiles = c(0.1, 0.9), num.threads = 1))
   user  system elapsed 
  1.081   0.007   1.089 
> system.time(get_forest_weights(q.forest, X.test, num.threads = 1))
   user  system elapsed 
  1.034   0.009   1.045 
```

All forest predictors computes predictions in parallel using num.threads. The utility function get_forest_weights does [not compute](https://github.com/grf-labs/grf/blob/master/r-package/grf/bindings/AnalysisToolsBindings.cpp#L77) weights for each sample in parallel the same way. We did not anticipate this function be used very frequently and did not pursue further optimizations (it is not as straight forward since it involves filling an Eigen object concurrently).

**Comment by nicolagnecco** [comment]
Hi @erikcs,

Thanks for the clarification.

As a suggestion, if I have an algorithm that relies on `get_forest_weights,` do you think the most efficient is to do everything in C++?

**Comment by erikcs** [comment]
Are you sure getting alpha is the bottleneck in your algorithm? You can try empirically with just `alpha = matrix(runif(ntest * n), ntest, n); alpha = sweep(alpha, 1, rowSums(alpha), "/")` - see how the runtime depends on n. Depending on what you are doing with alpha, just getting a sparse weight matrix might not be the bottle neck. That's the case for for ex. causal forest which would do a linear regression with each alpha row, and to speed that up does it with sufficient statistics instead:

https://grf-labs.github.io/grf/DEVELOPING.html#code-structure:
>[OptimizedPredictionStrategy](https://github.com/grf-labs/grf/blob/master/core/src/prediction/OptimizedPredictionStrategy.h) does not predict using a list of neighboring samples and weights, but instead precomputes summary values for each leaf during training, and uses these during prediction

Attached is a internal pdf note on the logic behind this: 
[grf_predictions.pdf](https://github.com/grf-labs/grf/files/7991343/grf_predictions.pdf)

**Comment by erikcs** [comment]
If it is the bottle neck then we can look into adding threading to get_forest_weights into the next grf release that's pegged for early this spring

**Comment by erikcs** [comment]
Also, another simple thing you can do from R to emulate collecting weights in parallel
```R
library(grf)
library(Matrix)
library(parallel)
n <- 500
ntest <- 2000
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
rf <- regression_forest(X,Y)
Xt <- matrix(rnorm(ntest * p), ntest, p)


system.time(w <- get_forest_weights(rf, Xt))
# user  system elapsed
# 1.411   0.028   1.181
system.time({
W <- mclapply(splitIndices(nrow(Xt), detectCores()),
              function(idx) get_forest_weights(rf, Xt[idx,, drop = FALSE]),
              mc.cores = detectCores());
W <- do.call(rbind, W)
})
# user  system elapsed
# 2.898   0.478   0.547

sum(W - w) == 0
```
(if this will be faster depends on n and ntest)
