### ISSUE TITLE
Estimation of ATE with subset gives a different result at each execution

### ISSUE THREAD

**Issue by gcasamat** [grf-labs/grf#1087]
I have trained a causal forest with a continuous treatment.
The average_treatment_effect command on a given subset of the data yields a different result each time it is executed (whereas the result is always the same when the subset option is not used). 

grf version: 2.0.2

**Comment by erikcs** [comment]
Hi @gcasamat, see https://github.com/grf-labs/grf/issues/1068.

**Comment by gcasamat** [comment]
Thank you @erikcs !
