### ISSUE TITLE
Discrepancy between average treatment effect and mean of CATE

### ISSUE THREAD

**Issue by gcasamat** [grf-labs/grf#1088]
I have trained a causal forest with a continuous treatment and I want to estimate an average treatment effect for specific geographical areas (called IRIS). I do not know if it might help but I should add that the level of the treatment is the same for all units in a given IRIS. 

I thus execute the following code:
`average_treatment_effect(cf.clust, subset = (data_for_reg$code_iris_num == 357))`
where cf.clust is the trained forest and 357 is the identifier of the specific IRIS for which I want to get the ATE. 

I obtain an estimate of -0.263  with a 95% CI: [-0.397, -0.128].
What surprises me is that a simple mean of the CATE for units in IRIS 357 is 0.107 (the standard deviation is 0.0164).
I noticed that the average_treatment_effect function makes use of doubly robust scores, but still I wonder how to explain that the average effect is large and negative, whereas all units in the IRIS have a CATE close to 0.1? Is is always the case that the use of doubly robust scores allows to improve the estimation of the ATE?

Another remark concerns the fact that the ATE for this IRIS is very different whether I decide to cluster or not the observations when training the forest, whereas the ATE on the full sample is pretty close with the two methods. I wonder if there is some kind of diagnosis test that would allow me to decide whether I should cluster the observations or not.

I also have another related question. I want to train a random forest on the CATE, in order to then apply the SHAP algorithm to the predictions of the random forest. Do you advise me to use the CATE as estimated by the causal forest as a target, or rather the doubly robuste scores?

**Comment by erikcs** [comment]
> I have trained a causal forest with a continuous treatment and I want to estimate an average treatment effect for specific geographical areas (called IRIS). I do not know if it might help but I should add that the level of the treatment is the same for all units in a given IRIS.

If all units in a IRIS are given the same treatment then the line below is not identified meaning you are trying to estimate a the different between being treated and not treated for a subpopulation that always receives one but not the other. 
 
> I thus execute the following code: `average_treatment_effect(cf.clust, subset = (data_for_reg$code_iris_num == 357))` where cf.clust is the trained forest and 357 is the identifier of the specific IRIS for which I want to get the ATE.


> I obtain an estimate of -0.263 with a 95% CI: [-0.397, -0.128]. What surprises me is that a simple mean of the CATE for units in IRIS 357 is 0.107 (the standard deviation is 0.0164). I noticed that the average_treatment_effect function makes use of doubly robust scores, but still I wonder how to explain that the average effect is large and negative, whereas all units in the IRIS have a CATE close to 0.1? Is is always the case that the use of doubly robust scores allows to improve the estimation of the ATE?

If you by improve the estimation of the ATE mean that it is efficient, then yes, under quite general conditions, see for ex. Lecture 3 in these notes http://web.stanford.edu/~swager/stats361.pdf (and the paragraph on "Semiparametric efficiency" for a very general statement)

> Another remark concerns the fact that the ATE for this IRIS is very different whether I decide to cluster or not the observations when training the forest, whereas the ATE on the full sample is pretty close with the two methods. I wonder if there is some kind of diagnosis test that would allow me to decide whether I should cluster the observations or not.

Clustering is a sampling level decision you as the researcher need to decide on, effectively deciding on an appropriate unit of observation, you can see an example application in https://arxiv.org/abs/1902.07409 

> I also have another related question. I want to train a random forest on the CATE, in order to then apply the SHAP algorithm to the predictions of the random forest. Do you advise me to use the CATE as estimated by the causal forest as a target, or rather the doubly robuste scores?

afaik using the cates directly is fine, the shap values for a CF is not exactly the same as a shap values for a RF anyways

**Comment by gcasamat** [comment]
Many thanks for your reply ! 
This is clear, although I am not sure about your first statement : "If all units in a IRIS are given the same treatment then the line below is not identified meaning you are trying to estimate a the different between being treated and not treated for a subpopulation that always receives one but not the other." 
I will give it more thoughts ..
