### ISSUE TITLE
Add support for factor variables.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#109]
We should likely implement the approach suggested in ESL where in each node, factor variables are ordered by their mean outcome before performing the split. This should be properly generalized to handle non-regression forests.

**Comment by lwu9** [comment]
When there is a categorical variable X1 in X, it is possible that there is a child node where those observations contain only one category, i.e. all values of the variable X1 are the same. In this case, how can we get pseudo-outcomes? The pseudo-outcomes is obtained through the inverse of Ap which may be singular. Isn't it?

**Comment by swager** [comment]
The X-values aren't used to compute the pseudo-outcomes in the leaf in the standard GRF formulation; rather, only the "outcomes" matter (e.g., W and Y for `causal_forest`). The features X enter into the problem by determining which leaf an observation falls into.

**Comment by lwu9** [comment]
Thanks for you reply @swager! I understand in your causal_forest, pseudo-outcomes only have W and Y. But if we want to do the local linear regression, so our psi should be:
psi(Y_i)=Y_i-theta * X_i, (here theta is related to the query point x), shouldn't it? So when we calculate Ap, we need take derivative of psi w.r.t. theta, and the result will include feature X. Is there anything wrong in my understanding?

**Comment by jtibshirani** [comment]
We added the [sufrep package](https://github.com/grf-labs/sufrep), which contains a collection of methods for handling categorical variables, and a [tutorial](https://grf-labs.github.io/grf/articles/categorical_inputs.html) for how to use sufrep with grf.

**Comment by lwu9** [comment]
Thanks
