### ISSUE TITLE
Interpretation of test_calibration() output

### ISSUE THREAD

**Issue by shibakoichiro** [grf-labs/grf#1090]
I am trying to evaluate a model fit of causal forest output (say, `forest.fit`). Following the recommendation in[ Athey and Wager (2019)](https://muse.jhu.edu/article/793356/pdf), I have tried the following two approaches.

Approach 1: We examined if ATEs for sub-groups of people with out-of-bag CATE estimates above versus below the median CATE estimate significantly differ from one another. 
Approach 2: Using the best linear predictor (i.e., the `test_calibration(forest.fit)`), we performed an omnibus test for effect heterogeneity.

With Approach 1, I got some evidence of effect heterogeneity (p for the difference in the subgroup-specific ATEs <0.05). However, with Approach 2, my estimate for "differential.prediction" was negative and the corresponding single-sided p-value = 0.8.

I am wondering how I should interpret these mixed findings and have the following specific questions.

1. Does this mean my causal forest fit was terribly off, and I should not be interpreting any output from the forest? I know a negative coefficient for the "differential.prediction" itself is not desirable and not interpretable, but I wonder what the implication of such result in terms of model finding is.
2. The estimate for "mean.forest.prediction" from the `test_calibration()` was close to 1 and significantly from zero (p<0.05). Does this mean the causal forest fit is okay, but there just wasn't (omnibus) evidence of heterogeneity?
3. In general, I am having hard time understanding how this "calibration" test works as model fit checking and test for heterogeneity given that we don't have ground-truth (i.e., CATEs) to validate against our tau estimates. Could someone give me an intuition? 
4. Can we make a calibration plot using `grf`?

Thank you in advance, and I am tagging my collaborator @adeldaoud here!

**Comment by erikcs** [comment]
Hi @shibakoichiro, we're adding a new method (rank_average_treatment_effect) in #1086 that can be used to assess whether HTEs are present. It can be seen as a generalization of approach 1, but comes with some stronger statistical guarantees, a "calibration plot" for visual inspection, and it uses CATE estimates on held-out data as "ground truth". For your application it would basically test if the causal forest CATEs can "rank" subjects on a test set s.t. the weighted (according to this rank) ATE is > 0.

As for disambiguation between quantile plots/test_calibration/this new method, we'll have to follow-up on that, and defer to @swager for exact interpretation for test_calibration, because I too find that method confusing ...

**Comment by shibakoichiro** [comment]
Hi @erikcs, thank you for your response. This is incredibly helpful. I look forward to the follow-up...

**Comment by adeldaoud** [comment]
Thanks @shibakoichiro for posting this question and @erikcs for your response. Hoping that @swager could help us understand the rest of these questions.

**Comment by swager** [comment]
Echoing what @erikcs said -- I would try computing the RATE here, and see how it comes out. The RATE is also an automated global test like the calibration check, but it's proven to be easier to interpret in a number of applications.

That being said, having the "differential.prediction" point estimate be negative is not a good sign; it does suggest that the forest is having a hard time uncovering heterogeneity here.

Beyond that, regarding question 2 above -- the coefficient for the mean prediction being significant signals that there's evidence of a non-zero ATE; but it doesn't say anything about heterogeneity.

**Comment by erikcs** [comment]
The RATE mentioned above is now available in the latest grf CRAN version, and an introductory vignette is available here: https://grf-labs.github.io/grf/articles/rate.html
