### ISSUE TITLE
Setting the seed does not work in Causal Survival Forest for seed = 0

### ISSUE THREAD

**Issue by scottfleming** [grf-labs/grf#1091]
**Description of the bug**
Causal survival forest (and potentially others?) doesn't give consistent results when the seed is set to 0 (other numbers >0 seem to work).

**Steps to reproduce**
```
seed <- 0
n <- 500
p <- 5
X.train <- matrix(runif(n * p), n, p)
X.test <- matrix(runif(n * p), n, p)
W.train <- rbinom(n, 1, 0.5)
Y.max <- 1
failure.times.train <- pmin(rexp(n) * X.train[, 1] + W.train, Y.max)
censor.time <- 9999
Y.train <- pmin(failure.times.train, censor.time)
D.train <- as.integer(failure.times.train <= censor.time)

set.seed(seed)
train.model.CSF <- grf::causal_survival_forest(
  X = X.train,
  Y = Y.train,
  W = W.train,
  D = D.train,
  W.hat = rep(mean(W.train), length(W.train)),
  target = "RMST",
  horizon = Y.max,
  honesty = FALSE,
  alpha = 0.05,  # Default value
  tune.parameters = "all",
  seed = seed
)
preds.1 <- predict(train.model.CSF, newdata=X.test)$predictions

set.seed(seed)
train.model.CSF <- grf::causal_survival_forest(
  X = X.train,
  Y = Y.train,
  W = W.train,
  D = D.train,
  W.hat = rep(mean(W.train), length(W.train)),
  target = "RMST",
  horizon = Y.max,
  honesty = FALSE,
  alpha = 0.05,  # Default value
  tune.parameters = "all",
  seed = seed
)
preds.2 <- predict(train.model.CSF, newdata=X.test)$predictions

all(preds.1 == preds.2)  # should be the same if the seed works correctly.
```

**GRF version**
Version 2.0.2

**Comment by erikcs** [comment]
I am fine with just keeping this as is, having 0 be a sentinel value that indicates randomness like Julie intended. Unless you feel strongly against this @scottfleming

**Comment by scottfleming** [comment]
I have no problem with that - it just needs to be spelled out in the docs (and maybe even a warning?). This ended up being a very nasty bug to figure out, but just a little added detail in the Reference [docs](https://grf-labs.github.io/grf/reference/causal_survival_forest.html) would have prevented the issue. 

My concern with keeping it as is, is that "seed" is a generic enough kind of argument that users may expect a certain behavior using it (e.g., consistent results despite a particular choice of seed) without actually reading every detail of all the arguments they're using. You could argue that's the user's fault, and that's also legitimate - seems like a matter of opinion. 

It's still a little unclear to me what the value is of keeping it as is, given that the user could randomly generate seeds on their end in R and then pass those along?

**Comment by susanathey** [comment]
@scottfleming makes sense--seems like the very least change should be to throw a warning if someone uses this seed

**Comment by erikcs** [comment]
>It's still a little unclear to me what the value is of keeping it as is, given that the user could randomly generate seeds on their end in R and then pass those along?

It's not for R but evidently a legacy left behind to easily instantiate many RF which exhibit randomness without coming up with seeds.

It's best to remove it altogether if it passes all tests, which seems reasonable since uint 0 should be a valid input in all c++ components which uses, but I haven't combed over, @scottfleming you can open PR trying to remove it if you want:
delete all I linked to on L57,  move the initialization up to after L44, and you can probably kill the include on L19
