### ISSUE TITLE
Which equation is used for computing tau(x) for binary treatment in Causal Forest?

### ISSUE THREAD

**Issue by ziweicong** [grf-labs/grf#1095]
Hi!

I'm using Causal Forest for my projects and recently I have a question about computing CATE (tau(x)) in Causal Forest when treatment is binary. I read from your comments in source code "causal_forest.R" that: When the treatment assignment W is binary and unconfounded, we have tau(X) = E[Y(1) - Y(0) | X = x]. When W is continuous, we effectively estimate an average partial effect Cov[Y, W | X = x] / Var[W | X = x].

My understanding to tau(X) = E[Y(1) - Y(0) | X = x] is that when W is binary, you estimate tau(x) by taking the difference between the mean outcomes of treated and control units in the same leaf. But I'm confused that given the algorithm actually uses residualized Y (=Y - Y.hat) and residualized W (=W - W.hat) to grow the tree, all cases may eventually become a continuous treatment case because residualized Y and residualized W are very like to be continuous. If so, it seems to be more appropriate to (always) use Cov[Y, W | X = x] / Var[W | X = x] to estimate tau(x)?

I'm not sure if my interpretation above is correct. An alternative interpretation is that we use residualized Y and W when "growing the tree", but still use original Y and W for the final estimation step (and so tau(X) = E[Y(1) - Y(0) | X = x] for CATE estimation). If this is the case, what equation do we use for estimating theta_p in the parent node when splitting the tree (see equation (4) (5) (6) in [Athey, S., Tibshirani, J., & Wager, S. (2019): Generalized Random Forest](https://arxiv.org/pdf/1610.01271.pdf))?

I also read [Athey, S., & Wager, S. (2019). Estimating treatment effects with causal forests: An application](https://arxiv.org/abs/1902.07409). They mentioned that Causal Forest estimates predictions via equation (7). Though equation (7) makes sense to me, it also makes me more confused as it seems to be different from tau(X) = E[Y(1) - Y(0) | X = x] that specified in the source code and R package documentation.
![1644722273812](https://user-images.githubusercontent.com/56111164/153736798-1e2d45ab-b639-4225-94dc-a62fa49813e2.jpg)

It would be great if you could provide any explanations or comments. Thanks!

**Comment by erikcs** [comment]
Hi @ziweicong, the causal forest tau(x) predictions for Xi=i is (19) in https://arxiv.org/pdf/1610.01271.pdf, i.e. the centered regression of Y on the centered W, using kernel weights alpha(x) derived by the GRF algorithm. For more on the motivation behind this residual-on-residual regression ("R-learner") see https://arxiv.org/pdf/1712.04912.pdf

Here is a code example if you find that helpful:
```R
library(grf)
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)

Y.forest <- regression_forest(X, Y, num.trees = 500)
Y.hat <- predict(Y.forest)$predictions
W.forest <- regression_forest(X, W, num.trees = 500)
W.hat <- predict(W.forest)$predictions
c.forest <- causal_forest(X, Y, W, Y.hat = Y.hat, W.hat = W.hat)

x.test <- matrix(0.5, ncol = p)
alpha.x <- get_forest_weights(c.forest, x.test)
Y.centered <- Y - Y.hat
W.centered <- W - W.hat

# The same:
lm(Y.centered ~ W.centered, weights = alpha.x[1,])$coefficients[[2]]
# [1] 0.2354195
predict(c.forest, x.test)$predictions
# [1] 0.2354195
```
