### ISSUE TITLE
How many folds are used for hyperparameter tuning?

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#1100]
I was checking the GRF manual, and it remains unclear how many folds the GRF algorithm uses for hyperparameter tuning. In the manual, under "causal_forest", the argument "tune.parameters" specifies which parameters are can be tuned but does not describe the tuning process and the number of folds used.  (1) How many folds are used and how can the user change that? And (2) what is the tuning processes in GRF?

**Comment by erikcs** [comment]
Hi @adeldaoud, OOB forest estimates from all samples are used to tune, folds are not used, see https://grf-labs.github.io/grf/REFERENCE.html#parameter-tuning for a description. The internal tuning code is also here https://github.com/grf-labs/grf/blob/master/r-package/grf/R/tune_forest.R if you have questions on that

**Comment by adeldaoud** [comment]
Thanks @erikcs , this answer my question.
