### ISSUE TITLE
How Do you get Predicted Values of Y after Causal Forest?

### ISSUE THREAD

**Issue by Matthew-R-Lehnert** [grf-labs/grf#1101]
Currently, I am working on a project involving predicting carbon emissions, and we want to compare predictions between causal forest with some other models.  Is there an easy way to get predicted values of Y using causal forest?  I understand the output of predict after causal forest is the CATE.  Did I miss something simple to where I can instead get predicted values of Y?  Or does one need to fit a regression_forest separately for W and Y?  Thank you so much for your help.  I apologize if I overlooked something simple.  Keep up the great work!

**Comment by erikcs** [comment]
Hi @Matthew-R-Lehnert, this vignette https://grf-labs.github.io/grf/articles/muhats.html has an example of how to recover the implicit E[Y(1)|X] and E[Y(0)|X] estimates from, E[Y|X],  E[W|X] and the CATEs

**Comment by Matthew-R-Lehnert** [comment]
Thanks!  this is a great link.
