### ISSUE TITLE
Probability RF prediction and tuning

### ISSUE THREAD

**Issue by watkilj** [grf-labs/grf#1109]
I am trying to use  Probability RF to model a discrete conditional distribution. I am looking for the prediction assignment rule for terminal nodes. How does Probability RF break ties with multiple classes in the terminal nodes/leafs? Is the prediction from a leaf assigned by majority vote? It looks like the _pv_values are the predictions for each forest, for each terminal node? What does the second index on _pv_values represent (e.g. Probability_Forest[["_pv_values"]][[1]][[X]])? I am looking for this information so I can write a function to tune probability forests based on the gini impurity/entropy of the leaf nodes that determine the predictions.

**Comment by erikcs** [comment]
Hi @watkilj, sorry I don't understand what you mean by tie breaking, PF predicts conditional probabilities P[Y = k | X = x], not a class assignment (which you could get by something like the prob.forest$predictions rowmax and decide on the tie yourself if they are equally likely). Everything underscored by _ are internal undocumented attributes, sufficient statistics for each leaf node's prediction values across all trees in this case, though if you want to compute a loss for the forest you could just compute an aggregate loss using your observed Y's and estimated predictions prob.forest$predictions...? That is roughly how  causal forest tuning is done, except the R-loss is computed internally in the C++ method PredictionStrategy::compute_error which incorporates a bias correction for a forest trained with a small number of trees to make tuning computationally feasible.

**Comment by watkilj** [comment]
@erikcs, I had assumed that the conditional probabilities that determine the predictions for the entire forest were derived from the distribution of class assignments in the leafs.  But I see now that it must be just a forest average of the conditional probability for each k since each _pv_values sum to 1 (and averaging these across the forest keeps the sum across all k at 1 for each observation). I was able to write a aggregate loss function using the estimated probabilities from the entire forest using the Brier Score.
