### ISSUE TITLE
Could not tune forest

### ISSUE THREAD

**Issue by ghowoo** [grf-labs/grf#1114]
I tried to tune parameters using causal_forest and it gave a warning message: 

"Could not tune forest because some small forest error estimates were NA.
Consider increasing tuning argument tune.num.trees"

The model itself still works and seems to work well. However, its tuning.output show status of "failure". I tried to increase tune.num.trees to 1000 (default is 200) and it gave the same warning message.

Is there a way to figure out what is the problem?

**Comment by erikcs** [comment]
Hi @ghowoo this will be fixed (#1067) in the upcoming release (expected to be on CRAN later this month). In the meantime you could try to just tune a subset of the parameters using the `tune.parameters` option

**Comment by erikcs** [comment]
Fixed in the current CRAN release (version 2.1.0)
