### ISSUE TITLE
(Question) Why do I get NaNs when using a few trees?

### ISSUE THREAD

**Issue by jseongpark** [grf-labs/grf#1125]
Dear GRF team,

Hello. Thank you for making this great open source.

I ran the multi_regression_forest and obtained the predicted value.
However, I obtained NaNs in the predicted value when I ran only 1 tree.
(It seems that when using more trees NaN does not occur.)

Below is the result of the R execution.

> forest = multi_regression_forest(X,Y,1)
> predict.multi_regression_forest(forest)
$predictions
                 y1           y2
  [1,]  0.582348681 -1.118220075
  [2,]  1.563825455  0.841172263
  [3,] -0.620531431 -0.899360910
  [4,]          NaN          NaN
  [5,] -1.210395482  0.050391957
  [6,] -0.610580094  1.261986990
  [7,]  1.726834051  0.625296881
  [8,] -3.203943052  0.189024429
  [9,]  2.307210903  0.629294890
 [10,]  0.734244783  0.499448605
 [11,]          NaN          NaN

I would like to know why I get NaNs.

Thank you

Park

**Comment by erikcs** [comment]
Hi, `predict(forest, newdata=NULL)` gives out of bag predictions (https://grf-labs.github.io/grf/reference/predict.multi_regression_forest.html): 

>newdata | Points at which predictions should be made. If NULL, makes out-of-bag predictions on the training set instead (i.e., provides predictions at Xi using only trees that did not use the i-th training example). Note that this matrix should have the number of columns as the training matrix, and that the columns must appear in the same order.
