### ISSUE TITLE
Calibration test for instrumental forests 

### ISSUE THREAD

**Issue by ZaidHattab** [grf-labs/grf#1134]
Hello, 
 While trying to apply the calibration test for the instrumental forest, R indicates that "Calibration check is not supported for this type of forest", so I simply added it to the function as follows: 

 TestCal = function(forest) {
 .
 .
 .
  } else if ("causal_forest" %in% class(forest)) {
    preds =  predict(forest)$predictions
    mean.pred = weighted.mean(preds, observation.weight)
    DF = data.frame(target = forest$Y.orig - forest$Y.hat,
                    mean.forest.prediction = (forest$W.orig - forest$W.hat) * mean.pred,
                    differential.forest.prediction = (forest$W.orig - forest$W.hat) *
                      (preds - mean.pred))
  **} ****else if ("instrumental_forest" %in% class(forest)) {
    preds =  predict(forest)$predictions
    mean.pred = weighted.mean(preds, observation.weight)
    DF = data.frame(target = forest$Y.orig - forest$Y.hat,
                    mean.forest.prediction = (forest$W.orig - forest$W.hat) * mean.pred,
                    differential.forest.prediction = (forest$W.orig - forest$W.hat) *
                      (preds - mean.pred)**)
  } else {****
    ........
}

I would like to know if this is acceptable. Otherwise, would you please inform me whether there is an analogous test for instrumental forests? 

Best Wishes, 
Zaid

**Comment by erikcs** [comment]
Hi @ZaidHattab, no that doesn't look right (maybe look at https://arxiv.org/abs/1712.04802 to see if they do IV there). If you want a way to assess heterogeneity with GRF that supports IV forest then you can try out [RATE](https://grf-labs.github.io/grf/reference/rank_average_treatment_effect.html) available in the latest CRAN version. An introduction is here: https://grf-labs.github.io/grf/articles/rate.html
