### ISSUE TITLE
(question) using estimated CATE(tau.hat) VERSUS doubly robust score in heterogeneity exploration

### ISSUE THREAD

**Issue by JunghwiShin** [grf-labs/grf#1136]
Dear Team,

Currently, I am interested in an analysis of treatment(binary) effect heterogeneity. 
I estimated CATE per unit(by `predict(cf)`) and then calculated doubly robust score, also per unit(by `get_scores()`). 
The average of the CATE estimates and the average of the doubly robust score(which is identical to ATE(by `average_treatment_effect()`) were similar in their values. However, in subgroups(defined by covariates) level, those two estimands were sometimes substantially different. 
For the purpose of effect heterogeneity exploration(plotting or subgroup analysis, etc), which do you think is more appropriate?
(I have checked Athey & Wager(2019) used both)

+)
I guess the differences in estimated CATE and doubly robust scores are due to some extreme propensity score values.
Here is the propensity score(W.hat) distribution.  
![image](https://user-images.githubusercontent.com/103505082/163120296-16b9e11f-6ce3-400b-8d2f-9381f89924d0.png)
 Do you think it is problematic in terms of overlap?
(I also checked the propensity score distribution by the treatment condition, and the overlap seemed fine.)

Athey, S., & Wager, S. (2019). Estimating treatment effects with causal forests: An application. Observational Studies, 5(2), 37-51.

**Comment by erikcs** [comment]
Hi @JunghwiShin, the `average_treatment_effect` function should give you a warning if overlap appears to be an issue. As for the HTE analysis in Athey/Wager the latest GRF includes a new and tailored way to do this with [RATE](https://grf-labs.github.io/grf/reference/rank_average_treatment_effect.html). Here is an introduction: https://grf-labs.github.io/grf/articles/rate.html

**Comment by JunghwiShin** [comment]
Dear @erikcs, Thank you so much for the reply and introduction of the RATE. However, if I'm not mistaken, it looks like RATE is a new way to quantify the degree of the HTE, which can be an alternative to the `test_calibration`. I think I was not clear enough. What I am interested in is how (estimated) treatment effects vary across the distribution of a specific covariate X or any set of covariates.
Now I see that what I am confused about is, at the individual or subgroup(defined by covariates) level, whether doubly robust scores are better estimates compared to CATE estimates. 

Again, sorry for not being clear in the first place and thanks for your kind response.

**Comment by erikcs** [comment]
Doing `average_treatment_effect(forest, subset = your.subset.defined.by.X)` would be the way, that also gives you SEs for the various group ATEs (which are valid given that you construct the subsets your.subset.defined.by.X w/o looking at the forest estimates)
