### ISSUE TITLE
average_treatment_effect - modification to included covariates 

### ISSUE THREAD

**Issue by njawadekar** [grf-labs/grf#1143]
Based on my current understanding, it appears that when running the _average_treatment_effect_ function to estimate CATEs, the default is for the AIPW it uses to be built on **all of the covariates** that originally went into the causal forest.

Yet, if one or more of such covariates happened to be a collider for the A-Y relationship, then this could be problematic. In light of this, is there any way to modify the covariates utilized to build the AIPW when running _average_treatment_effect_?

**Comment by njawadekar** [comment]
On a related note, I was looking for more general advice about the honest causal forest simulation I am going to run in an observational setting. I specifically wanted to try out a scenario where there are confounders and colliders, but in order to correctly specify the honest causal forest, I need to ensure I am only controlling for the confounders across the model. Where specifically should I be doing this? I am assuming I need to specify these confounders all three of the following places in my honest causal forest, but does this sound right to you?

(1) Specify my confounders as the covariates used for predicting the propensity score regression forest: e(x) = E[W|X=x] as part of the orthogonalization
(2) Specify my confounders as the covariates used for predicting the marginal outcome regression forest: m(x) = E[Y|X=x] as part of the orthogonalization
(3) Specify my confounders as the covariates used in the AIPW in the *average_treatment_effect* function, if this is allowed

**Comment by swager** [comment]
The short story is that if you suspect some of your X-variables may be colliders, you shouldn't use them at any point in training a causal forest. The covariates X you give causal forest should be a set of covariates satisfying unconfoundedness, i.e., {Yi(0), Yi(1)} \indep Wi | Xi. And then once you do this, all of these X can be used for AIPW.

**Comment by njawadekar** [comment]
Thanks - so assuming no colliders are included among the covariates (X), do you generally always recommend as a best practice to just include all of the covariates (including non-confounders) as predictors for both the orthogonalization step as well as the AIPW?

**Comment by swager** [comment]
Yes -- that's a good place to start.
