### ISSUE TITLE
Causal forest

### ISSUE THREAD

**Issue by yvc5154** [grf-labs/grf#1148]
Dear GRF team,

My name is Youngjoo Cho, a person who is studying GRF package. I found that both causal forest (through causal_forest.R) and instrumental forests (through instrumental_forest.R) use InstrumentalSplittingRule.cpp. How can I find (or distinguish) splitting rule for causal forests and instrumental forests in InstrumentalSplittingRule.cpp?

Sincerely,

Youngjoo Cho

**Comment by erikcs** [comment]
Hi, if you set the instrument equal to the treatment, you get the causal forest splitting rule.
