### ISSUE TITLE
Causal survival forests code for paper

### ISSUE THREAD

**Issue by yvc5154** [grf-labs/grf#1154]
Dear GRF team,

My name is Youngjoo Cho, who uses GRF package version 2.0.2. I looked at the causal_survival_forest.R and its reference "Estimating heterogeneous treatment effects with right-censored data via causal survival forests (Cui et al. 2020)". I tried to find expression (11), (13) and pseudo-outcome expression (14) in the paper (see attached) in the causal_survival_forest.R and CausalSurvivalSplittingRule.cpp, but I cannot find them (especially pseudo-outcome expression (14)). Where can I find these expressions in the R and cpp files?

Sincerely,

Youngjoo Cho
![pic1](https://user-images.githubusercontent.com/103315108/170508048-696d3f41-5e4f-41a1-bb6b-ff2487b6370b.png)
![pic2](https://user-images.githubusercontent.com/103315108/170508056-abdeda9b-6df4-46c8-952e-d284784b3c71.png)
![pic3](https://user-images.githubusercontent.com/103315108/170508057-fdabed8a-45dd-437e-8ff4-816d80e5df48.png)
[cui_et_al_2020.pdf](https://github.com/grf-labs/grf/files/8779656/cui_et_al_2020.pdf)

**Comment by erikcs** [comment]
Hi @yvc5154,

(11) solved for tau is decomposed into a numerator and denominator and is computed [here](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/causal_survival_forest.R#L457)

pseudo-outcomes (14) are computed in [CausalSurvivalRelabelingStrategy](https://github.com/grf-labs/grf/blob/master/core/src/relabeling/CausalSurvivalRelabelingStrategy.cpp)

point predictions (13) are computed in [CausalSurvivalPredictionStrategy](https://github.com/grf-labs/grf/blob/master/core/src/prediction/CausalSurvivalPredictionStrategy.cpp)
