### ISSUE TITLE
Obtain similarity weights for predictions causal forest

### ISSUE THREAD

**Issue by RAJP93** [grf-labs/grf#1156]
Dear grf team,

I was wondering whether it is possible to obtain the similarity weights (the alpha_i(x) in eq. (3) in the 2019 aos paper) for predictions. 
E.g. for the following working example

-----------------------------------------------------------------------------------
library(grf)

n <- 100
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
c.forest <- causal_forest(X, Y, W)

c.pred <- predict(c.forest)

X.test<-matrix(0,10,p)
X.test[,1] <- seq(-2,2,length.out=10)
c.pred.new<-predict(c.forest, X.test)

------------------------------------------------------------------------------------

It would be great to obtain a matrix nxn and a 10xn matrix containing the similarity weights where these predictions are based on. 

Many thanks in advance,

Richard Post

**Comment by erikcs** [comment]
Hi Richard, you can get these weights from [get_forest_weights](https://grf-labs.github.io/grf/reference/get_forest_weights.html)
