### ISSUE TITLE
Add example of custom forest for log-likelihood maximization

### ISSUE THREAD

**Issue by tvatter** [grf-labs/grf#117]
Hi,

Let's say that you have a parametric distribution where the goal is to let the parameter(s) be a function of covariates. If its likelihood and its gradient are tractable, it fits neatly within your framework through the score equation(s). For instance, I think that Stefan used forests to estimate the parameters of a GPD as functions of covariates.

I wondered if you could eventually provide an implementation example of CustomRelabelingStrategy/CustomPredictionStrategy for this kind of setup, which encompass, in my opinion, many cases of practical interest.

**Comment by swager** [comment]
I agree that this would be a great example to have. We don't have the bandwidth to do this right now, but should certainly do it at some point.

There's one special case that's particularly nice, though: GLMs. Suppose you want to learn a function theta(x) in the sampling model ``Y | X = x ~ exp(theta(x)Y - psi(theta(x))) * f_0(Y),`` where psi is some known link function (this covers, e.g., logistic regression, Poisson regression, exponential regression, etc.).

Then, an examination of first-order conditions on the log-likelihood implies that ``psi'(theta(x)) = mu(x),`` where ``mu(x) = E[Y | X = x].`` This suggests the following simple forest algorithm:

1. Estimate \hat{mu}(x) via ``regression.forest()`` (which is formally just an estimator for the conditional mean function mu(x)).
2. Get \hat{theta}(x) by solving ``psi'(\hat{theta}(x)) = \hat{mu}(x).``
3. Get confidence intervals via the delta method (i.e., if you have estimated sampling errors s(x) for \hat{mu}(x), just use ``s_{theta} = s(x) / psi''(\hat{theta}(x))`` as a sampling error for \hat{theta}(x)).

Finally -- as an aside -- the GPD example we talked about was in the zero-tail-index case, and so the GPD is just an exponential distribution (i.e., a GLM). So I used the trick above the estimate the parameter of interest.

**Comment by tvatter** [comment]
Yeah, I figured that it was a bandwidth issue and it's perfectly understandable. The GLM example is nice indeed.

I tried to think a bit about doing this outside the exponential family. Am I correct in my understanding that the RelabelingStrategy would amount at computing an MLE for a group of samples? 

If yes, I guess that (a) either the MLE has an analytical solution and a new RelabelingStrategy is (arguably) straightforward, or (b) the MLE has no analytical solution and one needs to numerically solve an optimization problem for each group of samples, which would be computationally burdensome.

If no, what am I missing?

**Comment by swager** [comment]
Yes that's right. Even in case (b), though, we'd only need to compute an MLE once per node (as opposed to once per candidate split); this amounts to computing on the order of n MLEs per tree. This is of course more demanding than case (a), but is still potentially feasible in cases where fast numerical algorithms exist (e.g., if we can get a decent MLE in just a few Newton steps).

**Comment by halflearned** [comment]
This issue seems stale. If there is still demand for this feature in the future, please re-open or file a new issue.
