### ISSUE TITLE
Multi-way Cluster-Robust Variance Estimate

### ISSUE THREAD

**Issue by crudup** [grf-labs/grf#1174]
First of all, thank you for the nice package.

In my project, I have individual data with treatment assignments based on year-country of residence. I was wondering whether GRF allows for a two-way cluster robust variance estimate. So far, I generated the clusters at the intersection of the two groupings (which is clearly wrong since imposes the restriction that observations are independent if they are in the same country but in different years). 

In the standard OLS Case, Cameron and Miller (2015) circumvent the issue by proposing the following:
_"For two-way clustering this robust variance estimator is easy to implement given software that computes the usual one-way cluster-robust estimate. First obtain three different cluster-robust “variance” matrices for the estimator by one-way clustering in, respectively, the first dimension, the second dimension, and by the intersection of the first and second dimensions. Then add the first two variance matrices and, to account for double-counting, subtract the third."_

Does it make any sense in the GRF framework?

**Comment by erikcs** [comment]
Hi @crudup, no, sorry, this is not something that easily extends to GRF (#533)
