### ISSUE TITLE
Testing for difference in treatment effects between groups

### ISSUE THREAD

**Issue by GalAmedi** [grf-labs/grf#1176]
Hey. First I would like to thank you for the development of the package and helpful replies here.

I have an application where I'm interested in the difference between the average treatment effect between different groups in the sample. For example, for some variable X, I want to know if the treatment effect in observations who has a high value of X (e.g., top quartile) have a treatment effect statistically different than the treatment effect for observations with a low value of X (e.g, bottom quartile). 

The best solution I have in mind is to estimate the average treatment effect for both groups separately using the 
`average_treatment_effect` function and proceed by conducting a Z test:

$Z = \frac{\beta_1 - \beta_2}{\sqrt{(SE\beta_1)^2+(SE\beta_2)^2}}$

Is there a more general or appropriate approach to answer this question?

**Comment by erikcs** [comment]
Hi @GalAmedi, yes that sounds reasonable if you decided on the Xj-subgroups w/o looking at the estimated tau.hats. 

@halflearned has a nice guide on this + data-driven subgroups [here](https://bookdown.org/stanfordgsbsilab/ml-ci-tutorial/hte-i-binary-treatment.html#data-driven-hypotheses) if that could be of interest.

**Comment by GalAmedi** [comment]
Hey Erik, thanks for the helpful reply. I'm closing the issue.

Gal
