### ISSUE TITLE
mean.forest.prediction in test_calibration 

### ISSUE THREAD

**Issue by LuqianSun** [grf-labs/grf#1179]
Is it important for the "mean.forest.prediction" to be significant? 
And is it possible to parallel the test_calibration function? Because we found we need more than one hour to get the results.
By the way, is tune.parameters ='TRUE'  in grf 0.10.2 equal to the tune.parameters ='ALL' in latest version?

**Comment by erikcs** [comment]
> And is it possible to parallel the test_calibration function? Because we found we need more than one hour to get the results.

https://grf-labs.github.io/grf/reference/test_calibration.html: 
`vcov.type | (...) For large data sets with clusters, "HC0" or "HC1" are significantly faster to compute.`


> By the way, is tune.parameters ='TRUE' in grf 0.10.2 equal to the tune.parameters ='ALL' in latest version?

Yes

**Comment by erikcs** [comment]
closing as covered in #1173

**Comment by LuqianSun** [comment]
If we select HC0 and HC1, do we follow the criteria in the tutorial?

**Comment by erikcs** [comment]
Yes, using HC0 or HC1 should barely change the std.errors

**Comment by LuqianSun** [comment]
Thanks for your reply! So how much computational complexity can be reduced for HC0 and HC1 compared to HC3?

**Comment by erikcs** [comment]
HC1 or HC0 should take just seconds

**Comment by LuqianSun** [comment]
Well, I just tried HC0 1 hour ago. And it takes more 1 hour for my data... Any ideas about that?

**Comment by erikcs** [comment]
Then I do not know what you are doing:

```R
library(grf)
n = 1e6
clusters = sample(1:10000, n, T)
X = matrix(runif(n), n, 1)
Y = runif(n)
W = rbinom(n, 1, 0.5)

cf = causal_forest(X, Y, W, W.hat = 0.5, Y.hat = 0.5,
                   clusters = clusters,
                   min.node.size = n, num.trees = 10, sample.fraction = 0.01)


system.time(test_calibration(cf, vcov.type = "HC0"))
# user  system elapsed 
# 0.988   0.177   1.174 


```
