### ISSUE TITLE
Test regression forest prediction performance in Orthogonal Causal Forest 

### ISSUE THREAD

**Issue by LuqianSun** [grf-labs/grf#1185]
Is there any way to test the regression forest performance in the orthogonal causal forest? Should we tune the parameters in W.forest and Y.forest? And How to set num_trees in forest.Y, forest.W and tau.forest?

```
forest.Y <- regression_forest(X, Y,cluster = Clusters,
          #tune.parameters= 'all'
          )
forest.W <- regression_forest(X, W,cluster = Clusters,
        #tune.parameters=  'all'
        )
tau.forest <- causal_forest(X, Y, W,num.trees = 10000,
                                  W.hat = W.hat, Y.hat = Y.hat,
                                  tune.parameters =  tune,
                                  clusters= Clusters)
```

**Comment by erikcs** [comment]
You can gauge a regression_forest forest's fit with its MSE. You can tune them if you want, `num.trees` are 500 by default for W.hat and Y.hat.

**Comment by erikcs** [comment]
Btw, it's great you have questions on GRF, but maybe if you have many you could collect them all in one issue? (That makes it easier to remember to respond), also feel free emailing one of us, if you have tons of things to ask we could do a zoom one time
