### ISSUE TITLE
What does the function "predict" return when the exposure variable is continuous? 

### ISSUE THREAD

**Issue by panqinglzmc** [grf-labs/grf#1186]
When the exposure variable is binary, the function "predict" will return weighted Tau(i) which is calculated as the difference of potential outcomes between treat and control groups within one leaf.

However, when the exposure is continuous, as the exposure level W(i) has more than one counterfactual outcome, the Tau(i) can not be calculated. 

So, what dose the function "predict" in grf generated?

**Comment by erikcs** [comment]
Hi @panqinglzmc, 

From the [docs](https://grf-labs.github.io/grf/reference/causal_forest.html):
>When W is continuous, we effectively estimate an average partial effect Cov[Y, W | X = x] / Var[W | X = x], and interpret it as a treatment effect given unconfoundedness.

**Comment by panqinglzmc** [comment]
@erikcs Ok, I see. Thanks a lot for your valuable reply.
