### ISSUE TITLE
Questions regarding clusters for the first stage in the orthogonal  causal forest 

### ISSUE THREAD

**Issue by LuqianSun** [grf-labs/grf#1187]
hi, in the R documentation, Y.hat can be predicted by boosted regression forest. Can it be used to predict W.hat?

Also, in the paper "Estimating Treatment Effects with Causal Forests: An Application", the authors mention we can use other predictive methods like boosting with cross-ﬁtting, is there any examples for that?

**Comment by erikcs** [comment]
Yes, you can use any good prediction method to predict Y.hat and W.hat. If you know the treatment propensities you can just supply that instead.

**Comment by LuqianSun** [comment]
Thanks a lot, Eric!  I meant to ask whether in the first stage when predicting Y_hat and W_hat if we should also set clusters=city_name? We have checked "Estimating Treatment Effects with Causal Forests: An Application" paper and grf GitHub menu and site but could not figure out what is the difference whether setting clusters or not in predicting Y-hat and W_hat.

What exactly does it mean to set clusters=school.id in Wager's "Estimating Treatment Effects with Causal Forests: An Application" paper's case in regression_forest?

Does this give different predictions compared with not setting clusters=school.id when predicting Y_hat and W_hat?

**Comment by erikcs** [comment]
Hi @LuqianSun, yes setting clusters for W.hat and Y.hat makes sense if you are setting them for causal forest. The online reference has a section on clustering here: https://grf-labs.github.io/grf/REFERENCE.html#cluster-robust-estimation
