### ISSUE TITLE
Is there a general rule for finding out the most representative heterogeneous treatment effect structure in grf?

### ISSUE THREAD

**Issue by panqinglzmc** [grf-labs/grf#1192]
A well defined heterogeneous treatment effect structure is important to inform a feasible practice in precision medicine. A single tree can generate a clear structure while it is sensitive to the variation of included samples. Although a forest with many trees can give a more robust prediction on individual treatment effect, it can not tell which tree structure is the most representative one which is key to medical practice.

So, is there a general rule for finding out the most representative heterogeneous treatment effect structure in grf?

**Comment by erikcs** [comment]
Hi @panqinglzmc, the tool you'd use for this depends on the question you are asking. If you want a linear association summary of the CATE that has good semi-parametric inferential properties: [best_linear_projection](https://grf-labs.github.io/grf/reference/best_linear_projection.html)  (a short overview of this in the context of grf is in section 3.2 in https://arxiv.org/pdf/2001.09887.pdf). If you want a simple tree based policy: https://github.com/grf-labs/policytree (a tutorial on this is [here](https://bookdown.org/stanfordgsbsilab/ml-ci-tutorial/policy-learning-i---binary-treatment.html). If you want to evaluate how well the estimated CATEs do in ranking individuals: [rank_average_treatment_effect](https://grf-labs.github.io/grf/reference/rank_average_treatment_effect.html) (intro vignette [here](https://grf-labs.github.io/grf/articles/rate.html)).
