### ISSUE TITLE
Question about the estimated variance

### ISSUE THREAD

**Issue by lucatrapin** [grf-labs/grf#1193]
Hi,

using the function predict() with the option estimate.variance=TRUE one can obtain both predictions and the corresponding variance estimates from the random forest. I was wondering how the package computes the variance but I cannot find any detail in the R documentation.

Is the infinitesimal jackknife used?

**Comment by erikcs** [comment]
Hi @lucatrapin, section 4 in https://arxiv.org/pdf/1610.01271.pdf describes the approach to CIs (bootstrap of little bags). A short description is in the online reference: https://grf-labs.github.io/grf/REFERENCE.html#variance-estimates
