### ISSUE TITLE
Minor issue in ll_regression_forest()

### ISSUE THREAD

**Issue by tmieno2** [grf-labs/grf#1197]
Hi @erikcs,

**Issue**: `ll_regression_forest()` can take a data.frame without `enable.ll.split = TRUE`, but cannot with it. I am using the latest version of the `grf` package. This is not a critical issue because we can just use X in matrix form. But, just wanted to let you know because I think this is not the intended behavior.

**Reproducible examples**:

```r
N <- 1000
data <- data.table(x1 = runif(N), x2 = runif(N), y  = runif(N))

# this works (X as a data.frame, enable.ll.split = FALSE)
ll_regression_forest(
    X = data[, .(x1, x2)],
    Y = data[, y]
  )

# this works (X as a matrix, enable.ll.split = TRUE)
ll_regression_forest(
    X = data[, .(x1, x2)] %>% as.matrix(),
    Y = data[, y],
    enable.ll.split = TRUE
  )

# this does not (X as a data.frame, enable.ll.split = TRUE)
ll_regression_forest(
    X = data[, .(x1, x2)],
    Y = data[, y],
    enable.ll.split = TRUE
  )
```

**Comment by erikcs** [comment]
Thanks for the notice @tmieno2, it's fixed now
