### ISSUE TITLE
Question on pseudo outcome for causal forest

### ISSUE THREAD

**Issue by tmieno2** [grf-labs/grf#1199]
Hi @erikcs,

Could you tell me what the pseudo outcome, $\rho_i$, looks like for causal forest? 

Since it follows the R-learner process, you have 

$$
\Psi(O_i) = \tilde{Y_i} - \theta \cdot \tilde{T_i}
$$

where  $\tilde{Y_i}$ and $\tilde{T_i}$ are the estimates of $Y_i - E[Y_i|X_i]$ and $T_i - E[T_i|X_i]$, respectively, obtained at the first stage.

Then,

$$
A_P = \frac{1}{|\{i:X_i\in P\}|}\sum_{i:X_i\in P} - \tilde{T_i} = -\bar{\tilde{T_i}}
$$

So, $A_P$ is the negative of the mean of $\tilde{T_i}$, which is just a constant.

Then, 

$$
\rho_i = \frac{\tilde{Y_i} - \hat{\theta}_P \cdot \tilde{T_i}}{\bar{\tilde{T_i}}}
$$

, which I believe is the same as setting 

$$
\rho_i = \tilde{Y_i} - \hat{\theta}_P \cdot \tilde{T_i}
$$

because $\bar{\tilde{T_i}}$ is just a constant and does not affect the splitting process?

**Comment by erikcs** [comment]
Hi @tmieno2, since $A_p$

**Comment by tmieno2** [comment]
Thanks for referring me to the paper, and the way score function is derived from the $L_2$ loss minimization problem makes a lot of sense. But, this seems to be inconsistent with the general procedure presented in the GRF paper. Throughout the GRF paper, score function is denoted by $\psi_{\theta,\nu}$. According to equation (4) in the GRF paper, 

<img width="1011" alt="Screen Shot 2022-08-06 at 9 07 41 PM" src="https://user-images.githubusercontent.com/13700450/183272222-a4a5435e-26d1-4e70-84e3-de66927a2444.png">

it looks like the score function, $\psi_{\theta,\nu}$, for CF has to be $\tilde{Y}_i - \theta\tilde{T}_i$ because you would like to minimize the sum of $(\tilde{Y}_i - \theta\tilde{T}_i)^2$. But, it looks like $\psi()$ in equation (4) needs to be residuals rather than the score function for CF.

**Comment by erikcs** [comment]
Sorry, I don't get the question? The first sentence of 6.1 in https://arxiv.org/pdf/1610.01271.pdf defines the score $\psi$ for causal forest, i.e. that of a regression of the (residualized) outcome on an intercept + treatment. Centering the outcome and treatment residuals by the respective parent means (_P subscript) takes care of the intercept $c(x)$ and you end up with pseudo outcomes (20),  where $A_p$ can be ignored for splitting purposes.

**Comment by tmieno2** [comment]
Oh, I think I understand what my confusion was in my previous comment now. Thanks a lot.
