### ISSUE TITLE
Ranger always.split.variables to help with staggered treatments?

### ISSUE THREAD

**Issue by Hergie** [grf-labs/grf#1200]
Hello,

I study staggered treatments in which some individuals are treated in January, others in February etc. The data include "control" individuals who are never treated for whom I observe outcomes in all treatment months. I want to measure the treatment effect in the month of treatment by comparing treated individuals to untreated individuals in the same month (because seasonal variation makes it nonsensical to compare outcomes across months). How to ensure that the algorithm always considers the month of observation when making predictions of the individual treatment effect? I'm thinking of something like the `always.split.variables` option in ranger. Would one option actually be to estimate `Y.hat` with ranger while requiring ranger to split on observation month?

**Comment by erikcs** [comment]
Hi @Hergie, a better approach might be to look at #1057, #973. (in general you can make GRF more likely to split on a covariate Xj by just duplicating it several times - feature weights are not yet added, #1097).
