### ISSUE TITLE
Plot tree with probability_forest

### ISSUE THREAD

**Issue by jackobenco016** [grf-labs/grf#1201]
Hello,

I tried to plot a tree (get_tree) from a forest created with probability_forest function.
The issue is that the plot doesn't give me the proportion of the labels in each leaf.
I just got the leaf's size. How can I solve that ?

Thanks
Have a good day

**Comment by erikcs** [comment]
Hi @jackobenco016, we haven't added a [leaf label](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/analysis_tools.R#L294) method for probability forest yet, you can define one yourself if you want:


```R
p <- 5
n <- 250
X <- matrix(rnorm(n*p), n, p)
Y <- as.factor(sample(c("A", "B", "C"), n, TRUE))
forest <- probability_forest(X, Y)

leaf_stats.probability_forest <- function(forest, samples, ...) {
  leaf_stats <- summary(forest$Y.orig[samples]) / length(samples)
  
  round(leaf_stats, 2)
}

plot(tree <- get_tree(forest, 1))
```
