### ISSUE TITLE
How to handle missing data in honest causal forest

### ISSUE THREAD

**Issue by njawadekar** [grf-labs/grf#1216]
Hi,
I am writing to better understand how the honest_causal_forest handles missing data. According to this [tutorial](https://grf-labs.github.io/grf/REFERENCE.html#missing-values), this algorithm is able to deal with missing covariate values (meaning it is okay for some covariate values to have the value of NA in them). 

Yet, when I tried running an honest causal forest in GRF with some numeric covariates with some NA's, I got the following error: 
_Error in validate_observations(Y, X) : 
  length of observation (W, Y, Z or D) does not equal nrow(X)._

This error made it seem to me that it is _not_ okay for there to be missing values in the covariates (X) that we use for the honest causal forest. But when I removed those rows with any NA's before re-running the causal forest, that fixed the issue and the causal forest ran without error. Ideally, however, I would like to keep all my rows (even those with some NAs) when running the causal forest. Any advice on how to approach this would be appreciated - thanks!

**Comment by erikcs** [comment]
Hi, @njawadekar, yes causal_forest supports NA in X, I am not sure what you tried:
```R
n <- 1000
p <- 5
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)

X[cbind(sample(1:n, 200), sample(1:p, 200, replace = TRUE))] <- NA
sum(is.na(X))
# [1] 200

cf <- causal_forest(X, Y, W)
cf
# GRF forest object of type causal_forest 
# Number of trees: 2000 
# Number of training samples: 1000 
# Variable importance: 
#   1     2     3     4     5 
# 0.625 0.084 0.104 0.089 0.099 
```

**Comment by njawadekar** [comment]
Thanks for clarifying! I was able to fix it. Turns out I was using the wrong function to create the matrix for X. But now when using the data.matrix function on the set of covariates that make up X, it runs without error when I run the causal forest on it.

`X = data.matrix(dataframe[, c(3, 4, 5, 6, 9:95)])`
