### ISSUE TITLE
ll_regression_forest(X, y, enable.ll.split = TRUE) Error in solve.default(t(D) %*% D + ll.split.lambda * J)

### ISSUE THREAD

**Issue by EoghanONeill** [grf-labs/grf#1228]
**Description of the bug**
``ll_regression_forest`` produces the following error message when ``enable.ll.split = TRUE`` and ``ll.split.lambda`` is set to the default value.

```
 Error in solve.default(t(D) %*% D + ll.split.lambda * J)
  system is computationally singular: reciprocal condition number = 2.10688e-26
```

**Steps to reproduce**

[y_bugexample.csv](https://github.com/grf-labs/grf/files/9559969/y_bugexample.csv)
[X_bugexample.csv](https://github.com/grf-labs/grf/files/9559970/X_bugexample.csv)

The data is attached to this issue, and the example code is below:

```

# Example ll_regression_forest bug

library(grf)

X = read.csv( file = "X_bugexample.csv")
X <- as.matrix(X, nrow = nrow(X), ncol = ncol(X))

y = read.csv( file = "y_bugexample.csv")
y <- as.matrix(y, nrow = nrow(y), ncol = ncol(y))

# Produces error
model <- ll_regression_forest(X, y, enable.ll.split = TRUE)

# Does not produce error
model <- ll_regression_forest(X, y, enable.ll.split = TRUE,
                              ll.split.lambda = 10^1000)

```

Perhaps this error is unavoidable for some datasets and the default value of `` ll.split.lambda ``

**GRF version**
 grf             * 2.2.0     2022-08-06 [1] CRAN (R 4.1.3)

**Comment by erikcs** [comment]
Hi @EoghanONeill, yes you are right that error is unavoidable for some data sets. Your X has more covariates than samples so a default ~ols won't work.

You can skip that "overall" beta calculation (`ll.split.cutoff=0`) and only use a subset of the variables (`ll.split.variables`) for the local liner step by doing for example

```
model <- ll_regression_forest(X, y, enable.ll.split = TRUE, ll.split.cutoff = 0, ll.split.variables = 1:4)
```

**Comment by EoghanONeill** [comment]
Thank you for the quick reply @erikcs . I realize now that ``J[1,1] <- 0`` on line 144 of ``ll_regression_forest.R`` , as in the local linear forests paper. This explains how the matrix is not necessarily invertible. I will close the issue now.
