### ISSUE TITLE
How to know which subjects are included in prioritized fraction from RATE

### ISSUE THREAD

**Issue by Jinwoo-Yi** [grf-labs/grf#1229]
Hi, guys!
First of all, thanks for publishing beautiful causal inference tool. 

I'm trying to estimate causal effects of discriminative experiences W on the mental health outcome(e.g. stress) Y using grf.

1) The average treatment effect of W on outcome Y seems to be significant robustly.
2) I divide vulnerable and resilient groups in terms of their tau.hat based on aipw.scores. Below is my code;
`aipw.scores <- get_scores(cf)`
`res_condition <- tau.hat < median(aipw.scores)`
`vul_condition <- tau.hat > median(aipw.scores)`
**3) However, when I got estimates and p-value of ATE for each group(i.e., res/vul groups) through average_treatment_effect functions, the estimation of ATE for resilience group is much bigger than ATE for vulnerable group ironically. The differences between them is also significant.**

I tested this in terms of various Y1, Y2, ..., Yn and found similar pattern across all results. How can I explain this? Above result seems to imply the existence of heterogeneity, but the interpretation is intuitive because the vulnerable groups got smaller effects than the resilient group did. Furthermore, the estimation of RATE was significant, but its value was negative. 

The result of test_calibration function indicates that the mean_forest_prediction is about .963 (p < .001) and differential.forest.prediction is about -5.234 (p = .998). I guess that there was serious issue in estimating heterogeneity...

One thing I guess about this issue is that there are too many covariates in my model. Specifically, I selected 250 covariates from 370 ones based on their variable importances and there are 1,100 subjects in this model. So, I would like to get advice from you guys about 1) the origins of these issues and 2) future directions for the analysis. 

I look forward from you guys. Thanks!

Sincerely,
Jinwoo Yi

**Comment by Jinwoo-Yi** [comment]
Oh, I found significant and plausible heterogeneity through reducing covariate dimensions, tuning causal forests and using RATE function(RATE est = .364, p = .036). In this context, I have another question about interpreting results from RATE function.

As you can see in attached TOC curve, the results from RATE point out that there are monotonic decrease in TOC curve after q=0.4. For this reason, I defined this prioritized as a  'vulnerable' group (i.e., who got the bigger treatment effects on mental health outcome Y from violent treatment W) and the rest of whole subjects as a 'base' group. Then, I would like to inspect the statistical differences in covariates between these two groups in order to find vulnerable factor. To achieve this, it will be meaningful to find which subjects are included in vulnerable group (q < 0.4). Is there any function or approach which I can use for this? 

![toc_curve](https://user-images.githubusercontent.com/97580229/192090969-edb78186-3769-4d8d-98c6-a07e586c6326.png)

**Comment by erikcs** [comment]
Hi @Jinwoo-Yi,

> I tested this in terms of various Y1, Y2, ..., Yn and found similar pattern across all results. How can I explain this? Above result seems to imply the existence of heterogeneity, but the interpretation is intuitive because the vulnerable groups got smaller effects than the resilient group did. Furthermore, the estimation of RATE was significant, but its value was negative.
>The result of test_calibration function indicates that the mean_forest_prediction is about .963 (p < .001) and differential.forest.prediction is about -5.234 (p = .998). I guess that there was serious issue in estimating heterogeneity...

Yes, this can happen, particularly on data with very weak signal. One reason why the RATE is negative even though it's ranking by positive CATEs can be because of OOB bias, if you do a train/test split like here https://grf-labs.github.io/grf/reference/rank_average_treatment_effect.html#examples you'd ideally see something different

> One thing I guess about this issue is that there are too many covariates in my model. Specifically, I selected 250 covariates from 370 ones based on their variable importances and there are 1,100 subjects in this model. 

Yes, that is not a very large sample size and reducing the dimensionality may help a lot.

For the TOC plot, if you are using OOB CATEs as priorities, then the x-axis is the fraction of units with the q-th highest estimated CATEs, so in your plot that would be the units with `tau.hat.oob > quantile(tau.hat.oob, 1 - 0.4)` (ps the value on the TOC curve `rate$TOC` at that point is `average_treatment_effect(forest, subset = tau.hat.oob > quantile(tau.hat.oob, 1 - 0.4)) - average_treatment_effect(forest)`)

**Comment by Jinwoo-Yi** [comment]
Your reply gave me a lot of help. I guess that this method is more reliable and intuitive than the heterogeneity-check approach introduced in the 2.2 section from "Estimating Treatment Effects with Causal Forests: An Application (2019)". Thanks!
