### ISSUE TITLE
calibration test for a subpopulation

### ISSUE THREAD

**Issue by robert702** [grf-labs/grf#1234]
I am training a causal forest with a large sample 500,000 observations on educational outcomes.  I want to measure the effect of the treatment on the time they spent on math assignments. In addition to general treatment effect heterogeneity, I am interested on treatment effect heterogeneity among students who enrolled in one particular elective. Only about 10% of them are enrolled in this elective.

I trained a causal forest on math assignments. and there is treatment effect heterogeneity according to the standard calibration test considering all 500k observations.

I want to see if there is treatment effect heterogeneity on math outcomes, among students who are enrolled in this elective. 
**Is it valid to test for treatment effect heterogeneity, running the calibration test (manually, see below) among this subpopulation (50K observations), but using the predictions of the causal forest that was trained with the full sample (500k).** 

Or do I need to train a separate causal forest for individuals who enrolled in that particular elective?

Thank you.

Manual calibration, among subpopulation:

preds <- predict(forest)$predictions
mean.pred <- mean(preds)
DF <- data.frame(
  target = unname(forest$Y.orig - forest$Y.hat),
  mean.forest.prediction = unname(forest$W.orig - forest$W.hat) * mean.pred,
  differential.forest.prediction = unname(forest$W.orig - forest$W.hat) *
    (preds - mean.pred), elective)

DF<- subset(DF, electve==1)

lm(target ~ mean.forest.prediction + differential.forest.prediction + 0,   data = DF)

**Comment by erikcs** [comment]
Hi @robert702, a simpler way to assess heterogeneity is to compute the [RATE](https://grf-labs.github.io/grf/reference/rank_average_treatment_effect.html) and look at the corresponding "TOC".  That function takes a `subset` argument you can use to define the sample you want a TOC for (ps, a vignette is [here](https://grf-labs.github.io/grf/articles/rate.html))
