### ISSUE TITLE
Treatment effect for binary outcome

### ISSUE THREAD

**Issue by ilovemane** [grf-labs/grf#1235]
Hi Grf team,

I am studying the grf package, I wonder is there a way to express the treatment effect for binary outcome as an log odd ratio? 

thanks,

Mike

**Comment by erikcs** [comment]
Hi @ilovemane, grf does not estimate this directly, however you can back out the implicit estimates of E[Y(1)|X] and E[Y(0)|X] ([example](https://grf-labs.github.io/grf/articles/muhats.html)) and construct it yourself (ref #720, #120).

As for forests that directly targets the odds ratio, I think @dandls and @thothorn may have something in the works in https://arxiv.org/abs/2210.02836 which can estimate objects of this sort using their model-based forests.

**Comment by ilovemane** [comment]
Thanks! @erikcs , I also want to compute the SE for odd ratios. Is there a way to compute that as well with output from Grf?

thanks,

Mike

**Comment by erikcs** [comment]
> I also want to compute the SE for odd ratios. Is there a way to compute that as well with output from Grf?

Not currently, sorry
