### ISSUE TITLE
bug in generate_causal_data

### ISSUE THREAD

**Issue by bokelmab** [grf-labs/grf#1239]
Dear authors,

thank you for providing the nice package. I just want to inform you about a bug in the generate_causal_data function. For the settings "ai1" and "ai2" the covariates are created by X <- matrix(rnorm(n, p), n, p). This is wrong, as it rather should be X <- matrix(rnorm(n * p), n, p).

Best regards,
Björn Bokelmann

**Comment by erikcs** [comment]
Thanks for pointing out that typo, do you want to send a PR?
