### ISSUE TITLE
Wrong similarity weights in example of algorithm reference

### ISSUE THREAD

**Issue by JeGemm** [grf-labs/grf#1251]
Hi everyone, 

in the "General Algorithm: Prediction" section of the algorithm reference, wrong similarity weights are calculated in the table.
In my view, it should be:

- Weight for training example 1: **4/9** (calculated from tree-specific weights 1/3; 0; 1)
- Weight for training example 2: **0** (calculated from tree-specific weights 0; 0; 0)
- Weight for training example 3: **1/9** (calculated from tree-specific weights 1/3; 0; 0)
- Weight for training example 4: **4/9** (calculated from tree-specific weights 1/3; 1; 0)

Using these weights, the final prediction for test sample x is 3.78 (and not 3.6).

Please correct me if I'm missing something & thank you for this great package!
Best,
Jens

**Comment by erikcs** [comment]
Hi @JeGemm, good catch, you are correct!
