### ISSUE TITLE
Selecting balanced splits in instrumental forests

### ISSUE THREAD

**Issue by JeGemm** [grf-labs/grf#1256]
Hi grf team,

I am currently trying to follow how instrumental forests select balanced splits. I have read the corresponding section in the algorithm reference for causal forests, but I suppose that this does not fully apply to instrumental forests.

In particular, I'm interested in:
1. how _min.node.size_ is determined
2. what the node size measure is which is used together with _alpha_ and _imbalance.penalty_
3. what changes in 1. and 2. if _stabilize.splits_ is set to FALSE

Thank you for your support & best regards,
Jens

**Comment by erikcs** [comment]
Hi @JeGemm, instrumental forest does [balanced splits](https://grf-labs.github.io/grf/REFERENCE.html#selecting-balanced-splits) the same way, just replace treatment with instrument. `min.node.size` is a tuning parameter and `stabilize.splits=FALSE` is just plain regression splits with the corresponding constraint a standard regression forest would have.

**Comment by JeGemm** [comment]
Hi @erikcs, thank you! 

I have one remaining question: In this [commit](https://github.com/grf-labs/grf/commit/038e26276f9c61f47a609e24025b2e97a8434045), min.node.size for instrumental forests is described as: 

"For instrumental splitting, use a tailored interpretation of min.node.size. Now, there can be no fewer than min.node.size samples in each leaf with instrument less than the parent's mean instrument, and no fewer with a greater instrument. In the case of causal estimation with binary treatment, this rule enforces that there are no fewer than min.node.size
treatment and control samples in each leaf."

Following the code in [InstrumentalSplittingRule.cpp](https://github.com/grf-labs/grf/blob/7fe6d08c3f20918cfc12110a93e0d56805e73d40/core/src/splitting/InstrumentalSplittingRule.cpp), I can't see how min.node.size puts a requirement on the number of treatment and control samples in a leaf?

Best,
Jens

**Comment by erikcs** [comment]
Hi Jens, in that code, when used by causal forest, then the instrument is set to the treatment.
