### ISSUE TITLE
How can I model Binomial (n, k) and Poisson outcomes

### ISSUE THREAD

**Issue by anirudhtomer** [grf-labs/grf#1257]
Dear team,

I am working with very large datasets with binary outcome and categorical covariates. Consequently running 1000's of iterations in the causal forest is very time consuming. However, I can convert the large datasets into a sparse format easily using Binomial (n, k) format instead (see https://stats.stackexchange.com/questions/144121/logistic-regression-bernoulli-vs-binomial-response-variables). Is there a way I can estimate the conditional average treatment effect using this representation of the data.

Thank you,
Anirudh

**Comment by erikcs** [comment]
Hi @anirudhtomer, if you mean that your data has many units with the same covariates and outcomes you could collapse them using sample.weights

**Comment by erikcs** [comment]
Hi @anirudhtomer, your aggregated data only contains ~8 rows, which isn't that much to fit a forest on. With subsampling + honest splitting each tree bare uses a single observation.

Besides the aggregated size your example looks reasonable:

```
> lm(aggregated_data$Y ~ aggregated_data$W, weights = aggregated_data$weights)

Call:
lm(formula = aggregated_data$Y ~ aggregated_data$W, weights = aggregated_data$weights)

Coefficients:
      (Intercept)  aggregated_data$W  
           0.4102             0.3652  

> lm(unaggregated_data$Y ~ unaggregated_data$W) 

Call:
lm(formula = unaggregated_data$Y ~ unaggregated_data$W)

Coefficients:
        (Intercept)  unaggregated_data$W  
             0.4102               0.3652  

> cfa = causal_forest(aggregated_data[,"X", drop=F], aggregated_data$Y, aggregated_data$W,
+                     sample.weights = aggregated_data$weights,
+                     W.hat = 0, Y.hat = 0, honesty = FALSE)
> mean(cfa$predictions)
[1] 0.3296694
```

**Comment by anirudhtomer** [comment]
Dear Erik,

Thank you for the reply. Then I would like to extend the grf package to my specific use case. Given the huge size of the datasets we have at our organization, fitting a grf with 500-1000 iterations is next to impossible.  Hence my aim is to fit model with the aggregated data frequencies (repeated number of rows/weights) rather than individual rows. I want to request you for some advice / starting pointers on how to modify the underlying code for this. 

Thank you
Anirudhll

**Comment by erikcs** [comment]
Sorry if I am misunderstanding, what is it that you need to extend? You could just use sample weights on the aggregated data? PS: https://grf-labs.github.io/grf/REFERENCE.html#grf-isnt-working-well-on-a-massive-dataset

**Comment by anirudhtomer** [comment]
Dear Erik,

Thank you for the reply with the link. It is indeed quite informative. 

Now what I want to do is "make the package work with the aggregated data". Currently, as you mentionted "With subsampling + honest splitting each tree barely uses a single observation." This is the case because the code splits data in rowwise manner. My aim is to aggregate the data into the compact form and then change the tree code to start using the frequencies. For example, if I want to split my 8 rows of data data for honest subsampling I would do subsampling this way. However, the current implementation is not suitable for it. Basically I am aiming to change the code to work on frequency data. Apologies if I am not able to explain my thoughts correctly, but happy to provide more examples. 

```
honesty_fraction = 0.25
test_data_aggregated = aggregated_data %>% 
  mutate(
    weights = c(
        rmultinom(
          n = 1, 
          size = round(sum(aggregated_data$weights) * honesty_fraction), 
          prob = aggregated_data$weights/sum(aggregated_data$weights)
        )
    )
  )

```

**Comment by erikcs** [comment]
Hi @anirudhtomer, grf works with aggregated data if you give it an appropriately sized data set. If you make your aggregated example much larger than 8, the sample weighted result will look much closer.
