### ISSUE TITLE
Using causal forest for event studies 

### ISSUE THREAD

**Issue by LauraWeile** [grf-labs/grf#1268]
Hi. 
I am new here, but I hope you can help me. I wish to use the causal forest for event studies, but I have a problem with the regression specification: I want to include som year fixed effects in the leaf regressions but not allowing the algorithm to split based on these dummy variables. Do any of you know whether it is possible to limit which variables the algorithm splits on? 
Any suggestions or idea are greatly appreciated! :-)

**Comment by erikcs** [comment]
Hi @LauraWeile, causal forest controls for covariates non-parametrically, fixed effects doesn't really carry over a meaning in this setting (https://github.com/grf-labs/grf/issues/631#issuecomment-600737559)

You could have a look at section 2.3.3 in https://pure.au.dk/portal/files/198663023/Nicolaj_Mu_hlbach_PhD_dissertation.pdf or https://arxiv.org/pdf/1905.11622.pdf for approaches to use CF in various panel designs using first-differences.
