### ISSUE TITLE
Sample weights

### ISSUE THREAD

**Issue by patr1ckm** [grf-labs/grf#128]
Just curious if there was bandwidth/interest in adding sample weights for training? If not, would you be open to a PR?

Thanks for your time!

**Comment by swager** [comment]
Yes there's been a fair amount of interest, but we haven't had the bandwidth for it yet. We'd certainly be open to a PR.

**Comment by jtibshirani** [comment]
A quick update -- the following two PRs have merged, which add basic support for sample weighting: #376 (for regression forests), #418 (for causal and instrumental forests). This feature is currently marked 'experimental', and will be released in 0.10.3.

I'll leave this issue open for now as we test it further. A remaining open question is if we want to incorporate sample weights into tree splitting (in addition to prediction, as we already do).

**Comment by swager** [comment]
Weighting now appears to be stable, so I'm closing this issue. Some remaining considerations are tracked in a new (non 1.0 release) ticket, #473.

Thanks everyone for your help with this!
