### ISSUE TITLE
estimate_average_effect function for test sample

### ISSUE THREAD

**Issue by jsrich** [grf-labs/grf#129]
It would be helpful to have the ability in the grf package to generate a doubly-robust ATE estimate for a separate test dataset. Right now I can use the predict statement to generate predictions of tau in a test dataset; however, taking the average of the predictions may yield very different results than the doubly-robust estimator for the ATE in situations where there is large shrinkage bias (as is the case in my data).

**Comment by erikcs** [comment]
Hi @jsrich, this is pretty late follow-up, but we've added a simple vignette describing a function you could copy/paste to estimate ATEs + SEs on a new test set here: https://grf-labs.github.io/grf/articles/ate_transport.html
