### ISSUE TITLE
What version of R / RStudio do I need to install grf version 0.10.2?

### ISSUE THREAD

**Issue by HeinzEllman** [grf-labs/grf#1295]
Hello,
I need to consistently replicate parts of the grf paper in Rstudio for my seminar. Due to breaking changes in updated versions of grf, which may or may not change results, I'd like to download the most recent version of grf which doesn't mention any breaking changes, see:
https://grf-labs.github.io/grf/CHANGELOG.html#changed

So what I tried so far with R 4.3.0 :
grf_ver_0.10.2 <- "https://cran.r-project.org/src/contrib/Archive/grf/grf_0.10.2.tar.gz"
install.packages("grf_ver_0.10.2", type = "source")
 ### Note that I need Rtools 4.3 in order to install packages from source.
I get an error:
Warning in install.packages: 
package ‘grf_ver_0.10.2’ is not available for this version of R

I also tried the same procedure with R versions 3.5.0 and 3.5.1 which released prior to the targeted grf update, however it gave me the same error message. I'd be happy for any advice on how to tackle this problem. Thanks for your time.

**Comment by erikcs** [comment]
Hi @HeinzEllman, you need to add one extra argument to install.packages, the following works here:
```
install.packages("https://cran.r-project.org/src/contrib/Archive/grf/grf_0.10.2.tar.gz", type = "source", repos = NULL)
```

**Comment by HeinzEllman** [comment]
Thank you very much erikcs, now it works; however I encounter a different error message now:

ERROR: compilation failed for package 'grf'

removing 'C:/Users/Expert/AppData/Local/R/win-library/4.3/grf'
restoring previous 'C:/Users/Expert/AppData/Local/R/win-library/4.3/grf' Warning in install.packages : Installation des Pakets ‘C:/Users/Expert/AppData/Local/Temp/RtmpSAih92/downloaded_packages/grf_0.10.2.tar.gz’ had non zero exit status

I know that sometimes it gets fixed by installing Rtools but in my case it doesn't help unfortunately; any ideas on how to fix that?
