### ISSUE TITLE
A little misleading in documentation

### ISSUE THREAD

**Issue by Ri0016** [grf-labs/grf#1309]
https://github.com/grf-labs/grf/blob/0318ce400a20bdf56ebbb3635d753f3b6ad19629/r-package/grf/R/quantile_forest.R#L28

Instead of a fixed mtry used for classical random forest algorithm, grf use a random number of variables tried for each split, min {max {Poisson(mtry), 1} , p}.

From my point, the description in documentation is not enough clear.

**Comment by erikcs** [comment]
Hi @Ri0016, the full description of the GRF algorithm + mtry/etc is here: https://grf-labs.github.io/grf/REFERENCE.html#mtry (we thought the R docstring could perhaps get very long and complicated if all algorithmic details like that was to be included)

**Comment by Ri0016** [comment]
Hi @erikcs, thanks for your link.
Yes, that page is much clear than documentation. I overlooked that.
