### ISSUE TITLE
question about heterogeneous causal forests

### ISSUE THREAD

**Issue by Tinatttina** [grf-labs/grf#1310]
**Description of the bug**

in the grf/experiments/acic18/ script.R 
there exists "
C1.exp = model.matrix(~ factor(X.raw$C1) + 0)
XC.exp = model.matrix(~ factor(X.raw$XC) + 0) "

Why we choose variables C1 and XC? but not other variables?

**Comment by erikcs** [comment]
You can choose them if you want
