### ISSUE TITLE
multiarm causal forests reports different treatment effects when evaluated in different but randomly assigned groups

### ISSUE THREAD

**Issue by lucytm111** [grf-labs/grf#1314]
Hello ---
I am running a multi arm causal forest. I would have expected that if i calculate the average treatment effect on each of the randomly assigned groups, the result would be the same. nevertheless, i get dramatically different results. 
What is the right average treatment effect of B-A? the one calculated on B? the one calculated on A? the one calculated with everyone?
Note that the same happens if i just get the aipw scores and average them.

n <- 5000
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- as.factor(sample(c("A", "B", "C", "D"), n, replace = TRUE))
Y <- X[, 1] + X[, 2] * (W == "B") - 1.5 * X[, 2] * (W == "C") - 3 * X[, 2] * (W == "D") + rnorm(n)
mc.forest <- multi_arm_causal_forest(X, Y, W)

average_treatment_effect(mc.forest, subset= (W=="A"))
average_treatment_effect(mc.forest, subset= (W=="B"))
average_treatment_effect(mc.forest, subset= (W=="C"))
average_treatment_effect(mc.forest, subset= (W=="D"))

**Comment by erikcs** [comment]
`average_treatment_effect(mc.forest)` gives you an estimate of the average treatment effect E[Y(B) - Y(A)]. The commands you list gives you various average treatment effect on the treated estimates.

**Comment by lucytm111** [comment]
Thanks Erick. I understand that, but the question is **why are the treatment effect estimates different on different random samples.** On an observatonal study that can be due to selection and lack of comparability, but here each group is just a different random sample, and the treatment effect estimates are quite different. Which of all should we interpret as the correct estimate? what is a justification for the differences? 
In a regular causal forest, the analogy would be to calculate average treatment effect on all, the control or the treatment groups. In general when doing that I've found the 3 estimates to be very similar. That doesn't seem to be the case here, and it does not seem to be related to sample size either--- you can try changing n to 1000, 5000, 10000.
Any guidance on how to interpret the discrepancy would be appreciated.

**Comment by felixrusche** [comment]
I have a very similar issue in an even weirder setting. In my sample, I observe each observation twice: Once treated and once untreated. They thus have the exact same covariates. Nevertheless, when I average_treatment_effect(sample.treated) and average_treatment_effect(sample.untreated) I get different numbers. 

More so, when I do a simple t-test between the mean predictions for either group, I get significantly different results. 

predictions <- predict(tau.forest, estimate.variance=FALSE)$predictions
dta <- cbind(dta, predictions)
dta_t <- test[test$treated == 1,]
dta_u <- test[test$untreated == 0,]
t.test(test1$predictions, test2$predictions)

This does not seem to change when increasing the number of trees. Also, as one might expect, the checks for heterogeneity etc fail, such as test_calibration()

**Comment by felixrusche** [comment]
Similarly, if I compute the average treatment effect for observations with high and low effects, the results suggest that the ATE for the high effects subgroup is much lower than that for the below-average one. This is despite the fact that the predictions for the low group are, by definition and in the data, much lower than in the high effect group. I have tried countless things, but it does not seem to work properly. 

high_effect = predict(tau.forest)$prediction > median(predict(tau.forest)$prediction)

ate.high = average_treatment_effect(tau.forest, subset = high_effect)
ate.low = average_treatment_effect(tau.forest, subset = !high_effect)

**Comment by erikcs** [comment]
>What's more, running rank_average_treatment_effect() shows a slope that starts below zero and goes up to 0. In my setting, this does not make sense, as tau.hat are almost exclusively positive

That may happen with rank_average_treatment_effect [when using out-of-bag estimates](https://grf-labs.github.io/grf/REFERENCE.html#subgroups-based-on-out-of-bag-oob-estimates) (i.e. `rank_average_treatment_effect(forest, predict(forest)$predictions)`) and suggests the forest didn't detect HTEs and is "miscalibrated". If you do a [train/evaluation split](https://grf-labs.github.io/grf/reference/rank_average_treatment_effect.html#examples) you'll see a TOC that makes more sense.


On calling `average_treatment_effect` with `subset` equal to the treatment: this doesn't really give you a quantity that the standard errors cover, https://grf-labs.github.io/grf/reference/average_treatment_effect.html:

> subset ... WARNING: For valid statistical performance, the subset should be defined only using features Xi, **not using the treatment Wi** or the outcome Yi.

**Comment by erikcs** [comment]
It's probably fine just sticking with the TOC/RATE since that exercise subsumes the low/high example in Athey and Wager (2019).

predict(forest)$predictions[i] gives predictions that don't use sample i for estimation
predict(forest, X)$predictions[i] gives predictions for a target sample matching the covariate profile of sample X_i
