### ISSUE TITLE
Weak instrument (get_scores.instrumental_forest)

### ISSUE THREAD

**Issue by howardzzhang** [grf-labs/grf#1343]
In get_scores.instrumental_forest, there is a test for weak instruments

```
if (abs(min(compliance.score)) <= 0.01 * sd(W.orig)) {
      warning(paste0(
        "The instrument appears to be weak, with some compliance scores as ",
        "low as ", round(min(compliance.score), 4)
      ))
    }
```

Should the condition be `min(abs(compliance.score))` instead? Since ` debiasing.weights <- (Z.orig - Z.hat) / (Z.hat * (1 - Z.hat)) / compliance.score`, it seems like there will be a large infusion of noise when the compliance score is close to zero (in absolute value).

**Comment by erikcs** [comment]
Thanks @howardzzhang, yes you are right, that is a bug, do you want to send a pull request?
