### ISSUE TITLE
object 'X' not found

### ISSUE THREAD

**Issue by RuhanLiu** [grf-labs/grf#1382]
When I use the causal_forest function and specify the covariates used in the causal regression, there is a warning that object 'X' not found, as shown in the following picture. I have transformed the data set of covariates into a matrix as required. I am not sure how to address this problem. Could you please provide some help?
![image](https://github.com/grf-labs/grf/assets/63593282/9f0ad41e-666f-4824-9a28-922462b8f73b)

**Comment by erikcs** [comment]
Hi @RuhanLiu, you have an 'X' in mtry = ...

**Comment by RuhanLiu** [comment]
Thanks a lot for your reply! The problem has been solved. Only after running the example code, the function can apply to my data set. 
    
        
            
                
                    
                        
                    
                    
                        
                            刘汝晗
                            
                                    
                                    北京大学光华管理学院
                                  
                                     - 
                                    市场营销系博士生
                            
                                
                                    ***@***.***
                                
                        
                    
                
            
        
    
---- Replied Message ----FromErik ***@***.***>Date12/31/2023 07:46 ***@***.***> ***@***.***>***@***.***>Subjectnot found (Issue #1382)
Hi @RuhanLiu, you have an 'X' in mtry = ...

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/grf-labs/grf/issues/1382#issuecomment-1872627622",
"url": "https://github.com/grf-labs/grf/issues/1382#issuecomment-1872627622",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
