### ISSUE TITLE
Multiple instruments in instrumental_forest() + first stage results

### ISSUE THREAD

**Issue by AleksandrZhuravlev98** [grf-labs/grf#1383]
Dear Developers, 

Based on my experimentations with the instrumental_forest() function, the argument Z accepts only a vector, meaning that it can be used only with a single instrument. I just wanted to double-check whether this is correct and if not, whether there exist ways to use the function with multiple instruments.  

One more thing that does not appear clear from the documentation is whether in the function's syntax, the argument W should be the exoeneous variable of the 2SLS procedure. Please correct me if I am wrong!

Additionally, I was wondering whether with the method, it is possible to get some proxy of the first-stage results. 

Finally, the current version supports estimation of the ATE only for binary instruments. Do you have any suggestions on how one can obtain the ATE with continuous instruments with the results currently outputed by the function? 

Sorry for so many (potentially silly) questions. I am looking forward to your reply!

**Comment by erikcs** [comment]
Hi @AleksandrZhuravlev98,

> Based on my experimentations with the instrumental_forest() function, the argument Z accepts only a vector, meaning that it can be used only with a single instrument. I just wanted to double-check whether this is correct and if not, whether there exist ways to use the function with multiple instruments.  
> 
That is correct, but @phkug shared a grf extension in #355 that supports multiple instruments.

> One more thing that does not appear clear from the documentation is whether in the function's syntax, the argument W should be the exoeneous variable of the 2SLS procedure. Please correct me if I am wrong!
> 
Yes, W is the treatment and Z is the instrument (https://grf-labs.github.io/grf/reference/instrumental_forest.html)

> Additionally, I was wondering whether with the method, it is possible to get some proxy of the first-stage results. 
> 
The fit object contains the vectors `W.hat` and `Z.hat` which are the 1st and 2nd stage predictions.

> Finally, the current version supports estimation of the ATE only for binary instruments. Do you have any suggestions on how one can obtain the ATE with continuous instruments with the results currently outputed by the function? 
> 
No, only binary instruments are supported currently
