### ISSUE TITLE
Question : Variance from quantile forest and multi_regression_forest

### ISSUE THREAD

**Issue by yvc5154** [grf-labs/grf#1385]
If you are filing a bug report, please consider using the following template.

**Description of the bug**
Hello,

My name is Youngjoo Cho and I use grf version 2.3.1. When I use quantile forest and multi_regression_forest, I cannot obtain variance estimates from prediction. Could I obtain the variance estimates from the prediction?

Please check this and let me know.

Sincerely,

Youngjoo Cho

**Steps to reproduce**
> # Train a quantile forest. 
> n <-50 
> p <-10 
> X <-matrix(rnorm(n*p),n,p) 
> Y <-X[,1]*rnorm(n) 
> q.forest<-quantile_forest(X,Y,quantiles=c(0.1,0.5,0.9)) # Predicton out-of-bag training samples. 
> q.pred<-predict(q.forest) # Predict using theforest. 
> X.test<-matrix(0,101,p) 
> X.test[,1]<-seq(-2,2,length.out=101) 
> q.pred<-predict(q.forest,X.test)
> q.pred<-predict(q.forest,X.test,estimate.variance=TRUE)
> head(q.pred)
$predictions
            [,1]        [,2]      [,3]
  [1,] -1.154864 -0.07305880 1.2961435
  [2,] -1.154864 -0.07305880 1.2961435
  [3,] -1.154864 -0.07305880 1.2961435

**GRF version**
2.3.1

**Comment by erikcs** [comment]
Hi @yvc5154, quantile forest doesn't compute variance estimates.
