### ISSUE TITLE
LATE implementation details

### ISSUE THREAD

**Issue by mili-yini** [grf-labs/grf#1399]
Does the implementation of LATE（instrumental variables (IV) regression） in grf have a detailed algorithm explanation, or are there any documents that can be referred to

**Comment by erikcs** [comment]
If you want an abstract algorithm description, `instrumental_forest` is Algorithm 1 in https://arxiv.org/abs/1610.01271 with the estimating equation $\psi$ given by the moment functions described in section 7.1 of the same paper. The grf package also takes [sample weights into account](https://github.com/grf-labs/grf/blob/df1b2c9232b9ec5c0ec98e76f8c3d246afbee099/core/src/prediction/InstrumentalPredictionStrategy.cpp#L41).

If you want something less abstract, then the description of `causal_forest` given [here](https://grf-labs.github.io/grf/articles/grf_guide.html#a-grf-overview-1) can be applied to IV forests too: IV forest first centers the outcome Y, treatment W, and instrument Z (ala Robinson for causal forest), then uses grf to find forest weights for a treatment effect $\tau(x)$ calculated as the forest-weighted two-stage least squares regression of centered Y on centered W and Z (i.e, where causal forest runs residualized regressions, instrumental forest runs two-stage residualized regressions).

**Comment by mili-yini** [comment]
> If you want an abstract algorithm description, `instrumental_forest` is Algorithm 1 in https://arxiv.org/abs/1610.01271 with the estimating equation ψ given by the moment functions described in section 7.1 of the same paper. The grf package also takes [sample weights into account](https://github.com/grf-labs/grf/blob/df1b2c9232b9ec5c0ec98e76f8c3d246afbee099/core/src/prediction/InstrumentalPredictionStrategy.cpp#L41).
> 
> If you want something less abstract, then the description of `causal_forest` given [here](https://grf-labs.github.io/grf/articles/grf_guide.html#a-grf-overview-1) can be applied to IV forests too: IV forest first centers the outcome Y, treatment W, and instrument Z (ala Robinson for causal forest), then uses grf to find forest weights for a treatment effect τ(x) calculated as the forest-weighted two-stage least squares regression of centered Y on centered W and Z (i.e, where causal forest runs residualized regressions, instrumental forest runs two-stage residualized regressions).

Than you very much,and how to understand in instrumental variable regression, 
<img width="735" alt="image" src="https://github.com/grf-labs/grf/assets/10042409/2c9681c0-bf87-473f-ba6f-6eb48c1f10fc">
