### ISSUE TITLE
Add support for missing values on predictors features

### ISSUE THREAD

**Issue by inti4digbi** [grf-labs/grf#1403]
Hi,
Thanks for developing and providing this excellent software. I wanted to know if there are plans to add support for missing values on the X matrix. This is supported in other tree-based algorithms like random forests on scikit-learn, or boosting algorithms like xgboost and catboost. It is super useful when working with sparse predictors. 

Is there another way of working with sparse predictors on this package?

Many thanks in advance!

**Comment by erikcs** [comment]
Hi @inti4digbi, grf supports missingness in X's with [MIA splitting](https://grf-labs.github.io/grf/REFERENCE.html#missing-values). 

The way to work with sparse X is to convert it to a standard dense matrix then pass it to grf.
