### ISSUE TITLE
ll_regression_forest slows down console in Rstudio

### ISSUE THREAD

**Issue by gabrielhoc** [grf-labs/grf#1404]
**Description of the bug**
After running a moderately large (7000 datapoints, 20 variables, reproducible code below) ll_regression_forest model, the console in that Rstudio session slows down a lot. 

For example, normally if I type 1+1 in my console, the answer 2 will show up immediately. After running ll_regression_forest, it takes a couple of seconds for 2 to be printed in the console. It is not just a printing problem though, other lines of code will not run until the last one is printed. This makes running any larger blocks of code extremely slow if I have a ll_regression_forest object in my environment.

- I checked my computer's resource monitor, and there is still a lot of free memory and processing. 
- If I open another Rstudio session, the console will be responsive as normal, I can even run other memory intensive analysis at the same time. 
- The issue seems to be only in the Rstudio session where the ll_regression_forest object is created, and only while the object is present in the environment, if I remove it, the console returns to its normal responsiveness. 
- Other grf functions like regression_forest and causal_forest do not cause the same issue.
- I tried a couple of other big models in other packages, they don't cause the same issue (caret, GBM, RandomForest, XGBoost).
- I checked Rstudio's Request log, and it seems that the culprit is the process "get_events", which is taking abnormally long to run (only when a ll_regression_forest object is present in the environment).

I'm using grf version 2.3.2. Rstudio version 2023.06.2 Build 561.

Here is my session info:

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_Israel.utf8  LC_CTYPE=English_Israel.utf8   
[3] LC_MONETARY=English_Israel.utf8 LC_NUMERIC=C                   
[5] LC_TIME=English_Israel.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] glmnet_4.1-4 Matrix_1.4-1 grf_2.3.2   

loaded via a namespace (and not attached):
 [1] compiler_4.2.1   tools_4.2.1      survival_3.3-1  
 [4] Rcpp_1.0.10      splines_4.2.1    codetools_0.2-18
 [7] grid_4.2.1       iterators_1.0.14 foreach_1.5.2   
[10] shape_1.4.6      lattice_0.20-45 

**Steps to reproduce**

```{r}
library(grf)
library(glmnet)

n <- 7000
p <- 20
sigma <- sqrt(20)

mu <- function( x ) {
  10 * sin(pi * x[1] * x[2]) + 20 * ((x[3] - 0.5) ** 2) + 10 * x[4] + 5 * x[5]
}

X <- matrix(runif(n * p, 0, 1), nrow = n)
Y <- apply(X, FUN = mu, MARGIN = 1) + sigma * rnorm(n)

rforest <- ll_regression_forest(X, Y)

1+1
```

Thanks a lot!

**Comment by erikcs** [comment]
Hi @gabrielhoc, according to #1374 upgrading to latest Rstudio should fix the issue.

**Comment by gabrielhoc** [comment]
Great! I will try it out, thank you very much
