### ISSUE TITLE
 Questions Regarding Causal Forest Variable Types and "test_calibration" Interpretation

### ISSUE THREAD

**Issue by Matt9617** [grf-labs/grf#1409]
Hi,
Thanks for your work.

I am a student currently learning about causal forest and have some questions regarding the variable types and `test_calibration` Interpretation in causal forest.

1. Does causal forest support scenarios where the treatment variable is continuous and the outcome variable is binary?
2. The documentation states: "If Y.hat or W.hat = NULL, these are estimated using a separate regression forest." Does this mean I can skip predicting Y.hat and W.hat before setting up the causal forest and just use the default parameters?
3. Is a significant value of `differential.forest.prediction` between 2 and 3 acceptable, and what is the implication of such a relatively high value?

Best Regards.

**Comment by erikcs** [comment]
Hi @Matt9617,

1. Yes.
2. That's correct.
3. Stefan has a nice video lecture [here](https://youtu.be/fAUmCRgpP6g?list=PLxq_lXOUlvQAoWZEqhRqHNezS30lI49G-&t=1241) on interpreting that kind of calibration exercise. You might find this recent grf feature, [RATE](https://grf-labs.github.io/grf/articles/rate.html), easier to interpret.
