### ISSUE TITLE
best_linear_projection returns NaN values

### ISSUE THREAD

**Issue by pakmasha99** [grf-labs/grf#1415]
Hi, I am using grf package for my research, and I'm currently experiencing an issue with the best_linear_projection function.

I'm using a simulated dataset containing 500 observations and 1000 covariates to check the grf performance on high-dimensional datasets.
So far, there have been no issues with lower-dimensional datasets and there's also no missing values.

What could be the reason for the best_linear_projection function to return NaN values? Thank you!

![image](https://github.com/grf-labs/grf/assets/55074303/eef860dc-af2e-4a31-b429-684e572fd099)

**Comment by erikcs** [comment]
Hi @pakmasha99, best_linear_projection fits a linear model using OLS, for that you need more samples than covariates. Fitting the best linear projection on some chosen subset of your X's should work as long as dim(X.subset) < n.

**Comment by pakmasha99** [comment]
Thank you!
