### ISSUE TITLE
ability to generate a dose-response (or causal) curve with GRF

### ISSUE THREAD

**Issue by kmaloneyUSGS** [grf-labs/grf#1417]
Is there a way to generate a dose-response or causal curve with grf, something akin to what is afforded with the python TMLE Regressor Tool ([
[TMLE_Regressor Tool (continuous treatments, continuous outcomes) — causal_curve 1.0.6 documentation (causal-curve.readthedocs.io)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcausal-curve.readthedocs.io%2Fen%2Flatest%2FTMLE_Regressor.html&data=05%7C02%7Ckmaloney%40usgs.gov%7C445445044e4746f0ced108dc7fd52797%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638525800671874698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=0aGvCyvg2LbJJbwkbUDotiV95WUKdkrQbx1ruAafyxQ%3D&reserved=0)
](https://causal-curve.readthedocs.io/en/latest/TMLE_Regressor.html)).  Also in full disclosure, I am fairly new to this field, and I wanting to use casual forest to generate these curves to enable an examination of potential thresholds along the treatment where we reach a management relevant criterion. I realize that there are many caveats associated with continuous treatments and would further appreciate any advice on such graphs/results on the theoretical grounds (i.e., are they appropriate?) or alternative approaches with the grf package.

**Comment by erikcs** [comment]
Hi @kmaloneyUSGS, unfortunately grf does not estimate a dose-response. If you supply a continuous treatment to causal_forest the statistical quantity tau(X) you are getting is an [average partial effect](https://grf-labs.github.io/grf/reference/causal_forest.html):
> When W is continuous, we effectively estimate an average partial effect Cov[Y, W | X = x] / Var[W | X = x], and interpret it as a treatment effect given unconfoundedness.

If it makes sense for your application, that could potentially be used to predict units (as defined by covariates X) that have either low or high treatment benefit (as defined by average partial effects)

**Comment by kmaloneyUSGS** [comment]
thank you for the response and clarification.
