### ISSUE TITLE
vignette splitting question

### ISSUE THREAD

**Issue by ras44** [grf-labs/grf#1418]
I may be misreading the prose in the vignette, but I wasn't sure if this was correct:

https://github.com/grf-labs/grf/blob/f79679d72124db505b92aca0be0ab2a694b70749/r-package/grf/vignettes/grf_guide.Rmd#L115

It seems like the optimal split point would be based on some impurity or information gain measure (like the reduction of variance due to the split) and not simply making the left and right means as similar as possible.

Thank you

**Comment by erikcs** [comment]
Hi @ras44, the criterion is in step 1 above the figure (the "Delta" criterion from the grf annals of statistics paper, which for the conditional mean is the same the CART MSE criterion). That is maximized when the means within each child node is similar, or equivalently, when the means across child nodes are different.

**Comment by ras44** [comment]
thanks, appreciate the comment!
