### ISSUE TITLE
Growing a CF - Prepare matrices 

### ISSUE THREAD

**Issue by hanneleer** [grf-labs/grf#1425]
Dear all, 

Thank you for solving so many questions related to the CF. 

I have another question/verification issue related to the covariates used in the causal_forest function. 

I use one-hot-encoding to deal with my categorical variables in my data frame. I do this by using model.matrix but it ignores creating a  dummy for all categories, and always leaves out one category for multicollinearity reasons. As I have read, multicollinearity shouldn't be an issue for the CF? So can I just include all the categories as dummy in my data frame? Particularly, I know that for prediction, multicollinearity is not an issue, so I wanted to verify/be sure that  it won't be an issue to explore the main drivers of heterogenous treatment effects when I include all categories of all variables? 

Any help is appreciated! Thanks in advance!

**Comment by erikcs** [comment]
Hi @hanneleer, yes you are right that multicollinearity isn't an issue for random forests. A forest is scanning over covariate values in sorted order to find a good split point. With duplicate/highly correlated variables present, exactly which ends up being split on is arbitrary though, and so you'd have to exercise some judgment when comparing heterogeneity predictors, as a bulk of them might measure/capture basically the same thing.

PS: Categorical variables with an embedded ordinality is simpler to deal with, you could just try and let the forest split on them directly (an example could be an education level that goes from low to high where splitting on this directly will just try levels of education as predictors of heterogeneity)
