### ISSUE TITLE
Standard errors calculation in average_treatment_effect() and best_linear_projection()

### ISSUE THREAD

**Issue by GalAmedi** [grf-labs/grf#1428]
Hey. I'm estimating a causal forest with a continuous treatment. When estimating the causal forest I choose a specific level of spatial aggregation in the 'clusters' argument. 

I would like to also calculate different types of standard errors of the average treatment effect, and for the coefficients displayed in the best linear projection of covariates on the CATE. Specifically I would like to calcuate Conley (1999) standard errors which allow for spatial auto-correlation, and a set of standard errors clustered by a set of different spatial aggregation levels (potentially different than the aggregation level used in the clusters argument when the forest was estimated.

I understand that currently both of these functions report standard errors clustered by the clusters variable in the original forest. I have looked in the algorithm reference and couldn't find a way to specficy different types of standard erros in these functions. Is there a way to estimate them?

Thanks in advance, 
Gal

**Comment by erikcs** [comment]
Hi Gal,

The standard errors are calculated using the doubly robust scores for the particular forest construction. Given these, you could supply your own options to `lmtest` and `sandwich` with something like the following.
```R
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- runif(n)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
clusters <- sample(0:100, n, TRUE)
c.forest <- causal_forest(X, Y, W, clusters = clusters)

# Retrieve AIPW scores for an ATE
# (Details on how these are constructed is here https://github.com/grf-labs/grf/blob/master/r-package/grf/R/get_scores.R#L47)
DR.scores <- get_scores(c.forest)

# Compute an ATE (BLP on a intercept), passing SE options to lmtest
lmtest::coeftest(lm(DR.scores ~ 1),
                 # The standard error options, this is the default (cluster-and-heteroscedasticity robust, HC3)
                 vcov = sandwich::vcovCL,
                 type = "HC3",
                 # The clusters to cluster SEs by, this is the default:
                 cluster = c.forest$clusters)
# Same as
best_linear_projection(c.forest)
# Same as (~ minor difference due to different numerical approaches)
average_treatment_effect(c.forest)
```

**Comment by GalAmedi** [comment]
Hey Erik, thank you very much for the quick and informative response. 

Just to clarify, lets assume that I am interested in estimating the best linear projection of covariates on the estimated effect. To demonstrate, lets say in your example I would like to know how does X4 and X5 correlate with the estimated effect.  So I would run:

`
best_linear_projection(forest = C.forest, A = X[,4:5])
`
But Now, les say I would also like to calculate the standard errors clustered by a different variable from the one used for estimation of the causal forest, 'clusters_alt'. So how do I go about doing this? my guess will be:
```
lmtest::coeftest(lm(DR.scores ~ 1 + X[,4] + X[,5]),
                 vcov = sandwich::vcovCL,
                 type = "HC3",
                 cluster = clusters_alt)
```
 Will that work? will the coefficients be the same in both methods?
Gal

**Comment by erikcs** [comment]
> will the coefficients be the same in both methods?

Yes!

**Comment by GalAmedi** [comment]
Thanks again, its been very helpful. I might suggest adding a simple explanation of the sort to one of the tutorials, I think it could actually fit quite nicely at the end of the 'Estimating and summarizing CATEs' section in the grf guided tour tutorial. Anyway I'm closing the thread, thanks.

**Comment by GalAmedi** [comment]
Thanks again, its been very helpful. I might suggest adding a simple explanation of the sort to one of the tutorials, I think it could actually fit quite nicely at the end of the 'Estimating and summarizing CATEs' section in the grf guided tour tutorial. Anyway I'm closing the thread, thanks.
