### ISSUE TITLE
Ensure that min.node.size is strictly enforced.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#143]
Currently, we don't prevent splits from occurring that could result in nodes with size less than `min.node.size`. Instead, the algorithm simply stops splitting if a node's size is less than or equal to `min.node.size`.

Although this is also the current behavior in both ranger and the original randomForest package, it's not intuitive and can be quite misleading. We should look into updating the splitting algorithm so that `min.node.size` is enforced as a true minimum.

**Comment by swager** [comment]
Just to add a little more context, the behavior of the randomForest package is discussed [here](https://stackoverflow.com/questions/28417826/nodesize-parameter-ignored-in-randomforest-package).

We still intend to update the behavior of our implementation to properly enforce `min.node.size` as a true minimum node size.

**Comment by ras44** [comment]
Hi @jtibshirani I'd be happy to continue contributing via PRs to grf.  I was thinking either this one or any of the below:

- https://github.com/grf-labs/grf/issues/420 cobalt style balance plots
- https://github.com/grf-labs/grf/issues/291 classification forests

... or any other suggestions you or the team may have.  Thanks!

**Comment by halflearned** [comment]
The implementation of `min.node.size` in grf is now documented in the REFERENCE. See [`min.node.size`](https://github.com/grf-labs/grf/blob/master/REFERENCE.md#minnodesize) and [`Selecting Balanced Splits`](https://github.com/grf-labs/grf/blob/master/REFERENCE.md#selecting-balanced-splits).
