### ISSUE TITLE
BLP interpretation(binary and continuous variable)

### ISSUE THREAD

**Issue by ninetale** [grf-labs/grf#1432]
First of all, I would like to express my gratitude for developing this package, which has been a great help for my paper.

I have a few questions regarding the use of this package in my research:

1. In my study, the dependent variable is binary. If the ATE (Average Treatment Effect) is 0.1, can this be interpreted as the treatment increasing the probability by 10%?(I have read posts about it, but just for confirmation)
	
2. I have questions regarding the interpretation of the Best Linear Projection (BLP) results, particularly when dealing with binary and continuous variables.

Assume that the result for the binary variable X1 is 0.3, and for the continuous variable X2, it is 0.1.

Does this mean that when X1 equals 1, the treatment effect increases by 30%, leading to an expected 40% increase in probability when both the treatment and X1 are present?

Also, for X2, can it be interpreted that for each unit increase in X2, the treatment probability increases by 10%, so that when X2 increases by 3 units, an expected 40% increase in probability occurs with the treatment?

Once again, thank you very much for your help.

**Comment by erikcs** [comment]
Hi @ninetale,

1. Yes, when the outcome is {0, 1} the causal forest ATE estimate can be interpreted as a probability difference (to see how, remember that that $E[1(Y_i = 1)] = P[Y_i = 1]$, and so the ATE = $E[Y_i(1) - Y_i(0)] = P[Y_i(1) = 1] - P[Y_i(0) = 1]$, where $Y_i(1),Y_i(0)$ are potential outcomes corresponding to the two treatment states).
2. You can interpret the BLP coefficients just as you would any other linear regression model. The LHS is an ATE conditional on X (CATE), and so the coefficient on the RHS tells you how a one-unit increase affects the best linear prediction on the CATEs.
