### ISSUE TITLE
Two questions about using Causal Forest

### ISSUE THREAD

**Issue by Hone-L** [grf-labs/grf#1435]
Dear All
I really appreciate your amazing work on the Causal Forest. I am using it to estimate causal effect now. I am writing to ask you two quick questions about it.

1. Would the estimator be unbiased if there is a certain relationship between covariates? For example, the case that  I contain both the COVID-19 pandemic and lockdowns which may have a impact on each other as covariates.
2. Would the estimation of APE (while my treatment variable is continuous) get rid of the limitation of overlapping?

**Comment by erikcs** [comment]
Hi @Hone-L, 1) random forests work fine with correlated predictor variables, 2) overlap is still required, the average_treatment_effect function option has an option for that.

**Comment by Hone-L** [comment]
Hi @erikcs
Thanks for the answer!!
Additionally, could I ask for the principle that why it would be fine to work with correlated predictor variables? Is it in the paper by Wager et al (2018)?

Thanks!

**Comment by Hone-L** [comment]
Hi @erikcs 
And also, does the answer mean it would be beneficial to deal with "feedback endogeneity" caused by predictors variables ( predictors variables influence each other).

Thanks!
:)
