### ISSUE TITLE
`validate_newdata` on a 0 by n matrix has misleading error

### ISSUE THREAD

**Issue by dsweber2** [grf-labs/grf#1461]
**Description of the bug**

For an empty matrix, the returned error is `feature matrix X must be numeric`, rather than something like "your matrix is empty". As we are using grf inside a recipes pipeline, this pointed in a completely different error direction than where I actually needed to be looking to solve the problem.

**Steps to reproduce**
```r
> library(grf)
> # Generate data.
n <- 2000
p <- 10
X <- matrix(rnorm(n * p), n, p)
X.test <- matrix(0, 101, p)
X.test[, 1] <- seq(-2, 2, length.out = 101)

# Train a causal forest.
W <- rbinom(n, 1, 0.4 + 0.2 * (X[, 1] > 0))
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
> tau.forest <- causal_forest(X, Y, W)
> tau.hat.oob <- predict(tau.forest, matrix())
Error in validate_X(newdata, allow.na = allow.na) : 
  The feature matrix X must be numeric. GRF does not currently support non-numeric features. If factor variables are required, we recommend one of the following: Either represent the factor with a 1-vs-all expansion, (e.g., using model.matrix(~. , data=X)), or then encode the factor as a numeric via any natural ordering (e.g., if the factor is a month). For more on GRF and categorical variables see the online vignette: https://grf-labs.github.io/grf/articles/categorical_inputs.html
```
Obviously much easier to see in this context than where it arose organically.

**GRF version**
grf_2.3.2

**Comment by erikcs** [comment]
Hi @dsweber2, sorry you are having trouble with your recipe, but your example shows a non-numeric 1x1 matrix being passed to predict, and where grf is just being consistent with R:
```

> dim(matrix())
[1] 1 1
> is.numeric(matrix())
[1] FALSE
```

**Comment by dsweber2** [comment]
Sorry for misunderstanding base R there. A closer example to what we had is `tau.hat.oob <- predict(tau.forest, matrix(double(),0L, 10L))` which does work (in that it returns an empty prediction), so I guess there must be some type conversions in our recipe that don't get applied if the data is empty. You may want to emit a warning/error on empty prediction data, but this does seem to have been on our end mostly.

**Comment by erikcs** [comment]
I think you should be covered in the next upcoming release, in the development version we recently added a check for zero/empty dims in X (#1408).

**Comment by dsweber2** [comment]
That is remarkably close! Though that's the training case, rather than the predict case; in my use case, I'm not using the same data matrix for both steps. I'm currently on 2.3.2, which appears to be latest.

**Comment by erikcs** [comment]
The same function is called in the predict case, it will cover you there too (you could install the development version and try it out)
