### ISSUE TITLE
causal forest for binary outcome

### ISSUE THREAD

**Issue by KarlKoe** [grf-labs/grf#1465]
I want to benchmark causal forests vs. meta-learners. I see that issue #120 and issue #291 where somewhat around this but with the latest version of grf I would not be sure how to run a causal forest for a binary outcome variable. Can `probability_forest()` be used to get estimates for ITE & CATE (I don't see a `W` parameter like in `causal_forest()`)? Thanks for your help!

**Comment by erikcs** [comment]
Hi @KarlKoe, yes, you can use causal forest with a binary outcome. [Here](https://arxiv.org/pdf/2409.01578) is an example with Y=1 if PTSD and 0 otherwise.

**Comment by KarlKoe** [comment]
Thank you very much @erikcs - appreciate it!
