### ISSUE TITLE
test_calibration() and best_linear_projection() doesn't finish

### ISSUE THREAD

**Issue by tsubasatakaya** [grf-labs/grf#1475]
Hi, I am having difficulty getting calibration results from test_calibration() and linear CATE estimates from best_linear_projection() for causal forest with clustered data.

**Description of the bug**
When I run test_calibration() or best_linear_projection() with a fitted causal_forest object, the process doesn't finish. For reference, the dataset contains 41,720 observations, a binary treatment, and 7 clusters. X contains 55 variables (most of them are fixed effect dummies, and their variable importance is 0).

**Steps to reproduce**
```
forest_v <- causal_forest(X = X_v,
                          Y = Y_v,
                          W = D_v,
                          clusters = route_id_v,
                          equalize.cluster.weights = TRUE,
                          )

test_calibration(forest_v)
```

**GRF version**
grf 2.4.0

What could be the potential problems?

**Comment by tsubasatakaya** [comment]
Update: It turned out that the problem is caused by coeftest() when estimating linear regression coefficient with clustered standard errors. Could it be perhaps replaced by other faster options such as `estimatr::lm_robust` or `fixest::feols`?

**Comment by erikcs** [comment]
Hi @tsubasatakaya, if you try and set `vcov.type` to "HC0" or "HC1" in either test_calibration or [best_linear_projection](https://grf-labs.github.io/grf/reference/best_linear_projection.html) it should run quicker:

>vcov.type | Optional covariance type for standard errors. The possible options are HC0, ..., HC3. The default is "HC3", which is recommended in small samples and corresponds to the "shortcut formula" for the jackknife (see MacKinnon & White for more discussion, and Cameron & Miller for a review). For large data sets with clusters, "HC0" or "HC1" are significantly faster to compute.

**Comment by tsubasatakaya** [comment]
@erikcs I missed that part in the vignette. Thank you!
