### ISSUE TITLE
Multiple Treatment Regimes

### ISSUE THREAD

**Issue by jeffwong** [grf-labs/grf#173]
Does GRF support datasets where the treatment variable is a factor with more than 2 levels? For example W = factor('treatment', 'control', 'treatment2', 'treatment3')

For the average treatment effect, I understand a tree is used to get heterogeneity, then a `lm` call is used to get the average treatment effect. I think if W is a factor with > 2 levels lm would still work and report the ATE for the non "control" levels of the factor.

**Comment by swager** [comment]
We don't currently support forests in the multi-treatment case, but have a student actively working on it. We'll keep you posted!

**Comment by jtibshirani** [comment]
I'm closing in favor of the issue #285, where we are tracking this work.
