### ISSUE TITLE
Fully parallelize prediction collection.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#230]
Currently, only one component of prediction is parallelized across multiple threads: determining which tree leaves each test sample falls in.

We should also parallelize the step in which predictions are collected given this leaf membership information. A non-trivial amount of work is performed during this step, especially with the more complex strategies like `LocalLinearPredictionStrategy`, and since we may additionally compute variance estimates and debiased errors.

Note that in this form of parallelization, test samples would be distributed across threads. This differs from the current instances of parallelization, where trees are split across threads.

**Comment by erikcs** [comment]
- [x] OptimizedPredictionCollector::collect_predictions is handled in #566 
- [ ] DefaultPredictionCollector::collect_predictions: to be done
