### ISSUE TITLE
Improve package documentation.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#236]
A few items in particular:
- [x] Improve the main help file (`grf.Rd`), as it is currently quite bare-bones. #516
- [x] Do a pass through the method documentation, making sure parameters are fully explained and that they're clearly marked 'experimental' as needed.
- [x] Make sure examples on the methods are helpful and capture the primary use case.
- [x] Explain algorithmic details not obvious from the 'Generalized Random Forests' paper, for example honesty and split penalization. #290

**Comment by predt** [comment]
Hello,
Quick question:  For a given final node "i" of a tree (i.e. a leaf), 
does the output   tree$nodes[[i]]$samples  correspond to the observations of the training sub sample used to build the tree (i.e. J1 in paper) falling in that leaf,  or  are they the observations from the other sub sample (J2) falling in that leaf? 
Thanks!

**Comment by markhwhiteii** [comment]
This would be helpful—most of the complexity is on the C++ end, so it is difficult for an R user who doesn't know C++ (like myself) to look at the raw code and see how the code in the package relates to the algorithm in the papers. It is mentioned on this repo and elsewhere that the `grf` `causal_forest` implementation is different from what is described in https://arxiv.org/abs/1510.04342. I have a pretty good handle on that paper, but unsure of where the implementation in `grf` differs from that paper.

For example, details like what the definition of `honesty` is. Is it the I/J split described in the double-sample trees in Procedure 1 here https://arxiv.org/abs/1510.04342?

**Comment by jtibshirani** [comment]
@predt I'm sorry I missed your question earlier! Would you be able to open a new issue with this question, and I will add a detailed answer there? Keeping each issue scoped to one topic helps ensure that other users with the same question will be able to find the answer as well. To answer briefly, that vector only contains examples from the second subsample (`J2`).

**Comment by jtibshirani** [comment]
@markhwhiteii thank you for the feedback -- I think the current lack of details around the algorithm is a big shortcoming of the package. We're planning to write a paper focused on the software aspect of grf that should really help fill in the gaps.

Above, you reference the paper 'Estimation and Inference of Heterogeneous Treatment Effects using Random Forests'. The paper that closely corresponds to this implementation is actually 'Generalized Random Forests' (https://arxiv.org/pdf/1610.01271.pdf). In particular, section 6.2 develops the the approach for causal effect estimation. It may help to review this section, but the grf paper is written from a theoretical, as opposed to algorithmic, perspective.

If you have particular questions about the code that would help in writing a tutorial, please let us know and we can add them to this list above as higher-priority items to document.

**Comment by susanathey** [comment]
@markhwhiteii the package github.com/susanathey/causalTree implements the JASA paper directly.  GRF is very close in the case of causal forest and our goal is to allow people to be able to use the GRF package for the JASA algorithm as well, but we haven't made it transparent how to do so yet.  Let me know if you have trouble and what exactly you want to do and happy to help trouble shoot.

**Comment by markhwhiteii** [comment]
I wrote this, if it helps at all with wording things to a less technical audience in a future vignette or other documentation: https://www.markhw.com/blog/causalforestintro
