### ISSUE TITLE
Create a suite of simulations and benchmark statistical performance.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#274]
It would be great to put together a suite of simulations, drawing from real datasets and examples in papers, and then run GRF along with some simple baselines. Having this set of statistical benchmarks would be beneficial in a couple ways:
- The results would help users understand how GRF performs under various conditions, and so make an informed decision about when (and how) it should be used.
- It helps us identify any low-hanging fruit in terms of statistical improvements, or major blind spots that need attention.

We should make both the code + data available in case users would like to replicate the results, or make any tweaks to the set-up.

**Comment by erikcs** [comment]
Closing for now as this is being done as part of a software paper.
