### ISSUE TITLE
Add the ability to determine what leaf nodes a test point falls in.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#275]
Given a set of test points, we should add support for determining which leaf nodes those test points fall in. In conjunction with `get_tree`, such a method could help in understanding/ debugging the forest's output.

The method would be added to `analysis_tools.R`, as a companion method to `get_sample_weights`.

**Comment by Buyannemekh** [comment]
We can get the index of leaf where each test point lands after pushing it down to the tree in `find_leaf()` [link](https://gist.github.com/Buyannemekh/dcb0dda480c3e533e0aff1148c25c880). Should we calculate more statistics using this information?

**Comment by erikcs** [comment]
Closing in favor of #661
