### ISSUE TITLE
Individual Trees: Estimation and Visualization

### ISSUE THREAD

**Issue by susanathey** [grf-labs/grf#277]
There are several use cases for visualizing individual trees:

1. Causal tree functionality, generalized: make a tree based on generalized splitting rules, including causal tree, orthogonalized version of causal tree, instrumental variables tree, etc.  Elements of this use case:
a. The researcher is only interested in a single, honest tree where, some fraction of data is used to build tree and the rest used to estimate parameters in leaves
b. Ideally, the researcher would also get standard errors for these estimates (this goes a bit beyond visualization and so may need more work)
c. The researcher wishes to plot this tree for presentations, showing splitting criteria, effects and standard errors (if available), with flexible plotting options, similar to packages that are available for plotting rpart

2. Debugging forest routines and gaining insight into how they are working
a. It would be helpful if we could not just display pretty graphical trees, but also a related visualization is a table where columns are leaves and rows are various summary stats, including parameter estimates, variances of parameter estimates, and means of covariates.  
b. For example, in the absence of variance corrections, splitting may be creating leaves where parameter estimates have very high variance.  By visualizing trees as described in (a), this would be obvious.
c. Forests may always make the same splits high in the tree.  If we have a prior belief that multi-way interactions are important, we may want to have more aggressive randomization on what variables are used for splitting to more fully explore complex interactions.

3. Post-processing of forests
a. After estimating a forest, it is challenging to describe what is learned from it scientifically.
b. Making a shallow tree out of forest estimates can be a useful way to summarize heterogeneity.
c. Although we could take the estimates and run them through rPart, we might prefer to build our own solutions to display the information most relevant, such as the summary stats described in 2a.

Implicit in all of these use cases is the ability to prune, which ideally could be done with cross-validation if desired; writing a cv routine is straightforward once we can prune according to fit parameters.  Pruning is essential because very quickly, a tree becomes impossible to visualize graphically.

So the action items would be:
- Look at packages like rattle and rpart.plot to see how plotting works there and what useful options are; note that for longer trees, rules-based output may be a better option than a plot
- Look at pruning/cv functionality in rpart 
- Create functionality to extract a tree and then prune or extract branches of the tree
- Create functionality to identify observations associated with leaves in training data or new test data
- Create functionality to estimate parameters and standard errors in each leaf in training data or new test data
- Add in more graphics options

**Comment by halflearned** [comment]
It seems that the suggestions in issue have been broken up into smaller tasks, or superseded by other functionality. 
 For example, visualizing individual trees is possible using `get_tree` and then `plot`. And instead of extracting a tree from the forest, the user can instead fit a tree policy via [`policytree`](https://github.com/grf-labs/policytree). Closing this for now, re-open if needed.
