### ISSUE TITLE
Add support for multivariate treatment effects

### ISSUE THREAD

**Issue by rajkumarkarthik** [grf-labs/grf#285]
We plan to add support for multivariate estimands. Here are the major tasks involved:

- [ ] Allow `causal_forest` to accept multivariate treatments (i.e. more than one treatment arm). Each one of these treatments could be binary or real-valued.
- [ ] Allow just-identified `instrumental_forest` to accept multivariate endogenous treatments and instruments. Specifically, we work on the case where the number of treatments is the same as the number of instruments, but could be larger than 1.
- [ ] Allow multi-task estimation of `regression_forest`. Specifically, this means letting outcome variables be multivariate, so that multiple regression functions can be estimated simultaneously. 

The first two have already been implemented and may be found [here](https://github.com/rajkumarkarthik/mgrf-develop). These edits will be pulled into this repo shortly.

**Comment by ZhangMengxia** [comment]
So for the first support "Allow causal_forest to accept multivariate treatments (i.e. more than one treatment arm). Each one of these treatments could be binary or real-valued.", in this case, how is the tree built (only X, or X plus the other treatment)?  For observational data, when there is only one W, all the other IV is grouped as X for matching (split the tree). When there are two treatments, if the assumptions are
(Y1, Y0) ⊥ W1| W2, X
(Y1, Y0) ⊥ W2| W1, X
is the method [here](https://github.com/rajkumarkarthik/mgrf-develop) suitable?
What is the assumption for the method [here](https://github.com/rajkumarkarthik/mgrf-develop)?

**Comment by jtibshirani** [comment]
This is a valuable feature and we have concrete plans to work on it. We'll be building off @rajkumarkarthik's original work but introducing a new implementation based on the latest grf code. For this reason I'm closing the issue -- we will open a new roadmap issue once the work begins.
