### ISSUE TITLE
classification forests

### ISSUE THREAD

**Issue by tibshirani** [grf-labs/grf#291]
It would be great if you could provide a classification_forest function.
Both probability and 0-1 loss would be useful, and would be something I would use often!

**Comment by seangupta** [comment]
Seconded. Using a more typical loss criterion as a splitting rule (such as Gini) for binary outcomes would be really helpful.

**Comment by jtibshirani** [comment]
We added a new forest called `probability_forest` in version 2.0 (https://github.com/grf-labs/grf/pull/711), which accepts multi-class input and outputs class probabilities. For classification, you can take an argmax of the class probabilities. The forest uses Gini impurity for the splitting criterion, which seems common for both probability estimation and classification.
