### ISSUE TITLE
Create a suite of performance benchmarks.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#299]
We should create a set of tests that run grf on data with fairly large `n` and `p`, and report important aspects of computational performance such as running time and heap usage. These tests will help us (1) characterize the performance of grf in different scenarios, and (2) prevent regressions in performance as we make changes.

At the least, we would run the benchmarks before every CRAN release. Ideally, these benchmarks would be run on a more regular basis to help narrow in on performance regressions.

**Comment by swager** [comment]
The DGPs from #475 may be helpful for this.

**Comment by erikcs** [comment]
The DGPs above are now part of the R package (#735).
