### ISSUE TITLE
Consider adding a linter or other static analysis tool as part of the C++ build.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#300]
Some research is required to determine the best choice.

**Comment by erikcs** [comment]
This [branch](https://github.com/erikcs/grf/blob/clang-tidy-ci/.travis.yml) tries CI with [clang-tidy](https://clang.llvm.org/extra/clang-tidy/). 

With only `readability` checks enabled, the (non-failing) build will look like:

![Screen Shot 2019-11-12 at 17 03 39](https://user-images.githubusercontent.com/7185264/68724367-1b41e200-0570-11ea-915a-dc615312f6da.png)

**Comment by jtibshirani** [comment]
Although we've had success linting locally to catch issues before release, enforcing that all lint checks pass on CI doesn't strike the right balance between code quality and development speed.
