### ISSUE TITLE
Bug: cannot use categorical variable

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#310]
Dear grf developers,

I am trying causal_tree with some simulated panel data. When I include dummies for individuals 
to control for individual fixed effects, the causal_tree got lost.

Then I read about how one-hot encoding can be bad for decision tree here https://roamanalytics.com/2016/10/28/are-categorical-variables-getting-lost-in-your-random-forests/

Therefore, I try to fix the problem by replacing dummies with just one categorical (factor) vector representing individuals. Then I got this following error alert. It seems the grf package cannot handle categorical variable in the recommended way? 

`Error in regression_train(data$default, data$sparse, outcome.index, as.numeric(tunable.params["mtry"]),  : 
  Not compatible with requested type: [type=character; target=double].`

Regards,
Mengxia.

**Comment by susanathey** [comment]
Are you wanting to interact these dummies with the treatment effect to see which individuals have larger treatment effects?  If not, and you just want to control for them, you should residualize the outcomes first.  But also, there are more complex issues involved in applying this with panel data.  Can you explain better what you are trying to do?

**Comment by ZhangMengxia** [comment]
@susanathey,
Thanks a lot for your reply.
 
I am trying to study such a question:
Y_it is whether an individual i survives in time t. Define Y_it=1 if i survives in time t.
W_it is whether individual i is treated in time t
S_it is some characteristic of individual i at time t. Suppose S_it and W_it are correlated positively.
I also consider individual age_it.
Suppose there are some individual fixed effects and time fixed effects that are not observed by researchers.

Then I simulate data in the following way:
Draw i_fix, t_fix, S_it randomly.
`W_it=rbinom[n=1,size=1, prob=exp(S_it)/(1+exp(S_it)) ]`, namely W_it is more likely to be 1 if S_it is higher.
`m=-0.01*age_it+3*S_it+0*W_it+i_fix+t_fix`
`prob(Y_it=1)=exp(m)/(1+exp(m))` , **namely W_it in fact has NULL effect on Y_it**.
Also,
Each individual is observed since their birth. They are born at different time.
Each individual is observed for a random number of time periods.
Namely, no left censoring, only random right censoring.
The observation window for individual i is closed since the first Y_it=1. 

I want to know models' abilities to resist confounding from S_it when estimating effect of W_it on Y_it. Since causal_tree() in package grf does not handle categorical individual index and time index directly, I transform individual index and time index into a huge matrix of dummies. 
Then I treat 
1) (S_it, age_it, individual dummies_i, time dummies_t) as X_it.
1) (S_it, age_it) as X_it_nodummy.


I compared linear fixed effects model from lfe package and causal_forest model from grf package.
**The results are:
Linear fixed effect model always finds NULL effect of W_it on Y_it.
Causal_forest model finds significant positive effect of W_it on Y_it when I run causal_tree(X,Y,W), but it is able to find NULL effect when I omit individual and time dummies and run causal_tree(X_nodummy, Y, W).**

So it seems the causal_forest got confused when I included individual and time dummies? Usually people ask me to include individual and time effects for control.

According to your reply, I tried the following two ways, and both can get NULL effect of W_it.
1) residualize Y by regressing Y on individual and time dummies and get the residuals as Y_rs, and run causal_forest(X_nodummy, Y_rs, W)
2) residualize Y, X_nodummy, W by regressing them on individual and time dummies separately, and get the residuals as Y_rs, X_nodummy_rs, W_rs. Run causal_forest(X_nodummy_rs, Y_rs, W_rs)

So my questions now are:
**1) If I only want to control some variables, I should first use them to residualize Y first, and do not use the controls as inputs for causal_tree()?
2) Shall I also residualize W and X by the controls, in case W, X are correlated with the controls?
3) I should put certain X in causal_tree() only when I believe effect of W has an interaction with X?**

Best regards,
Mengxia.

**Comment by swager** [comment]
Hi @ZhangMengxia, apologies for the delayed response on this.

We're working on better ways to handle categorical variables in GRF. We do have support for random effects, though, so you could do something like this for now:

- Define X = {S_it, age_it, t}, where time t is entered as a real value (not a dummy)
- Run `causal_forest` on (X, Y, W), with the option `clusters` set to the individual.

This will treat the individual effects as random effects, and control for time non-parametrically. One important difference between forests and linear models is that if you put time in as a covariate, we'll automatically control for it non-parametrically, so there's no need to explicitly create dummies.

Another option that's more closely motivated by classical fixed-effect modeling is your option # 2 above, which residualizes everything. Again, however, I'd only treat individuals as fixed effects, and put in time as a predictor. With non-parametric methods, there's no need to create dummies with a variable that has a natural ordering.

Hope this helps!

**Comment by jtibshirani** [comment]
I'm going to close this as it seems your question has been answered, but feel free to re-open or file another issue if that's not the case.

**Comment by ginward** [comment]
> Hi @ZhangMengxia, apologies for the delayed response on this.
> 
> We're working on better ways to handle categorical variables in GRF. We do have support for random effects, though, so you could do something like this for now:
> 
> * Define X = {S_it, age_it, t}, where time t is entered as a real value (not a dummy)
> * Run `causal_forest` on (X, Y, W), with the option `clusters` set to the individual.
> 
> This will treat the individual effects as random effects, and control for time non-parametrically. One important difference between forests and linear models is that if you put time in as a covariate, we'll automatically control for it non-parametrically, so there's no need to explicitly create dummies.
> 
> Another option that's more closely motivated by classical fixed-effect modeling is your option # 2 above, which residualizes everything. Again, however, I'd only treat individuals as fixed effects, and put in time as a predictor. With non-parametric methods, there's no need to create dummies with a variable that has a natural ordering.
> 
> Hope this helps!

Is "controlling for time non-parametrically" here similar to controlling for time fixed effects in linear regressions?

**Comment by ginward** [comment]
> > Hi @ZhangMengxia, apologies for the delayed response on this.
> > We're working on better ways to handle categorical variables in GRF. We do have support for random effects, though, so you could do something like this for now:
> > 
> > * Define X = {S_it, age_it, t}, where time t is entered as a real value (not a dummy)
> > * Run `causal_forest` on (X, Y, W), with the option `clusters` set to the individual.
> > 
> > This will treat the individual effects as random effects, and control for time non-parametrically. One important difference between forests and linear models is that if you put time in as a covariate, we'll automatically control for it non-parametrically, so there's no need to explicitly create dummies.
> > Another option that's more closely motivated by classical fixed-effect modeling is your option # 2 above, which residualizes everything. Again, however, I'd only treat individuals as fixed effects, and put in time as a predictor. With non-parametric methods, there's no need to create dummies with a variable that has a natural ordering.
> > Hope this helps!
> 
> Is "controlling for time non-parametrically" here similar to controlling for time fixed effects in linear regressions? @swager

Besides, if there is no time-fixed effect, can I safely leave the time covariate out, and still get robust standard errors?

**Comment by NicolasWoloszko** [comment]
Dear @susanathey ,
When you write:

> But also, there are more complex issues involved in applying this with panel data

Are you referring to the paper `When Should You Adjust Standard Errors for Clustering?`, or are there other issues than clustered standard errors I should be wary of? 

My current project involves analysing the heterogeneous effects of labour market regulation using a micro-data from EU LFS at the household/person level for various countries and years. Identification relies on time variations of the level of labour market regulation. 

I plan to include country fixed effects in the orthogonalisation phase and cluster by country*year. Does it sound right to you? 

Lastly, to what extent is the panel structure taken into account in the orthogonalisation step ? As far as I understand it should follow the Panel Double ML recipe (https://arxiv.org/abs/1712.09988). Does it? 

Thanks a lot in advance for your help.
