### ISSUE TITLE
Bug of version 0.10.1: X has to have at least two columns for average_partial_effect() function

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#311]
I tried 
`X=matrix(rnorm(100), 100,1)
Y=t(t(rnorm(100)))
W=t(t(rbinom(100,size=1, prob=0.5)))
forest = causal_forest(X,Y,W)
average_partial_effect(forest)`

And the following alert comes out
`Error in if (length(Y) != nrow(X)) { : argument is of length zero`

Then I look inside the partial effect function, I found line 69 of average_partial_effect (forest) changes the one-column matrix X into a row vector by `forest$X.orig[subset,]` in
`  variance_forest <- regression_forest(forest$X.orig[subset,],
                                       (subset.W.orig - subset.W.hat)^2)
`

Then this is a problem inside the regression_forest(X,Y) function on line 84
`if(length(Y) != nrow(X)) { stop("Y has incorrect length.") }`

because now the input X becomes a row vector,   nrow(X) will be NULL.

Mengxia.

**Comment by jtibshirani** [comment]
Hi @ZhangMengxia, thank you for the detailed report and diagnosis of the issue! We plan to fix this bug for the next release.

**Comment by jtibshirani** [comment]
Addressed in #317.
