### ISSUE TITLE
Question: Does grf allow for within-cluster dependence?

### ISSUE THREAD

**Issue by kendonB** [grf-labs/grf#314]
This issue is discussed here and can cause (harmful) overfitting with random cross validation:

https://cran.r-project.org/web/packages/CAST/vignettes/CAST-intro.html

**Comment by swager** [comment]
I'm not sure I follow your question -- could you please be a little more specific? The point of the <a href="https://github.com/grf-labs/grf/blob/master/REFERENCE.md#cluster-robust-estimation">clustering option</a> is to allow for dependency within clusters.

**Comment by kendonB** [comment]
This is exactly what I was after - I had just missed that in the documentation. Thanks
