### ISSUE TITLE
Feature request: multi-way clustering? 

### ISSUE THREAD

**Issue by kendonB** [grf-labs/grf#328]
It would be fantastic if grf supported multi-way clustering as in the CAST package:

Ref:
https://github.com/environmentalinformatics-marburg/CAST/blob/master/R/CreateSpacetimeFolds.R

**Comment by swager** [comment]
Hi @kendonB, this sounds like a feature that would be nice to have; however, in the short term, we're focusing on building up core workflows for causal inference. If you need multi-way clustering in a way that interfaces with current grf functionality, I'd be happy to discuss how to make that work.
