### ISSUE TITLE
causal mediation analysis with grf?

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#356]
I wonder what procedures one would have to take to conduct a causal mediation analysis using grf? Assume we have the attached DAG and that the researcher aims to identify the direct effect (*c*) of a treatment (assume unconfoundedness controling for confounders) and the indirect effect *ab* via a defined mechanism. In traditional path analysis (or linear SEM), we would regress M on T to obtain the effect *a*; regress T on Y, controling for M to get *c*. 

Would grf be suitable for such analysis? One advantage would be using grf instead of traditional SEM is that we can estimate causal hetergenity in each step. DAGs do not make parametric assumptions so using grf would be an innovative application. 

![dag](https://user-images.githubusercontent.com/9431362/49980198-79111880-ff20-11e8-98d1-51a81b3ff1ed.jpg)

**Comment by swager** [comment]
As discussed in the generalized random forests paper (https://arxiv.org/pdf/1610.01271.pdf), we can build a forest that targets any parameter identified via an estimating equation. So if you have an estimating equation that can identify a constant direct effect (ignoring covariates), then in principle the grf recipe allows for building a forest for estimating heterogeneity in the direct effect. It's not immediately clear to me, though, how easy/hard it would be to get something like this to work.

**Comment by adeldaoud** [comment]
ok, so estimating total, direct and indirect effects are not as simple as adding variables to block paths or removing them to open up paths, as one would do in a structural equation model (in a linear world)?

To elaborate my point, so say that I drew that DAG I posted in my initial comment to identify the effect of this treatment of on the outcome and imagine two scenarious:

A)
Say that I aim to capture $E[Y(1) - Y(0)|C, M]$, where C = Counfounders and M = Mechanism. Given my DAG and since I am blocking path *a* and *b*, am I thus estimating *c*? That is assume I use *grf*'s causal_forest and feed it with W = Treatment, X = c(C, M). Am I not in this scenariou estimating the direct effect, *c*? If not, then what quantity is my ATE representing?

B)
Say now that I removed M from my estimation, namely $E[Y(1) - Y(0)|C]$, and provided these data to my causal_forest. I am deducing that the quantity of interest that causal_forest is estimating is the total effect, that is *c + ab*. 

Hence, accross these two scenarious the ATE changed depending on what node I blocked or unblocked, given my DAG. What am I missing with this reasoning? Thanks for your help.

**Comment by swager** [comment]
So that would be one way to do it. I'm worried, though, that this forest wouldn't be designed to target the direct effect specifically--rather, it'd be piecing together results from forests trained for different tasks. And this can potentially lead to regularization bias. (Analogously, one could estimate treatment effects by training a single regression forest on (X, W), and then taking the difference of predictions at (X, 1) vs (X, 0). This, however, is much more vulnerable to confounding than a causal forest.)

So what I'd start by doing is to write an estimating equation for the direct effect without covariates, i.e., c is identified via linear regression while controlling for M. Then we can turn this into a forest following, e.g., Section 6 of the GRF paper.

**Comment by ginward** [comment]
Hi @adeldaoud 

Have you figured out the answers to your question yet? I have a similar problem here - I want to do mediation studies with CF. Can we have a chat?

**Comment by ginward** [comment]
> As discussed in the generalized random forests paper (https://arxiv.org/pdf/1610.01271.pdf), we can build a forest that targets any parameter identified via an estimating equation. So if you have an estimating equation that can identify a constant direct effect (ignoring covariates), then in principle the grf recipe allows for building a forest for estimating heterogeneity in the direct effect. It's not immediately clear to me, though, how easy/hard it would be to get something like this to work.

What if the direct effect is heterogeneous as well?

**Comment by ginward** [comment]
> As discussed in the generalized random forests paper (https://arxiv.org/pdf/1610.01271.pdf), we can build a forest that targets any parameter identified via an estimating equation. So if you have an estimating equation that can identify a constant direct effect (ignoring covariates), then in principle the grf recipe allows for building a forest for estimating heterogeneity in the direct effect. It's not immediately clear to me, though, how easy/hard it would be to get something like this to work.

@swager what is the direct effect here is not constant, but dependent on X, for example, c(X)?

**Comment by adeldaoud** [comment]
@ginward , my collaborators and I have some ideas about help extending CF to a mediation study, but this will require more studies. However, if you want to apply nonparametric techniques in general to mediation, then I would take a closer look at VanderWeele, Robins, Pearl's work.

**Comment by ginward** [comment]
> @ginward , my collaborators and I have some ideas about help extending CF to a mediation study, but this will require more studies. However, if you want to apply nonparametric techniques in general to mediation, then I would take a closer look at VanderWeele, Robins, Pearl's work.

Thanks for your reply. 

I agree with you that by copying the SEM approach to causal forests won’t work. Using the DAG you posted earlier by including the mediators as the controlling covariates, we are treating the mediators as one of the confounding variables that makes the outcome variable independent of treatment. However, being the confounding variable is different from being the mediator, as mediator has causal implications other than treatment T.
