### ISSUE TITLE
Limit number of CPUs when training

### ISSUE THREAD

**Issue by hammer-wang** [grf-labs/grf#357]
Hi, 

Is it possible to set the number of cpus to use for training? Currently the training processes takes all cpus available on my server. It would be nice if we could set this number.

Thanks,
Haozhu

**Comment by hammer-wang** [comment]
> Have you tried using the `num.threads` argument to control the number of threads?

Thanks! I was not aware of the argument option. Just tried it and it worked perfectly.

**Comment by adeldaoud** [comment]
Does the `num.threads `argument refer to the number of physical or logical cores? 

thanks
