### ISSUE TITLE
Estimate of LATE using instrumental_forest

### ISSUE THREAD

**Issue by pachard** [grf-labs/grf#358]
Hello,

I am trying to obtain a point estimate of the IV procedure (together with se) in fashion similar to the output of the function average_partial_effects.  However it's not obvious to me how to average the different tau hats and mostly calculate standard errors. Will there be such a function in the future? Could you give me guidelines on how I could do it? 

Best, 
Pascal

**Comment by swager** [comment]
@pachard, we don't have a function for this yet, but here's something you could do.

Equation 52 of this paper, https://arxiv.org/pdf/1702.02896v4.pdf, has a doubly robust score for estimating what could be called the "average conditional local average treatment effect" (i.e., writing tau(x) for the LATE conditional on x, the estimand is \tau = E[\tau(X)]).

Then, using these doubly robust scores \hat{Gamma}_i, you can estimate \hat{\tau} = 1/n \sum \hat{Gamma}_i and \hat{Var}[\hat{\tau}] = 1/(n * (n-1)) \sum (\hat{Gamma}_i - \hat{\tau})^2.

**Comment by pachard** [comment]
Thanks a lot. I will look at the paper and try to implement the doubly robust score.
