### ISSUE TITLE
Confidence intervals for CLATE in instrumental forest?

### ISSUE THREAD

**Issue by lepromatous** [grf-labs/grf#364]
I can't seem to figure out a CI for CLATE in an instrumental forest is computed appropriately - any thoughts or direction-to-be-pointed-in is much appreciated.  Thanks so much!

**Comment by swager** [comment]
Hi @lepromatous, I'm not sure I quite understand the question. Are you trying to get CIs for the average CLATE (like in the `average_treatment_effect` method), or do you want CIs for \hat{tau}(x) as provided by an instrumental forest? A code snippet outlining what you're aiming to do would be helpful.

**Comment by foo-bar-baz-qux** [comment]
Also very interested in this, would be great to have `average_treatment_effect()` work for instrumental forests as well.

**Comment by swager** [comment]
Apologies @lepromatous for dropping this thread.

1. If there's regular demand for this functionality, we should probably add an `averagage_clate` function to the package that takes an IV forest as an argument. See #358 for a discussion of how to do this "by hand". Contributions welcome!
2. One way to make CIs shorter is to use a larger minimum node size to regularize the forest more heavily. If the CIs are outside the [0, 1] interval even after that, then this may be indicative of a weak IV. For issues like these, I'd recommend doing simulation studies with data-generating distributions that look a lot like your real dataset so you can get a better feel for what the forest is doing.

**Comment by jtibshirani** [comment]
I've marked this as a feature request. Note that this was previously requested in #358.

**Comment by kingsharaman** [comment]
+1 for this feature! Just run into this thread while trying to solve a similar problem.

**Comment by hliebert** [comment]
I'd be very interested in this feature as well.
