### ISSUE TITLE
Error: cannot allocate vector of size "X" GB

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#365]
**Description of the bug**
I have a dataset that is 2,000,000X34 with a binary outcome, binary treatment, and clustered data.  The causal_tree finishes the estimation with 1000 trees without any error. However, when I increase the forest size to e.g. 4000 trees, the procedure fails due to memory problems: "Error: cannot allocate vector of size 14.1 Gb". The error comes at the very end of the estimation procedure (after about 3 h of estimation.), which indicates that it is something at the very end of the causal_tree function that induces the error.

I am using a Windows PC with 64 GB of RAM, four core i7 Intel quad core. 

**Steps to reproduce**
The following code outlines the parameters I am using. Can send you a version of the data in confidence if necessary.

```
tau.forest.clust <- causal_forest(covariates,
+                             outcome, 
+                            treatment, 
+                             clusters = cluster.int,
+                             num.trees = 4000)
Error: cannot allocate vector of size 14.1 Gb
```

**GRF version**
Package version  0.10.1.

**Comment by jtibshirani** [comment]
Hi @adeldaoud, after seeing this issue I realized that I forgot to respond to your comment on #179 -- my apologies for that. I think you are running into the same shortcoming reported there. I'll close this one in favor of continuing the conversation on the existing issue.
