### ISSUE TITLE
Does the num.threads argument refer to the number of physical or logical cores?

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#366]
Related to issue #357, does the `num.threads` argument refers to the number of physical or logical cores? I could not figure this out from the documentation.

I have a four physical core CPU with eight logical cores. I would like to use 7 these logical CPUs and reserve the last one for misc processing. Should I then specify `num.threads = 7`?

Thanks

**Comment by jtibshirani** [comment]
The `num.threads` argument refers to the number of threads of execution that grf will use during compute-heavy parts of the algorithm, such as growing trees. Threads are typically scheduled across the logical cores of a machine. Hopefully that helps answer your question, let me know if something is still unclear.

**Comment by adeldaoud** [comment]
Thanks @jtibshirani for your explanation. What confused me about the `num.threads ` function is the difference between the number of threads and logical cores of a physical CPU. After reading a bit about it, I conclude that the number of threads and logical cores a CPU has are the same things. In other words, they both refer to how many threads a physical CPU can process simultaneously. Hence, if I want to save one logical CPU for other tasks and my PC has eight logical cores, `num.threads = 7` is the correct call.

**Comment by jtibshirani** [comment]
I think there may be some confusion over what the 'thread' `num.threads` is referring to: it describes the number of software threads (in our case C++ threads), not hardware threads. In any case, I agree that if you want to run grf on 7 logical cores, setting `num.threads = 7` is the right way to go.
