### ISSUE TITLE
install the development version

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#367]
Hi @jtibshirani , trying to install the development version but no success. Can you please let me know what is wrong with my code below:

```
library(devtools)

# try this function
install_github("grf-labs/grf/master/r-package/build_package.R") # does not work
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 50/60
  Rate limit reset at: 2019-01-18 23:28:05 UTC

# try different code
install.packages("https://raw.github.com/grf-labs/grf/master/r-package/build_package.R", repos = NULL, type = "source") # does not work either

Installing package into ‘C:/Users/add893/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://raw.github.com/grf-labs/grf/master/r-package/build_package.R'
Content type 'text/plain; charset=utf-8' length 955 bytes
downloaded 955 bytes

Error in getOctD(x, offset, len) : invalid octal digit
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/add893/AppData/Local/Temp/RtmpSIwaV4/downloaded_packages/build_package.R’ had non-zero exit status
```

**Comment by jtibshirani** [comment]
Hi @adeldaoud, to install the development version you will need to clone or download the github repository, then change into the directory `r-package` and run the `build_package.R` script. The `install_github` command unfortunately does not work with this repository.

**Comment by adeldaoud** [comment]
@jtibshirani thanks again. Downloaded the package from github, unpacked it, and opened the `build_package.R` script. First, I unistalled the existing grf package with `remove.packages("grf")`. Then I set the working directory "C:\grf\grf-master\r-package", and then run the `build_package.R` script. The installer could not find the dependency `DiagrammeR`, although it is an installed package. Please see the full script results below:

![grf not found1](https://user-images.githubusercontent.com/9431362/51432229-10454c00-1c02-11e9-879a-8211e9a677d9.jpg)

![grf not found2](https://user-images.githubusercontent.com/9431362/51432271-a5e0db80-1c02-11e9-9fc0-b59e1d143fa6.jpg)

**Comment by halflearned** [comment]
I've had some issues with `DiagrammeR` before (although I simply could not install it at the time). This is not fantastic advice, but in a pinch you can simply comment out [this](https://github.com/grf-labs/grf/blob/54b5e4f39a80e72edd3d02ba4641b9c3b04137d0/r-package/grf/DESCRIPTION#L23) line. You'll still be able to install `grf`, but won't be able to plot trees.

**Comment by jtibshirani** [comment]
I'm going to close this because we haven't heard back, but feel free to send an email if you need more help with installation.
