### ISSUE TITLE
OOB predictions for causal forest are all NaN

### ISSUE THREAD

**Issue by lminer** [grf-labs/grf#368]
On my current dataset, OOB predictions for causal forest are all NaN. y.hat is also all NaN. There are around 5000 observations split 50/50 between treatment and control. All features are integers, although I coerce them to floats. 

Is the dataset perhaps too small? It makes no difference if I set honesty to false and ci.group.size to 1. Within the forest object itself. This seems related to [this issue] (https://github.com/grf-labs/grf/issues/313).

GRF version is 0.10.2.

```r
library(dplyr)
library(grf)
raw_dat <- read_csv("data/mydata.csv", guess_max = 4000)
raw_dat <- raw_dat[complete.cases(raw_dat[ , c('a', 'b', 'c', 'd')]),]

X <- raw_dat[, c('a', 'b', 'c', 'd')]
Y <- pull(raw_dat, 'foo')
W <- pull(raw_dat, 'treat')

forest <- causal_forest(X, Y, W, num.trees = 5000)
tau.hat <- predict(forest)
```

**Comment by swager** [comment]
Interesting, thanks for bringing this up. Could you please share a small simulation study that replicates the issue so we can look into it?

**Comment by lminer** [comment]
@swager Shared a file with you via dropbox

**Comment by swager** [comment]
It looks like this might be a missing data issue. The 4th line in the script checks for missing data in `X`. Does also removing rows with missing `Y` or `W` help? This change seemed to fix the issue at least on the example file you shared. (Whether or not this indeed is indeed the issue here, we certainly need to improve error handling with missing values of `Y` or `W`... Now, the forest just silently gives a bunch of `NA`predictions when this happens.)

**Comment by lminer** [comment]
You are correct. I thought I'd checked for that, but apparently not (face palm). How does GRF treat missing data in X? Is it robust to missing data like a normal random forest?

**Comment by swager** [comment]
The short story is that tree-based methods can in principle handle NA values very elegantly, but none of the current random forest packages implement those best practices (unlike standalone tree packages, which do).

Currently, I'd recommend not running grf if you have missing values in X, as we do not guarantee good behavior (or rather, I'd recommend filtering out either rows or columns with missingness, or enconding the missingness by hand if there's a good way of doing so). Adding better support for missing values in the future is high-priority for us.

**Comment by lminer** [comment]
Interesting. I didn't realize current implementations don't do a good job of handling NAs. I would say that support for missing values is very valuable in the RCT context where there are often problems with missing data due to survey issues.

**Comment by jtibshirani** [comment]
I'm going to close this in favor of #373, where we're tracking the fact that we need to check for missing observations. As @swager mentioned, we are also thinking through how to best add support for missing data in `X`, and will file an issue once we have a better idea about what the approach might look like.

Thank you for raising this issue, I'm sure many other users have run into this same confusing behavior as well.
