### ISSUE TITLE
Support for Multiple Outcome Variables?

### ISSUE THREAD

**Issue by awooddoughty** [grf-labs/grf#374]
Is there any plan to support multiple outcome variables (i.e. `Y` is `N x K` with `K > 1`)? It **seems** like it shouldn't be too difficult to implement, but I haven't read the paper carefully enough to know for sure. 

The current solution would be to just train separate models for each outcome, but this is likely inefficient computationally and you could miss important correlations between the outcomes by treating them as independent. For instance, imagine you are interested in both the cost and benefit of a treatment. It would make sense to model the joint distribution of `(cost, benefit)` as a function of the treatment as opposed to assuming they are independent.

For reference here's the sklearn [documentation](https://scikit-learn.org/stable/modules/tree.html#multi-output-problems) on multi-output problems.

**Comment by susanathey** [comment]
Yes we have a version that does this, but we need some refinements to how it is implemented in our production package.  I totally agree it is an important use case and need it for several of my projects too. @jtibshirani had some thoughts about this-- @jtibshirani can you comment?  If you need it soon, email me and we can discuss getting access to the version.

**Comment by swager** [comment]
Yes multi-task learning is a valuable feature, and fits naturally in the conceptual framework. We're working on implementing it, and are tracking progress on this issue in #285.
