### ISSUE TITLE
Question: Local Linear Causal Forests

### ISSUE THREAD

**Issue by guanhuac** [grf-labs/grf#381]
I wonder if the Local Linear Causal Forests (section 4.4 of https://arxiv.org/pdf/1807.11408.pdf) has been implemented in the current version of grf. Thank you very much.

**Comment by swager** [comment]
We're working on it; the most recent progress is in #382. Hopefully we'll have this integrated soon.

**Comment by rinafriedberg** [comment]
Hey @guanhuac ! We're hoping to merge this fully in the next few days and I'll comment again and tag you when it's pushed through. Thanks for your interest :)

**Comment by jtibshirani** [comment]
Closing this issue, as we're tracking progress in #276.
