### ISSUE TITLE
how to handle time invariant variables with panel data

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#384]
Dear developers, 
when I using causal forest, I have the following question, which I could not figure out myself.

Related to Issue #310, for panel data, if I already residualize Y using a fixed effect model with individual fixed effects (individual dummies), according the answers there.   new Y=old Y - individual fixed effect. With the new Y, can causal tree correctly estimate effects of time invariant variables (treating them as W)? (effects of time invariant variables are not identifiable under fixed effect model)

Thanks a lot!

**Comment by ZhangMengxia** [comment]
By simple simulation (Y_it=b0+b1W_i+b2X_it+a_i+e_it), I found effect of time invariant treatment (b1) cannot be correctly identified, if Y is already residualized by individual dummies.

**Comment by swager** [comment]
The parameter b1 in the model you wrote down is not identified, because any effect of Wi is absorbed by the fixed effects. If you have fixed effects, then you need treatment variation over time in order to estimate the treatment effect (like in a difference in differences design).
