### ISSUE TITLE
will very high correlation between W (treatment) and X be a problem for causal forest

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#385]
Suppose both X and W are continuous. Suppose X, W have very high correlation, with 0.95 correlation coefficient. The tree is built on X, where within a leaf the nodes have very similar X. Because of the high correlation between X and W, W should be very similar within one leaf, too. In this situation, can causal forest correctly identify the effect of W?  
Thanks a lot!

**Comment by swager** [comment]
If you have high correlation between X and W, overlap may be a problem. See #256 for more discussion of the meaning of overlap with continuous treatments.
