### ISSUE TITLE
Quantile regression forest broken by commit 996f3b3fd4d89761b7b9ed6b0da31dbbba6895ac

### ISSUE THREAD

**Issue by davidahirshberg** [grf-labs/grf#387]
**Description of the bug**
predict returns nondeterministic junk --- probably the contents of uninitialized memory.

**Steps to reproduce**
The following code is a stripped-down version experiments/quantile_examples/quantile_simu_2.R. 

p = 10
n = 500
i = 5
X = matrix(2 * runif(n * p) - 1, n, p)
Y = rnorm(n)  + 100 * (X[,i] > 0)
X.new = matrix(2 * runif(n * p) - 1, n, p)

forest = quantile_forest(X, Y)
all(predict(forest,X.new) == predict(forest,X.new)) # true pre-commit, false afterward
predict(forest,X[1:4, ])                                                # reasonable pre-commit, junk afterward

**GRF version**
Development, commit 996f3b3fd4d89761b7b9ed6b0da31dbbba6895ac and after

**Comment by davidahirshberg** [comment]
It's an off-by-one error in the quantile forest bindings. PR soon.

**Comment by halflearned** [comment]
Just reopening this until #389 gets merged in.
