### ISSUE TITLE
What's the default min.node.size?

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#392]
I checked the document and the reference. I could not find the default value for the min.node.size parameter for causal_forest function.

When min.node.size = NULL, what's the default value of min.node.size?

Thanks a lot!

**Comment by halflearned** [comment]
Hi @ZhangMengxia, thanks for the question. Default values are determined in [input_utilities.R](https://github.com/grf-labs/grf/blob/dd89efa447e69b1ae37d728c4d9c8a5cdfec76e9/r-package/grf/R/input_utilities.R#L60). For `min.node.size`, the default value is 5.

**Comment by ZhangMengxia** [comment]
Hi @halflearned, thanks a lot for your answer!
