### ISSUE TITLE
representative heterogeneous treatment/partial effects

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#397]
Following code on the homepage for "Add confidence intervals for heterogeneous treatment effects; growing more trees is now recommended", I am trying to get tau(X1) while holding other X at 0. I standardized X, so all X have mean 0. 

I found tau(X1, other X=0) is very different from the estimated average partial effect E(tau(X)).

I am wondering the tau(X1, other X=0) may not be representative. The example on the main page is very simple, as tau(X)=tau(X1). While in my case, X have about 200 columns, tau(X1, other X=0) could be very different from tau(X1, other X=other value). 

Not sure whether my understanding is correct. Is there a better solution to get tau(X1) when there are many X that moderates the effect of W?

Thanks a lot!

This question might be related to issue #303

**Comment by swager** [comment]
I'm not sure I understand the question, sorry. Could you please share a small simulation that exhibits the phenomenon you're asking about?

**Comment by ZhangMengxia** [comment]
@swager Thanks for your reply and question!

The context is
Y=m(X)+W.tau(X)+epsilion
X=(X1, X2,..., X200),  namely X have 200 columns.
Suppose Y is restaurant exit in each period, W is number of customer posted images a restaurant received during last period, X1 is whether the restaurant is chain restaurant.

So first I used the following function.

tau.forest=causal_forest(X, Y, W,  num.threads = 5, seed=1234, clusters=clusters, num.trees = 4000)

the result is
estimate=-0.7232190    
std.err=0.3047159

My understanding is that estimate tau=-0.7232190 is mean(tau(X)).

Then I want to know how tau(X) vary with X1, so I generate a new X_test with various X1 (chain or not chain restaurant) and all other X (namely X2, X3....) constant at 0. 

Then I use the following function to get Tau(X1, other X=0)

tau.hat = predict(tau.forest, X.test, estimate.variance = TRUE)

For chain:
tau.hat=-0.007662772, std=0.007676945

For not chain:
tau.hat=-0.007566261, std=0.0075799

So the first thing I observe is that tau=-0.7232190 is very different from tau.hat(X1=chain, other X=0)=-0.007662772.

So I am wondering whether tau.hat(X1, other X=0) is representative of tau.hat(X1).

Sorry for the long explanation. 

--



clusters is restaurant ID.

**Comment by swager** [comment]
Got it, thanks. The is a big difference indeed -- looks like tau.hat(X1, other X=0) may in fact not really be representative of average behavior. Some comments:
- Forests may lose power if they are run on hundreds of covariates. If you can screen which covariates you use for the tau.forest following, e.g., the example at the end of the package README, you may get more accurate CATE estimates.
- The average treatment effect function doesn't just take the mean of the CATE predictions, but instead runs a doubly robust aggregation; see Section 2.1 of https://arxiv.org/pdf/1902.07409.pdf for details.
- If you want subgroup average treatment effects, you can try things like `average_treatment_effect(tau.forest, subset = (X1 == chain))`. This is also based on doubly robust estimation.

**Comment by ZhangMengxia** [comment]
@swager Thanks a lot for your answers and comments! I really appreciate it.
