### ISSUE TITLE
hist(tau.hat.noclust, ..., breaks=...) causes error in experiments/acic18/script.R

### ISSUE THREAD

**Issue by MaxGhenis** [grf-labs/grf#400]
These lines cause an error:
https://github.com/grf-labs/grf/blob/036962492b1423ca6c966dcbdfc34e32e92c3026/experiments/acic18/script.R#L260-L261

>Error in hist.default(tau.hat.noclust, xlab = "estimated CATE", main = "", : some 'x' not counted; maybe 'breaks' do not span range of 'x'

As the error suggests, this is because of `tau.hat.noclust` going outside the [0, 0.55] range:

`range(tau.hat.noclust)`
>-0.0333109446082792 0.627913695407719

This is resolved by removing the `breaks=...` argument, producing this histogram:

`hist(tau.hat.noclust, xlab = "estimated CATE", main = "")`
![image](https://user-images.githubusercontent.com/6076111/56226053-5a827180-6027-11e9-8a98-6d44bba0828a.png)

See cell 32 in https://nbviewer.jupyter.org/github/MaxGhenis/random/blob/8659f5208782e96433bb9966de6febce17d0e9bc/grf_acic18.ipynb

**Comment by MaxGhenis** [comment]
In case helpful, this notebook goes through that example R script (with the hist fix to run through the full thing): https://nbviewer.jupyter.org/github/MaxGhenis/random/blob/master/grf_acic18.ipynb

**Comment by swager** [comment]
Interesting. It might be because this is run on a different machine so we end up with different forests despite using the same seed. We're working on fixing this issue in #379.

**Comment by jtibshirani** [comment]
I'm going to close this, as we're tracking the randomization issues in #379. Thanks for calling this to our attention, it reaffirms the need to fix the underlying issue.
