### ISSUE TITLE
Question: Does get_sample_weight take into account the clusters?

### ISSUE THREAD

**Issue by qiy17** [grf-labs/grf#401]
Hi!

I have a question when trying to apply the method. Does get_sample_weight take into account the clusters? 

I explored it using my own simulated data and it seems that when making OOB predictions, the samples within the same cluster get different weights.

Thanks,

**Comment by qiy17** [comment]
Just to add a few more details to clarify my question:

It seems (I looked into the trees from get_tree) that when building individual trees, the whole cluster is sampled. However, when placing the splits, it is possible that the observations in the same cluster end up in different leaves. Is this a correct way of understanding the algorithm?

**Comment by jtibshirani** [comment]
Hi @qiy17, clusters are largely relevant to the training procedure -- it might be helpful to consult [the reference](https://github.com/grf-labs/grf/blob/master/REFERENCE.md#cluster-robust-estimation) for more background. Cluster membership is also considered during prediction when deciding what trees are out-of-bag for each datapoint.

However, during prediction for a particular tree, it is entirely possible that two samples from the same cluster fall in separate leaves. This explains why two samples from the same cluster might have different values for `get_sample_weights`.
