### ISSUE TITLE
Obtain (conditional) outcome estimates and confidence intervals

### ISSUE THREAD

**Issue by ad8437128** [grf-labs/grf#403]
Please feel free to direct me if this issue has been addressed elsewhere.

1. While causal_forest predicts conditional treatment effects, I would like to obtain estimates and confidence intervals for (conditional) potential outcome estimates of the form: E[Y|X=x, W=w] and E[Y|W=w], where w=0, 1 denotes treatment status.  

2. Also, I would like to find if the above in (1) can be done for J multiple treatment levels, i.e., w=0,1,..., J-1. 

Thanks for your time.

**Comment by ras44** [comment]
Not sure if this helps, but for E[Y|X=x,W=w] you might want to consider the model described in Comment 2.2 [here](https://arxiv.org/pdf/1712.04802.pdf).

**Comment by davidahirshberg** [comment]
For E[Y|X=x, W=w], a regression_forest fit on X' = (X,W) will work.

If you want to estimate E[Y|W=w], a natural estimator is the average of the outcomes {Y_i : W_i=w}. But it sounds to me like you're more interested in estimating some kind of average of a potential outcome. The code in average_treatment_effect can be modified to do this, and I'd be happy to help, but if that is the case I'd need to know what kind of average you're interested in --- an average over the whole sample like E[Y(w)], or over subsample of units like those who receive treatment w' like E[Y(w) | W=w'].

**Comment by susanathey** [comment]
Just to clarify Skip's answer above, you would not want to put both X and W into a single forest.  If you have enough data you could estimate the models for different treatment levels separately.  If you want to use a single forest for all treatment levels, we have another project called mgrf.  Can you clarify what you want to do?

**Comment by jtibshirani** [comment]
In some parts of the package (e.g., `average_treatment_effect`) we need to estimate quantities of the form `mu(x, w) = E[Y|X=x, W=w]`, and do the following:

1. Fit the propensity score `e(x) = P[Y|X=x]` and marginal response surface `m(x) = E[Y|X=x`] via separate regression forests.
2. Fit a causal forest for `tau(x)`, with nuisance components as estimated in step 1.
3. Estimate `mu(x, w) = m(x) + (w - e(x)) * tau(x)`.

It might help to take a look at the following lines in `average_treatment_effect`, that perform this computation: https://github.com/grf-labs/grf/blob/master/r-package/grf/R/average_treatment_effect.R#L170-L172

In the case of multiple treatments, this idea can be generalized in several ways. One approach that works with the package currently is a 'one-vs-all' generalization of the above idea, where you run the above steps with treatment 'k' coded as 1 and all other treatments coded as 0. As @susanathey mentions, another approach is to build a variant of grf that accounts for multi-level treatments directly (not currently integrated, we are tracking its progress in #285).

Finally, it would be nice to provide a short function which performs the above steps, or at least add this information to our [algorithm reference](https://github.com/grf-labs/grf/blob/master/REFERENCE.md).

**Comment by ad8437128** [comment]
Thanks for all the feedback! Apologies that I was a bit sloppy with my definition of the causal parameters. I will respond in turn.

@ras44: Comment 2.2 is helpful but does not directly address my question. 

@davidahirshberg and @susanathey: You're exactly right that I am interested in estimating averages of a potential outcome. Let me clarify. Let Y(w) denote the potential outcome associated with treatment W=w' (for both binary and multi-level cases).  I am interested in the following causal functions: 

(1) E[Y(w)]: The treatment-specific counterfactual potential outcome.

(2) E[Y(w) | W=w']: The treatment-specific counterfactual potential outcome for those assigned to treatment W=w'.
 
(3) E[Y(w) | W=w', X]: The treatment-specific counterfactual potential outcome if everyone was assigned to treatment W=w', conditional on X.

Comment (a): @jtibshirani: Thanks for your helpful suggestion! This is the closest to what I have in mind.  Based on your response, it would seem that your suggestion works in the case when unconfoundedness holds (by design in RCTs). I think your 'one-vs-all' generalization of this idea should work as well.  

Comment (b): @susanathey: Thanks for pointing me to mgrf. As a follow-up, should one expect the 'one-vs-all' generalization and mgrf approach being tracked in #258 to produce similar (or identical) estimates? 

Comment (c): I am also interested in these causal parameters for observational studies where an instrument is available (e.g., using the instrumental_forest). It appears to me that @jtibshirani's suggestion would not extend to IV forests? This is based on my reading of #364 and #358, where there's no current function for averaging over the instrumental_forest predictions. Correct? 

Finally, I definitely agree with @jtibshirani that adding this information to the reference would be helpful as well as providing a function for these steps. Thanks!

**Comment by swager** [comment]
Thanks @ad8437128 for the clarifications. The solution provided by @jtibshirani is the best we've currently got in `grf` for the estimand (3).

The estimand (1) is discussed in #380, which also has sample code for a doubly robust estimator for it. Note that E[Y(w)] is effectively "half" of the definition of the ATE = E[Y(1)] - E[Y(0)], and the estimation strategy in #380 reflects this fact.

Finally, for (2), it's also possible to construct a double robust estimator by hand. This estimand is "half" of an ATT, and it's possible to build an estimator for it by combining ideas from the ATT option in `average_treatment_effect` and the discussion in #380. Let me know if it'd be helpful for me to go in more detail.

**Comment by ad8437128** [comment]
Thanks @swager. This is very helpful. Thanks for pointing me to #380. I'll start from there. The only aspect that remains a bit unclear to me is how this (i.e., @jtibshirani's solution) extends to the IV forest case using instrumental_forest as I noted in Comment (c). Again, thank you.

**Comment by swager** [comment]
Apologies for the long silence on this. In general, things like `hat{mu}(x, w) = hat{m}(x) + (w - e(x)) * hat{tau}(x)` still work with IV forests -- the only thing to be careful about is that now `hat{tau}(x)` needs to be estimated via an IV forest (else it will be confounded). The implementation of #490, and references therein, have more discussion of related issues.

**Comment by austindenteh** [comment]
Sorry to have to re-open this issue but I had a question based on @swager's comment https://github.com/grf-labs/grf/pull/411#issuecomment-525582725. I understand that we can obtain conditional means, for instance, as described in the function `est_counterfactual_outcomes` based on https://github.com/grf-labs/grf/issues/403#issuecomment-486915981. However, how do we get variance estimates of these conditional means? Thanks for your time.
