### ISSUE TITLE
details for estimating continuous treatment

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#409]
Dear authors,

I have the following three questions for continuous treatment, especially when clusters are specified.

1) What is the objective function for splitting the tree? 
Is it minimizing sums of squared error of centered W and prediction using X, namely
![CodeCogsEqn](https://user-images.githubusercontent.com/17790770/56777977-e6636e80-6788-11e9-967c-1b61748b806b.gif)
?

2) Is the causal_tree() function using double sample trees or propensity trees? 
For continuous treatment, is propensity trees still applicable?  For question 1, I am assuming something like a propensity tree.

3) What is the estimator of tau(x) for continuous treatment, analogous to equation (8) below?
Paper https://www.tandfonline.com/eprint/v7p66PsDhHCYiPafTJwC/full equation (5) mentioned the estimator for binary treatment.
![Screenshot 2019-04-25 18 37 21](https://user-images.githubusercontent.com/17790770/56778042-36423580-6789-11e9-8c3b-0ec768dc0207.png)
Paper https://arxiv.org/pdf/1902.07409.pdf equation (8) specified an estimator using the above estimator but with some adjustment.
![Screenshot 2019-04-25 18 38 21](https://user-images.githubusercontent.com/17790770/56778061-596ce500-6789-11e9-909e-64a4228b726c.png) (8)

Or could you please refer me to the parts of the code that address the above questions or some papers? Today I got lost in the code. Sorry.

Thanks a lot!!!!

**Comment by ZhangMengxia** [comment]
For point 1, 2 above, based on section 2.2 of this paper https://projecteuclid.org/euclid.aos/1547197251
Is the double sample tree used for every forest function (e.g., causal_forest, instrumental_forest) in the grf package? As the splitting is to maximize heterogeneity in the estimated effects, and only double sample tree splits based on this rule.

Thanks!

**Comment by ZhangMengxia** [comment]
For point 3, I think maybe the answers is the equation (19) of paper https://projecteuclid.org/euclid.aos/1547197251

![Screenshot 2019-04-26 16 31 54](https://user-images.githubusercontent.com/17790770/56841157-d4dd9d80-6840-11e9-856a-118e9f05f57e.png)

Thanks!

**Comment by ZhangMengxia** [comment]
For point 3 above, maybe the estimator correspond to equation (5) above is equation (19) of paper  https://projecteuclid.org/euclid.aos/1547197251
![Screenshot 2019-04-26 16 31 54](https://user-images.githubusercontent.com/17790770/56841218-3a318e80-6841-11e9-932d-548e4f1f06e1.png)

Then for cases where clusters are specified, the equation (8)  of paper https://arxiv.org/pdf/1902.07409.pdf is computed to generate estimates that are robust to clusters?

Thanks!

**Comment by davidahirshberg** [comment]
Honest trees, in which the splits and the values in the leaves are based on disjoint samples, are used by default in every forest type. Passing the honesty=FALSE argument to the *_forest functions will disable this, but can increase bias. 

You've got it right on point 3.  With continuous treatment, the estimator described in Equation 8 in [Estimating Treatment Effects with Random Forests](https://arxiv.org/pdf/1902.07409.pdf), is generalized by replacing the denominator of the second term with an estimate of Var[W | X=x]. When W is binary, Var[W | X=x] = e(x)(1-e(x)), so we can used the specialized estimator that appears in Equation 8.

The splitting rule for causal tree essentially considers a simple estimator of tau(x) that is constant in each child node, and splits to minimize this simple estimator's mean squared error over observations in the parent node. This goes for both binary and continuous treatments. More precisely, we split to maximize the difference between a first-order approximation to these simple estimators, which has a similar effect. See section 2.2 of [Generalized Random Forests](https://arxiv.org/abs/1610.01271) for details on splitting.

**Comment by ZhangMengxia** [comment]
@davidahirshberg Thanks a lot for your answer! This helps me a lot.

I have always wondered where are the doubly robust designs in Equation 8 in [Estimating Treatment Effects with Random Forests](https://arxiv.org/pdf/1902.07409.pdf). Is the first robust design the out-of-bag prediction ![Screenshot 2019-04-29 09 51 05](https://user-images.githubusercontent.com/17790770/56912559-582b0900-6a64-11e9-8b84-3bb9858dafb7.png)? And the second robust design is the cluster level aggregation so the estimator is robust to clusters? What is the purpose of the second term in Equation (8), is it another robust design?

Also since double-sample tree is used, how is the out-of-bag prediction ![Screenshot 2019-04-29 09 51 05](https://user-images.githubusercontent.com/17790770/56912559-582b0900-6a64-11e9-8b84-3bb9858dafb7.png) implemented? I mean if Y_i is used to split the trees but not compute tau(x), is the estimate out-of-bag?

Thanks a lot!

**Comment by swager** [comment]
The causal forests from our 2018 JASA paper, corresponding to (5) in your first comment, were not orthogonalized. One of the big advantages of the GRF framework is that it lets us do orthogonalization (closely related to double robustness), which results in a big performance gain in observational studies. See Table 1 of the GRF paper.

The causal forests implemented here are based on the GRF framework. We estimate \hat{\tau}(x) as described in (7) of https://arxiv.org/pdf/1902.07409.pdf. We used this formula within each leaf for splitting (with constant weights for each observation in the leaf), and then run the weighted formula (7) for final predictions.

Equation (8) of https://arxiv.org/pdf/1902.07409.pdf describes what we do to compute the average treatment effect (as opposed to the CATE function \hat{\tau}(x)). Here, we're just using the standard doubly robust estimator (i.e., AIPW) based with random forest estimates for all the nuisance components.

**Comment by ZhangMengxia** [comment]
@swager Finally found out the meaning of "doubly robust". Thanks a lot for your answer!
