### ISSUE TITLE
How to allow correlation between errors belong to the same cluster

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#433]
Dear authors,
I am wondering for GRF with clusters, how to achieve this  "standard errors from average_treatment_effect and average_partial_effect estimation are also cluster-robust"? Could you give an intuitive explanation? What is the algorithm or procedures?

Thanks a lot for your time!

**Comment by swager** [comment]
At a high level, you can think of clustered GRF confidence intervals as having the same interpretation as a bootstrap that resamples clusters (as opposed to units). These intervals are formally justified if you have a population of clusters, and then you sample the clusters IID from it.

**Comment by ZhangMengxia** [comment]
Got it. @swager thanks so much again!!
