### ISSUE TITLE
A conceptual question regarding the difference between generalized random forests and causal forests

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#446]
Dear authors,

I am wondering whether the following statement is correct?

The estimation procedure of the [generalized random forests ](https://arxiv.org/abs/1610.01271)is different from the earlier work of [causal forests](https://arxiv.org/abs/1510.04342). 

The key difference is that the generalized random forests first use trees to get the global weights for similarity (equation (3) in the grf paper), and then estimate the treatment effect (for example, equation (19) in the grf paper).

While the earlier work of causal forest first estimates the local treatment effect for each tree (equation (5) in the early paper), then average the effect across trees. The grf can be generalized for more cases, maybe that's why it is called "generalized".

Thanks a lot for your time!!

**Comment by ZhangMengxia** [comment]
Sorry for the bothering. I found the answer in the paper of [grf](https://arxiv.org/abs/1610.01271) in Section 6.2 "the only substantive differences being that they (Wager and Athey 2018) split using the exact loss criterion (5) rather than our gradient-based loss criterion (9), and **let each tree compute its own treatment effect estimate rather than using the weighting scheme from Section 2.1** (these methods are exactly equivalent for regression forests, but not for causal forests)."

**Comment by jtibshirani** [comment]
Closing out the issue, happy you were able to find the answer to your question.
