### ISSUE TITLE
weird tree with small number of trees

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#447]
Dear authors,

For an easier interpretation of the heterogeneous treatment effects, I tried to train the forest with a single tree, hoping the tree to be representative.

But when I visualize the tree I found there is only a single node in the tree, which is very weird. Then I keep increasing the number of trees. The grf package gives me a reasonable sample of trees (with multiple nodes and branches) when the number of trees is bigger than 14. 

Could you give me some suggestions on this issue? Thanks!

**Comment by davidahirshberg** [comment]
This is weird. Can you give me the code and data so I can try to replicate it?

**Comment by jtibshirani** [comment]
@ZhangMengxia pinging on this question again -- would you be able to send a script that reproduces the issue? The behavior you describe is concerning and we would want to make sure there's not a bug in the latest version.

**Comment by ZhangMengxia** [comment]
@jtibshirani Thanks for following up on this! I am working on that. I was using some proprietary data. Let me see if I can simulate some data to replicate the problem.

**Comment by ZhangMengxia** [comment]
@davidahirshberg @jtibshirani Thanks a lot for your help!
Here is the R code I come up to simulate the data and visualize the trees.

```
rm(list=ls())
library(grf)

##### generate data 
set.seed(0)
x1=rbinom(n=10000, size=1, prob=0.1)
x2=rbinom(n=10000, size=1, prob=0.15)
x3=rbinom(n=10000, size=1, prob=0.06)
x4=rbinom(n=10000, size=1, prob=0.07)
x5=rbinom(n=10000, size=1, prob=0.40)

W=rbinom(n=10000, size=1, prob=0.5)

y_mean=-0.008*x1+0.004*x2+0.05*x3+0.06*x4+0.09*x5+(0.03*x1+0.02*x2-0.03*x3-0.02*x4+0.01*x5)*W

Y=c()

for(i in 1:10000){
  Y[i]=rbinom(n=10000, size=1, prob=max(y_mean[i],0))
  
}
X=cbind(x1,x2,x3,x4,x5)
```
```
##### train and visualize trees 
# many trees
tau.forest = causal_forest(X, Y, W,  num.threads = 5, seed=1234)
plot(get_tree(tau.forest,7))
```
The tree I got is 
<img width="839" alt="Screenshot 2019-07-21 19 13 04" src="https://user-images.githubusercontent.com/17790770/61601935-84ca6900-abec-11e9-8147-1505471e386e.png">

```
# single tree 
tau.forest.single = causal_forest(X, Y, W,  num.threads = 5, seed=1234, num.trees=1)
plot(get_tree(tau.forest.single,1)) # got a weird tree

```
The tree I got is
<img width="791" alt="Screenshot 2019-07-21 19 13 16" src="https://user-images.githubusercontent.com/17790770/61601969-9f044700-abec-11e9-83db-6176428cfc4c.png">
The tree I got when these is a single tree looks weird.

**Comment by erikcs** [comment]
That example did not give the same weird tree on my computer, but this did

```R
library(grf)
set.seed(0)
n = 50; p = 3
X = matrix(rnorm(n, p), n, p)
y = rnorm(n)
w = sample(c(0, 1), n, TRUE)
f = causal_forest(X, y, w)
plot(get_tree(f, 1))
```

![Rplot02](https://user-images.githubusercontent.com/7185264/61653246-bbe15e80-ac6e-11e9-9828-5b8febb81af9.jpeg)

**Comment by swager** [comment]
@ZhangMengxia, the problem here is that a causal forest with default inputs actually trains 3 forests:

- A regression forest for predicting Y from X,
- A regression forest for predicting W from X, and
- A causal forest that uses the first 2 forests for pre-processing. 

When one sets the number of trees to 1, the result is that only 1 tree is used for each of the 3 forests. Then the first two regression forests aren't good and we do the pre-processing for the causal forest badly, resulting in a poorly trained causal forest.

To fix the problem, you can run the first two regression forests manually with a standard number of trees, and then just run the causal forest on its own with 1 tree. This appears to work.
```R
Y.forest = regression_forest(X, Y)
Y.hat = predict(Y.forest)$predictions

W.forest = regression_forest(X, W)
W.hat = predict(W.forest)$predictions

tau.forest.single.adj = causal_forest(X, Y, W,
                                      W.hat = W.hat, Y.hat = Y.hat,
                                      num.threads = 5, seed=1234, num.trees=1)
plot(get_tree(tau.forest.single.adj,1))
```

![image](https://user-images.githubusercontent.com/1275702/61658344-01575900-ac7a-11e9-9fc8-cc75c6b01e32.png)
