### ISSUE TITLE
How to make prediction with causal forest on new dataset from different clusters?

### ISSUE THREAD

**Issue by kai0511** [grf-labs/grf#449]
Hi authors,

I split my dataset into two pieces, and the dataset have clusters. Thus I trained causal forest with clusters on one piece using causal forest. 

Here is some pseudocode：
```
cf = causal_forest(X[, selected.idx], Y, W , 
    clusters = cluster.id, 
    tune.parameters = TRUE)
```

So if I want to make predictions with the other piece, how could I incorporate cluster information when predicting on the new piece? And I check the predict function for causal forest don't find the option that can absorb cluster information.

Could you give me some suggestions on this issue? Thanks!

**Comment by kai0511** [comment]
To clarify, here I mean I would like to make predicts on new observations with cluster information. 

If I run following code:
`cf_predictions <- predict(tau.forest.train, newdata = X[ , -selected.idx], estimate.variance = TRUE)
`
I am wondering whether the function considers the potential correlations within each cluster, that is, if we have a new observation `x`, and `x` belongs to cluster `j`, whether will it consider observations also from cluster `j` to predict the treatment effect for `x`?

Any help for this issue? Thanks!

**Comment by erikcs** [comment]
Hi @kai0511 , from the grf [reference](https://github.com/grf-labs/grf/blob/master/REFERENCE.md#cluster-robust-estimation) on cluster robust estimation:

> To use this feature, the forest must be trained with the relevant cluster information by specifying the clusters and optionally samples_per_cluster parameters. _Then, all subsequent calls to predict with will take clusters into account, including when estimating the variance of forest predictions._

**Comment by kai0511** [comment]
@erikcs  Just for confirmation, all subsequent calls to predict, even in the new dataset, will remove cluster heterogeneity when estimating treatment effect. 

Thank you so much for your reply.

**Comment by kai0511** [comment]
@erikcs could you also give a short explanation of how causal forest works to realize this,  if possible?

**Comment by swager** [comment]
@kai0511 yes that's correct, cluster information only needs to be passed in at training time. For a description of what cluster-robust forests are doing, see Section 1.2 of https://arxiv.org/pdf/1902.07409.pdf

**Comment by kai0511** [comment]
@swager Thank you so much for your confirmation and help.
