### ISSUE TITLE
Causal Tree

### ISSUE THREAD

**Issue by jfschaeper** [grf-labs/grf#451]
In a previous version of this package it was possible to build a single causal tree using the procedure from _Susan Athey and Guido Imbens PNAS July 5, 2016 113 (27) 7353-7360_ if I am not mistaken. Is it still possible to generate a similar tree with the grf package?
Furthermore, it appears that the function "export_graphviz" is not included anymore as well. Are there any alternatives for visualising the tree?

**Comment by jtibshirani** [comment]
Hi @jfschaeper, this package does not implement the causal tree approach from the paper you cite ("Recursive partitioning for heterogeneous causal effects"). Code for causal tree can be found in https://github.com/susanathey/causalTree.

We stopped exporting the method `export_graphviz`, as it was an internal helper method. To visualize a tree, you can simply call `plot` on the tree:
```
tree = get_tree(forest, 1);
plot(tree)
```

**Comment by jfschaeper** [comment]
Thanks for your quick and helpful response @jtibshirani . I will check out the referenced repository.
