### ISSUE TITLE
Make the R randomized tests more robust.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#452]
Many of our R tests are quite fragile, only passing the test conditions if a particular random seed is used. It would be good look into how to solidify these tests so that they are more reliable and meaningful.

One approach is to audit the tests and make sure that we are using a large enough sample size and number of trees to reliably detect the behavior we're testing. This could substantially increase the amount of time required for each test, so we could also look into restructuring the tests to share expensive set-up logic. In many cases it seems like we could train a large forest once and then run several different checks using the trained forest, as opposed to training a new forest per test case.

**Comment by halflearned** [comment]
It seems to me that if we want to increase the number of observations per forest _and_ we want to keep the test runtime small, then we must fit fewer forests.

For example, [here](https://gist.github.com/halflearned/0bcbddb74befafdded5d4d3cd288eba2)'s how we can save a few forests in `test_average_effect.R`. It feels weird to allow forests to be global variables floating in the scope, but each of these scripts should run by itself anyway, so the variables will be destroyed at the end of it. In Python, `pytest` allows for [fixtures](https://docs.pytest.org/en/latest/fixture.html), but I don't know of a similar feature in `testthat`. ([unless?](https://gist.github.com/halflearned/8458475e7e578acab914c28d91b3f214))

**Comment by erikcs** [comment]
> In Python, pytest allows for fixtures, but I don't know of a similar feature in testthat. (unless?)

Testthat has [helper files](https://testthat.r-lib.org/reference/test_dir.html#test-files)

For example, to train a large causal forest and make it available to all tests in `test_causal_forest.R`, create a file named `helper_causal_forest.R` where you do `forest = causal_forest(...)`

**Comment by swager** [comment]
The PR #468 makes progress towards this. OK to close this issue once we merge it?

**Comment by jtibshirani** [comment]
@swager although #468 is a nice step forward, I would like to keep this open until we do a more thorough audit and take the time to reconsider our R testing approach.

**Comment by erikcs** [comment]
Closing for now as currently all R tests are being run on two different build OS's without any issues (hopefully most flaky tests have been weeded out here and there), and they (a lot) finish within 10-15 minutes (https://dev.azure.com/grf-labs/grf/_build?definitionId=2&_a=summary)
