### ISSUE TITLE
is there a way to visualize a tree with predicted treatment effect for each leaf

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#462]
Dear authors,

I am just wondering is there a convenient way to label treatment effect for each leaf in the tree. One way I can think of is to manually predict each leaf and label each leaf manually. Not sure whether this is the best way.

Currently,  the tree I can get is like this
![Picture1](https://user-images.githubusercontent.com/17790770/61679365-d80aed00-acba-11e9-8c00-4344338a06b4.png)

The aim is to get a tree like this
![Picture2](https://user-images.githubusercontent.com/17790770/61679373-dfca9180-acba-11e9-9bac-ac17ff20a1a1.png)

Thanks a lot for your time!

**Comment by swager** [comment]
There are many ways to look at this. A first answer is that we provide information on the units that fall into (the estimation sample of) each leaf via the get tree command, so you can manually compute a CATE based on that. The limitation of that, though, is that the trees in GRF really aren’t optimized for the “single tree” use (in particular, we don’t prune them, and we only grow them on a half-sample), so this is probably not the best way to get a single good tree.

Issue #281 is about using causal forests to find a single consensus tree. We have some ideas and a prototype, but haven’t integrated it into the package yet. If you have any thoughts from using this, please let us know.

**Comment by ZhangMengxia** [comment]
@swager Thanks a lot!! Thanks for pointing me to the very interesting discussion.
