### ISSUE TITLE
Heterogeneity evaluation

### ISSUE THREAD

**Issue by PolinaKoroleva** [grf-labs/grf#463]
I was replicating the analysis from the paper _Estimating Treatment Effects with Causal Forests: An Application_ (Athey & Wager, 2019), directory _experiments/acic18_.under version 0.10.3. It seems to me that comparison of the regions with the high and low treatment effects is not available under the new version.

Here is the code I used: 
`# Compare regions with high and low estimated CATEs
high_effect = tau.hat > median(tau.hat)
ate.high = average_treatment_effect(cf, subset = high_effect)
ate.low = average_treatment_effect(cf, subset = !high_effect)
paste("95% CI for difference in ATE:",
      round(ate.high[1] - ate.low[1], 3), "+/-",
      round(qnorm(0.975) * sqrt(ate.high[2]^2 + ate.low[2]^2), 3))`

The error I get is:
`
"Error in average_treatment_effect((cf, subset = high_effect) : If specified, subset must be a vector contained in 1:n,", "or a boolean vector of length n."))
`

The code worked well under 0.10.1. I have also noticed that in the function description there is a warning: 

> **subset** specifies subset of the training examples over which we estimate the ATE. WARNING: For valid statistical performance, the subset should be defined only using features Xi, not using the treatment Wi or the outcome Yi.
> 

Does it mean that subset can not be defined by the treatment effect value in the 0.10.3 versions? And if no, what is the right way to compare the regions with different treatment effects? Or, for example, compare the region with high treatment effect vs random sample.

**Comment by swager** [comment]
I don't see any reason a-priori why this shouldn't work. Could you please post a simulation that replicates the issue?

**Comment by PolinaKoroleva** [comment]
Sure!

`# Train a causal forest.
n = 50; p = 10
XX = matrix(rnorm(n*p), n, p)
WW = rbinom(n, 1, 0.5)
YY = pmax(XX[,1], 0) * WW + XX[,2] + pmin(XX[,3], 0) + rnorm(n)
c.forest = causal_forest(XX, YY, WW)
tau.h = (c.forest)$predictions

h_effect = tau.h > median(tau.h)
low = average_treatment_effect(c.forest, subset = !h_effect)
high = average_treatment_effect(c.forest, subset = h_effect)
high
low`

This exact simulation works under 0.10.2, but under 0.10.3 I'm getting this error:

> Error in average_treatment_effect(c.forest, subset = !h_effect) : If specified, subset must be a vector contained in 1:n, or a boolean vector of length n.

While under 0.10.2 I got the estimates:
` estimate    std.err 
-2.1586819  0.5635359 
 estimate   std.err 
2.1666750 0.6239291 `

**Comment by erikcs** [comment]
[this](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/average_treatment_effect.R#L84) line is not executed because between 0.10.2 and 0.10.3 an internal object has gone from a vector to a one dimensional matrix:

0.12.2:
```
> class(h_effect)
[1] "logical"
> tau.h
 [1] 0.4639014 0.6597651 0.5705937 0.3733333 0.5889534 0.5892164 0.5119794
```

0.12.3:
```
class(tau.h)
```

if you switch from accessing the attribute

```
tau.h = (c.forest)$predictions
```

to using the generic function

```
tau.h = predict(c.forest)$predictions
```

the example runs

**Comment by swager** [comment]
Thanks @erikcs!
