### ISSUE TITLE
GRF Honest trees + Double/Debiased Machine Learning

### ISSUE THREAD

**Issue by tcovert** [grf-labs/grf#464]
Hi Team GRF,

First, I am a big fan of this package!  Thanks for making it!  

Second, I am currently using `grf` inside of some estimators proposed in the Chernozhukov et all Double/De-biased Machine Learning [paper](https://academic.oup.com/ectj/article/21/1/C1/5056401).  One thing I am not sure about is whether (a) I should be using honest trees or not and (b) if I do use honest trees, is there a way around all of the sample splitting that goes on in the Chernozhukov et al approach?  Recall, that paper suggests sample splitting as a "first stage" in estimating nuisance parameters, and plugging in those non-parametric estimates into parametric estimation of the main model in the validation sample.  This process is averaged over k cross-validation splits (say, k = 5) and then the entire process itself is averaged over a large number of such splits (say, 100).  So, instead of estimating a forest 1 time (as I'd do with the `regression_forest` command in grf), I gotta do it 500 times.  

Is there a sense in which the "honest" option in the `grf` package means I don't need to do all this splitting?  That would certainly make my estimation time 500 times shorter!  For what its worth, I've found that for a standard partially linear model, in which I use honest regression forests to partial out the non-parametric nuisance in a Robinson-style transformation, I get very similar point estimates and standard errors as I do with the explicit Double/Debiased approach with tons of sample splitting.

Thanks in advance for any advice!

**Comment by swager** [comment]
One advantage of random forests is that it's very easy to do leave-one-out prediction (also called out-of-bag prediction): If you want to predict mu(Xi) at a training point Xi, just take the average over all trees that don't use the i-th training example. GRF automatically implements out-of-bag prediction. For example, if you have a regression forest rf and just call predict(rf) without specifying a training set, out-of-bag predictions are returned.

Out-of-bag prediction is not exactly the same thing as the out-of-fold prediction advocated in the Chernozhukov et al. paper, but empirically it appears to be very close. The upshot is that, if you're willing to rely on out-of-bag predictions, you can do cross-fitting based on just a single forest in each estimation step (i.e., just train a single forest and evaluate its out-of-bag predictions).

We actually do this in the package, in the `average_treatment_effect` function. There, we estimate the ATE via the doubly robust estimator with out-of-bag predictions (which is very closely related to the cross-fit doubly robust estimator). For a more specific discussion, see Section 2.1 of https://arxiv.org/pdf/1902.07409.pdf.

Finally, the "honest" option does something different -- it's not about cross-fitting, but rather about stabilizing the forest fit to ensure consistency. For debiasing methods, the important thing is to use out-of-bag predictions.
