### ISSUE TITLE
a few questions regarding instrument forest

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#465]
Dear authors,
I have the following questions for instrument forest

1) Instrumental_forest, in fact, does not allow specifying Z.hat? When I specify Z.hat, there is an error says that "unused argument (Z.hat = Z.hat)".

2) How to correctly get the mean treatment effect for instrumental_forest? The function average_treatment_effect or average_partial_effect  is not implemented for instrumental_forest.

3) Related to 2), how to understand the predicted treatment effect for each individual for the instrumental forest? I learned that the estimate for 2SLS is, in fact, local average treatment effect, namely effect for compliers. What does this mean for the predicted effect for each individual?

Thanks a lot for your time!

**Comment by swager** [comment]
For 1., do you have latest version of `grf` installed?

For 2., this is something we plan to have, but haven't implemented yet; see #358 and #364 

For 3., yes, what comes out of intstrumental forests should be interpreted a type of 2SLS run over the forest neighborhood. So perhaps \tau(x) should be called a conditional local average treatment effect in that case.

**Comment by ZhangMengxia** [comment]
@swager thanks a lot for your answers! Super helpful!
