### ISSUE TITLE
Consider sample weights in tree splitting.

### ISSUE THREAD

**Issue by swager** [grf-labs/grf#473]
The current implementation of sample-weighted forests considers sample weights only during the prediction phase, but not during splitting (see #128, #376, #418). For example, in the case of regression forests, given sample weights gamma_i our prediction at a test point x is:

\hat{mu}(x) = sum_{i = 1}^n \gamma_i alpha_i(x) Y_i / sum_{i = 1}^n \gamma_i alpha_i(x),

where the alpha_i(x) are forest weights obtained "as usual" (i.e., without considering the gammas).

In principle, it should be possible to improve power by also considering the gammas in the splitting phase. Of course, doing so requires caution (e.g., we don't want to overfit to a handful of observations with very large weights), but it would be interesting to investigate.

The following script shows the current state of affairs (running 0.10.3). In the case of censored data, using sample weights helps; however, we ought to be able to get closer to the complete data forests with splitting rules that are aware of censoring. (Note, also, that the tree-splits obtained with and without splits are exactly the same; the gain of the weighted forest comes entirely from the prediction phase.)

```R
set.seed(1)
n = 2000; p = 6
X = matrix(rnorm(n*p), n, p)
prob.missing = 0.75 * as.numeric(X[,1] > 0 & X[,2] > 0)
mu = 4 * as.numeric(X[,1] > 0 & X[,2] > 0) +
    as.numeric(X[,3] > 0) + as.numeric(X[,4] > 0)
Y = mu + rnorm(n)
cc = rbinom(n, 1, 1 - prob.missing) == 1

rf.complete = regression_forest(X, Y, seed = 1)
rf.obs = regression_forest(X[cc,], Y[cc], sample.weights = 1/(1 - prob.missing[cc]), seed = 1)
rf.obs.unweight = regression_forest(X[cc,], Y[cc], seed = 1)

X.test = matrix(rnorm(n*p), n, p)
mu.test = 4 * as.numeric(X.test[,1] > 0 & X.test[,2] > 0) +
    as.numeric(X.test[,3] > 0) + as.numeric(X.test[,4] > 0)

mu.hat.complete = predict(rf.complete, X.test)$predictions
mu.hat.obs = predict(rf.obs, X.test)$predictions
mu.hat.obs.unweight = predict(rf.obs.unweight, X.test)$predictions
```

Output...

```R
> sqrt(c(mean(mu.hat.complete - mu.test)^2,
+        mean(mu.hat.obs - mu.test)^2,
+        mean(mu.hat.obs.unweight - mu.test)^2))
[1] 0.02919705 0.11936710 0.24248302
> 
> print(rf.complete)
GRF forest object of type regression_forest 
Number of trees:  2000 
Number of training samples: 2000 
Variable importance: 
    1     2     3     4     5     6 
0.488 0.275 0.106 0.108 0.011 0.012 
> print(rf.obs)
GRF forest object of type regression_forest 
Number of trees:  2000 
Number of training samples: 1624 
Variable importance: 
    1     2     3     4     5     6 
0.188 0.107 0.345 0.332 0.013 0.014 
> print(rf.obs.unweight)
GRF forest object of type regression_forest 
Number of trees:  2000 
Number of training samples: 1624 
Variable importance: 
    1     2     3     4     5     6 
0.188 0.107 0.345 0.332 0.013 0.014 
```

**Comment by ginward** [comment]
@swager By considering the sample weights during splitting, did you mean adding sample weights to [the sampler here](https://github.com/grf-labs/grf/blob/5368949568e564d418e587ad187ce59d04d3241c/core/src/forest/ForestTrainer.cpp#L115)? For example, sample the individuals based on their weight. 

Besides, is this feature currently in active development, or are you waiting for a PR from someone?

**Comment by erikcs** [comment]
Now that sample weighted splitting is implemented (#590) this looks like

```R
> sqrt(c(mean(mu.hat.complete - mu.test)^2,
+        mean(mu.hat.obs - mu.test)^2,
+        mean(mu.hat.obs.unweight - mu.test)^2))
[1] 0.03181151 0.05020404 0.24384639
```

**Comment by erikcs** [comment]
Briefly re-opening this issue as we have appear to have overlooked step 3:

1. Sample weighted prediction was added in #418 
2. Sample weighted splitting was added in #590 (pseudo code is [here](https://grf-labs.github.io/grf/DEVELOPING.html#tree-splitting-algorithm)
3. Sample weighted relabeling for causal/instrumental forest

A quick reminder for everyone, in the case of a causal forest, the [InstrumentalRelabelingStrategy](https://github.com/grf-labs/grf/blob/master/core/src/relabeling/InstrumentalRelabelingStrategy.cpp) reduces to:

```
// Algo: create pseudo-outcomes for a causal forest
input: samples in node and data (outcomes Y, treatment W)
output: n-vector responses_by_sample

let average_Y and average_W be the average of Y and W in the node

// 1. Calculate the parent treatment effect, the coefficient beta in the regression Y = W*beta + epsilon:
let numerator, denominator = 0
for each sample in node:
  numerator += (W[sample] - average_W) * (Y[sample] - average_Y)
  denominator += (W[sample] - average_W) * (W[sample] - average_W)
leta beta = numerator / denominator

// 2. Create the new outcomes, the influence of sample i on beta in the above regression 
// (ignoring a constant term that will be the same for every sample):

for each sample in node:
  let residual = (Y[sample] - average_Y) - beta * (W[sample] - average_W)
  let responses_by_sample = (W[sample] - average_W) * residual

return responses_by_sample 
```

Sample weighted relabeling is added over here:

https://github.com/erikcs/grf/commit/ad2a54938a5d2bfd08f7e41fd7ca76eb118c8058

A test that the pseudo outcomes is not "wrong" is added here: (this breaks if the pseudo outcomes is not multiplied with weight_i)

https://github.com/erikcs/grf/commit/9bac5a9a5feed34df62b66f6db6be246e4b58ba5

Surprisingly, this makes MSE worse:

sample weighted [MSE check](https://gist.github.com/erikcs/315e108d7fa60439e6a4dbae455d42b5) from causal forest test suite

```
# master
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
# 0.4085  0.6369  0.7115  0.7089  0.7833  0.9644

# with sample weights in relabeling
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
# 0.4559  0.6612  0.7213  0.7289  0.7936  1.1186
```

@davidahirshberg do you spot anything wrong in the above implementation?

**Comment by erikcs** [comment]
Confirming that it was the above sanity check that was wrong, accidentally double counted the weights when multiplying pseudo outcomes by weight_i (the weighted average of the influence is zero) - so the last MSE result above is the correct one, which shows a very small reduction.
