### ISSUE TITLE
issues regarding continues treatment variable

### ISSUE THREAD

**Issue by kai0511** [grf-labs/grf#476]
Dear authors, 

In the case of continuous treatment setting, is test_calibration available? 

Since I took a quick look at the relevant code, it does not mention that continuous W is a must. I am still not sure whether it can be generalized to continuous setting. Relevant code is adopted below.

```
DF <- data.frame(
      target = unname(forest$Y.orig - forest$Y.hat),
      mean.forest.prediction = unname(forest$W.orig - forest$W.hat) * mean.pred,
      differential.forest.prediction = unname(forest$W.orig - forest$W.hat) *
        (preds - mean.pred)

lm(target ~ mean.forest.prediction + differential.forest.prediction + 0,
      weights = observation.weight,
      data = DF
    )
```

Please kindly leave some comments regarding this issue. Thank you so much for your time.

Kai

**Comment by swager** [comment]
Yup, test_calibration works with continuous treatments. The only function that doesn’t work with continuous treatments is average_treatment_effect (one needs to use average_partial_effect instead).

**Comment by kai0511** [comment]
@swager Thanks for your instant reply. I am also interested in the mechanism of adjustment to deal with continues treatment. Could you kindly give me some hints?

Assume tau risk is defined as below, t
au_risk = \sum (y_i - \hat m(x_i)  - (w_i - \hat p(x_i)) * \tau(x_i) )^2, 
which is defined in this paper(https://arxiv.org/abs/1804.05146) and is just a derivation from Nie and Wager 2017.

If I would like to assess the tau risk of causal forest fitted, is it also can extended to continuous case from your point of view?

Thanks for your patience!

Kai

**Comment by swager** [comment]
Yes that's right -- the methodology from the Nie & W. 2017 paper extends to the case of continuous treatments. One just needs to re-interpret the propensity score as a conditional expectation, E[W | X = x], and then everything goes through.

**Comment by kai0511** [comment]
@swager Thanks for your explanation!

**Comment by ginward** [comment]
> Yup, test_calibration works with continuous treatments. The only function that doesn’t work with continuous treatments is average_treatment_effect (one needs to use average_partial_effect instead).

Except the `overlap `option in `average_treatment_effect`? I think that one works on continuous treatment as well.
