### ISSUE TITLE
multi-core support 

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#479]
Does `grf` package automatically use multi-cores for computation? I am using HPC to run causal forest with the `grf` package and I allocated 32 CPUs to build 5000 trees on a very large dataset. But I am not sure if those cores are all utilised, or am I just using 1 core and wasting all other 31 cores computational power. 

Thanks!

**Comment by erikcs** [comment]
Yes, grf automatically uses all available cores (see the option `num.threads`, you can try setting it manually as well).

**Comment by ginward** [comment]
@erikcs Thanks for your prompt reply. But is the `num.threads` parameter for multi-threading or multi-core processing? I understand that there might be a difference between the two.

**Comment by erikcs** [comment]
Yes, you can have more threads than physical cores. Trees are [trained](https://github.com/grf-labs/grf/blob/master/core/src/forest/ForestTrainer.cpp#L66) in parallel using C++ threads (i.e. shared memory concurrency). [Here](https://github.com/grf-labs/grf/blob/master/core/src/forest/ForestOptions.cpp#L90) is how the default num.threads option is set, if you have 4 cores with hyperthreading this will be 8.
