### ISSUE TITLE
Removing unordered_maps may give big performance improvements

### ISSUE THREAD

**Issue by halflearned** [grf-labs/grf#483]
We noted in our meeting today that our splitting rules seem to be making use of `unordered_map`. As we've seen before (#359), it seems that we should avoid c++ hash tables at all costs.

What I have now is far from a full-blown perf analysis, but check this out.

1. On [this](https://github.com/halflearned/grf/tree/cli) branch, I run a `regression_forest` on `test/forest/resources/regression_data.csv` (n=500, p=10). This is the output of CLion's profiler.
 
<img width="975" alt="Screen Shot 2019-08-15 at 11 08 47 PM" src="https://user-images.githubusercontent.com/20155021/63148588-805c5a80-bfb6-11e9-9988-818b991f354a.png">

The total runtime was **3.43** seconds. (Note this branch contains the same code as the current development version of grf, except I added a command-line interface for profiling).

2. On [this](https://github.com/halflearned/grf/tree/cli_perf) branch, all I did was to search and replace instances of `std::unordered_map<size_t, double>` with `std::vector<double>` in folders `splitting` and `relabeling`, and then make sure that the vectors are property initialized.

This time, the total runtime was **2.26** seconds, which is 65.8% of the version with unordered_map.

---

With a larger dataset (n=15000, p=10), the runtime is **61s** with grf development version, and about **37s** using `std::vector`.

**Comment by erikcs** [comment]
On this and #359 : did you want to switch out all unordered_maps?

_Aside for future reference: easy way to set up profiling:_

On Mac you can get the above output without starting from the C++ side. Build the package from source as usual, debug symbols are included by default (the -g in $ R CMD config CXXFLAGS).

a) Start R from the command line (not Rstudio).
b) Open Xcode->Xcode->Open Developer Tools->Instruments:
select profile. Next to the record button attach to the R process. Press record
c) In R run the commands you want to profile. For example training a large causal_forest.
e) Instruments: stop the recording and you get the profiling output:

![Screen Shot 2019-10-30 at 11 39 56](https://user-images.githubusercontent.com/7185264/67888250-05f99c00-fb0a-11e9-951e-8b7259b0b3f1.png)

**Comment by erikcs** [comment]
This was already fixed in #514 but the issue remained open. Closing now
