### ISSUE TITLE
Options for cluster weighting in cluster-robust forests

### ISSUE THREAD

**Issue by swager** [grf-labs/grf#488]
In the current implementation of causal forests, etc., when a user specifies clusters for samples, each cluster is given equal weight. For example, if we have data from a randomized trial clustered by village, and one village has 100 people and the other has 400 people, then both villages get equal weight in the forest. For details, see <a href="https://github.com/grf-labs/grf/blob/master/REFERENCE.md#cluster-robust-estimation">here</a>, and for an example in code, see <a href="https://github.com/grf-labs/grf/blob/584d85613ecded99f07275536b78d90f2f0c7d6f/r-package/grf/R/average_treatment_effect.R#L324">here</a>, and also #280 #393 #431.

In some applications, however, this choice may be inappropriate -- and it may be preferable not to re-weights clusters, and instead to give each cluster a weight proportionate to the number of samples it contains. We should thus add an option to turn off the cluster weighting if desired. Furthermore, we should add a transparent way for power users to manually specify the weight given to each cluster (potentially via the sample weights argument).

**Comment by erikcs** [comment]
In the analysis functions computing all the different ATE/LATE/CATE etc:

**Comment by swager** [comment]
Ok so this is simply a little tricky in terms of notation (one could probably write this more nicely with slightly less condensed code). The point is to estimate the variance of
```R
aclate.hat <- weighted.mean(Gamma.hat, subset.weights)
```
where data across clusters are independent. Write samples as i and clusters as j, the "Gamma.hat" as Gij and weights as Sij. So aclate.hat (theta) is
```
theta = sum_{cluser j} Aj / sum_{cluser j} Tj.
```
where Aj = sum_{sample i} Gij Sij and Tj = sum_{cluser j} sum_{sample i} Sij; notice that we grouped samples by cluster j because samples within cluster may be arbitrarily dependent. Assuming the clusters are IID, the variance of theta then scales like
```
(number of clusters) * Var[theta] -> Var[Aj] / E[Tj]^2.
```
In the code, we compute this as
```R
    clust.avg <- Matrix::sparse.model.matrix(
      ~ factor(subset.clusters) + 0,
      transpose = TRUE
    ) %*% (Gamma.hat * subset.weights) 
    sigma2.hat <- var(as.numeric(clust.avg)) * length(clust.avg) /
      sum(subset.weights)^2
```
To see that the expressions match, note that `clust.avg` corresponds to the terms `Aj` defined above, and that `E[sum(subset.weights)] = (number of clusters) * E[Tj]`.

**Comment by erikcs** [comment]
Thank you, I am not sure what the best way to customize cluster weighting is and wouldn't want to make a (slightly) complicated setup even more complicated (like sample.weights serving two purposes?)

Just a code example of the current weighing behavior from the documentation example for reference:
```R
library(grf)
set.seed(1)
n = 200; p = 5
# 20 clusters. One obs in 1:10, 19 obs in 11:20
clusters = c(1:10, sort(rep(11:20, 19)))
tau = c(rep(1, 10), rep(0, 190))
X = matrix(rnorm(n*p), n, p)
W = rbinom(n, 1, 0.5)
Y = 1 * W*tau + rnorm(n, sd = 0.1)

cf1 = causal_forest(X, Y, W)
average_treatment_effect(cf1)
# estimate    std.err 
# 0.05052072 0.02584468  

cf2 = causal_forest(X, Y, W, clusters = clusters)
average_treatment_effect(cf2)
# estimate   std.err 
# 0.5314864 0.1566749 
```

**Comment by erikcs** [comment]
The online package documentation renders latex, so maybe all these details could be included in the roxygen2 documentation ([example](https://gsbdbi.github.io/policyTree/reference/get_double_robust_scores.html), though Rstudio will not render the equations)

**Comment by erikcs** [comment]
Current plan:

1. (simplify interface) Introduce a new boolean parameter `clusters.subsample` that toggles whether clusters are subsampled or not:
   
     This replaces the [samples.per.cluster](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/causal_forest.R#L30) argument.

    * `clusters.subsample = FALSE` (new default) will use all the observations in each cluster. It is the same as setting `samples.per.cluster` to maximum number of observations in `clusters`.

    * `clusters.subsample = TRUE` will use the number of observations that are in the smallest cluster. It is the same as setting `samples.per.cluster` to the minimum number of observations in `clusters`.

    * [example of this behavior](https://gist.github.com/erikcs/6ed45c52c7f3068f760377f578165c28)


2. Modify the average treatment effect functions to reflect the following possibilities:

| sample.weights \ clusters |                            |               |
|---------------------------|----------------------------|---------------|
|                           | normalize                  | no normalize  |
| Yes                       | a Current default = remove | b New default |
| No                        | c                          | d             |

**Comment by erikcs** [comment]
#545 adds this feature, the following summaries the change:

| sample.weights | equalize.cluster.weights = FALSE                                                 | equalize.cluster.weights = TRUE                                                                                       |
|----------------|----------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
|                |                                                                                  |                                                                                                                       |
| No             | Each unit is given the same weight, regardless of cluster size.  **New default** | Each cluster is given equal weight.  If the smallest cluster has K units, each tree is grown with a random K elements |
| Yes            | Additional custom weighting option                                               | X Disallowed X                                                                                                        |

In particular, here is the updated example for average treatment effects: when clusters are specified, then each unit gets equal weight by default. For example, if there are 10 clusters with 1 unit each and per-cluster ATE = 1, and there are 10 clusters with 19 units each and per-cluster ATE = 0, then the overall ATE is 0.05 (additional sample.weights allow for custom weighting). If equalize.cluster.weights = TRUE each cluster gets equal weight and the overall ATE is 0.5.
