### ISSUE TITLE
Tuning instrumental forests

### ISSUE THREAD

**Issue by swager** [grf-labs/grf#501]
We currently have functionality for automatically tuning regression forests and causal forests, but nothing for instrumental forests. This hinders applications of instrumental forests because, more so than regression or causal forests, they appear to be quite sensitive to proper tuning (presumably because effects in IV analyses are often so weak). See, for example, the effect of `min.node.size` in the following simple example:

```R
library(grf)
n = 3000; p = 5

reps = replicate(25, {
    X = matrix(rbinom(n*p, 1, 0.5), n, p)
    Z = rbinom(n, 1, 0.5)
    Q = rbinom(n, 1, 0.5)
    T = Q * Z
    eps = rnorm(n)
    TAU = X[,1] / 2
    Y = rowSums(X[,1:3]) + TAU * T + Q + eps
    
    ivf.0 = instrumental_forest(X, Y, T, Z)
    ivf.25 = instrumental_forest(X, Y, T, Z, min.node.size = 25)
    ivf.50 = instrumental_forest(X, Y, T, Z, min.node.size = 50)
    ivf.75 = instrumental_forest(X, Y, T, Z, min.node.size = 75)
    
    c(mean((TAU - predict(ivf.0)$predictions)^2),
      mean((TAU - predict(ivf.25)$predictions)^2),
      mean((TAU - predict(ivf.50)$predictions)^2),
      mean((TAU - predict(ivf.75)$predictions)^2))
})

rowMeans(reps)
# [1] 0.15597533 0.02725053 0.01815592 0.01828230
```

Optimal methods for tuning heterogeneous treatment effect estimators with instrumental variables (IVs) are still an open research topic. However, here's something reasonable we could already do now, motivated by Chernozhukov and Hansen (2008). At a high level, this paper argues that a good way to diagnose whether an IV analysis is doing anything useful is to look at the quality of the reduced form regression (i.e., the causal model used to measure the effect of the exogenous instrument `Z` on the outcome `Y`).

We could also use the same idea for tuning. Define `rho(x) = E[Y | X, Z = 1] - E[Y | X, Z = 0]` as the "CATE" of the instrument (assuming exogeneity). Although we do not compute it explicitly, the IV forest implies a natural estimate of `rho()`, namely

`hat{rho}(x) = sum_i alpha_i(x) (Yi - hat{m}(Xi)) (Zi - hat{z}(Xi)) / sum_i alpha_i(x) (Zi - hat{z}(Xi))^2`

where the `alpha_i(x)` are the instrumental forest weights. Then we can define the R-loss for `rho()` (where of course everything is out-of-bag as usual)

`L(rho) = sum_i ((Yi - hat{m}(Xi)) - rho(Xi) (Zi - hat{z}(Xi))^2`

The proposal is to tune the instrumental forest by minimizing the R-loss for rho.

In terms of action items for the C++ part of the code, this would entail defining the "debiased error" of an instrumental forest in terms of rho. As a related contribution, it may also be of interest to expose the implicit estimates of the reduced form effect `rho(x)` to the user.

References
Chernozhukov, Victor, and Christian Hansen. "The reduced form: A simple approach to inference with weak instruments." <i>Economics Letters</i> 100.1 (2008): 68-71.

### Status:

- [x] The core tuning functionality described above is in place with #547.

The following robustness modifications can be done in follow-up PRs:

1. Settle on a potentially new parameter grid for IV forest (for some DGPs large enough `min.node.size`'s aren't explored often enough).

2. Decide which parameters to tune by default (tuning just `min.node.size` may give better results than tuning `all`).

**Comment by erikcs** [comment]
Plan:

Update [InstrumentalPredictionStrategy::compute_error()](https://github.com/grf-labs/grf/blob/master/core/src/prediction/InstrumentalPredictionStrategy.cpp#L202) (debiased.error) to compute this quantity (a causal_forest is an instrumental forest with Z=W)

**Comment by erikcs** [comment]
The core tuning functionality described above is in place in #547.

The following robustness modifications will be done in follow-up PRs:

1. Settle on a potentially new parameter grid for IV forest (for some DGPs large enough `min.node.size`'s aren't explored often enough).

2. Decide which parameters to tune by default (tuning just `min.node.size` may give better results than tuning `all`).

**Comment by erikcs** [comment]
Closing as finished for now - can be reopened if interest in bullet points 1. and 2. warrants exploring those further.
