### ISSUE TITLE
Sample Weight and AIPW

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#525]
I have a quick question regarding how to specify the `sample.weights` argument in the [causal_forest function](https://github.com/grf-labs/grf/blob/81b6a9786fecef468de5185f1ff7e5941439fd77/r-package/grf/R/causal_forest.R#L139). 

I looked at the source code [here](https://github.com/grf-labs/grf/blob/629802de00f7f4673328d6007a4cdb68d90049a4/core/src/prediction/InstrumentalPredictionStrategy.cpp#L177), and it looks like that the sample weights are applied at the last phase of pre-computed prediction. It seems that it applies weighting to the final outcome variables Y. 

However, I am curious of how to obtain the sample weights. For example, if I have two datasets,  with one being a random experiment data and the other being the non-random experiment data. I would like the train the forest on the non-random experiment dataset as if it were from a random experiment (I would like to re-weight the samples in the non-random experiment data so that the population characteristics are similar to that of the random experiment data). Should I construct a dummy variable that indicates if the data is from the random experiment dataset, and calculate the propensity score of the non-random experimental data being in the random experiment dataset, and use the propensities as sample.weights? 

Besides, looks like that the sample.weights argument is only being used in the pre-computed predictions, but not applied to predict function with new data. Is this a functionality that will be considered later?

**Comment by ginward** [comment]
Thanks @davidahirshberg 

It seems that I understood causal forest a little bit wrong before. Is it fair to say that, the pre-computed computations is used in all predictions (no matter in-sample or out-of-sample)? Say I have an individual that my causal forest had never seen before, and I push it down 100 trees. In each of the tree, when the individual reaches the bottom, he will have neighbours, whose outcome values are pre-computed above. We then use the average outcome variable of the treated - average outcome variable of the control as the treatment effect (of course, this is the plain Vanillina way, there are doubly robust etc.). 

Is my understanding now correct?

**Comment by ginward** [comment]
I thought I should have clarified my questions further. 

[In this paper](https://www.jstor.org/stable/23014404?seq=1#metadata_info_tab_contents), the author proposed a concept of propensity score that models the probability of being in the randomised sample, rather than receipt of the treatment. 

Let S_i be the indicator that the subject is in the random trial sample, and let T_i be the indicator that the subject is in the treated sample of the random trial sample. The idea is that, by using the inverse probability of being in the random trial sample 1/P(S_i), we can provide a more accurate estimate of the average treatment effect in a target population whose population characteristics are different from the random trial population. 

My question is simply that, can the sample.weights parameter be used in such a manner, or is it intended for something else? @swager @davidahirshberg 

This question is related to #418

**Comment by davidahirshberg** [comment]
That's what it's for.

**Comment by ginward** [comment]
Thanks!
