### ISSUE TITLE
Panel Data Application

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#532]
Hello guys, 

I was wondering if I could ask a quick question on applying grf to panel data. 

I understand that there is a `clusters` argument in the `causal_forest` function. Suppose that I have a panel data of the following form, where `W_it` is a continuous treatment variable that varies with individual `i` and time `t`: 

```
    loan_id    borrower_id    loan_amount     lender_id     W_it       time        Age
    
     xxxx      xxxx            xxxx            xxxx         xx         20xx        xx

```
Also suppose that I would like to cluster by `borrower_id` controlling for time. Do you think it is possible for me to identify the **unbiased** causal effect of `W_it` on `loan_amount` conditioning on `Age` with **robust** standard errors, by supplying `dat[,borrower_id]` to the `clusters` argument in the `causal_forest` function, and include time as a covariate in X? 

In a linear OLS setting, if I have an alpha in the residual that is individual-invariant through time, I can use fixed-effect/random-effect estimator to eliminate the alpha, and obtain unbiased estimates of treatment effects (suppose, controlling for age, subjects are randomly assigned to treatment). I can also obtain clustered robust standard errors by clustering. 

Can I obtain similar unbiased results as well as robust standard errors with causal_forest in this setting? Other than supplying `causal_forest`'s `clusters` argument: 
1. in a fixed effect regression: should I also include and individual dummy variable `D_i` in to the covariate matrix X to obtain an unbiased estimate of treatment effect? 
2. in a random effect regression, should I quasi-demean the variables to eliminate the serial correlation in the residuals, just like what I would have done with a linear random-effect model? 
Thanks!

**Comment by ginward** [comment]
I have read the thread [here](https://github.com/grf-labs/grf/issues/310#issuecomment-439289042), and it looks like, instead of using time as one of the clusters, I can use time as one of the covariates. However, do I still need an individual fixed effect dummy? Thanks!

**Comment by ginward** [comment]
One more thing, in [this thread](https://github.com/grf-labs/grf/issues/310#issuecomment-439289042),  do you think the time needs to be ordered (as in 1, 2, 3, 4 ,5) or can it just be unordered strings (such as "2013-01-05")? I assume that unordered string is fine, as we are not assuming any orders of correlations in the residuals in this case?

**Comment by swager** [comment]
How best to incorporate fixed effects into machine learning analyses is an active research area. One option we've been exploring is described in https://arxiv.org/pdf/1908.09874.pdf

And yes, just giving time to the random forest is enough to control for time effects. How you encode it doesn't matter (as long as monotonicity is preserved).

**Comment by ginward** [comment]
Thanks!
