### ISSUE TITLE
two way clustering

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#533]
Hi, 

Related to #328 - does grf package supports multi-way clustering now? For example, in a panel data setting, can I cluster by both time and individuals? 

Thanks!

**Comment by ginward** [comment]
I currently have a naive idea of implementing two-ways clustering. 

Suppose I have two variables, event_id and customer_id. Can I simply use the combination of event_id x customer_id as clusters, thus achieving two-ways clustering? 

For example, suppose I would like to cluster by time and customer_id: 

```
time      customer_id

0             a

1             b

```

Can I simply construct four clusters: 

```
cluster 

0-a
0-b
1-a
1-b 

```
And supply them to the clusters argument in causal forests?

**Comment by swager** [comment]
No we do not support multi-way clustering. The justification for how we support cluster-robust SEs is essentially the same as the justification for how the cluster-robust bootstrap works (i.e., we consider a population of clusters). However, this family of ideas does not directly generalize to multi-way clustering.

**Comment by ginward** [comment]
Not sure if this paper is relevant: 

https://www.tandfonline.com/doi/full/10.1080/07350015.2019.1677473
