### ISSUE TITLE
merge_forests segfaults if forests trained on samples of different size

### ISSUE THREAD

**Issue by halflearned** [grf-labs/grf#542]
**Issue**
If the user trains forest in datasets of different size, then `merge_forests` hits segfault when trying to retrieve oob predictions. 

**Example**
This causes a segfault
```r
library(grf)

X <- matrix(runif(400), 200, 2)
Y <- pmax(X[,1] > 0.5) + rnorm(200)

X1 <- X[1:80,]
X2 <- X[81:200,]
Y1 <- Y[1:80]
Y2 <- Y[81:200]

rf1 <- regression_forest(X1, Y1)
rf2 <- regression_forest(X2, Y2)
big_rf <- merge_forests(list(rf1, rf2), compute.oob.predictions = T) # Segfault 
```
If we don't compute oob predictions during merge, we can still hit a segfault later.

```r
big_rf <- merge_forests(list(rf1, rf2), compute.oob.predictions = F) 
yhat <- predict(big_rf) # Segfault
```

This, however, is fine.
```r
X <- matrix(runif(300), 150, 2)
big_rf <- merge_forests(list(rf1, rf2), compute.oob.predictions = F) 
yhat <- predict(big_rf, X_test)  # predicting on new dataset.
```

**Comments**
We might not be consider this a bug necessarily, since it involves using `merge_forests` in an unexpected way. The documentation states that `merge_forests`...

>  ...Merges a list of forests that were grown **using the same** data into one large forest

However, we might still want some users to be able to compute predictions on a test set as above. And in either case we should catch that error before it hits a segfault.

**GRF version**
0.10.4

**Comment by erikcs** [comment]
It will not segfault if it's [merged](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/merge_forests.R#L37) with the biggest forest first

```
big_rf <- merge_forests(list(rf2, rf1), compute.oob.predictions = T)
```
