### ISSUE TITLE
Variable Importance Metric

### ISSUE THREAD

**Issue by JulianDuggan** [grf-labs/grf#544]
Hi grf, 

I've read through the documentation and checked your change log for more information about what measure of variable importance you use, but I couldn't find details beyond the change log's description, "Create a simple method for variable importance based on split frequency and depth." Could you provide a more detailed description of how you calculate this metric? 

Thanks,

Julian

**Comment by erikcs** [comment]
It is available in the source:

[variable_importance](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/analysis_tools.R#L154) ([split_frequencies](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/analysis_tools.R#L126)) (a simple weighted sum of how many times variable xp was split on at each depth in the forest)

**Comment by JulianDuggan** [comment]
Thank you!
