### ISSUE TITLE
isFALSE incompatible with R 3.3.2

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#549]
**Description of the bug**
It looks like that [the isFALSE statement introduced here](https://github.com/grf-labs/grf/blob/96f496b28667025a04d99aae56982e5ee3d4c099/r-package/grf/R/input_utilities.R#L169) is not available in older versions of R (for example, v3.3.2): 

**GRF version**
development

**Comment by erikcs** [comment]
Thanks @ginward 

`isFALSE` was introduced in R [3.5.0](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html)

Suggestion @halflearned @jtibshirani : bump grf minimum required R version from [3.3.0](https://github.com/grf-labs/grf/blob/master/r-package/grf/DESCRIPTION#L21) (released April 2016) to 3.5.0 (released April 2018)

**Comment by erikcs** [comment]
We can bump it to 3.5.0, do you want to send a PR @ginward ?

**Comment by ginward** [comment]
Sure, will do it today. @erikcs
