### ISSUE TITLE
average_treatment_effect overlap or treated option not available for average_late or average_partial_effect

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#550]
I noticed that the `average_treatment_effect `function is [not available](https://github.com/grf-labs/grf/blob/c3ae6d9561e885ca8ecf433de8136d755218b9b2/r-package/grf/R/average_treatment_effect.R#L72) for `instrumental_forest`. 

Similarly, the `average_partial_effect `function is [not available](https://github.com/grf-labs/grf/blob/18d3d37cc724c930cd2e3b6e47d296a08cf68599/r-package/grf/R/average_partial_effect.R#L38) for `instrumental_forest `either. 

Is there a specific reason why instrumental forests are not supported for average treatment effects? How do I obtain an average treatment effect estimation from `instrumental_forest`, similar to the average treatment effect estimation from `causal_forest`?

**Comment by ginward** [comment]
Has this issue been addressed in #490 already?

**Comment by ginward** [comment]
What is the difference between CLATE and CATE?

**Comment by erikcs** [comment]
@ginward see [average_late](https://grf-labs.github.io/grf/reference/average_late.html) for instrumental forest

**Comment by ginward** [comment]
Thanks @erikcs 

What if I got the following warnings from the `average_late `function: 

```
Warning messages:
1: In average_late(entry.forest) :
  Estimated treatment propensities take values between -1.534 and 3.004 and in particular get very close to 0 or 1. Poor overlap may hurt perfmance for average conditional local average treatment effect estimation.
2: In average_late(entry.forest) :
  The instrument appears to be weak, with some compliance scores as low as -0.1285

```

Because there is no `overlap `or `treated `option available to deal with  the low propensity score issue. Is there a reason why these two options were not implemented?

**Comment by ginward** [comment]
Similarly, for causal forests, when the treatment is non-binary, we use average_partial_effect to obtain the average treatment effect. However, there is no overlap or treated option either. Will the results be biased if there is a cluster of low propensity scores?
