### ISSUE TITLE
Can causal_forest be used on observational data?

### ISSUE THREAD

**Issue by RicPorteousNSWIS** [grf-labs/grf#551]
Hi authors,

Apologies this is a silly question, or if this question has been answered before, but I have gotten myself quite confused. 

My basic question is, can causal_forest be used in a setting where the data doesn't come from a RCT? Specifically, can it be used on observational data where there is likely selection bias in the application of the treatment?

As I was researching this question, I came to the conclusion that it cannot be (this is based on #256 , assumption 2)

However, further research also suggests there are workarounds. For example:
 - #525 suggests that we can pass inverse propensity weights into the causal_forest() method to deal with this
 - The example code on the front uses a treatment assignment that is dependent on X[,1] with no alteration to the training code. 

Would the authors be able to clarify this point of confusion? Are there workarounds to apply this to observational data with bias in the treatment assignment? Or have I completely misrepresented the model and package/

Thanks in advance!!

**Comment by ginward** [comment]
I think we can apply it to non-random datasets. However, note that the conditional non-confounding assumptions must hold (for example, the overlap assumption, which guarantees good recovery of the counterfactual). Please see this paper  for a discussion: https://arxiv.org/abs/1902.07409

You might also need to consider sample weighting if there is poor overlap (which is different from propensity weighting). Propensity weighting focuses on internal validity, while sample weighting focuses on external validity. For discussion of sample weighting methods, see #525

**Comment by RicPorteousNSWIS** [comment]
Thank you very much - that seems to settle it. I'll dig a bit more into the paper reference you have provided.

**Comment by erikcs** [comment]
@RicPorteousNSWIS in a RCT Y⟂W, and the principle underlying inference in observational studies is that once you control for all variables that may affect a unit's receipt of treatment, the treatment is once again (conditionally) independent of the outcome: Y⟂W|X (the unconfoundedness assumption) and you proceed (with a suitable adjustment, propensity score weighting being one of them) as usual (with the usual caveats as the propensities should not be exactly 0 or 1 for any units).  

A good reference

Imbens, G.W. and Rubin, D.B., 2015. Causal inference in statistics, social, and biomedical sciences. Cambridge University Press.
