### ISSUE TITLE
average_late with poor overlap or compliance

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#553]
**Is it possible for #490 to calculate Cov[Y, Z | X = x] / Cov[W, Z | X = x] | W=1 , or  Cov[Y, Z | X = x] / Cov[W, Z | X = x] | Z=1? From the covariance term in the denominator, it looks like the denominator will explode.** 

I am estimating average treatment effects with continuous treatments. However, my dataset is imbalanced (only a small set of population is assigned to treatment), meaning that many compliance scores are close to 0. 

I got the following warnings from the `average_late `function: 

```
Warning messages:
1: In average_late(entry.forest) :
  Estimated treatment propensities take values between -1.534 and 3.004 and in particular get very close to 0 or 1. Poor overlap may hurt perfmance for average conditional local average treatment effect estimation.
2: In average_late(entry.forest) :
  The instrument appears to be weak, with some compliance scores as low as -0.1285

```

Because there is no `overlap `or `treated `option available to deal with  the low propensity score issue. Is there a reason why these two options were not implemented?

**Comment by ginward** [comment]
maybe it is less confusing if we could add an overlap option to average partial effect? I understand that the average treatment effect's overlap option also works for average_partial_effect, so it might be relatively easy to do so ...

**Comment by ginward** [comment]
But still, looks like there is still no way to do overlap option for average_late. Any ideas on that?

**Comment by jtibshirani** [comment]
Hello @ginward, I've noticed that you have opened and closed a few issues without any discussion. Could you please hold off on closing an issue until it has been resolved?

If you ended up finding the answer to your question, you can add it in a comment for future reference. We would like to avoid issues that contain open questions with no answer -- many people read over GitHub issues when debugging/ looking for information, and it can be confusing to see closed issues with no resolution.
