### ISSUE TITLE
Bug: Warning message in average_late inaccurate

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#557]
**Description of the bug**
It seems that the warning message [here ](https://github.com/grf-labs/grf/blob/25114ddd7ecc6ad2ce6a459dee8152025d9b4006/r-package/grf/R/average_late.R#L113)in `average_late ` function committed by #490 is inaccurate: 

```
if (min(subset.Z.hat) <= 0.01 || max(subset.Z.hat) >= 0.99) {
    rng <- range(subset.W.hat)
    warning(paste0(
      "Estimated treatment propensities take values between ",
      round(rng[1], 3), " and ", round(rng[2], 3),
      " and in particular get very close to 0 or 1. ",
      "Poor overlap may hurt perfmance for average conditional local average ",
      "treatment effect estimation."
    ))
  }

if (min(subset.compliance.score) <= 0.01 * sd(subset.W.orig)) {
      warning(paste0(
          "The instrument appears to be weak, with some compliance scores as ",
          "low as ", round(min(subset.compliance.score), 4)
      ))
  }
```

Because when `W `is continuous, `W `hat (or compliance score) could be **negative** or **greater** than 1. Similarly, when `Z` is continuous, `Z` hat could also be negative or greater than 1. In these cases, I don't think it is wise to use the criteria to judge poor compliance or overlap based on the 0 and 1 interval. 

Or rather, is it the case that average_late should not be applied to a continuous treatment?

**Comment by jtibshirani** [comment]
Closed by https://github.com/grf-labs/grf/pull/562.
