### ISSUE TITLE
Can GRF's causal forests estimate treatment effects for more than one treatment?

### ISSUE THREAD

**Issue by TomKealy** [grf-labs/grf#559]
I have a dataset I need to analyse that includes multiple treatments and a control, is grf capable of handling this case yet?

**Comment by erikcs** [comment]
Not yet, but it in the works: #285

**Comment by erikcs** [comment]
A "naive" approach using grf is to one-hot encode each treatment and fit k separate causal forests, one for each treatment (a package for doing this will soon be available in grf-labs).

In the meantime, you can do this yourself if you wish. The steps are described in this paper https://arxiv.org/abs/1810.04778: page 36 (section 6.4.2). An example:

```R
library(grf)
n <- 500
p <- 10
treatments <- c(1, 2, 3, 4)
X <- matrix(runif(n * p), n, p)
W <- sample(treatments, n, replace = TRUE)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)

Y.hat <- predict(regression_forest(X, Y))$predictions # these are the mean rewards mu on page 36
W.onevsall <- sapply(treatments, function(treatment) as.integer(W == treatment))
W.hat <- apply(W.onevsall, 2, function(Wi) predict(regression_forest(X, Wi))$predictions) # treatment propensities for each action
multi_causal_forest <- lapply(1:length(treatments), function(i) {
  causal_forest(X, Y, W.onevsall[, i], Y.hat, W.hat[, i]) # k separate causal forests
})

# tau.hats for treatment 1...4 (tau_a page 37)
prediction.objects <- sapply(multi_causal_forest, predict)
tau.hats <- data.frame(prediction.objects["predictions", ])
colnames(tau.hats) <- make.names(treatments)
head(tau.hats)
        X1         X2        X3        X4
1 -0.3262252 -0.1248584 0.1392025 0.3327248
2 -0.7172470 -0.2034654 0.2476034 0.6399697
3 -2.1749475 -0.3442007 0.2859436 2.1082174
4 -1.1429245 -0.2364281 0.2761516 1.2696782
5 -0.2221472 -0.2091747 0.1934955 0.4105628
6 -1.4539585 -0.1098223 0.3530950 1.2250981
```

**Comment by anaveenan** [comment]
Thanks for providing this. In two treatment the prediction provides the uplift for 1 vs other. In the example you had 4 treatments, which one is control and lets assume 1 is the control how is uplift computed

**Comment by erikcs** [comment]
Section 6.4.2 in the paper linked to above

> This quantity (tau.a) can be viewed as the performance difference between this action a and the weighted average of all the other actions
