### ISSUE TITLE
How to calculate confidence intervals of CATE?

### ISSUE THREAD

**Issue by lpgarcia18** [grf-labs/grf#563]
Hi everyone!

I have a doubt calculating confidence intervals for CATE.

You can read on page 28 of the Package ‘grf’ document that: "The square root of the column 'variance.estimates' is the standard error of CATE".

Is the square root of variance the standard error or standard deviation?

If square root of variance is the standard deviation, which n should I use for calculating the standard error: the number of individuals I am using on the training (or test) basis or the number of trees?

Thanks a lot for the help!

**Comment by erikcs** [comment]
`average_treatment_effect` returns the SE for the CATEs: https://grf-labs.github.io/grf/reference/average_treatment_effect.html
