### ISSUE TITLE
Nonsensical results: Absent treatment effects, no results with few covariates

### ISSUE THREAD

**Issue by wuttkea** [grf-labs/grf#564]
First, thanks to everyone for your work and for making this package available to the scientific community.

I am running separate causal forests on small-N survey experiment (N=1,500) with multiple pre-registered DVs and two experimental manipulations. Because most experimental treatment effects are indistinguishable from 0, the main goal for running causal forests is to identify/preclude potential effects in subgroups.

Two issues are puzzling me.

1) **Average Treatment Effects are not recovered**
One of my tests yields a small (cohen's 0.17) but highly significant positive treatment effect. 
Yet, when I run a causal forest analysis on this DV the predicted treatment effects do not indicate a significant,  positive average treatment effect (see plot attached).

![image](https://user-images.githubusercontent.com/28829190/68235848-44102780-0004-11ea-9a2d-f637bdb8a255.png)

What is more, the mean predicted effect is negative although it should be positive.  Did I miss that causal forests do not preserve the direction of the treatment effect? (On another,  significant test with stronger effect size this problem does not occur). 

2) **No results with few covariates**
I run the causal forests on 12 covariates. However, when I use a low number of covariates (<6) I obtain predicted treatment effects that do not differ between individuals. This occurs regardless of the dependent variable I investigate.

Any advice is appreciated.

**Comment by erikcs** [comment]
Do you have an example data set? If you look at the grf introduction (2nd plot) treatment effects are recovered: https://grf-labs.github.io/grf/articles/grf.html buy you can of course construct DGPs and make examples that exhibit the opposite...

**Comment by wuttkea** [comment]
Thanks, @erikcs, for the response.

This is my very first project in R. So the mistake is probably on my side. I am grateful for any help.

You can find the data here: [data.zip](https://github.com/grf-labs/grf/files/3827183/data.zip)

This is a section from my code, based on these blogposts ([1](https://humboldt-wi.github.io/blog/research/applied_predictive_modeling_19/social_pressure/), [2](https://www.markhw.com/blog/causalforestintro)).

```r

##Packages
if (!require("pacman")) install.packages("pacman")
library(pacman)

p_load(tidyverse, pdp, grf, tidylog, naniar, DiagrammeRsvg, ggeffects, Hmisc, tidyr, printr )



#Vector that contains the expl. variables
variables <- c("pre_mot_intrinsic", "pre_mot_identified", "pre_mot_introjected", "pre_mot_external", "civ_vote", "civ_taxes", "civ_law", "civ_watch", "civ_association", "civ_understand", "civ_buycott", "female", "age", "edu_c", "comp_quiz_rank", "para_device", "para_os")

#treatment is used as a placeholder for the respective treatment variable name throughout the script
treatment <- "needforcompcondition"

#dependent variable
dv <- "dv_qual_obj"


#####Train test split#####

set.seed(1839)


#partition the data into training and test set 
cases <- sample(seq_len(nrow(data)), round(nrow(data) * .7))
train_data <- data[cases, ]
test_data <- data[-cases, ]





#####Build causal forest#####


#create the inputs X, Y and W (treatment) for train data
train_X <- train_data[,variables]
train_Y <- train_data[,dv]
train_W <- train_data[,treatment]



## causal_forrest() requires vectors.  Hence, the following lines transform train_? into vectors
train_Y <- dplyr::pull(train_Y, 1);
train_W <- dplyr::pull(train_W, 1); 
train_W<-as.vector(train_W)


#NULL parameters are tuned
cf <- causal_forest(X = train_X, Y = train_Y, W = train_W,
                    num.trees = 2000, 
                    sample.fraction = NULL, #each uses half of the data
                    honesty = TRUE, #use honest splitting
                    honesty.fraction=0.5, #half of each subsample (see sample.fraction) is used for splitting,
                    ci.group.size=2, #2 is default. number of trees grown on each subsample (in order to provide confidence intervals)
                    alpha=NULL, #maximum imbalance of a split
                    compute.oob.predictions = FALSE, #should OOB predictions be precomputed
                    imbalance.penalty = NULL,
                    tune.parameters = TRUE) 


#Predict the test_data, also get variance estimates for confidence intervals
#note: with newdata=NULL, we can make out-of-bag predictions
pred_cf <- predict(cf, newdata = test_data[,variables], estimate.variance=TRUE) 
test_data[,"pred_effect"] <- pred_cf[,"predictions"]
test_data[,"var_pred_effect"] <- pred_cf[,"variance.estimates"]
#compute confidence intervals for the test_data
test_data$ci_upper <- test_data$pred_effect + 1.96 * sqrt(test_data$var_pred_effect)
test_data$ci_lower <- test_data$pred_effect - 1.96 * sqrt(test_data$var_pred_effect)


# Plot results

ggplot(
  mapping = aes(
    x = rank(test_data$pred_effect), 
    y = test_data$pred_effect
  )) +
  geom_point() +
  labs(x = "Rank", y = "Estimated Treatment Effect") +
  theme_light() +
  geom_errorbar(
    mapping = aes(
      ymin = test_data$ci_lower,
      ymax = test_data$ci_upper
    ), alpha=.1)
```

**Comment by erikcs** [comment]
I can't read your data:
```
> load('data')
Error in load("data") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘data’ has magic number 'X'
  Use of save versions prior to 2 is deprecated 
```

**Comment by swager** [comment]
@wuttkea for estimating the average treatment effect, you can use the function `average_treatment_effect`. This will give you shorter CIs than if you try to get pointwise CIs for each datapoint.

As for testing for the presence of heterogeneity, the function `test_calibration` may be helpful. See also https://arxiv.org/pdf/1902.07409.pdf for further discussion.

Overall, the tasks of estimating the ATE versus detecting some treatment heterogeneity versus getting short CIs for tau(x) have vastly different statistical complexities; so it's possible to get good results for the easier tasks while still having long CIs for tau(x).

**Comment by wuttkea** [comment]
Sorry for the inconvenience, @erikcs. Below you find a self-contained script that runs on my and on a colleagues' PC (data: [data.zip](https://github.com/grf-labs/grf/files/3827183/data.zip))

However, thinking again, I suspect that not recovering the original treatment effect might be due to having to split the already small sample. As a consequence, the originally significant, positive effect might have turned into an insignificant negative effect.

@swager: Thanks. These hints are helpful. Thank you.

```r
#load data from working directory
data <- readRDS("data.rds")

##Packages
if (!require("pacman")) install.packages("pacman")
library(pacman)

p_load(tidyverse, grf, tidyr )



#Vector that contains the expl. variables
variables <- c("pre_mot_intrinsic", "pre_mot_identified", "pre_mot_introjected", "pre_mot_external", "civ_vote", "civ_taxes", "civ_law", "civ_watch", "civ_association", "civ_understand", "civ_buycott", "female", "age", "edu_c", "comp_quiz_rank", "para_device", "para_os")

#treatment is used as a placeholder for the respective treatment variable name throughout the script
treatment <- "needforcompcondition"

#dependent variable
dv <- "dv_qual_obj"


#####Train test split#####

set.seed(1839)


#partition the data into training and test set
cases <- sample(seq_len(nrow(data)), round(nrow(data) * .7))
train_data <- data[cases, ]
test_data <- data[-cases, ]



#####Build causal forest#####


#create the inputs X, Y and W (treatment) for train data
train_X <- train_data[,variables]
train_Y <- train_data[,dv]
train_W <- train_data[,treatment]



## causal_forrest() requires vectors.  Hence, the following lines transform train_? into vectors
train_Y <- dplyr::pull(train_Y, 1);
train_W <- dplyr::pull(train_W, 1);
train_W<-as.vector(train_W)


#NULL parameters are tuned
cf <- causal_forest(X = train_X, Y = train_Y, W = train_W,
                    num.trees = 2000,
                    sample.fraction = NULL, #each uses half of the data
                    honesty = TRUE, #use honest splitting
                    honesty.fraction=0.5, #half of each subsample (see sample.fraction) is used for splitting,
                    ci.group.size=2, #2 is default. number of trees grown on each subsample (in order to provide confidence intervals)
                    alpha=NULL, #maximum imbalance of a split
                    compute.oob.predictions = FALSE, #should OOB predictions be precomputed
                    imbalance.penalty = NULL,
                    tune.parameters = TRUE)




#Predict the test_data, also get variance estimates for confidence intervals
#note: with newdata=NULL, we can make out-of-bag predictions
pred_cf <- predict(cf, newdata = test_data[,variables], estimate.variance=TRUE)
test_data[,"pred_effect"] <- pred_cf[,"predictions"]
test_data[,"var_pred_effect"] <- pred_cf[,"variance.estimates"]
#compute confidence intervals for the test_data
test_data$ci_upper <- test_data$pred_effect + 1.96 * sqrt(test_data$var_pred_effect)
test_data$ci_lower <- test_data$pred_effect - 1.96 * sqrt(test_data$var_pred_effect)
```

# Plot results

ggplot(
  mapping = aes(
    x = rank(test_data$pred_effect),
    y = test_data$pred_effect
  )) +
  geom_point() +
  labs(x = "Rank", y = "Estimated Treatment Effect") +
  theme_light() +
  geom_errorbar(
    mapping = aes(
      ymin = test_data$ci_lower,
      ymax = test_data$ci_upper
    ), alpha=.1)
````
