### ISSUE TITLE
Variable selection

### ISSUE THREAD

**Issue by AsgerAndersen** [grf-labs/grf#565]
Hi grf community!

Thank you very much for developing the grf package! Does anybody have suggestions for a systematic way of detecting which variables the treatment is heterogeneous with respect to? I know that I can use test_calibration to test, if there seems to be any heterogeneity in the treatment effects with respect to some combination of the included variables. However, I don't know of any systematic way of selecting some specific subset of the variables for further inspection. I know that I can look at the importance measure from the variable_importance function, but I do not know how to systematically use these measures to select a subset of variables (except for just choosing the K most important variables according to the importance measures, but then the problem is to choose what number K to use). Does anybody have a suggestion for how to approach this?

Again: Thank you very much for developing the package :-)

**Comment by erikcs** [comment]
This thread might be relevant for you: https://github.com/grf-labs/grf/issues/238

(https://github.com/grf-labs/grf/issues/130 and https://github.com/grf-labs/grf/issues/136 slightly related)

In the future more of this will be presented in a principled way in the documentation! One more resource https://arxiv.org/abs/1909.00836

**Comment by AsgerAndersen** [comment]
Thanks for the answer, @erikcs
