### ISSUE TITLE
Is multicollinearity a concern 

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#567]
Suppose I have two covariates X1 and X2, treatment W and dependent variable Y. 

In OLS regressions, when two regressors X1 and X2 are highly correlated, the coefficients might have a larger variance. 

I was wondering if multicollinearity is a concern for causal forest. Suppose that, two of my covariates X1 and X2 are highly correlated, but X1 and X2 are not highly correlated with the treatment W.  Does it hurt if I put both X1 and X2 in as covariates input to causal forest, or is it better if I leave one of them out? 

Out of the top my head, I think there is no problem of doing so, as we are not inferring the coefficients of X1 and X2. In fact, I think it might help to make the assumption of W independent on Y conditional both on X1 and X2 rather than conditioning on X1 alone. 

Thanks!

**Comment by davidahirshberg** [comment]
When estimating treatment effects, high correlation between covariates is fine as long as there is overlap between the covariate distributions for treatment and control units. If X1 and X2 are highly correlated, if we have overlap we'll see the same correlation between X1 and X2 in the treatment and control subsamples.

**Comment by ginward** [comment]
Thanks!
