### ISSUE TITLE
How to save a trained forest

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#572]
It might be worthwhile to add an option to save the trained forest after training. This might come in handy when the training set is large, and it might allow us to use the trained forest to make predictions and draw graphs without having to train the forest every time.

**Comment by erikcs** [comment]
This is already in place through R:

```
saveRDS(fitted.forest, file = "large.forest.Rds")
```

**Comment by ginward** [comment]
I see. Thanks!
