### ISSUE TITLE
Look into improving the performance of `get_sample_weights`.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#577]
As noted in https://github.com/grf-labs/grf/issues/295#issuecomment-435184200, the R method `get_sample_weights` can be fairly slow on a large dataset. We could look into improving the performance through parallelization, and also consider reviving @halflearned's work in https://github.com/grf-labs/grf/pull/360.

**Comment by erikcs** [comment]
The first thing that makes `get_sample_weights` slow is inserting the result into the sparse matrix , which is being resized at every iteration:

<img width="1136" alt="Screen Shot 2019-11-23 at 21 43 53" src="https://user-images.githubusercontent.com/7185264/69490298-62668780-0e3a-11ea-8136-9b2e06daa1f0.png">

**Comment by halflearned** [comment]
As I have written in #359, `unordered_map` does not seem to be a bottleneck for `get_sample_weights` or `DefaultPredictionStrategy`. 

@erikcs' PR #578 already provided a pretty great improvement for `get_sample_weights`. Hoping that's okay with everyone, I'll move to close this now. Please re-open as needed.
