### ISSUE TITLE
Should the correlation between W and X be 0? 

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#581]
This question is related to #385 that @swager answered. 

It was made clear that high correlation between W (treatment) and X (covariates) might cause the overlap assumption to fail, which in turn might lead to biases in the treatment effects estimates tau(X). 

**However, do we require that W is independent of X absolutely?** 

That is, is it true that there cannot be any correlation between W and X? 

Or rather, is there a certain **threshold** of correlation between W and X below which there won't be any biases in the treatment effect estimates tau(X)?

**Comment by ginward** [comment]
Sorry, I realised that this question was a little naive. W and X shouldn't be independent, of course, otherwise there will be no point in estimating the propensity score. But too much correlation between W and X will also cause the propensity score to be too high or too low. 

I think there is no hard threshold as in what makes the correlation "too high". Probably need to test the overlap assumptions to determine if the correlation is too high or too low ...

**Comment by susanathey** [comment]
Take a look at Imbens and Rubin, and also Crump, Richard K., et al. "Dealing with limited overlap in estimation of average treatment effects." Biometrika 96.1 (2009): 187-199.

**Comment by ginward** [comment]
Thanks @susanathey !
