### ISSUE TITLE
The printed tree is inconsistent (only applies to grf 1.0.0)

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#599]
I plotted a tree in my instrumental forest with the following structure: 

<img width="1028" alt="Screenshot 2019-12-15 at 16 58 48" src="https://user-images.githubusercontent.com/6193977/70866026-52832480-1f5c-11ea-8a88-5fac128f87de.png">

If you look at the first and second node to the right, they seem to be contradictory. If it is **false** that variable A is less than 210618096.42, variable A should be greater than 210618096.42. Then how come the immediate next split is based on the criteria that A is less than 167979476, which is less than 210618096.42? Wouldn't these two criteria be self-contradictory, i.e. variable A is greater than 210618096.42 but less than 167979476 at the same time? The weirdest things is that there seems to be observations that falls within this category ...

**Comment by erikcs** [comment]
There was a bug in the tree printing order https://github.com/grf-labs/grf/pull/587. It is fixed in the latest version on Cran (https://grf-labs.github.io/grf/CHANGELOG.html#fixed)

**Comment by ginward** [comment]
@erikcs is it fixed in the development branch on GitHub?

**Comment by erikcs** [comment]
Yes, both the github and Cran https://cran.r-project.org/package=grf has that fix

**Comment by ginward** [comment]
Which commit fixed it? @erikcs

**Comment by erikcs** [comment]
https://github.com/grf-labs/grf/pull/587

**Comment by ginward** [comment]
Thanks!
