### ISSUE TITLE
Is "samples_per_cluster" an unused argument?

### ISSUE THREAD

**Issue by tyanagiura** [grf-labs/grf#600]
I am trying to replicate the causal forest codes shown on "Estimating Treatment Effects with Causal Forests: An Application" by Athey and Wager (2019). However, I couldn't run the code shown in Algorithm 1 (page 6) where the algorithm is supposed to create the object "cf" with the following error message: "unused argument (samples_per_cluster = 50)". When I ran the same code without the argument, I obtained a slightly different ATE "95% CI for the ATE: 0.252 +/- 0.033" (whereas in the paper, that's 0.247 +/- 0.04), so I figure this argument has some role. Is this argument not used entirely or replaced by something else?

**Comment by erikcs** [comment]
Yes, `samples.per.cluster` was removed here https://github.com/grf-labs/grf/pull/545

**Comment by tyanagiura** [comment]
Thanks for the clarification.
