### ISSUE TITLE
Allow for different set of confounders/moderators

### ISSUE THREAD

**Issue by NicolasWoloszko** [grf-labs/grf#601]
The list of controls/confounders `X` used to deconfound the relationship between `W` and `Y` may differ from the list of moderators/effect modifiers (let's call it `S`). As a result, it could be nice to have : 
``` causal_forest(X, Y, W, S)```
Where `S` would be an optional parameter (by default equal to `X`)

**Comment by swager** [comment]
Currently it's possible to get at this workflow via:

```
Y.forest = regression_forest(X, Y)
Y.hat = predict(Y.forest)$predictions #note that this is OOB

W.forest = regression_forest(X, W)
W.hat = predict(W.forest)$predictions

cf = causal_forest(S, Y, W, Y.hat = Y.hat, W.hat = W.hat)
```
