### ISSUE TITLE
Checkpointing

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#605]
Is there any plan to add checkpointing to forest training? For example, training 10,000 trees might take a long time. If the program gets interrupted when training the 50,000th tree, it can resume from the checkpoint later.

**Comment by erikcs** [comment]
Can't you checkpoint the way you mention here https://github.com/grf-labs/grf/issues/558#issuecomment-559443149 ?

**Comment by ginward** [comment]
It is possible to use DMTCP. But it is very unstable. It will be nice if grf could support checkpoints natively like tensorflow does.

**Comment by halflearned** [comment]
It seems like we don't have any plans of implementing this feature right now. If you have a concrete proposal for implementation, please feel free to re-open this issue.
