### ISSUE TITLE
best_linear_projection with non-binary treatment

### ISSUE THREAD

**Issue by AlexiaJM** [grf-labs/grf#608]
Here is a reproducible example which shows that although **average_partial_effect** is stable to transformations of the treatment variables (addition, multiplication, standardization) but that  **best_linear_projection** is extremely unstable to these transformation on the treatment variables. 

This suggests that **best_linear_projection** is too unstable for use. Why is that the case? Is there an alternative to finding the effect of variables on the ATE? I know we can subset, but that only works if the variable is binary.

# Generate data.
set.seed(666)
n <- 2000
p <- 10
X <- matrix(rnorm(n * p), n, p)
X.test <- matrix(0, 101, p)
X.test[, 1] <- seq(-2, 2, length.out = 101)

tau.forest <- causal_forest(X, Y, W)
print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))
average_partial_effect(tau.forest)

tau.forest <- causal_forest(X, Y, W + 1)
print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))
average_partial_effect(tau.forest)

tau.forest <- causal_forest(X, Y, W + 10)
print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))
average_partial_effect(tau.forest)

tau.forest <- causal_forest(X, Y, W + 100)
print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))
average_partial_effect(tau.forest)

tau.forest <- causal_forest(X, Y, 2*W)
print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))
average_partial_effect(tau.forest)

tau.forest <- causal_forest(X, Y, 4*W)
print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))
average_partial_effect(tau.forest)

print(sd(W))
tau.forest <- causal_forest(X, Y, (W - mean(W))/sd(W))
print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))
average_partial_effect(tau.forest)

## Results
```
> # Generate data.
> set.seed(666)
> n <- 2000
> p <- 10
> X <- matrix(rnorm(n * p), n, p)
> X.test <- matrix(0, 101, p)
> X.test[, 1] <- seq(-2, 2, length.out = 101)
> 
> tau.forest <- causal_forest(X, Y, W)
> print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))

Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

              Estimate Std. Error t value  Pr(>|t|)    
(Intercept)  0.3985716  0.0715507  5.5705 2.884e-08 ***
A1          -0.0013761  0.0731211 -0.0188     0.985    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> average_partial_effect(tau.forest)
  estimate    std.err 
0.39882332 0.07156194 
> 
> tau.forest <- causal_forest(X, Y, W + 1)
> print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))

Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

             Estimate Std. Error t value Pr(>|t|)    
(Intercept)  0.412530   0.023641  17.450   <2e-16 ***
A1          -0.005239   0.024483  -0.214   0.8306    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> average_partial_effect(tau.forest)
  estimate    std.err 
0.39980389 0.07153699 
> 
> tau.forest <- causal_forest(X, Y, W + 10)
> print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))

Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

              Estimate Std. Error  t value Pr(>|t|)    
(Intercept)  0.3958952  0.0016401 241.3836   <2e-16 ***
A1          -0.0012995  0.0016482  -0.7884   0.4305    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> average_partial_effect(tau.forest)
  estimate    std.err 
0.39557384 0.07156714 
> 
> tau.forest <- causal_forest(X, Y, W + 100)
> print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))

Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

              Estimate Std. Error  t value Pr(>|t|)    
(Intercept) 0.39376449 0.00170742 230.6197   <2e-16 ***
A1          0.00058036 0.00172776   0.3359    0.737    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> average_partial_effect(tau.forest)
  estimate    std.err 
0.39791791 0.07172981 
> 
> tau.forest <- causal_forest(X, Y, 2*W)
> print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))

Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

            Estimate Std. Error t value Pr(>|t|)
(Intercept)   62.155     50.344  1.2346   0.2171
A1           -76.171     49.783 -1.5301   0.1262

> average_partial_effect(tau.forest)
  estimate    std.err 
0.19952215 0.03588625 
> 
> tau.forest <- causal_forest(X, Y, 4*W)
> print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))

Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

              Estimate Std. Error t value Pr(>|t|)   
(Intercept)  0.0909210  0.0350687  2.5927 0.009593 **
A1          -0.0045975  0.0371835 -0.1236 0.901611   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> average_partial_effect(tau.forest)
  estimate    std.err 
0.09919461 0.01791591 
> 
> print(sd(W))
[1] 0.5000688
> tau.forest <- causal_forest(X, Y, (W - mean(W))/sd(W))
> print(best_linear_projection(tau.forest,  X[,1,drop=FALSE]))

Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

            Estimate Std. Error t value Pr(>|t|)  
(Intercept)  -66.485     36.774 -1.8079  0.07077 .
A1            23.369     27.144  0.8609  0.38938  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> average_partial_effect(tau.forest)
  estimate    std.err 
0.19642143 0.03577364 
```

**Comment by swager** [comment]
Currently, the function `best_linear_projection` assumes that `W` is binary, kind of like `average_treatment_effect`. So our first priority is to document + enforce this requirement. In this script, treatment is not coded as {0, 1}, so the behavior of `best_linear_projection` is unspecified.

Now, it'd also be interesting to have a version of `best_linear_projection` that works with continuous `W`, kind of like `average_partial_effect`. That will take a little bit of implementation work, though.

**Comment by swager** [comment]
Concretely, when implementing this, what we need is the following. A key step of `best_linear_projection` is forming doubly robust scores <a href="https://github.com/grf-labs/grf/blob/d56a3b79ab12cf7df3411c09eea8ce0220fce177/r-package/grf/R/forest_summary.R#L174">here</a>, which involves inverse-propensity weights:
```R
(subset.W.orig - subset.W.hat) / (subset.W.hat * (1 - subset.W.hat))
```
With a continuous treatment, we can no longer use this form (which relied on binary treatment), and instead need to use what we call `debiasing.weights` in the `average_partial_effect` function, <a href="https://github.com/grf-labs/grf/blob/d56a3b79ab12cf7df3411c09eea8ce0220fce177/r-package/grf/R/average_partial_effect.R#L96">here</a> (it's just the relevant Riesz representer for this problem, as discussed in Section 3 of https://arxiv.org/pdf/1712.00038.pdf).

Beyond that, the logic is the same. When implementing this, we may want to fold out the logic for producing IPW-style weights with a continuous treatment, since it's a little much code to duplicate.
