### ISSUE TITLE
Can the outcome be used as a moderator ? 

### ISSUE THREAD

**Issue by NicolasWoloszko** [grf-labs/grf#609]
I am interested in the heterogeneous effect of some policy `P` on household income `Y`. The effect may be moderated by `Y`, so that poorer households are more affected than richer ones. 
Is it ok to use `Y` both as the outcome and a moderator as long as I do not use as a control (obviously), using the `Y.hat` and `W.hat` arguments in order to have a different set of controls/moderators ? 

In other terms, can GRF be used to assess the effect of a policy on household income along the income distribution among other moderators ?

**Comment by swager** [comment]
No outcomes Y themselves cannot be used as moderators with GRF (although one could use an out-of-sample estimate of E[Y|X, W=0] as a moderator). Anything used as a moderator must satisfy unconfoundedness, i.e., {Y(0), Y(1)} \indep W | X.

**Comment by NicolasWoloszko** [comment]
Thanks a lot for this swift answer. Is there any reference about the trick you suggest I should look at ? In my case, W is continuous (= the minimum wage). I guess E[Y|X, W=Wmin] or E[Y|X] could work as well ?

**Comment by NicolasWoloszko** [comment]
I’m confused actually. In a standard econometric setting I’d be allowed to manually « split » on the outcome in order to estimate effects on target populations. Say I’m interested in the effect of minimum wage in income, I can split the sample by income quintiles and get 5 « local » estimates of the effect of MW increase. In this case, i don’t need to adjust for any sort of selection bias. I could even run 5 GRF, one in each quintile... Then how come GRF can’t split on the outcome (as long as we don’t control for it obviously) ?

**Comment by swager** [comment]
For your earlier comment -- yes exactly, as long as one uses cross-fitting. One reference on this type of approach is:

Hansen, Ben B. "The prognostic analogue of the propensity score." Biometrika 95.2 (2008): 481-488.

For the latter comment: I don't believe it's typical to make strata based on outcomes. What's more common is, with panel data, to stratify subjects based on pre-treatment outcomes (e.g., income before minimum wage increase); but, in doing so, one uses the pre-treatment outcomes more like something we'd usually call covariates. Stratifying on post-treatment outcomes could lead to biases.

**Comment by NicolasWoloszko** [comment]
Thank you very much for this. Very useful thanks!
