### ISSUE TITLE
Question about Missing values

### ISSUE THREAD

**Issue by jhmaccuish** [grf-labs/grf#613]
Hello,

Am I correct in coming to the conclusion from issue #457 "Random forests with missing X-values" that it is not possible in the current release to use causal_forest with missing values in X? Or is there some work around that allows the handling of missing values even if inefficiently before the functionality in issue 457 is implemented? 

Thanks

**Comment by erikcs** [comment]
You can use the data duplication workaround in the meantime: if a feature Xj has missing values, replace it with two copies. In the first copy you set all missing to minus infinity, and the other plus infinity (i.e. a number larger than all other Xj).

**Comment by jhmaccuish** [comment]
Thanks. So to make sure I've understood if i transfer the X something like this:

`X1 <- XX1[is.na(X1)] <- Inf
X2 <- X
X2[is.na(X2)] <- -Inf
X <- cbind(X1,X2)
rm(X1,X2)`
X1 <- X
X1[is.na(X1)] <- Inf
X2 <- X
X2[is.na(X2)] <- -Inf
X <- cbind(X1,X2)
rm(X1,X2)

then causal_forest will correctly handle missing values?

Thanks,

**Comment by erikcs** [comment]
Yes, that is right, except maybe use for example 1e9 instead of R's Inf to be sure it's handled correctly in C++.

**Comment by erikcs** [comment]
@jhmaccuish The latest grf version (1.1.0) now supports missing values in X https://cran.r-project.org/web/packages/grf/index.html
