### ISSUE TITLE
Difference between OLS and average_partial_effect

### ISSUE THREAD

**Issue by pachard** [grf-labs/grf#619]
Hello, 

I would have a question about the grf package/method and did not know where to send it. I hope this forum is the right place, please tell me if it is not.

I have different results when I estimate average partial effects with OLS and with grf. When I estimate the equation Y = \alpha + \beta ln_something + X + \epsilon with OLS  and use the command average_partial_effect where X are the covariates and ln_something the W (in the causal_forest), the estimates of \beta and the average_partial_effect are very different. In a regression context, I reject the null of equality of \beta and the numerical value of average_partial_effect at the 5% level.  

I don't expect OLS and GRF estimates to be numerically the same of course but both methods are consistent and rely on the same exogeneity assumption. Should they not give a similar picture? Grf seems clearly superior when it comes to estimating effect heterogeneity as testing on multiple subgroups can lead to over-rejection with OLS and not GRF but it is not clear to me that grf is by design "better" than OLS for estimating unconditional effect. In my case, the average_partial_effect is in absolute value larger than the OLS estimates. The inference from OLS is of a zero effect and with GRF it is of a non-zero effect. 

I was wondering if you had a rationale for this difference (splitting rule maximizing heterogeneity, failure of linearity which would be more problematic with one the methods or more trivially a misunderstanding from my part ...)? 

Thanks in advance, 
Best,
Pascal

**Comment by swager** [comment]
Hi @pachard, what's going on here is that OLS needs more than an exogeneity assumption to consistently recover the average partial effect: It also needs a functional form assumption (i.e., not only does W need to be exogenous conditionally on X, but for OLS we need to assume that linearly controlling for X is enough to adjust for any confounding). In contrast, GRF is non-parametric and so does not rely on such a functional form assumption.

Here's a simple simulation (where exogeneity holds as assumed) that has the same qualitative behavior as what you're finding: OLS gets a 0 APE, whereas GRF doesn't. Here, GRF is getting the correct answer, whereas OLS is not due to functional form misspecification.

```R
set.seed(1)

n = 8000; p = 8
X = matrix(rnorm(n * p), n, p)
L = 2 / (1 + exp(5 * X[,1] + 5 * X[,2]))
W = L + rnorm(n)
Y = 0.25 * W - 1.6 * L + rnorm(n)

summary(lm(Y ~ W + X))

cf = causal_forest(X, Y, W)
average_partial_effect(cf)
```
The output is
```R
#OLS
Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) -1.347640   0.018114 -74.400   <2e-16 ***
W           -0.004630   0.012342  -0.375   0.7075    
X1           0.717976   0.014691  48.873   <2e-16 ***
X2           0.726926   0.015094  48.161   <2e-16 ***
X3          -0.023237   0.013321  -1.744   0.0811 .  
...

#GRF
 estimate   std.err 
0.2380881 0.0115196 
```

**Comment by pachard** [comment]
Hi @swager , 

Thanks for your answer. I have a few follow-up questions. 
Indeed linearity is such a common assumption in applied economics (my background) that one easily forgets it is restrictive. Your method is more general but I would like to understand better why there are similarities/differences between GRF and OLS. GRF is still a ‘’new’’ method and many referees will ask to explain at length why GRF should be preferred to OLS. If failure of linearity is a common issue, other researchers doing applied work could be in a similar situation.   

I have two additional elements about my results: 
I tried to make the controls enter non-linearly. This is not always easy in my case since most of my controls are categorical variables (country of origin, year of immigration …) that appear as dummies in linear regressions and as factors in the GRF algorithm. I tried to include powers of the (few) non categorical controls, x^(2) , x^(3) , x^(4) , x^(-1) , x^(-2) , x^(-3) , x^(-4) as additional controls to approximate an unknown non-linear form in the ols estimation but that didn’t change anything. Do you see other ways to specify which pattern of non-linearity is biasing the OLS? Could the discrepancies between OLS and GRF be due to the effect being non-linear in the variables I control for in OLS?
 
I have actually two outcome variables, one where OLS gives a well-estimated 0 and GRF a negative effect (the one I talked about) and another one where OLS is close to GRF. What do you mean when you say that identification relies on linearity of inclusion of the controls? Is it in relation to the outcome or the treatment variable? Does it mean that the relation between the outcome and the controls should be linear? or that identification relies on the relation between the treatment and the controls to be linear? If it’s the latter case, the same treatment variable and the same controls should provide identification regardless of the outcome, something that fails in my case.
Thanks in advance, 
Best, 
Pascal

**Comment by halflearned** [comment]
Hi @pachard, thanks again for your question! 

The keywords you're looking for are "model misspecification" and "nonparametric econometrics/statistics". The former is about testing for whether a particular chosen model is correct, in the sense that it agrees with the "true" underlying process that generated your data.  The latter is about using statistical methods that are agnostic about the true data-generating process (grf is such a model, and OLS is not). 

As @swager's example showed, if the true data-generating process is nonlinear, a linear model will produce incorrect results. That could be what is going on in either or both of the models described in your issue.

**Comment by athammad** [comment]
Hi guys,

this example is very clear. Is there a way to replace the continuous treatment variables (`W`) in the simulation above with a dichotomous variable where exogeneity holds ?

best wishes

**Comment by erikcs** [comment]
> Hi guys,
> 
> this example is very clear. Is there a way to replace the continuous treatment variables (`W`) in the simulation above with a dichotomous variable where exogeneity holds ?
> 
> best wishes

```R
set.seed(42)
n = 8000
p = 5
X = matrix(rnorm(n * p), n, p)
L = 1 / (0.1 + exp(abs(sin(X[, 1]))))
W = rbinom(n, 1, L)
Y = 0.25 * W - L + rnorm(n)
summary(lm(Y ~ W + X))
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
#   (Intercept) -0.516790   0.016717 -30.914  < 2e-16 ***
#   W            0.155343   0.022494   6.906 5.37e-12 ***
#   X1           0.010124   0.011119   0.911    0.363    
#   X2          -0.002021   0.011070  -0.183    0.855    
#   X3           0.003861   0.011107   0.348    0.728    
#   X4          -0.020099   0.011013  -1.825    0.068 .  
#   X5          -0.004119   0.011109  -0.371    0.711  
cf = causal_forest(X, Y, W)
average_treatment_effect(cf)
# estimate    std.err 
# 0.27139904 0.02408306 
```
