### ISSUE TITLE
Continuous outcome

### ISSUE THREAD

**Issue by shaddyab** [grf-labs/grf#624]
Does this package support cases where the target variable is continuous (Sale, revenue, etc.)? How is the Qini index calculated for such cases?

**Comment by erikcs** [comment]
The outcome is traditionally continuous, the treatment assignment can be either discrete or continuous https://grf-labs.github.io/grf/reference/causal_forest.html (am not familiar with the Qini index)

**Comment by halflearned** [comment]
Hi @shaddyab, I hope we've answered your question. Regarding Qini indices and the like for model evaluation, please see the discussion in #395.
