### ISSUE TITLE
Level predictions with causal inference

### ISSUE THREAD

**Issue by sma11s101** [grf-labs/grf#626]
Is it possible to recover the level predictions from `causal_forest` in a way that is consistent with the estimated treatment effects?

I have continuous treatment W and binary outcome Y.  What I would like are estimates of E[Y|X,W=w_1] and E[Y|X,W=w_2]  where there is a causal interpretation of the change in W.  I understand that `predict` from `causal_forest` is returning the slope associated with W, but is it possible to recover the levels?  Is this equivalent to simply using `regression_forest` to predict E[Y|X,W]?

**Comment by halflearned** [comment]
Yes, this is sort of "one-half" of a treatment effect. You can compute it from the `causal_forest` output as follows

```r
forest <- causal_forest(X, Y, W)
tau.hat <- predict(forest)
Y.hat.0 <- forest$Y.hat -  forest$W.hat * tau.hat   # E[Y|X,W=0]
Y.hat.1 <- forest$Y.hat + (1 -  forest$W.hat) * tau.hat  # E[Y|X, W=1]
```

Incidentally the function [average_treatment_effect](https://github.com/grf-labs/grf/blob/7f0ae5e2ba03f46a218550dd294a07627e5f6767/r-package/grf/R/average_treatment_effect.R#L191) performs this computation (but it does not output it).
