### ISSUE TITLE
Average partial effect with a continuous treatment and clustered data

### ISSUE THREAD

**Issue by gcasamat** [grf-labs/grf#628]
I build a causal forest with the option clusters and I would like to compute the average partial effect for a given cluster.
I run the command: 
average_partial_effect( cf
                                         , calibrate.weights = TRUE
                                         , subset = (X$cluster_id_1 == 1)
                                         , num.trees.for.variance = 500
), where cluster_id_1 is a dummy variable indicating if the observations belong to cluster 1.
I get the following error message:
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

**Comment by erikcs** [comment]
Thanks @gcasamat, this will be fixed in #629

**Comment by gcasamat** [comment]
Many thanks for your quick reaction!

**Comment by erikcs** [comment]
And sorry for the confusion, but this should raise an error (but more informative): it is not possible to calculate this estimate for the desired subset as with clustering enabled you treat each cluster as a distinct unit, which here would be the same as asking for the average partial effect for a single observation.

**Comment by gcasamat** [comment]
Thanks for your explanation. However, knowing that we have estimates of individual effects, isn't it possible to compute an aggregate effect at the cluster level?

**Comment by gcasamat** [comment]
A little more precise comment: 
it seems that the problem in computing the average partial effect at the cluster level is due to the fact that V.hat cannot be estimated (in the script average_partial_effect.R). 
The method for estimating V.hat consists in running a regression forest of 
    (subset.W.orig - subset.W.hat)^2 on subset.X.orig, with clustered data. Wouldn't it be possible to perform this estimation on unclustered data?
