### ISSUE TITLE
report the casual effect of each of leaves in the plot

### ISSUE THREAD

**Issue by zhong1969** [grf-labs/grf#630]
I have a question related to the codes of “grf”.
 
I used the following codes to plot a tree:
 
tree3.plot = plot(get_tree(forest3.iv, 1))
cat(DiagrammeRsvg::export_svg(tree3.plot), file='plot_non_cluster.svg')
 
In each of leaves in the plot, it reported size, avg_Y, avg_W  and avg_Z. Could you please kindly tell me how to report the casual effect of each of leaves in the plot?
 
Great thanks!

**Comment by erikcs** [comment]
There is currently no built in functions to report that, but this thread may be useful: #238 . The are also some resources in the documentation: https://grf-labs.github.io/grf/articles/diagnostics.html#assessing-fit

**Comment by erikcs** [comment]
It will eventually be possible to do this with #281. Note that you can also use the package [policytree](https://github.com/grf-labs/policytree) to fit a shallow tree on the double robust scores, see the package documentation [here](https://grf-labs.github.io/policytree/articles/policytree.html#binary-treatment-effect-estimation-and-policy-learning)

**Comment by fateme74** [comment]
Hi,
when we run these lines of codes below,is str.error the MSE?
If not how we can access MSE  or MAE?
#> 
#> Best linear fit using forest predictions (on held-out data)
#> as well as the mean forest prediction as regressors, along
#> with one-sided heteroskedasticity-robust (HC3) SEs:
#> 
#>                                Estimate Std. Error t value    Pr(>t)    
#> mean.forest.prediction          1.01173    0.12993  7.7867  5.48e-15 ***
#> differential.forest.prediction  1.19326    0.10122 11.7885 < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

**Comment by fateme74** [comment]
Hi,
after fit a causal forest how we can access to final leaf and save observation that fall in final leaf to make other prediction on them?(Actually I want to fit a causal forest on my data to find subgroups and I need to do other prediction on each subgroup)
