### ISSUE TITLE
Using true or estimated propensity scores in causal forest for an RCT

### ISSUE THREAD

**Issue by boyercb** [grf-labs/grf#636]
We are using the `grf::causal_forest()` function to estimate heterogeneous treatment effects in a large RCT and were wondering whether it is always preferable to use the known propensity scores (i.e. in our case, to set `W.hat = 0.5`) or is there any case in which one might still want to train a RF to determine estimated propensity scores? Thanks!

**Comment by swager** [comment]
You should use the true propensity scores if they're available. At the very least, I'm not aware of any scenario where grf would do better with estimated as opposed to true propensity scores.

**Comment by eliormi** [comment]
Just to make sure, in case of a Stratified Control Trial, where we know the true propensity scores **in each cluster**, but the propensity scores are not fixed to all clusters (not always 0.5)
Is it better to use for unit i in cluster j  ,  W.hat[i] = true_known_PS for cluster j ? Thanks

**Comment by swager** [comment]
Yes exactly. You should pass in the true propensity scores when known, including when they are not constant.

Very roughly and heuristically, the confounding bias of doubly-robust-type estimators (including causal forests) depends on the product of the error you had in the propensity estimates W.hat and the baseline estimates Y.hat. So in general, if W.hat and Y.hat are pretty accurate, then you can hope for the confounding bias to be small. But if propensity scores are known exactly and so there's no error in W.hat, the confounding bias disappears.

NOTE: The question about how exactly errors in W.hat and Y.hat trade off against each other for CATE estimation is still an active research area. For formal statements, see:

Kennedy, Edward H. "Optimal doubly robust estimation of heterogeneous causal effects." arXiv preprint arXiv:2004.14497 (2020).
Nie, Xinkun, and Stefan Wager. "Quasi-oracle estimation of heterogeneous treatment effects." arXiv preprint arXiv:1712.04912 (2017).
