### ISSUE TITLE
Best linear projection with a single covariate

### ISSUE THREAD

**Issue by gcasamat** [grf-labs/grf#639]
I try to use the function best_linear_projection with a single covariate: 
best_linear_projection(cf$forest,data_for_reg[c(treat_var)])
but I get the error message: 
Error in `colnames<-`(`*tmp*`, value = paste0("A", 1:ncol(A))) : 
  attempt to set 'colnames' on an object with less than two dimensions
When I use more than one covariate, everything works fine.

**Comment by swager** [comment]
Does this issue persist with the latest version (1.1.0)?

**Comment by gcasamat** [comment]
You are right, I was not using the latest version. Everything works fine now. Thanks.

**Comment by swager** [comment]
Thanks!
