### ISSUE TITLE
Questions about calibrate.weights option

### ISSUE THREAD

**Issue by gcasamat** [grf-labs/grf#644]
I want to compute average partial effect in distinct geographical areas. 
With the default setting of the average_partial_effect function (calibrate.weights = TRUE), I get the following histogram of APEs per area:
[iris_hist.pdf](https://github.com/grf-labs/grf/files/4373816/iris_hist.pdf)
When I turn the option to calibrate.weights = FALSE, I get:
[iris_hist_no_calib.pdf](https://github.com/grf-labs/grf/files/4373851/iris_hist_no_calib.pdf)
The two graphs look very different (and the first one seems more "reasonable" to me), so my first question is: 
What is the meaning of the option calibrate.weights and in which circumstances should it be helpful? Is it supposed to always provide "better" results when it is activated? 
I also performed the best linear projection of the individual partial effects on the geographical dummies, with results consistent with the second graph. I was however not able to do an analysis similar to the first graph as there is no option calibrate.weight in the best_linear_projection function. Why is it the case? Is there a specific reason not to implement the option calibrate.weight within the best_linear_projection function?

**Comment by erikcs** [comment]
(Closed as the `calibrate.weights` option is removed now)
