### ISSUE TITLE
The formula of clustered standard errors

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#648]
Hi

I wonder how clustered standard errors are calculated, and its mathematical formulations? I understand that the SE for each individual unit effect is the variation in treatment effects across all trees, but what correction do we do at the clustering level? This question is related to issue #631 but it elaborates the math-side of things. 

I could not find any reference for this in, Athey, Susan, Julie Tibshirani, and Stefan Wager. 2019. “Generalized Random Forests.” The Annals of Statistics 47(2):1148–78.

**Comment by erikcs** [comment]
Is the [algorithm reference](https://grf-labs.github.io/grf/REFERENCE.html#cluster-robust-estimation) on clustering helpful or are there details you think we can add?

**Comment by adeldaoud** [comment]
@erikcs Thanks for the link. The section you refer to describes the procedure well, however, I am missing references to either your work where the sampling procedure is explained in further detail (including half sampling) and possibly other material about how bootstrapping with hierarchical data. The reason being is that I would like to refer to those references in my scientific articles.

**Comment by erikcs** [comment]
@adeldaoud Is [this](https://arxiv.org/pdf/1902.07409.pdf) paper what you are looking for? (section 1.2 and 3.1)

**Comment by swager** [comment]
Yes -- we added cluster-robust inference after finishing the GRF paper, so the algorithm is not described there. We're planning to discuss it in a paper about the package, but we haven't written it yet. In the mean time, the reference @erikcs noted is the only published place we describe cluster-robust GRF. For a general reference on cluster-robust bootstrapping, the following may be helpful:

Cameron, A. Colin, Jonah B. Gelbach, and Douglas L. Miller. "Bootstrap-based improvements for inference with clustered errors." The Review of Economics and Statistics 90.3 (2008): 414-427.

**Comment by adeldaoud** [comment]
@erikcs and @swager, many thanks for the references! I am closing this thread
