### ISSUE TITLE
Large dataset

### ISSUE THREAD

**Issue by lpereirasantos** [grf-labs/grf#658]
Hi,

I tried to run the package in a dataset with 1 million observations and 21 variables (continuous and categorical), but I was not successful. After hours of processing, it did not come to an end, including using a virtual machine, with much more memory.

Do you have any idea what may be going on? any suggestion?

Thank you!

**Comment by halflearned** [comment]
Hi @lpereirasantos. A million observations is a lot, so I wouldn't be surprised if it took many hours for the task to complete. Perhaps you could start by fitting forests with a small number of trees, and then checking how your speed and memory requirements increase? You also merge trained forests later ([reference](https://github.com/grf-labs/grf/blob/master/REFERENCE.md#merging-forests)).

**Comment by erikcs** [comment]
Hi @lpereirasantos as @halflearned says 1 million observations would be a bit much to do on a laptop. Are you using the latest version of grf? (there are some speed improvements)

Here is an example of runtime and memory use for n = 1 million and p = 25 on a machine with 24 cores and 100 G memory

```R
library(grf)
n <- 1e6
p <- 25
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
system.time(c.forest <- causal_forest(X, Y, W))
#    user    system   elapsed 
# 88138.250   471.351  4324.447  

object.size(c.forest)
# 24265631000 bytes
```
i.e. it takes just over 1 hour and requires around 25 G memory. Increasing `min.node.size` will reduce the tree depth and may give some speed improvements.

**Comment by lpereirasantos** [comment]
Hi,
Thanks for your feedback.
I am using the latest version of grf @erikcs . 

I will try to start by fitting forests with a small number of trees @halflearned , and also to use min.node.size.
