### ISSUE TITLE
Add the ability to determine what leaf nodes a test point falls in.

### ISSUE THREAD

**Issue by yifan-cui** [grf-labs/grf#661]
First, incorporate find_leaf_node function into the package.
```
find_leaf_node <- function(tree, sample) {
  node <- 1
  while (TRUE) {
    if (tree$nodes[[node]]$is_leaf) {
      break()
    }
    split_var <- tree$nodes[[node]]$split_variable
    split_value <- tree$nodes[[node]]$split_value
    if (sample[split_var] <= split_value) {
      node <- tree$nodes[[node]]$left_child
    } else {
      node <- tree$nodes[[node]]$right_child
    }
  }
  node
}
```

Second, find_leaf_node gives external numbering but s.forest$`_leaf_samples`[[1]] is internal.

**Comment by erikcs** [comment]
For 1) I think we can add a version of find_leaf_node to Analysis Tools, for 2) obtaining the leaf samples, that may be additional output. This can go towards #277

**Comment by jtibshirani** [comment]
@yifan-cui for our context it would be helpful if you could describe your overall goal/ use case for this functionality.

**Comment by yifan-cui** [comment]
Goal: For an individual tree and a given test point, it would be nice if one can identify observations associated with the leaf that includes the test point. This goes towards #277 

Currently,  the above find_leaf_node function helps to identify which leaf includes the test point. In the future, we might need a function to identify which samples are in that given leaf. 
For example, if honesty.prune.leaves is off, we can achieve this by (e.g., tree 1)
fit.forest$`_leaf_samples`[[1]][[find_leaf_node(tree, X.test)]]+1
When honesty.prune.leaves is on, we can not directly access this from `_leaf_samples` and might need something else.

**Comment by erikcs** [comment]
I forgot Julie had opened an issue for this in #275, keeping this issue and recording Julie's comment here:

> I was actually thinking that this function would return the leaf node information for the whole forest and batch of test points (similar to how get_sample_weights operates over an entire forest + test dataset). To do so efficiently and share code as much as possible, the function would call into C++.

**Comment by jtibshirani** [comment]
@yifan-cui my question was around the use case -- are you just hoping to use this information for debugging/ understanding the forest? Or would you use it as a part of some analysis?

**Comment by yifan-cui** [comment]
@jtibshirani Yes, Julie. I was thinking that this information would be helpful for debugging/understanding the forest purposes. For example, we currently need to search manually to identify leaf samples within a given node when honesty.prune.leaves is on.
As for the use part, I am not sure if this would be very useful as we are all doing kernel weighted predictions.
