### ISSUE TITLE
Quantile forest prediction should use training quantiles by default

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#667]
**Description of the bug**
If no quantiles are specified during prediction, then quantile forests default to using 0.1, 0.5, 0.9. It would be better if we used the quantiles that were used to train the forest. Otherwise, it's easy to predict at quantiles that you didn't intend to.

**Steps to reproduce**
```
X = matrix(rnorm(100*10), 100, 10)
Y = rnorm(100)
qrf = quantile_forest(X, Y, quantiles=c(0.2, 0.8))
p = predict(qrf, X)
```

Running `dim(p)` gives
> [1] 100   3

**GRF version**
1.1.0

**Comment by erikcs** [comment]
We can merge #665 and #666 , then add this?
