### ISSUE TITLE
The dataset with the treatment assigned randomly

### ISSUE THREAD

**Issue by zhong1969** [grf-labs/grf#671]
I wonder whether Casual Forest applies to the dataset with the treatment assigned randomly. I think that it does not apply but I want to get a definite answer from you. Thanks and regards

**Comment by erikcs** [comment]
@zhong1969 yes, this is fine. The identifying assumptions in grf are unconfoundedness and overlap, which both hold with random treatment assignment. https://arxiv.org/abs/1902.07409 might be of interest for you.
