### ISSUE TITLE
Web link goes to an incorrect paper

### ISSUE THREAD

**Issue by RandallJEllis** [grf-labs/grf#683]
At the bottom of https://grf-labs.github.io/grf/index.html, in the reference for "Susan Athey and Stefan Wager. Estimating Treatment Effects with Causal Forests: An Application. Observational Studies, 5, 2019. [paper, arxiv]," the "paper" link goes here: https://obsstudies.org/wp-content/uploads/2019/09/all-papers-compiled.pdf, which is not the correct paper.

**Comment by erikcs** [comment]
Thanks @RandallJEllis, I think only the issue pdf is available, the paper is on page 16 on that link.

**Comment by RandallJEllis** [comment]
Ah! :)
