### ISSUE TITLE
Formatting of GRF documentation

### ISSUE THREAD

**Issue by swager** [grf-labs/grf#688]
In some cases, the GRF reference formatting isn't quite right. For example, in https://grf-labs.github.io/grf/reference/best_linear_projection.html, the first line of text is:

"Let tau(Xi) = E[Y(1) - Y(0) | X = Xi] be the CATE, and Ai be a vector of user-provided covariates. This function provides a (doubly robust) fit to the linear model"

but the next line of text from the Roxygen documentation only follows way later, the details heading:

"tau(Xi) ~ beta_0 + Ai * beta."

It seems like the reference documentation treats the first line from the Roxygen documentation differently from the rest of the text. We should re-write the documentation so that everything makes sense when processed into the GRF reference.

**Comment by erikcs** [comment]
From http://r-pkgs.had.co.nz/man.html: 

* The first sentence becomes the title of the documentation

* The second paragraph is the description: this comes first in the documentation

* The third and subsequent paragraphs go into the details:
    This is where "tau(Xi) ~ beta_0 + Ai * beta." is placed (https://github.com/grf-labs/grf/blob/master/r-package/grf/R/forest_summary.R#L90)

(Reminder: to check the generated documentation through R studio: "Build -> Document", then `? best_linear_projection`)

**Comment by erikcs** [comment]
I have gone through the online reference at https://grf-labs.github.io/grf/reference/index.html and did not spot any more formatting mistakes.

Closing this issue, please re-open if I missed something.
