### ISSUE TITLE
Error in causal_forest(): unused argument (samples.per.cluster)

### ISSUE THREAD

**Issue by flozanor82** [grf-labs/grf#693]
**Description of the bug**
Error in causal_forest(): unused argument (samples.per.cluster)

**Steps to reproduce**
To learn, I am using your code for replicating the exercise and after applying it to my data as in https://github.com/grf-labs/grf/blob/master/experiments/acic18/script.R. When running lines 52-56:

cf = causal_forest(X[,selected.idx], Y, W,
                   Y.hat = Y.hat, W.hat = W.hat,
                   clusters = school.id,
                   samples.per.cluster = 50,   
                   tune.parameters = "all")

I get the following error:
'Error in causal_forest(X[, selected.idx], Y, W, Y.hat = Y.hat, W.hat = W.hat,  : 
  unused argument (samples.per.cluster = 50)'

I found in the documentation ([Cluster Std.Err](https://grf-labs.github.io/grf/REFERENCE.html#cluster-robust-estimation)), a reference to the currently available options, and explains that the draw is the total sample within cluster. However, it still makes the case that the argument, samples.per.cluster, can be used. 

I cannot use the option, and I was wondering if it was a bug or an error in my code.
Thanks :)

**GRF version**
1.1.0

**Comment by erikcs** [comment]
Thanks @flozanor82 , the `samples.per.cluster` cluster option was removed in grf version 1.0. We have updated the script to remove this option in #694.
