### ISSUE TITLE
causal_forest with categorical outcomes

### ISSUE THREAD

**Issue by jgellar** [grf-labs/grf#698]
I have an outcome with 3 categories, and a binary treatment variable. Do you have a suggestion as to how I can estimate (a) the marginal probabilities of ending up in each outcome category (with SEs) under both treatments, and (b) the marginal effects for each outcome category?

More specifically I want:

(a) Pr(Y=k|T=0) and Pr(Y=k|T=1) for k \in {1,2,3}, along with standard errors (confidence intervals) around these probabilities
(b) \tau_k = Pr(Y=k|T=1) - Pr(Y=k|T=0) for k \in {1,2,3}

I can think of two potential ways to do this using causal_forest:

(1) Fit a separate model for each outcome category, i.e. define a binary outcome $Y_{ik}$ that is 1 if $Y_i = k$, and 0 otherwise, and then fit the 3 binary forests. Or fit just two of them, with one being the "reference" level. The problem is that since the trees are optimized separately you could get weird results (e.g., $Pr(Y=1) + Pr(Y=2) > 1$).
(2) Fit a model for $Pr(Y\in {2,3}|X,T)$, and then fit a model for $Pr(Y=3 | Y\in {2,3},X,T)$. But I don't think there's a clean way to get the uncertainty estimates in this case.

If there's a built-in way to do this using causal_forest that I'm missing, please let me know!

**Comment by swager** [comment]
That's a great question. Currently, we don't have specific support for this workflow, so the best thing to do is presumably something like (1). We also do something similar in the `multi_causal_forest` function in <a href="https://github.com/grf-labs/policytree">policytree</a>.

We're working on adding built-in support for multiple outcomes and treatments, though. So hopefully in the longer term we'll have a better answer to this.

**Comment by erikcs** [comment]
Closing this as multiple outcomes and categorical treatments is now available in GRF 2.0: https://grf-labs.github.io/grf/reference/multi_arm_causal_forest.html
