### ISSUE TITLE
Leaf nodes information and outcome probability estimation

### ISSUE THREAD

**Issue by CarolienMaas** [grf-labs/grf#699]
Hi!

I’m currently using causal_forest to estimate heterogeneous treatment effect. 

I am wondering whether it is possible to output the observations in each leaf node such that the outcome probability of an observation P(Y=1|W, X) can be calculated?

As far as I know, currently predict.causal_forest only supports treatment effect estimation E(Y(1)-Y(0)|X=x). However in some applications, e.g. simulation of the outcome and treatment effect, it is useful to obtain the outcome probability from the causal forest.

I’ve looked at the function leaf_stats.causal_forest, but it only seems to output the outcome vector for the full tree. I’m searching for a functionality that outputs the observations of each leaf node.

Thank you in advance.

**Comment by erikcs** [comment]
There is currently no functionality for querying nodes based on a test sample (feature issue #661), but you can manually inspect leaf samples with the output from [get_tree](https://grf-labs.github.io/grf/reference/get_tree.html) (see details about the "samples" attribute).

```R
set.seed(1)
n <- 100
p <- 1
X <- matrix(rnorm(n * p), n, p)
X.test <- matrix(0.5, 1, 1)
Y <- X[, 1] * rnorm(n)
r.forest <- regression_forest(X, Y, num.trees = 1, ci.group.size = 1)

tree <- get_tree(r.forest, 1)
plot(tree)
# X.test falls into node 9
tree$nodes[[9]]$samples
# [1] 73  7 43
predict(r.forest, X.test)
#  predictions
#1  -0.1773265
mean(Y[tree$nodes[[9]]$samples])
#[1] -0.1773265
```

**Comment by CarolienMaas** [comment]
Thank you very much. That helped me a lot.

**Comment by swager** [comment]
In terms of how to estimate mu(x, 1) = E[Y | X, W = 1]: Causal forests start by first estimating m(x) = E[Y | X = x] and e(x) = E[W | X = x], and only then proceed to CATE estimation. It's possible to estimate mu(x, 1) by stitching together these different subcomponents; see, e.g., equation (8) in https://arxiv.org/pdf/1902.07409.pdf.

**Comment by CarolienMaas** [comment]
Thank you for your response.

I see that mu(x, 1) = E[Y | X, W = 1] = E[Y, W=1 | X] / E[W=1 | X], thus a division of m(x, 1) and e(x, 1) in some sense.

However, I am confused about the following:
1. How to obtain m(x, 1) = E[Y, W=1 | X=x] from m(x) = E[Y | X=x], because m(x) doesn’t use the treatment assignment information (W)?
2. To obtain e(x, 1) = E[W=1 | X=x] from e(x) = E[W | X=x], can I use the predictions of the e(x)? Thus W.hat in algorithm 1 of the paper ‘Estimating Treatment Effects with Causal Forests: An Application’?

Thank you very much for your help.

**Comment by erikcs** [comment]
@CarolienMaas we added an example explaining this to the grf tutorial collection:

https://grf-labs.github.io/grf/articles/muhats.html

Please let us know if it is clear.

**Comment by CarolienMaas** [comment]
Thank you very much! 

It is clear. This helped me understand how to compute mu(x, 1) and mu(x, 0).

**Comment by CarolienMaas** [comment]
Hi all!

I have one more question concerning this topic.

My dependent variable Y is binary, thus mu(X, W) is interpreted as the probability that Y = 1 given X and W, which naturally can’t be smaller than 0 or larger than 1. 

However, for example, mu.hat.0 <- Y.hat – W.hat * tau.hat does occasionally fall outside the [0, 1] range.

What could be an easy solution to this? Could I apply some transformation to mu.hat, e.g. log-odds, to ensure that it falls in the [0, 1] range?

Thank you in advance.

**Comment by swager** [comment]
Yes that is a shortcoming of this approach. Here, we reverse-engineered mu.hat.w so that mu.hat.1 - mu.hat.0 = tau.hat. If you transform the mu.hat (e.g., by clipping at [0, 1]) that would make the mu.hat estimates themselves better, but you'd lose the property that mu.hat.1 - mu.hat.0 = tau.hat.

**Comment by CarolienMaas** [comment]
Okay, thank you for your response.
