### ISSUE TITLE
Question - Variable selection 

### ISSUE THREAD

**Issue by eliormi** [grf-labs/grf#705]
Hi, 
My question is about the true meaning behind the usage of variable selection in Causal_Forests.

In the paper "Estimating Treatment Effects with Causal Forests: An Application (Athey & Wager (2019)" a two stage causal forest was built, 

- In the first stage a causal forest with default parameters and all the variables in X 
- In the second stage a causal forest with some parameter tuning and a subset of variables from X that had Variable-Importance(Xj) > mean(Variable-Importance(X)) from the first stage.
In the paper the reason was specified as "improved performance".

**_My question is_**  - does the variable selection is needed for the validity of the statistical inference (confidence intervals, etc...)?
more precisely is the variable selection is a way of enforcing that  "The leaves of the tree become small in all dimensions of X"(definition 3 in "Estimation and Inference of Heterogeneous Treatment Effects using Random Forests (Wager & Athey (2018)" )
By giving the Causal_Forest only variables that have reasonable probability of being chosen as a splitting variable? or does the algorithm enforce that in a different manner and the variable selection is only for improved precision of estimation and performance?

In "Wager & Athey (2018)" the validity of Random Forest statistical inference is limited to forests that keep 5 rules.
In simple words as I understand them the 5 rules are:

1.  We assume that the random forest is built with large enough B (Number of trees in the forest).
2. The trees that we build the forest with are "honest".
3. Each split leaves at least a fraction "alpha" of the training data in each side of the split 
4. Each tree results are independent of the order of the observations in the training data.
and 
5. "The leaves of the tree become small in all dimensions of X"  -- maybe I misunderstood this, but to me this means that each explanatory variable in the matrix X, can be chosen (with a large enough probability) as the splitting variable for the trees of the random forest.
the formal definition for satisfying this rule is : 
![image](https://user-images.githubusercontent.com/44525997/87871327-10213a80-c9b8-11ea-9ad9-d52b1acd5656.png)

**Comment by erikcs** [comment]
@eliormi the paper mentions this is done to enable the forest to place more splits on important features in low-signal data.
