### ISSUE TITLE
Confusion Regarding "tune.parameters"

### ISSUE THREAD

**Issue by aruniz** [grf-labs/grf#706]
The parameter tuning section has little conflicting details mentioned in two sources. Would be good to get clarification on the 
'tune.num.trees' and 'tune.num.reps' parameters.

The parameter tuning section in **_algorithm reference_**(https://grf-labs.github.io/grf/REFERENCE.html#parameter-tuning)
"For tuning to be computationally tractable, we only train ‘mini forests’ composed of 50 trees (tune.num.trees). With such a small number of trees, the out-of-bag error gives a biased estimate of the final forest error. We therefore debias the error through a simple variance decomposition."

However the **_cran GRF PDF_** (https://cran.r-project.org/web/packages/grf/grf.pdf) has two distinct parameters - 
tune.num.trees ="The number of trees in each ’mini forest’ used to fit the tuning model. Default
is 200."
tune.num.reps=" The number of forests used to fit the tuning model. Default is 50."

1. It is not clear if for each set of parameter values, the algorithm builds a forest consisting 50 trees or 200 trees ?
2. Also, tune.num.reps has no mention in algorithm reference , how is  this playing a role in tuning.
(my use case concerns causal forest)

**Comment by erikcs** [comment]
The algorithm reference explains `tune.num.trees` and  `tune.num.reps` or am I misunderstanding something? If `tune.num.trees` is 200 each forest consists of 200 trees. If `tune.num.reps` is 50 then 50 random forests are fit to a random grid of 50 parameter values.

**Comment by aruniz** [comment]
Hi Erikcs,

attaching two screen shots from two different documentations of causal forest . Let me know your view after going through these screens.

<img width="1427" alt="Screenshot 2020-07-26 at 4 01 45 PM" src="https://user-images.githubusercontent.com/17499433/88476908-9958e400-cf59-11ea-8f17-63352298d242.png">

<img width="925" alt="Screenshot 2020-07-26 at 4 00 55 PM" src="https://user-images.githubusercontent.com/17499433/88476912-9bbb3e00-cf59-11ea-8235-b95bed17190c.png">


By these two documents , it is not clear what is the default value of tune.num.trees ( 50 or 200)

**Comment by erikcs** [comment]
The default is what is stated in the function reference. Regression forest default is [50](https://grf-labs.github.io/grf/reference/regression_forest.html). Causal forest default is [200](https://grf-labs.github.io/grf/reference/causal_forest.html)

**Comment by jtibshirani** [comment]
I can see why this is confusing, perhaps we could change the algorithm reference to say "For tuning to be computationally tractable, we only train 'mini forests' composed of a small number of trees (`tune.num.trees`)".
