### ISSUE TITLE
Multi-class probability estimation

### ISSUE THREAD

**Issue by swager** [grf-labs/grf#708]
It would be useful to have a method for multi-class probability estimation. We could use that, for example, for propensity score estimation in `multi_causal_forest` in `policytree`.

One thing to note here is that we already have a ProbabilitySplittingRule implemented in the package (we use it for quantile forests), and this splitting rule accommodates the multi-class setting. So we wouldn't need to write a new splitting rule in order to allow for multi-class probability estimation forests.

**Comment by erikcs** [comment]
a) For splitting: do we simply do ProbabilitySplitting on the class label Yi : [0, 1, ..., num_classes-1]? or on pseudo outcomes based on some score function?

b) For the predictions: do we simply predict the forest weighted class probabilities for each sample? As in:

```
// Prediction for sample i:
// Input: 
// weights_by_sample<size_t, double> : forest weight for all neighbors of sample i
// num_classes : number of classes in Y
// output: num_classes sized vector of predictions of class probabilities
vector<double> predictions(num_classes)
for (entry : weights_by_sample) {
  sample = entry.first
  forest_weight = entry.second
  sample_class = Y[sample] // relabeled to [0, 1, ..., num_classes-1]
  predictions[sample_class] += forest_weight // (potentially adjusted by a sample_weight as well?)
}
return predictions
```

c) The way ProbabilitySplitting is implemented all num_classes is looped over in every split node, with very many classes there may be a moderate speedup by only considering num_classes_in_current_node

**Comment by erikcs** [comment]
- [ ] `probability_forest(X, Y)` is added in #711
- [ ] Update `ProbabilitySplittingRule` to only consider num_classes_in_current_node:

**Comment by erikcs** [comment]
Closing this as we keep an overview of this + more in #733.
