### ISSUE TITLE
Fixed effects 

### ISSUE THREAD

**Issue by athammad** [grf-labs/grf#713]
Hi guys,

first of all, thank you very much for your great work.
I have been reading your papers, the algorithm references, the past issues and tried your library but I am still struggling with the idea of fixed effects. While I understand and I agree that it doesn't make sense to apply one hot encoding on time variables (time-fixed effect), I would appreciate some guidance on how to deal with say city-fixed effects. 
In the documentation, you suggest to transform the variable in a way that the model can take advantage of the spatial relation between the observations (closer and further cities), but what if we do not have such information? What if the variable is a simple indicator of each city? One hot encoding the variable sims reasonable and required in a purely OLS approach, but things are differente with GRF. Moreover, in many cases, omitting fixed effects can cause the estimation to be completely different (magnitudine and direction of the effect)  in both OLS and GRF. 

More guidance on this issue would be greatly appreciated.

Best regards

**Comment by erikcs** [comment]
@athammad GRF is a non-parametric estimator and so the term "fixed-effect" from linear models does not really carry over an analogous meaning here (see for example https://github.com/grf-labs/grf/issues/631#issuecomment-600737559). 

As you mention, for categorial inputs the factor encoding is a modeling choice (https://grf-labs.github.io/grf/REFERENCE.html#categorical-inputs):

>For example, numbering contiguous geographical areas sequentially can often help forests make splits that group nearby areas together. If geographical proximity is important, the forest performance will likely increase.

if you have an indicator variable for each city and wanted to follow the above suggestion you would have to do that yourself using a data set of city borders/or similar, no?

**Comment by athammad** [comment]
Hi @erikcs ,

Thank you for your reply. I have managed to get the coordinates of the cities that I am working on. Any raccomandation on using this variables in grf?

**Comment by swager** [comment]
One simple approach would be to, say, record the latitude, longitude, and population of each city. Then you could pass those predictors as-is to GRF (i.e., if person i lives in city j, then you augment the feature set of person i using the latitude, longitude, and population of city j).
