### ISSUE TITLE
A "naive" approach using grf is to one-hot encode each treatment and fit k separate causal forests, one for each treatment (a package for doing this will soon be available in grf-labs).

### ISSUE THREAD

**Issue by mochithegato** [grf-labs/grf#714]
Hello, was the package mentioned in the post ever released?

A "naive" approach using grf is to one-hot encode each treatment and fit k separate causal forests, one for each treatment (a package for doing this will soon be available in grf-labs).

In the meantime, you can do this yourself if you wish. The steps are described in this paper https://arxiv.org/abs/1810.04778: page 36 (section 6.4.2). An example:

```R
library(grf)
n <- 500
p <- 10
treatments <- c(1, 2, 3, 4)
X <- matrix(rnorm(n * p), n, p)
W <- sample(treatments, n, replace = TRUE)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)

Y.hat <- predict(regression_forest(X, Y))$predictions # these are the mean rewards mu on page 36
W.onevsall <- sapply(treatments, function(treatment) as.integer(W == treatment))
W.hat <- apply(W.onevsall, 2, function(Wi) predict(regression_forest(X, Wi))$predictions) # treatment propensities for each action
multi_causal_forest <- lapply(1:length(treatments), function(i) {
  causal_forest(X, Y, W.onevsall[, i], Y.hat, W.hat[, i]) # k separate causal forests
})

# tau.hats for treatment 1...4 (tau_a page 37)
prediction.objects <- sapply(multi_causal_forest, predict)
tau.hats <- data.frame(prediction.objects["predictions", ])
colnames(tau.hats) <- make.names(treatments)
head(tau.hats)
        X1         X2        X3        X4
1 -0.3262252 -0.1248584 0.1392025 0.3327248
2 -0.7172470 -0.2034654 0.2476034 0.6399697
3 -2.1749475 -0.3442007 0.2859436 2.1082174
4 -1.1429245 -0.2364281 0.2761516 1.2696782
5 -0.2221472 -0.2091747 0.1934955 0.4105628
6 -1.4539585 -0.1098223 0.3530950 1.2250981
```

_Originally posted by @erikcs in https://github.com/grf-labs/grf/issues/559#issuecomment-548576447_

**Comment by erikcs** [comment]
Yes, it is available here: https://github.com/grf-labs/policytree

**Comment by erikcs** [comment]
Hi,

With categorical categorical treatments, policytree can estimate CATEs for
the different treatment arms. There are some introductory examples here:
https://grf-labs.github.io/policytree/articles/policytree.html. We have not
added summary functions yet, more of that can be expected when we have come
further along with multivariate treatments in GRF.
