### ISSUE TITLE
Comparing performance across models

### ISSUE THREAD

**Issue by dsantamaria94** [grf-labs/grf#715]
We are trying to compare the performance of different causal forests where the data and all parameters are the same, but we change the vector of covariates.

We understand that since we do not know the true CATE for each observation, it is not feasible to use standard measures such as MSE or R2 to compare models and evaluate their performance.

One possibility that we considered is using the omnibus test (as defined in Athey & Wager, 2019), but it is not clear whether this provides a one-dimensional measure of performance. We could look, for example, at how close the coefficient of Di is to 1 in absolute value, or choose the model with the smallest p-value. Would the omnibus test work for this purpose, and if yes do you have suggestions on how to interpret it?

Alternatively, (a) are there other measures we could use to compare models and (b) is there a way to quantitatively tell how much a model is improving (eg when adding an additional covariate)? Any input would be greatly appreciated.

Thanks in advance!

**Comment by erikcs** [comment]
Hi, a simple way to gauge whether a covariate matters or not is to look at [variable_importance](https://grf-labs.github.io/grf/reference/variable_importance.html).

**Comment by swager** [comment]
This paper, https://arxiv.org/pdf/1712.04912.pdf, discusses that "R-loss" as a means to evaluate the accuracy of different CATE predictions. This is what we use for tuning causal forests.

Alternatively, if you're in an RCT, you could also use the approach taken in equation (13) of this paper, https://arxiv.org/pdf/1807.11408.pdf, for evaluation.
