### ISSUE TITLE
Estimating overlap-weighted LATE for instrumental forest

### ISSUE THREAD

**Issue by NadjaUvA** [grf-labs/grf#716]
Good afternoon,

I have a question concerning the (local) average treatment effect in case of the instrumental forest. I am applying the instrumental forest using clustered data with a continuous treatment variable W, continuous instrument Z and a continuous dependent variable Y. Currently, the grf package allows for estimation of the local average treatment in case of binary treatment variables and not for continuous treatment variables. Furthermore, I would like to implement the overlap-weighted version of the treatment effect, since the propensity scores are not uniformly distributed between [0,1]. I wondered whether the overlap-weighted (local) average treatment effect in case of a continuous treatment variable and clustered data can then be estimated as follows:

instf <- instrumental_forest(X, Y, W, Z, Y.hat = Y.hat, W.hat = W.hat, Z.hat = Z.hat, clusters = states)
Z.residual <- Z - Z.hat
Y.residual <- Y - Y.hat
tau.ols <- lm(Y.residual ~ Z.residual, weights = observation_weights(instf))
tau.est <- coef(summary(tau.ols))[2, 1]
tau.se <- sqrt(sandwich::vcovCL(tau.ols, cluster = instf$clusters)[2, 2])
ATE <- c(tau.est, std.err = tau.se)

I would appreciate your help. Thank you for your time.

**Comment by swager** [comment]
@NadjaUvA, I'm not aware of a concrete proposal for an overlap-weighted local average treatment effect in the literature. This sounds like a useful thing to have, but may first require some research into what the a good definition is.

One simple thing you could do is just run 2SLS on all the data with outcome Y - Y.hat, treatment W - W.hat and instrument Z - Z.hat. At least algorithmically, this is a natural analogue to the residual-on-residual regression estimator we use for the overlap weighted treatment effect under unconfoundedness.

**Comment by halflearned** [comment]
Closing this issue as the question seems to have been answered. Please feel free to re-open if you have follow-up questions.
