### ISSUE TITLE
Request for replication codes in Athey & Imbens 2016

### ISSUE THREAD

**Issue by ellenxtan** [grf-labs/grf#718]
I know this is not a good place to ask, but it seems the GitHub repo for the causalTree hasn't been updated for a long time. I was wondering if the simulation codes in Athey & Imbens 2016 could be uploaded to see the details of the experiments? I really appreciate your help!

**Comment by swager** [comment]
The experiments in Athey & Imbens 2016 were based on a different code base, and so aren't part of GRF. The issue you opened on causalTree is the right place to ask.
