### ISSUE TITLE
Calculating risk ratio

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#720]
Hi

I have a binary treatment (Y) and a binary treatment (T), and a set of covariates (X). Assuming equal weights, I would like to calculate the risk ratio a/b, where $a=E[Y|T=1, X]=Pr[Y=1|T=1, X]$ and $b= E[Y|T=0, X] = Pr[Y=1|T=0, X]$. However, grf only gives me $\tau$ (i.e., a - b), the difference between potential outcomes. Is there a way around this?

**Comment by swager** [comment]
GRF doesn't handle this natively. What you could do (and what we do for functions like `average_treatment_effect`) is to first estimate E[Y|T=1, X] as E[Y|X] + (1 - P[W|X) tau(X), or, in terms of package notation, Y.hat + (1 - W.hat) * tau.hat, etc., and then read off the risk ratio from those. What we don't have, though, is a forest construction that directly targets the risk ratio.

**Comment by shibakoichiro** [comment]
Hi Dr. Wager,

Thanks for suggesting the potential solution to our problem. If I understood what you wrote correctly, the way back-calculate the E[Y|W=w, X] for each treatment arm W=w is the following: 

E[Y| W=1, X] = tau.hat + y.hat/(1-w.hat), E[Y|W=0.,X] = y.hat/w.hat - tau.hat

We can take ratios of these two sets of conditional expected values of the binary outcome Y and assess heterogeneity in causal risk ratios, but what if we want to estimate ATT in the risk ratio scale? I assume a point estimate would simply be an average but is there a way to compute associated SEs?

**Comment by shibakoichiro** [comment]
Hi Dr. Wager,

Thanks for the solution and I was able to compute the risk ratios based off the formula you suggested. One remaining question I have is whether grf can compute standard errors for the conditional risk ratios or ATT in the risk ratio scale.

**Comment by adeldaoud** [comment]
Thanks @swager ! I am seconding @shibakoichiro questions about calculating the SE. If I recall some earlier exchange we had, then it is not entirely correct to calculate the SE from the predicted empirical distribution, right?

**Comment by swager** [comment]
The short version is that, currently, GRF doesn't have functionality that enables simple SE calculations for the risk ratio. Sorry.

**Comment by adeldaoud** [comment]
@swager , ok thanks for letting us know. To question or confirm my current understanding, the reason why we cannot calculate the SEs (for either tau at the probability scale or RR scale) from the predicted empirical distribution is that this predicted distribution does not account for the uncertainty in each individual prediction?

**Comment by agentzel** [comment]
> GRF doesn't handle this natively. What you could do (and what we do for functions like `average_treatment_effect`) is to first estimate E[Y|T=1, X] as E[Y|X] + (1 - P[W|X) tau(X), or, in terms of package notation, Y.hat + (1 - W.hat) * tau.hat, etc., and then read off the risk ratio from those. What we don't have, though, is a forest construction that directly targets the risk ratio.

I'm also trying to calculate risk ratios from the output of causal_forest, and I'm not following how you got that E[Y|T=1, X] = E[Y|X] + (1-P(W|X))*tau(X).  Could you explain where that comes from?

(And then is E[Y|T=0,X] = E[Y|X] + P(W|X)*tau(X) ?)

**Comment by erikcs** [comment]
> > GRF doesn't handle this natively. What you could do (and what we do for functions like `average_treatment_effect`) is to first estimate E[Y|T=1, X] as E[Y|X] + (1 - P[W|X) tau(X), or, in terms of package notation, Y.hat + (1 - W.hat) * tau.hat, etc., and then read off the risk ratio from those. What we don't have, though, is a forest construction that directly targets the risk ratio.
> 
> I'm also trying to calculate risk ratios from the output of causal_forest, and I'm not following how you got that E[Y|T=1, X] = E[Y|X] + (1-P(W|X))*tau(X). Could you explain where that comes from?
> 
> (And then is E[Y|T=0,X] = E[Y|X] + P(W|X)*tau(X) ?)

tau(X) := E[Y(1) - Y(0) | X]
P[W | X] := E[W | X]

E[Y | X] := E[Y(0) | X) + E[W * (Y(1) - Y(0)) | X]
which given unconfoundedness is equal to
= E[Y(0) | X) + P[W | X] * tau(X)

https://grf-labs.github.io/grf/articles/muhats.html

**Comment by halflearned** [comment]
Please re-open if you have follow-up questions.

**Comment by yujias424** [comment]
Can a similar approach be used in the continuous treatment case?
