### ISSUE TITLE
Use expect_equals in testing

### ISSUE THREAD

**Issue by swager** [grf-labs/grf#722]
In testing, when we're checking that two numbers `a` and `b` match up to some tolerance, we should use commands like `expect_equal(a, b, tolerance = 0.01)` instead of `expect_true(abs(a - b) <= 0.01)`, as this enables more transparent error messages and debugging. There are many examples of the latter idiom in, e.g., `test_average_effect.R`.

```R
> library(testthat)
> a = 1.15; b = 1.1
> expect_equal(a, b, tolerance = 0.01)
Error: `a` not equal to `b`.
1/1 mismatches
[1] 1.15 - 1.1 == 0.05
> expect_equal(a, b, tolerance = 0.1)
> expect_true(abs(a - b) <= 0.01)
Error: abs(a - b) <= 0.01 isn't true.
```

**Comment by erikcs** [comment]
On a related note a future test cleanup can also swap out `testthat` with the zero dependency alternative [tinytest](https://cran.r-project.org/web/packages/tinytest/index.html).

**Comment by erikcs** [comment]
Taken care of in #865.
