### ISSUE TITLE
causal forest - Understanding the output, what are pv_values? and a question on variable interactions.

### ISSUE THREAD

**Issue by yjacoby** [grf-labs/grf#727]
Hi, 

I am new to using the grf package and am trying to understand the causal forest algorithm. 

Looking at the causal forest object, what are the "_pv_values"? 

A second question is, other than variable importance, can the causal forest also highlight the most 'important' variable interactions? 

Thank you in advance

**Comment by erikcs** [comment]
Hi @yjacoby, all the attributes with an underscore are internal forest data structures not meant to be accessed by the user (_pv_values are stored prediction values), you can see available functions [here](https://grf-labs.github.io/grf/reference/index.html)

**Comment by yjacoby** [comment]
Thank you so much for your quick response @erikcs. 

In regards to my second question, while predictions from a causal forest give us the treatment effect for each individual with variance estimates. I was wondering if there is a way to gain standard errors and variance estimates on the coefficients of  interactions? For example if there are two covariates the coefficient, x_1* x_2 * Treatment? Of course in my case there are more than two covariates so the process of discovering the important interactions is a little more involved. 

Apologies if my question is unclear.

**Comment by yjacoby** [comment]
I have found that this topic was discussed in the thread : #238 

Thank you for all of your help.
