### ISSUE TITLE
Estimating ATE and ATT using local linear forests

### ISSUE THREAD

**Issue by athammad** [grf-labs/grf#736]
Since local linear forests are an improvement over regular random forests I wonder if there is a way to use `ll_regression_forest` to estimate treatment effects (ATE, ATT and CATE).

Thanks

**Comment by swager** [comment]
Some things that are already in the package that you could use to support this workflow are:
- You can fit local linear regression forests to get predictions `W.hat` and `Y.hat` that can be passed to the causal forest.
- When predicting with a causal forest, you can use `linear.correction.variables` to run prediction in LLF-mode (i.e., the forest is grown as a usual causal forest, but at prediction time we run local linear regression along the given variables).

We do not currently have an API for doing this via the ATE function, but you can get a doubly robust ATE estimate by following what's done in `get_scores_ATE`.

**Comment by erikcs** [comment]
If there is interest in adding support for this then one could add a "dots" (`...`) argument to `average_treatment_effect` which passes on the dots to all other function taking dots in this method, like `predict`. One could then do `average_treament_effect(causal.forest, linear.correction.variables = c(1, 2))`. 

(Note: the function `get_scores_ATE` mentioned above is available in the development version of grf ( > v 1.2.0))

**Comment by halflearned** [comment]
Closing this for now, as the feature is available as described above. We can revisit this if there's demand for a separate feature.

**Comment by athammad** [comment]
hi guys,

I am coming back on this one because I would like to know if there is any plan to implement the suggestion of @erikcs. This would help to create consistency and facilitate the use of LLF in causal inference.
Alternatively, I would appreciate some guidance on how to retrieve the ATE and the corresponding `std.err` in the right way (I am still a bit confused about this).
Below is a little example that I have been working on. 

Thank you very much. 
Best wishes

```
library(grf)
library(glmnet)
#GRF example
set.seed(1)
n = 8000; p = 8
X = matrix(rnorm(n * p), n, p)
L = 2 / (1 + exp(5 * X[,1] + 5 * X[,2]))
W = L + rnorm(n)
Y = 0.75 * W - 1.6 * L + rnorm(n)

forest.W <- ll_regression_forest(X, W, enable.ll.split = TRUE,
                                 num.trees = 4000,# increase trees for variance calculation
                                 ll.split.weight.penalty = TRUE)
W.hat <- predict(forest.W)$predictions
forest.Y <- ll_regression_forest(X, Y, enable.ll.split = TRUE,
                                 num.trees = 4000,# increase trees for variance calculation
                                 ll.split.weight.penalty = TRUE)
Y.hat <- predict(forest.Y)$predictions

# Select covariates 
lasso.mod <- cv.glmnet(X, Y, alpha = 1)
lasso.coef <- predict(lasso.mod, type = "nonzero")
selected <- lasso.coef[,1]
selected

tau.forest <- causal_forest(X, Y, W,
                            W.hat = W.hat, Y.hat = Y.hat,
                            tune.parameters = "all")

preds.llf <- predict(tau.forest, linear.correction.variables =selected,ll.weight.penalty = TRUE,estimate.variance = TRUE)
preds.llf

#### average treatment effect & std.err from LLF?


```

**Comment by erikcs** [comment]
Hi @athammad, you can see how to construct doubly robust scores for causal forest here: https://github.com/grf-labs/grf/blob/master/r-package/grf/R/get_scores.R#L47
