### ISSUE TITLE
Make separate predictions for each tree in a causal forest model

### ISSUE THREAD

**Issue by ellenxtan** [grf-labs/grf#737]
Hi! Thanks for making this great package.

I was wondering if it is possible to get predictions for a single tree extracted from the causal forest model? Below are the codes I use:
`library(grf)`
`n <- 2000`
`p <- 10`
`X <- matrix(rnorm(n * p), n, p)`
`X.test <- matrix(0, 101, p)`
`X.test[, 1] <- seq(-2, 2, length.out = 101)`
`W <- rbinom(n, 1, 0.4 + 0.2 * (X[, 1] > 0))`
`Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)`
`tau.forest <- causal_forest(X, Y, W)`
`single.tree <- get_tree(tau.forest, 1)`
`predict(single.tree)`
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "grf_tree"`

If possible, could you kindly correct me or maybe point me in another direction? 
Thank you so much! Appreciate it.

**Comment by erikcs** [comment]
Hi @ellenxtan, if you want you predict with only one tree, you can fit the causal forest with only one tree (using the `num.trees` argument).

**Comment by ellenxtan** [comment]
Hi! Thanks for your response. I would like to predict every tree in my fitted forest. Is there a way to do this? Thank you!

**Comment by erikcs** [comment]
No, sorry, this vignette might also be useful:

https://grf-labs.github.io/grf/articles/visualize_tree.html

**Comment by ellenxtan** [comment]
Thank you for pointing me to somewhere I didn't think about before!

Just one more very quick question, for my purpose, could I fit B causal forests, each with num.trees=1, to resemble a causal forest with B trees? In that sense, it seems I would be able to get predictions for each forest respectively. 
Thank you so much for your patience!

**Comment by erikcs** [comment]
No, that will not be the same, GRF uses the forest weights as kernel weights in estimating the CATEs. The kernel weight for sample x is a function of how many trees the training samples falls into the same leaf as x, see section 2.1 in https://arxiv.org/pdf/1610.01271.pdf

**Comment by ellenxtan** [comment]
Really appreciate your help!
