### ISSUE TITLE
Different types of response variables

### ISSUE THREAD

**Issue by palmierieugenio** [grf-labs/grf#744]
I think an interesting integration would be to support different types of response variables or treatments, as suggested [here](https://github.com/grf-labs/grf/issues/698).

I see that at the moment you support continuous response variables Y and binary or categorical treatments W.

I think some useful outcome variables are: binary, count data, fractional, bounded variables. A particular interest could be put on zero-inflated variables, which are very common, but often neglected.
I suggest you give a look at [A Random Forest Approach for Modeling Bounded Outcomes](https://arxiv.org/pdf/1901.06211.pdf), which could give you some indications on how to solve this problem for fractional and bounded outcome variables. There is also an implementation of the beta Random Forest in the package [ranger](https://cran.r-project.org/web/packages/ranger/).

I think also some work on continuous treatments could be useful. Also here some attention on the appropriate distribution for the treatment could be appropriate: it's frequently the case of zero-inflated and/or strictly positive treatments.

Thank you for your work.

**Comment by erikcs** [comment]
Thanks for the suggestions @palmierieugenio, multiple categorical treatments and multiple continuous treatments are work in progress (#733). Binary or continuous treatment is already supported.

**Comment by palmierieugenio** [comment]
One simple approach for zero inflated continous outcome variables could be to estimate two separate models: one binary model for P(Y=0) on the full data and one continous model for E(Y|Y≠0) on the data with values different from zero. A similar logic could be applied to zero inflated continous treatments variables.

For other types of variables, maybe boosting could be a good option to find black box reliable algorithms already implemented. For example packages like [mboost](https://cran.r-project.org/web/packages/mboost/index.html). It seems like there has been more research on different families of variables with Boosting than Random Forest. Of course they would need a "causal modification" too, but at least the base algorithm exist and I am not sure the same is true for Random Forest at the moment, but I could be wrong.

**Comment by palmierieugenio** [comment]
The [distRforest package](https://github.com/henckr/distRforest) seems relevant, with implementations of Random Forest for count data (Poisson), Survival (exponential scaling) and long-tailed data ( gamma or log-normal distribution), and also the [mobForest package](https://cran.r-project.org/web/packages/mobForest/) with implementations of Random Forest for Poisson and Binomial data.

**Comment by erikcs** [comment]
Thanks @palmierieugenio, we recently added a survival forest (currently only in the development version) for estimating treatment effects in survival data. I am unsure about development priority for generic forest types that are not directly required (for example in nuisance estimation) for targeting some parameter of interest using the [grf framework](https://arxiv.org/pdf/1610.01271.pdf).

**Comment by hakianmehr** [comment]
How to set up the "casual_forest" and "find_best_tree" functions for categorical response variable (Y=0,1)?

**Comment by palmierieugenio** [comment]
> I am unsure about development priority for generic forest types that are not directly required (for example in nuisance estimation) for targeting some parameter of interest using the grf framework.

@erikcs , I am not sure I understand this sentence, but I try to answer.

I expect that a standard random forest would usually give reasonable results even when used with different kinds of response variable (for example count data), but I also expect that using more reasonable assumptions (for example variants of the random forest specific for count data) would generally improve the results and be more reliable. I expect the same is true for causal forest: it is probably not essential to have support for a specific distribution, but it is better to have it. I would give priority to the most common distributions.

**Comment by erikcs** [comment]
@palmierieugenio [generalized random forests](https://arxiv.org/abs/1610.01271) provide a forest-weighted fit to an estimating equation, in the case of causal forest this takes the form of a local linear regression of the outcome on the treatment (example 6.1 in https://arxiv.org/pdf/1610.01271.pdf) - if you have an outcome type that dictates a different estimating equation (odds ratio for example), you can target this parameter with GRF by creating a new forest where you specify the pseudo-outcomes (influence function of your estimating equation), the are some resources for creating a custom forest in the docs: https://grf-labs.github.io/grf/DEVELOPING.html#creating-a-custom-forest. The first draft of the GRF paper may also be easier to read: https://arxiv.org/abs/1610.01271v1 if you want a better overview of GRFs. Feel free to ask for help if you want to try and create your own custom forest.
