### ISSUE TITLE
average_treatment_effect() with small subsets

### ISSUE THREAD

**Issue by bakered** [grf-labs/grf#745]
**Description of the bug**
The output of the average treatment effect function for small subsets is often far away from the naive mean of the pointwise predictions of the causal forest.

**Steps to reproduce**
```
library(grf)
library(ggplot2)
set.seed(1)
n = 1000; p = 5
X = matrix(rnorm(n*p), n, p)
W = rbinom(n, 1, 0.5)
Y = W + rnorm(n)
forest = causal_forest(X, Y, W)

rand.sample = sample(1:n, n/10)
preds = predict(forest, estimate.variance = TRUE)[rand.sample,1:2]
preds$variance.estimates = sqrt(preds$variance.estimates)
colnames(preds)[2] = "Std.err"
func.output = average_treatment_effect(forest, subset = rand.sample)
preds = rbind(preds, func.output)
preds$type = c(rep("Individual Treatment Effect", nrow(preds)-1), "Average Treatment Effect")

ggplot(preds, (aes(y=predictions, x=predictions, colour=type))) +
  geom_point() +
  geom_errorbar(aes(ymin=predictions-Std.err, ymax=predictions+Std.err)) +
  geom_hline(yintercept = 1) +
  labs(title="Treatment Effect with Std.Err")
```
![image](https://user-images.githubusercontent.com/23657039/96604948-f3b5d680-12f5-11eb-9f10-ab27476bcc23.png)

**GRF version**
grf_1.2.0

**Comment by erikcs** [comment]
Hi @bakered, the average treatment effect function computes the ATE based on a double robust correction and may differ from the pointwise mean. If you replicate the above example many times you would see that ATE has 95 % coverage using the standard error returned from the same function

**Comment by erikcs** [comment]
Closing this for now, let us know if you think anything is unclear

As an example here is a histogram of the doubly robust ATE estimates described in your example. They are centered around 1 but may have a larger variance than purely averaging the CATEs:

```R
res = replicate(200, {
n = 1000; p = 5
X = matrix(rnorm(n*p), n, p)
W = rbinom(n, 1, 0.5)
Y = W + rnorm(n)
forest = causal_forest(X, Y, W)
rand.sample = 1:100
preds = predict(forest)$predictions
ate.dr = average_treatment_effect(forest, subset = rand.sample)

c(ate.dr = ate.dr[[1]],
  # 95 % confidence interval:
  coverage.dr = ate.dr[[1]] - 2*ate.dr[[2]] < 1 && ate.dr[[1]] + 2*ate.dr[[2]] > 1
  )
})

mean(res["coverage.dr",])
# [1] 0.965
hist(res["ate.dr",])
abline(v = 1, col = "red")
```

![Screen Shot 2020-11-28 at 10 21 27](https://user-images.githubusercontent.com/7185264/100523328-96b70700-3164-11eb-9ad8-aa198c0ebf5f.png)

section 2.1 in https://arxiv.org/pdf/1902.07409.pdf has more details on how the ATE is computed (equation 8)
