### ISSUE TITLE
Consider alternatives to virtual function getter in Data

### ISSUE THREAD

**Issue by erikcs** [grf-labs/grf#747]
`Data::get` is virtual to allow for different underlying storage (dense and sparse). This gives a modest performance hit since `get` is very hot function that benefits from compile-time optimizations. 

1. An alternative way to bake this in at compile time is with the [curiously recurring template pattern](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern). However, this adds code complexity as the `Data` passed to all forest components now has to be parameterized according to the underlying storage type `Data<T>`.

2. Another tangential item for this issue is other storage options for the multivariate outcomes/treatments that would allow `get_outcomes` to just return a view of outcome row j. `Data` could hold a separate `Eigen::Array` (row major) for only outcomes for example (is an empirical question whether this is a bottleneck).

**Comment by jtibshirani** [comment]
Adding an idea we discussed: could we just remove support for sparse matrices in order to make `Data` a concrete class?

**Comment by erikcs** [comment]
Another tangential item for this issue is other storage options for the multivariate outcomes/treatments that would allow `get_outcomes` to just return a view of outcome row j. `Data` could hold a separate `Eigen::Array` (row major) for only outcomes for example (is an empirical question whether this is a bottleneck).

**Comment by erikcs** [comment]
> Adding an idea we discussed: could we just remove support for sparse matrices in order to make `Data` a concrete class?

That would be convenient. 

In GRF forest size >>> training data size X, so the savings from a compressed X seems almost negligible, unless X is gigantic, in which case GRF would have speed issues anyways.

**Comment by erikcs** [comment]
Not relevant anymore after #946.
