### ISSUE TITLE
Confidence intervals for survival random forest

### ISSUE THREAD

**Issue by rickyking** [grf-labs/grf#750]
Hi,

Thanks for your great package that includes a lot of interesting randomForest.

I am wondering if you have any chance to implement the `Confidence intervals` estimation with `variance` for `survival random forest`?

Thanks

**Comment by erikcs** [comment]
Hi @rickyking, we have variance estimates listed as potential todos in #652, but it is currently not very high priority.

**Comment by rickyking** [comment]
Let me wait for #652 

I am in need of that functionality for a production appkication.
