### ISSUE TITLE
CATE over categorical subgroups not matching

### ISSUE THREAD

**Issue by TheFightMilk** [grf-labs/grf#751]
I am trying to calculate heterogeneous treatment effects over different values of a categorical variable (similar to #238). As a learning exercise, I am trying to recreate the results "by hand" from the `average_treatment_effect` function for the whole sample and for each categorical variable. I find that my calculations are slightly different from the function output, and wanted to understand where I might be going wrong. 

Problem setup:
* Standard Y and binary W setup.
* X has 4 numerical columns (C1-C4), and one categorical column (C5) that takes 5 values `c("a","b","c","d","e")`.
  * Since I have reason to believe that C5 might be correlated with W, I use `sufrep` to mean encode the column.
* I want to calculate the ATE and CATE over different levels of C5.

```
## Edit
library(grf)
library(sufrep)
library(dplyr)

set.seed(123)

# Generate data.
n <- 2000
p <- 4

# X contains 1:4 numeric columns and 5th as categorical column
X <- matrix(rnorm(n * p), n, p)%>%
  as.data.frame()
colnames(X) <- paste0("C",seq_len(p))
X <- X%>%mutate(C5 = as.factor(sample(c("a","b","c","d","e"),n,replace = T)))

# W and Y
W <- rbinom(n, 1, 0.4 + 0.2 * (X[, 1] > 0))
Y <- pmax(X[, 1], 0) * W - pmax(X[, 1], 0)*W*(X[,"C5"] %in% c("b","e")) + X[, 2] + pmin(X[, 3], 0) + rnorm(n)


# Run the model
# To enter categorical column in the causal forest
# I encode with sufrep

encoder <- make_encoder(X[,-5],X[,5], method = "means")
X_enc <- encoder(X[,-5],X[,5])
X_enc$C5 <- X$C5

numcol <- which(colnames(X_enc) != "C5")

## Orthogonalize
Y.forest = regression_forest(X_enc[,numcol], Y)
Y.hat = predict(Y.forest)$predictions
W.forest = regression_forest(X_enc[,numcol], W)
W.hat = predict(W.forest)$predictions

## Run the causal forest
cf = causal_forest(X_enc[,numcol], Y, W,
                   Y.hat = Y.hat, W.hat = W.hat)

## OOB treatment effect from causal forest
tau.hat = predict(cf)$predictions

## AIPW ATE
average_treatment_effect(cf)

## CATE over different subgroups
lapply(c("a","b","c","d","e"), function(x) average_treatment_effect(cf,subset = which(X_enc$C5 %in% x)))%>%
  bind_rows()
```
Results:

```
## AIPW ATE
  estimate    std.err 
0.18728847 0.04776458 

## CATE over different subgroups
estimate          std.err
1   0.424    0.112 
2  -0.0808  0.106 
3   0.427    0.0978
4   0.195   0.113 
5  -0.0320  0.106 

```

Now I want to calculate this by hand:

```
### Double robust score
db.wt <- (cf$W.orig-cf$W.hat)/(cf$W.hat*(1 - cf$W.hat))
mu.hat <- cf$Y.hat + (cf$W.orig-cf$W.hat)*tau.hat
dr.scr <- tau.hat + db.wt*(cf$Y.orig - mu.hat)
```
```
###  ATE
mean(dr.scr)
 0.1873161
```

```
### CATE
cat.id <- model.matrix(~ -1 + C5, data = X)
cat.scr <- t(cat.id) %*% dr.scr/colSums(cat.id)
```
Comparing this by "hand" CATE to the one calculated previously:
```
function          hand  c5
0.42376638	0.42395350	a		
-0.08080594	-0.08488423	b		
0.42702810	0.42602039	c		
0.19482447	0.19327970	d		
-0.03203411	-0.02711692	e
```
I want to understand if this is the correct way to estimate the CATE across the different subgroups and where the difference is cropping up from. 

Thanks

**Comment by erikcs** [comment]
Have you tried running this with the latest GRF development version? (your example did not run on a laptop with only grf and sufrep loaded). The average treatment effect functions where modified slightly in #723

**Comment by TheFightMilk** [comment]
Hey @erikcs, thanks for the reply. 

I have added the packages that I am using the code above. Also added `set.seed(123)` so that results don't change everytime we run it. I have not tried the development version. Will give it a try soon. Does the calculation for the "byhand" estimates look right to you? Looking through the code fore `average_treatment_effect`, I saw a function called `observation_weights()`. What is that doing?

**Comment by erikcs** [comment]
Yes, they look the same, you can see the calculations behind the ate [here](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/average_treatment_effect.R#L207) and [here](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/get_scores.R#L45). The internal observation_weights is for weighting when sample.weights and/or clusters are [passed](https://grf-labs.github.io/grf/reference/causal_forest.html):

```
equalize.cluster.weights:

If FALSE, each unit is given the same weight (so that bigger clusters
get more weight). If TRUE, each cluster is given equal weight in the
forest. In this case, during training, each tree uses the same number
of observations from each drawn cluster: If the smallest cluster has K
units, then when we sample a cluster during training, we only give a
random K elements of the cluster to the tree-growing procedure. When
estimating average treatment effects, each observation is given weight
1/cluster size, so that the total weight of each cluster is the same.
Note that, if this argument is FALSE, sample weights may also be
directly adjusted via the sample.weights argument. If this argument is
TRUE, sample.weights must be set to NULL. Default is FALSE.
```

**Comment by TheFightMilk** [comment]
Thanks!
