### ISSUE TITLE
Unable to Build From Source

### ISSUE THREAD

**Issue by yu45020** [grf-labs/grf#754]
I check Makevars and CMakeLists.txt in grf/core, but I am not able to fix it. 

**Steps to reproduce**

* git clone https://github.com/grf-labs/grf
* cd grf 
* open r-package/grf/grf.Rproj and build

**Error Message**
```
==> Rcmd.exe INSTALL --preclean --no-multiarch --with-keep.source grf

* installing to library 'C:/Programs/R/R-4.0.3/library'
* installing *source* package 'grf' ...
** using staged installation
** libs
Makevars:1: *** missing separator.  Stop.
Makevars:1: *** missing separator.  Stop.
ERROR: compilation failed for package 'grf'
* removing 'C:/Programs/R/R-4.0.3/library/grf'

Exited with status 1.

```

System:
Win 10 
R: 4.0.2
Rtools40 
GRF: v1.2.0, v1.1.0, v1.0.0 all fail to build

**Comment by erikcs** [comment]
Hi @yu45020 the Rstudio build integration is not expected to work on Windows as mentioned [here](https://grf-labs.github.io/grf/DEVELOPING.html#note-for-windows-users):

```
Note for Windows users:
Symlinks in the src directory point to the core C++ and R bindings. On
Windows one has to clone this repository with symlinks enabled: git
clone -c core.symlinks=true https://github.com/grf-labs/grf.git (this
command needs to be run as an administrator: right click Command Prompt
-> Run as administrator). Caveat: the above RStudio workflow is not
tested on Windows.

```

Manually building the package, or using the build_package [script](https://github.com/grf-labs/grf/blob/master/r-package/build_package.R) should work regardless of platform

**Comment by yu45020** [comment]
Thank you very much @erikcs . But the solution doesn't work. I end up replacing links with target files and successfully build it.
