### ISSUE TITLE
average_late() for non-binary instruments

### ISSUE THREAD

**Issue by hliebert** [grf-labs/grf#756]
The `average_late()` function is only implemented for binary but not real-valued ones. Is this currently on the development roadmap? Any suggestions on how to compute this?

**Comment by erikcs** [comment]
Hi @hliebert, this feature is currently not on the roadmap as it could be characterized as a somewhat esoteric estimand (the approach taken here https://arxiv.org/abs/1607.02566 would be a very involved addition to GRF - particularly considering we do not expect a big user base for this feature)

**Comment by erikcs** [comment]
And I think @swager or @davidahirshberg might have suggestions on how to compute this if you wish to try yourself

**Comment by hliebert** [comment]
Thank you for the quick reply Erik. I am aware that my request is a bit unusual. Any suggestions would be appreciated.

**Comment by jthiel100** [comment]
Just bumping this issue. I do expect there would be demand for functionality for continuous instruments, and would appreciate any direction on how to compute independently.

**Comment by erikcs** [comment]
Maybe @ehkennedy has some suggestions for trying this?

(the doubly robust score calculation for an instrumental forest with binary instrument is [here](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/get_scores.R#L139))

**Comment by davidahirshberg** [comment]
One reference to look at, if the interpretation you want is E[tau(X)] where tau(x) is the conditional LATE estimated by the instrumental forest, is https://arxiv.org/pdf/1608.00033.pdf. See Theorem 19. We're not currently planning to implement this in the package.

**Comment by ginward** [comment]
> Just bumping this issue. I do expect there would be demand for functionality for continuous instruments, and would appreciate any direction on how to compute independently.

I agree - I think non-binary instrument could be immensely helpful, too.

**Comment by halflearned** [comment]
Closing this since we don't have plans for implementing it at the moment. If there's a concrete proposal, please feel free to re-open.
