### ISSUE TITLE
Is c(x) available?

### ISSUE THREAD

**Issue by timothyb0912** [grf-labs/grf#770]
# Question
In your Generalized Random Forest paper, the causal forest estimating equation implicitly includes an intercept term c(x). See attached image.  Is c(x) exposed to users through the `grf` api?

<img width="906" alt="Screen Shot 2020-12-10 at 11 21 00 AM" src="https://user-images.githubusercontent.com/5533699/101819342-f81e9480-3ad9-11eb-86b4-6faa1bd580c7.png">

**Comment by erikcs** [comment]
No, it is not even estimated directly, `beta` is obtained by regressing the de-meaned variables.

**Comment by erikcs** [comment]
However you could estimate the intercept afterwards using the forest `weights` alpha:

```R
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
c.forest <- causal_forest(X, Y, W)

X.test <- matrix(0, 101, p)
X.test[, 1] <- seq(-2, 2, length.out = 101)
c.pred <- predict(c.forest, X.test)

weights <- get_sample_weights(c.forest, X.test)
Y.centered <- Y - c.forest$Y.hat 
W.centered <- W - c.forest$W.hat
lm(Y.centered ~ W.centered + 1, weights = weights[1, ])
Coefficients:
(Intercept)   W.centered  
   -0.05276      0.35184  
head(c.pred, 1)
  predictions
1   0.3518441
```

**Comment by timothyb0912** [comment]
@erikcs, thanks for the swift reply!

In your example, you estimate a single intercept coefficient.
I'm confused though.
From the screenshot above, `c(x)` looks like it should be a function / object-with-a-predict-method.

Let me know if I'm interpreting this incorrectly, and thanks again for your help!

**Comment by timothyb0912** [comment]
Ah, it seems I might not need it. The only reason I was interested in `c(x)` was to recreate `c.forest$Y.hat`.

@erikcs Do you know offhand of any way to retrieve the prediction interval for `c.forest$Y.hat`?
I tried looking at [here](https://grf-labs.github.io/grf/reference/predict.causal_forest.html) but that's just the confidence intervals for the CATE, as opposed to the prediction intervals for `c.forest$Y.hat`.

**Comment by halflearned** [comment]
@timothyb0912 thanks for your question. Could you explain what is your use-case? If you're interested in the conditional means for the control group, i.e. `E[Y(0)|X=x]`, then you can retrieve that as I do below (also used [here](https://github.com/grf-labs/grf/blob/73ddbf75268333a650fbee8898162023728d6b04/r-package/grf/R/average_treatment_effect.R#L236)).
```r
c.forest <- causal_forest(X, Y, W)
tau.hat <- predict(c.forest)$predictions
Y.hat.0 <- c.forest$Y.hat - tau.hat * c.forest$W.hat
```

**Comment by timothyb0912** [comment]
Hi @halflearned, my use case is wanting to produce model diagnostic plots where I compare observed outcomes with simulated counterfactual predictions, given the observed values of the treatment.

If `c.forest$Y.hat` is available, as well as an estimate of the scale of epsilon,
(assuming i.i.d. `epsilon` terms in a potential outcomes model of `Y = c(X) + b(X) * W + epsilon`),
then I can simulate counterfactual values of `Y` by drawing from the distribution of `epsilon`.
I can then compare these simulated values of `Y` to the observed values as for example done [here](https://arxiv.org/abs/1806.02307).

Does that make sense to you?

**Comment by erikcs** [comment]
Closing as resolved, please feel free to re-open if anything is unclear.
