### ISSUE TITLE
Is it possible to get OOB variance estimates?

### ISSUE THREAD

**Issue by ellenxtan** [grf-labs/grf#772]
I was wondering if a forest could return OOB variance estimates along with the OOB predictions? The default `variance.estimates` returns a blank matrix. Thanks!

`n <- 500`
`p <- 10`
`X <- matrix(rnorm(n * p), n, p)`
`W <- rbinom(n, 1, 0.5)`
`Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)`
`c.forest <- causal_forest(X, Y, W)`

`> c.forest$variance.estimates`
`<0 x 0 matrix>`

**Comment by erikcs** [comment]
`predict(c.forest, estimate.variance = TRUE)$variance.estimates`

**Comment by ellenxtan** [comment]
Thanks!
