### ISSUE TITLE
ATE >> 1 for binary outcome

### ISSUE THREAD

**Issue by cxcxxin** [grf-labs/grf#773]
We apply the "grf" R package to estimate the ATE in a data set with binary outcomes. However, the point estimate of the ATE is -1.964, while the s.e. is 0.024. The treatment is not sparse (3213 vs. 3731). Can anyone advise what is going on?

Code:
load("data.rdata")
set.seed(1234567890L)
Forest = causal_forest(X = X, Y = Y, W = W, tune.parameters = "all")
ATE = average_treatment_effect(Forest, target.sample = "control")

**Comment by erikcs** [comment]
Hi @cxcxxin, tau(x) may take on any values on the real line, there is nothing that restricts it to be in some interval.

**Comment by huangyunhao** [comment]
Hi @erikcs, as @cxcxxin mentioned, the outcomes are binary, i.e., they can take only 0 or 1 values. Since tau(x) is the difference in means of the treatment and control, I am confused by your statement "tau(x) may take on any values on the real line." Could you elaborate more on that?

**Comment by erikcs** [comment]
Hi @huangyunhao, for a sample `x` a causal forest predicts `tau(x)` from the kernel weighted linear regression `Yi = c(x) + tau(x)Wi + ei` with kernel weights `alpha(x)` derived from the forest (6.1 in https://arxiv.org/pdf/1610.01271.pdf). Even if the `Yi` are all binary, the OLS estimate of `tau(x)` may still lie outside [0, 1].

**Comment by erikcs** [comment]
Also note that with [orthogonalization](https://grf-labs.github.io/grf/REFERENCE.html#orthogonalization), on by default,  then the centered  value for `Yi` (`Yi-m(Xi))` is not necessarily binary anymore.
