### ISSUE TITLE
Tuning for subsamples for building a tree in the forest

### ISSUE THREAD

**Issue by ellenxtan** [grf-labs/grf#775]
I was trying to reproduce the Wager & Athey (2018, JASA) paper and failed to get a nominal coverage. The paper mentions in Table 4 of the supplement that varying `s` and `n` could result in different coverage results. 

I was trying to tune the `sample.fraction` in the causal_forest function for different `s` but got the error of "When confidence intervals are enabled, the sampling fraction must be less than 0.5.". But in the paper (screenshot attached below), the authors used `s=1333` which is about 0.67 of the total sample size `n=2000`. So I was wondering if `sample.fraction` the correct way to tune the number of subsamples in a tree of the forest? Thank you so much!

![image](https://user-images.githubusercontent.com/38412452/102549268-d26d2e80-4089-11eb-978f-625125293ba3.png)

**Comment by erikcs** [comment]
Hi @ellenxtan, from the [grf experiments folder](https://github.com/grf-labs/grf/tree/master/experiments):

>Wager and Athey (2018): This paper is not based on GRF, but on the deprecated causalForest. For replication code see https://github.com/swager/causalForest

**Comment by ellenxtan** [comment]
Thanks. In the current grf implementation, I found it very difficult to get a nominal coverage with the same setting in the original paper. I was wondering if this is due to tuning possibly? The causalForest repo mentions grf should have a better statistical performance. Does that refer to estimation instead of inference?

**Comment by erikcs** [comment]
Could you please post your example here?

**Comment by ellenxtan** [comment]
Based on codes in setting 27 in the original paper and causalForest package https://github.com/swager/causalForest/blob/master/experiments_for_paper/table1_propensity.R

```
library(causalForest)
library(mgcv)
library(randomForestCI)
library(Hmisc)
library(xtable)
library(grf)

rm(list = ls())

n = 500
ntree = 1000
sigma = 1

n.test = 100

dvals = c(2, 5, 10)#, 15, 20, 30, 40)
simu.reps = 500

baseline = function(x) {
    2 * (x[1] - 0.5)
}

propensity = function(x) {
    0.25 + dbeta(x[1], 2, 4)/4
}

simu.fun = function(d) {
    
    X = matrix(runif(n * d, 0, 1), n, d) # features
    e = apply(X, 1, propensity)
    W = rbinom(n, 1, e) #treatment condition
    
    # no treatment effect
    Y = apply(X, 1, baseline) + sigma * rnorm(n)
    
    X.test = matrix(runif(n.test * d, 0, 1), n.test, d)
    
    # random forest
    ## grf implementation
    forest = causal_forest(X, Y, W, num.trees = ntree, sample.fraction = 0.5, min.node.size = 1)
    preds = predict(forest, X.test, estimate.variance = TRUE)
    predictions = preds$predictions
    se.hat = preds$variance.estimates
    
    ## causalForest implementation (original codes for the paper)
    forest = propensityForest(X, Y, W, num.trees = ntree, sample.size = n / 10, nodesize = 1)
    predictions = predict(forest, X.test)
    forest.ci = randomForestInfJack(forest, X.test, calibrate = TRUE)
    se.hat = sqrt(forest.ci$var.hat)
    
    # true effect is 0
    rf.covered = mean(abs(predictions) <= 1.96 * se.hat)
    rf.mse = mean(predictions^2)
    
    c(rf.covered = rf.covered,
      rf.mse = rf.mse)
}

results.raw = lapply(dvals, function(d) {
    print(paste("NOW RUNNING:", d))
    res.d = sapply(1:simu.reps, function(iter) simu.fun(d))
    res.fixed = data.frame(t(res.d))
    print(paste("RESULT AT", d, "IS", colMeans(res.fixed)))
    res.fixed
})
```

The causalForest yields a nominal coverage (~95%) while the grf yields ~50%, for either sample.fraction=0.1 or sample.fraction=0.5. 

Thank you so much in advance!

**Comment by ellenxtan** [comment]
Based on codes in setting 27 in the original paper and causalForest package https://github.com/swager/causalForest/blob/master/experiments_for_paper/table1_propensity.R

```
library(causalForest)
library(mgcv)
library(randomForestCI)
library(Hmisc)
library(xtable)
library(grf)

rm(list = ls())

n = 500
ntree = 1000
sigma = 1

n.test = 100

dvals = c(2, 5, 10)#, 15, 20, 30, 40)
simu.reps = 500

baseline = function(x) {
    2 * (x[1] - 0.5)
}

propensity = function(x) {
    0.25 + dbeta(x[1], 2, 4)/4
}

simu.fun = function(d) {
    
    X = matrix(runif(n * d, 0, 1), n, d) # features
    e = apply(X, 1, propensity)
    W = rbinom(n, 1, e) #treatment condition
    
    # no treatment effect
    Y = apply(X, 1, baseline) + sigma * rnorm(n)
    
    X.test = matrix(runif(n.test * d, 0, 1), n.test, d)
    
    # random forest
    ## grf implementation
    forest = causal_forest(X, Y, W, num.trees = ntree, sample.fraction = 0.5, min.node.size = 1)
    preds = predict(forest, X.test, estimate.variance = TRUE)
    predictions = preds$predictions
    se.hat = sqrt(preds$variance.estimates)
    
    ## causalForest implementation (original codes for the paper)
    forest = propensityForest(X, Y, W, num.trees = ntree, sample.size = n / 10, nodesize = 1)
    predictions = predict(forest, X.test)
    forest.ci = randomForestInfJack(forest, X.test, calibrate = TRUE)
    se.hat = sqrt(forest.ci$var.hat)
    
    # true effect is 0
    rf.covered = mean(abs(predictions) <= 1.96 * se.hat)
    rf.mse = mean(predictions^2)
    
    c(rf.covered = rf.covered,
      rf.mse = rf.mse)
}

results.raw = lapply(dvals, function(d) {
    print(paste("NOW RUNNING:", d))
    res.d = sapply(1:simu.reps, function(iter) simu.fun(d))
    res.fixed = data.frame(t(res.d))
    print(paste("RESULT AT", d, "IS", colMeans(res.fixed)))
    res.fixed
})
```

The causalForest yields a nominal coverage (~95%) while the grf yields ~98-99%, for either sample.fraction=0.1 or sample.fraction=0.5. 

Thank you so much in advance!

**Comment by erikcs** [comment]
1000 trees is not enough for accurate CIs, https://arxiv.org/pdf/1610.01271.pdf section 7.2 uses 100k trees in their CI example.

**Comment by ellenxtan** [comment]
Thanks. Another quick question about the implementation of grf and causalForest package: is there a grf function that has similar functionality to the propensityForest(X, Y, W) in causalForest package, which builds Propensity Trees as in the causal forest paper?

I notice the input of the regression_forest in grf is (X,Y) or (X,W) instead of (X,Y,W). If I want to build similar propensityForest using grf, what should I do?

Thanks!

**Comment by erikcs** [comment]
I guess if you want the old propensityForest it is simplest to just use the defunct causalForest package. Closing as resolved, if anything is unclear please feel free to open.
