### ISSUE TITLE
A question about the doubly robust estimator in causal forests

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#776]
Hello,

I have a question regarding equation (8) of the paper [here](https://arxiv.org/pdf/1902.07409.pdf)
I know the idea of AIPTW or doubly robust estimator, but I cannot see how the second part of the equation is derived exactly. May I please get some hints from you? Thank you very much!!

Mengxia.

**Comment by erikcs** [comment]
Hi @ZhangMengxia, considering you are familiar with AIPW what is you are wondering about? If it is how to compute this from estimates returned by grf you can look here: https://github.com/grf-labs/grf/blob/master/r-package/grf/R/get_scores.R#L45, if it is about what the expression would like for other estimands then https://arxiv.org/pdf/1702.02896.pdf section 2.1 discuss this in the context of binary treatments (14) and more

**Comment by ZhangMengxia** [comment]
@erikcs Thanks a lot!! 
[https://arxiv.org/pdf/1702.02896.pdf](https://arxiv.org/pdf/1702.02896.pdf) section 2.1 is exactly what I am looking for. That's very helpful!
