### ISSUE TITLE
Poor Performance With Model Tuning

### ISSUE THREAD

**Issue by zmarkovich** [grf-labs/grf#777]
I've observed that when I use the causal forest with default settings except for honesty disabled the causal_forest function performs quite well: the output of test_calibration suggests there is significant treatment effect heterogeneity and the out of bag predictions verify that the causal forest is successfully identifying subsets with high and low individual treatments effects. However, this good performance vanishes when I use the built in parameter tuning procedure. Indeed, if tuning.parameters is set to "all" the out of bag predictions of treatment effect heterogeneity look backwards -- they identify subsets of the data as having a high treatment effect when they really have a low treatment effect and vice-versa.

I was wondering if there are situations for which this poor performance of the model tuning utility is expected? A manual inspection of the parameter values chosen seems to suggest that it's identifying values of "min.node.size" that are much larger than those which successfully identify the treatment effect heterogeneity. I have also tried tuning only a subset of the variables and tweaking the settings which govern the model tuning process, but the results are not changed: in all cases, the model tuning procedure seems to choose parameter values that fail to discover the treatment effect heterogeneity or even backfire in some cases.

To provide more context, this is a relatively small n setting. The dataset only includes about 1,000 observations. The outcome variable is continuous but bounded between -7 and 7. We are searching for heterogeneity conditioning on 5 variables which are all either ordinal or binary variables. 

Thank you for the help troubleshooting this difficulty and please let me know if I can provide any more details

**Comment by erikcs** [comment]
Hi @zmarkovich, do you have an example?

**Comment by zmarkovich** [comment]
Hi @erikcs, thanks for the reply. The code below replicates the behaviour (at least on my machine). 

It might also be possible to share the actual data if that would be helpful, although I'll have to check with my collaborators first since there might be some privacy concerns.

```set.seed(02143)
library(grf)

##initialize covariates
X <- do.call(cbind, lapply(rep(1000, 5), function(n){sample(1:5, n, replace=T)}))

##make a model matrix so we can add heterogeneity from higher order interactions
mm <- model.matrix(~.*.,as.data.frame(X))
mm <- model.matrix(~.*.,as.data.frame(mm))
mm <- model.matrix(~.*.,as.data.frame(mm))

skip <- 8000

tau <- mm %*% c(rep(0, skip), rnorm(ncol(mm)-skip, sd=10)) 
tau <- tau/sd(tau)
tau[tau > 0] <- rnorm(sum(tau > 0))

#generate treatment vector and outcome
W <- rbinom(1000, 1, .5)
y <- tau*W + rnorm(100,sd=.5)

#fit causal forest model and check internal benchmarks
#without tuning
cf <- causal_forest(X=X,Y=y, W=W, honesty=F, ci.group.size=1,
                    num.trees=2000)                          

test_calibration(cf)

tau.hat <- predict(cf)$predictions
high.effect <- tau.hat > median(tau.hat)
ate.high <- average_treatment_effect(cf, subset = high.effect)
ate.low <- average_treatment_effect(cf, subset = !high.effect)
ate.high[["estimate"]] - ate.low[["estimate"]]


#fit causal forest model and check internal benchmarks
#with tuning
cf <- causal_forest(X=X,Y=y, W=W, honesty=F, tune.parameters='all',
                     ci.group.size=1)                          
test_calibration(cf)

tau.hat <- predict(cf)$predictions
high.effect <- tau.hat > median(tau.hat)
ate.high <- average_treatment_effect(cf, subset = high.effect)
ate.low <- average_treatment_effect(cf, subset = !high.effect)

ate.high[["estimate"]] - ate.low[["estimate"]]
```

**Comment by erikcs** [comment]
In your example the signal is very weak (`cor(tau, tau.hat)=-0.01161249`), and tuning may overfit (even in out-of-bag):

```R
set.seed(8)
n <- 1000
p <- 5
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
tau <- pmax(X[, 1], 0) * 0.05
Y <- tau * W + X[, 2] + pmin(X[, 3], 0) + 2 * rnorm(n)
cf <- causal_forest(X, Y, W)
cf2 <- causal_forest(X, Y, W, tune.parameters = "all")
cf3 <- causal_forest(X, Y, W, tune.parameters = "all",
                     tune.num.reps = 150)

> cor(cf$predictions, tau)
           [,1]
[1,] 0.02291302
> mean(predict(cf)$debiased.error) # R loss
[1] 4.478613
> cor(cf2$predictions, tau)
            [,1]
[1,] -0.01428938
> mean(predict(cf2)$debiased.error)
[1] 4.486865
> cor(cf3$predictions, tau)
             [,1]
[1,] -0.001970128
> mean(predict(cf3)$debiased.error)
[1] 4.488233
```

Tuning minimizes [R-loss](https://arxiv.org/pdf/1712.04912.pdf) by @xnie and was implemented by @halflearned, perhaps they have thoughts

**Comment by halflearned** [comment]
Closing this as the question seems to have been answered, and there isn't anything that looks immediately actionable. Please re-open as appropriate.
