### ISSUE TITLE
Difference between variable importance and the best tree

### ISSUE THREAD

**Issue by hakianmehr** [grf-labs/grf#780]
Hello,

I'm using the function "find_best_tree (casual)" to find the best tree but the tree that I could find is completely different from the variable importance ranking. 
I need to have both in the same direction, is there any way to solve my issue (tune parameters or ....)? 
n.observations: 9000
Y (categorical): 0(8000) 1(1000)
n.independent variables: 62

**Comment by erikcs** [comment]
Hi @hakianmehr, I think your question was answered in https://github.com/grf-labs/grf/issues/281#issuecomment-689142974 ?

>There is no guarantee that the "best" tree would split along the "most important" variables as given by our variable importance measure. The variable importance measure captures which variables are split on the most on average -- but the best tree doesn't need to split first on the variable that is most commonly split on.

**Comment by hakianmehr** [comment]
Thanks for your response but I **just need the tree** split along with the "most important" variables. 
is there any other way to help me? 
For example, suppose that we have 2000 trees (grown in the forest), is it possible that I go through all of them and find the tree (or trees) split exactly along the most important variables?

**Comment by erikcs** [comment]
Sorry for not understanding exactly what you are after - can you maybe explain what question you are trying to answer, then we can evaluate how (if possible) to do it with GRF?

**Comment by hakianmehr** [comment]
I need to have for example the first 10 best trees (top 10 trees selected). How can I get it from the function? 
Thank you.

**Comment by erikcs** [comment]
GRF does not currently have any functionality for that

**Comment by xxh23-bit** [comment]
@erikcs @hakianmehr I may understand the question that hakianmehr asked. There was a post-hoc analysis using Causal Forest method in Look AHEAD trial to detect heterogeneity of weight loss interventions to reduce cardiovascular complications of type 2 diabetes (Baum A et al. Lancet Diabetes Endocrinol 2017, 5(10):808-815.). In their methods, they find the most representative causal tree by the following three criteria: (1) we identified trees split on covariates with the highest variable importance measures whose most important variable was the covariate with the greatest variable importance measure across the forest; (2) from these trees, we identified the tree whose samples had the greatest variance in individualized treatment effects calculated by the causal forest, a surrogate of heterogeneity; (3) within this tree, each leaf with at least 10% of the total cohort sample size was considered for downstream analysis. actually, I also want to know how to find the best representative causal tree split along with the "most important" variables. Can grf package meet this requirement? thanks a lot!

**Comment by erikcs** [comment]
Hi @xxh23-bit, so GRF has gotten a new tool for doing HTE analysis called the [RATE](https://grf-labs.github.io/grf/articles/rate.html). For certain tasks this tool could give you some statistical confidence which would be harder to assure for more ad-hoc approaches (like looking at single trees). The TOC curve could be a place to start, it could for example tell you if there's some subset of units that benefit more than average from a treatment (this implicitly gives you a covariate profile you could explore further). You could also "rank" this curve by variables that have the highest causal forest split frequency.

**Comment by xxh23-bit** [comment]
> Thank you very much for your reply. In fact, the problem I want to solve is how to select the best representative causal tree split along with the "most important" variables from the causal forest and give the corresponding splitting value.  For example, suppose that we have 2000 trees (grown in the function causal_forest() ), Is there any way to go through all of them and find the tree (or trees) split exactly along the most important variables? thanks a lot!
