### ISSUE TITLE
Including the treatment variable as a moderator of the treatment effect

### ISSUE THREAD

**Issue by gcasamat** [grf-labs/grf#783]
Suppose that I want to estimate the price elasticity of demand. I then specify log(quantity) as the outcome variable and log(price) as the treatment variable. 
I am interested in how the price elasticity varies with the price itself. In this purpose, does it make sense to include the price in the set X of covariates? Do you have other suggestions for modeling the price elasticity as a function of price?
Many thanks.

**Comment by erikcs** [comment]
Closing as addressed in https://github.com/microsoft/EconML/issues/378
