### ISSUE TITLE
Is there any way to get predictions from all trees from grf?

### ISSUE THREAD

**Issue by hakianmehr** [grf-labs/grf#784]

**Comment by erikcs** [comment]
If you mean individual tree predictions: no, sorry

**Comment by erikcs** [comment]
GRF uses random forests from the perspective of a data adaptive weighting function, see for example section 2.1 here https://arxiv.org/pdf/1610.01271.pdf. As such, individual tree predictions are not a primary object of interest, forest weights are, you can retrieve them using this function: https://grf-labs.github.io/grf/reference/get_sample_weights.html

**Comment by hakianmehr** [comment]
Thank you very much for your response. So, is it possible to reproduce the individual tree predictions based on the forest weights?

**Comment by erikcs** [comment]
No

**Comment by hakianmehr** [comment]
Thank you.
