### ISSUE TITLE
test_calibration/best_linear_projection: slow with clustered SEs and large data

### ISSUE THREAD

**Issue by adeldaoud** [grf-labs/grf#786]
I am running causal_forest with 2000 trees, using data with about 2.8 million rows, 16 covariates, binary outcome and treatment. I am using a Windows 10 machine with 384 GB ram and 42 cores of i7 Intel, and loaded version grf_1.2.0. That causal_forest model takes about 10.5 h to run. To test for the presence of heterogeneity in an omnibus test, I am using the test_calibration model. However, this model has now run for over four days (96h<)—at the time of writing—without converging. 

Is this long estimation time of test_calibration considered normal compared to the causal_forest estimation time? 

If not, what advice can you give to speed up this long estimation time?

The causal_forest code block is the following 

```
tau.forest.2000.u5 <- causal_forest(df4[covariates],
                                    df4[,outcome], 
                                    df4[,treatment],  
                                    clusters = df4[,clusters],
                                    num.trees = 2000,
                                    honesty.fraction = 0.5,
                                    tune.parameters = "all")


m_cal <- test_calibration(tau.forest.2000.u5)
```

**Comment by erikcs** [comment]
[test_calibration](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/forest_summary.R#L32) only does a simple linear regression and computes clustered SEs with `lmtest` and `sandwich`.

But the way clustered standard errors are computed appear to scale quadratically in the cluster size, so if you have few clusters and a couple of million samples `lmtest` will most likely stall forever:

```R
> n = 10000
> z = matrix(rnorm(n*3), n, 3)
> best.linear.predictor <- lm(z[,1] ~ z[,2] + z[,3] + 0)
> clusters = 1:n
> system.time(lmtest::coeftest(best.linear.predictor,
+                              vcov = sandwich::vcovCL,
+                              type = "HC3",
+                              cluster = clusters))
   user  system elapsed 
  0.060   0.008   0.068 
> clusters = sample(c(1:10), n, T)
> system.time(lmtest::coeftest(best.linear.predictor,
+                              vcov = sandwich::vcovCL,
+                              type = "HC3",
+                              cluster = clusters))
   user  system elapsed 
  9.551   0.090   9.642 
> clusters = sample(c(1:5), n, T)
> system.time(lmtest::coeftest(best.linear.predictor,
+                              vcov = sandwich::vcovCL,
+                              type = "HC3",
+                              cluster = clusters))
   user  system elapsed 
 36.499   0.145  36.664 
```

**Comment by erikcs** [comment]
Maybe it is worth bringing this to @zeileis' attention: the above example is with `sandwich_3.0-0`.

**Comment by zeileis** [comment]
See Equations 16, 17, and 18 in `vignette("sandwich-CL", package = "sandwich")`: Clustered HC2 and HC3 necessitate scaling with the square root of the inverse of hat matrices of dimension n_g x n_g where n_g is the number of observations in cluster g. In short, this quickly becomes burdensome when n_g becomes large. Some more details are provided below, in case this is helpful.

_Details:_ In the case where every observation is its own cluster, the computations can be nicely vectorized. However, otherwise `vcovCL()` uses a `for()` loop over all clusters in which things like `qr()`, `chol2inv()`, `eigen()`, or `solve()` are applied.

**Comment by erikcs** [comment]
Thanks @zeileis.

@adeldaoud I'm sorry to say there is not much we can do, you can do `forest$clusters = 1:n`, and only look at the point estimates from `test_calibration`/`best_linear_projection`.

We could make a minor note about n_g and computation time in the documentation, unless anyone in @grf-labs has any other suggestion (considering this is the first issue raised on this, it does not appear to be frequent problem).

**Comment by zeileis** [comment]
Wouldn't using HC1 or HC0 for the right clusters make more sense than using HC3 for the wrong clusters?

**Comment by erikcs** [comment]
Thank you @zeileis, HC1 is orders of magnitude faster than HC3!

1. We can add an extra `vcov.type` argument to `test_calibration/best_linear_projection` suggesting HC1 for cases like these
 
2. Or, considering #723 there is still room for changing how standard errors are computed before the next major release - if you do not expect HC1 to give worse coverage than HC3 in grf use cases @swager.

**Comment by swager** [comment]
Thank you all! Yes, adding a user-facing option to let them specify `vcov.type` in `best_linear_projection` (and elsewhere where we use `lmtest`) sounds good to me. I'd still prefer keeping HC3 as the default, though, and then add documentation saying that HC1 is faster with very large datasets involving clusters.

Also, thank you @zeileis for all you contributions to `sandwich` and associated packages -- they're really a great addition to `R`!

**Comment by zeileis** [comment]
That would have been my suggestion as well!

And you're very welcome, let me know when I can help. And also thanks for all of your contributions, both methodological and in terms of software!
