### ISSUE TITLE
Model with Tuning Specified 

### ISSUE THREAD

**Issue by ejin-kim-GPRL** [grf-labs/grf#788]
We are running the same causal forest model with the same number of seed and trees, but we are getting different predictions each time when the tuning option (tune.parameters, tune.num.trees, tune.num.reps, tune.num.draws) is specified.

We were wondering if we were missing anything and what we can do to generate stable results.
Please let us know if you need any more details.

**Comment by erikcs** [comment]
You can get the same result by doing `set.seed()` first. Tuning draws a random grid in R, in the next release just the `seed` argument will be enough (#704).
