### ISSUE TITLE
Usage example incorrectly states that CATE and CATT should be identical

### ISSUE THREAD

**Issue by dlindelof** [grf-labs/grf#791]
I think there's an inaccuracy in the usage example given in https://grf-labs.github.io/grf/. When I run the following lines:

```
# Estimate the conditional average treatment effect on the full sample (CATE).
average_treatment_effect(tau.forest, target.sample = "all")

# Estimate the conditional average treatment effect on the treated sample (CATT).
# Here, we don't expect much difference between the CATE and the CATT, since
# treatment assignment was randomized.
average_treatment_effect(tau.forest, target.sample = "treated")
```

I get the following results:

```
> average_treatment_effect(tau.forest, target.sample = "all")
  estimate    std.err 
0.34927965 0.04757066 
> average_treatment_effect(tau.forest, target.sample = "treated")
  estimate    std.err 
0.40879758 0.04815796 
```

The difference is small and possibly not statistically significant, but since the treatment probability is given by

`W <- rbinom(n, 1, 0.4 + 0.2 * (X[, 1] > 0))
`

we have that `X[, 1]` is a true confounder, and it's not true anymore that the treatment is 'randomized': units for which `X[, 1] > 0` are more likely to be treated, and will thus have a higher CATT. In fact the "true" CATE and CATT are given by:

```
> mean(pmax(X[, 1], 0))  # CATE
[1] 0.3852868
> mean(pmax(X[, 1], 0)[W == 1])  # CATT
[1] 0.4406283
```

Does this make sense?

**GRF version**
1.2.0.0

**Comment by erikcs** [comment]
Thanks @dlindelof, looking at the version history if the README this used to be `W <- rbinom(n, 1, 0.5)`, but was updated here https://github.com/grf-labs/grf/commit/f069e1624cdb70fd010257840fce9af771430554 without changing the comment "`Here, we don't expect much difference between the CATE and the CATT,`"

@swager / @davidahirshberg : would you want `W <- rbinom(n, 1, 0.4 + 0.2 * (X[, 2] > 0))` instead? or (any `X` except `X1`?) - or remove that comment?
