### ISSUE TITLE
Cannot replicate the outcome in different laptops with the same seed

### ISSUE THREAD

**Issue by zhong1969** [grf-labs/grf#793]
Dear Sir/Madam:

I found that I cannot replicate the outcome on different laptops while setting the same number as the seed. The outcomes obtained on the two laptops are very close but different. On the same laptop, the outcome is stable if the seed is set as the same.
Hope that you can help solve the problem since the editor inquires this.

Thanks and regards,
Zhong

**Comment by erikcs** [comment]
Hi @zhong1969, please try using the same number of threads (`num.threads`) on both computers. More details: https://grf-labs.github.io/grf/REFERENCE.html#forests-predict-different-values-depending-on-the-platform-even-though-the-seed-is-the-same

**Comment by zhong1969** [comment]
Dear Eric. I followed your suggestions and solved the problem. Thanks! Zhong
