### ISSUE TITLE
Are there updates of GRF in which parameters of Instrument Forest are tuned by cross-validation or any other ways?

### ISSUE THREAD

**Issue by zhong1969** [grf-labs/grf#794]
Dear Sir/Madam:

Could you please tell me whether there are any updates of GRF in which parameters of Instrument Forest are tuned by cross-validation or any other ways?

Thanks and regards,
Zhong

**Comment by erikcs** [comment]
Hi @zhong1969, there are no updates beyond what is described in the current [algorithm reference](https://grf-labs.github.io/grf/REFERENCE.html#parameter-tuning). One minor thing to keep it mind though is that for IV forest, tuning for example just `min.node.size` works better in some cases than tuning all parameters: #501.
