### ISSUE TITLE
Is there an example where a causal_forest clearly outperforms random forests?

### ISSUE THREAD

**Issue by dlindelof** [grf-labs/grf#795]
I'm trying to convince myself that using a `causal_forest` yields more accurate treatment effects estimates than naively training with random forests. I'm using the same example given in the documentation:

```
library(grf)

# Generate data.
n <- 20000
p <- 10
X <- matrix(rnorm(n * p), n, p)

# Train a causal forest.
W <- rbinom(n, 1, 0.4 + 0.2 * (X[, 1] > 0))
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
tau.forest <- causal_forest(X, Y, W)
```

The CATE and CATT are almost the same as the theoretical values:

```
> average_treatment_effect(tau.forest, target.sample = 'all')
  estimate    std.err 
0.41131110 0.01458405 
> average_treatment_effect(tau.forest, target.sample = 'treated')
  estimate    std.err 
0.48722262 0.01488336 
```

```
> # Theoretical CATE
> 1/sqrt(2*pi)
[1] 0.3989423
> # Actual CATE
> mean(pmax(X[, 1], 0))
[1] 0.396278
> 
> # Theoretical CATT
> 1/sqrt(2*pi) * 6 / 5
[1] 0.4787307
> # Actual CATT
> mean(pmax(6 / 5 * X[, 1], 0))
[1] 0.4755336
```

But I get almost identical results by training two random forests, one on the treated units and one on the control units; then predicting the outcome using both models and taking the difference:

```
library(ranger)
> treated <- W == 1
> data_untreated <- data.frame(cbind(Y = Y[!treated], X[!treated, ], W = W[!treated]))
> model_untreated <- ranger(Y ~ ., data = data_untreated)
> data_treated <- data.frame(cbind(Y = Y[treated], X[treated, ], W = W[treated]))
> model_treated <- ranger(Y ~ ., data = data_treated)

> ranger_cate_two_models <- function(model_treated, model_untreated, X) {
  data_untreated <- data.frame(cbind(Y = NA, X, W = 0))
  data_treated <- data.frame(cbind(Y = NA, X, W = 1))
  mean(predict(model_treated, data_treated)$predictions - predict(model_untreated, data_untreated)$predictions) 
}

> ranger_cate_two_models(model_treated, model_untreated, X)
[1] 0.4127993
> ranger_cate_two_models(model_treated, model_untreated, X[treated, ])
[1] 0.4837266
> 
```

So I guess my question is this: under what conditions will a `causal_forest` yield better treatment estimates than when training two separate random forests? How would you 'sell' the `grf` package to causal inference practitioners?

**GRF version**
1.2.0

**Comment by erikcs** [comment]
Hi @dlindelof, https://arxiv.org/pdf/1712.04912.pdf section 6 has a comparison with what you are doing ("T-learner") with what causal forest is based on ("R-learner")

**Comment by dlindelof** [comment]
Thank you @erikcs this looks like exactly what I need.
