### ISSUE TITLE
The causal forest have not split.

### ISSUE THREAD

**Issue by yang9198** [grf-labs/grf#807]
result:
GRF tree object 
Number of training samples: 300 
Variable splits: 
(1) * num_samples: 150  avg_Y: 0 avg_W: 0.33 

code:

Y1 <- data1$CAR
W1 <- data1$W
X1 <- data1[,3:12]
set.seed(7989)
Y1.forest <- tune_regression_forest(X1, Y1, tune.parameters = "all", tune.num.reps = 300)
set.seed(7989)
W1.forest <- tune_regression_forest(X1, W1, tune.parameters = "all", tune.num.reps = 300)
set.seed(7989)
Y1forest <- regression_forest(X1, Y1, num.trees = 200,
                              min.node.size = as.numeric(Y1.forest$params["min.node.size"]),
                              sample.fraction = as.numeric(Y1.forest$params["sample.fraction"]),
                              mtry = as.numeric(Y1.forest$params["mtry"]),
                              alpha = as.numeric(Y1.forest$params["alpha"]),
                              imbalance.penalty = as.numeric(Y1.forest$params["imbalance.penalty"]))
set.seed(7989)
W1forest <- regression_forest(X1, W1, num.trees = 200,
                              min.node.size = as.numeric(W1.forest$params["min.node.size"]),
                              sample.fraction = as.numeric(W1.forest$params["sample.fraction"]),
                              mtry = as.numeric(W1.forest$params["mtry"]),
                              alpha = as.numeric(W1.forest$params["alpha"]),
                              imbalance.penalty = as.numeric(W1.forest$params["imbalance.penalty"]))
set.seed(7989)
forest.1 <- tune_causal_forest(X1, Y1, W1, Y.hat = Y1forest$predictions, W.hat = W1forest$predictions, tune.parameters = "all", tune.num.reps = 300)
forest1 <- causal_forest(X1, Y1, W1, Y.hat = Y1forest$predictions, W.hat = W1forest$predictions, num.trees = 1000,
                         min.node.size = as.numeric(forest.1$params["min.node.size"]),
                         sample.fraction = as.numeric(forest.1$params["sample.fraction"]),
                         mtry = as.numeric(forest.1$params["mtry"]),
                         alpha = as.numeric(forest.1$params["alpha"]),
                         imbalance.penalty = as.numeric(forest.1$params["imbalance.penalty"]))
get_tree(forest1, 1)

**Comment by erikcs** [comment]
A forest does not split if the number of samples is less than min.node.size, or if there is zero variation in W.

**Comment by yang9198** [comment]
> 如果样本数量小于最小节点大小或W的变化为零，则森林不会分裂。
But sometimes I can get the normal results for same sample datas. 
What should I do to solve this problem?

**Comment by erikcs** [comment]
Hi @yang9198, if you mean the magnitude of the tuned `min.node.size` is such that sometimes the forest splits, and sometimes not, depending on tuning run - there is randomness in [tuning](https://grf-labs.github.io/grf/REFERENCE.html#parameter-tuning), in the grid of parameter values it explores.

Also, if the trees are very shallow in the case when tuning leads to "split inducing" parameter values: tuning works by minimizing R-loss as defined here https://arxiv.org/pdf/1712.04912.pdf, and when it settles on parameter values that leads to almost no splits, then one explanation could be that this estimated loss function is minimized by predicting a (close to) constant treatment effect (@xnie may have more on this).

**Comment by yang9198** [comment]
I found that when I set the seeds, some seeds can make the forest divide normally, but some cannot. Is there any way to find the seeds that make the best results?

**Comment by halflearned** [comment]
I'll close this issue for the moment as the discussion seems to have gone stale. @yang9198 please let us know if you have further follow-up questions.
