### ISSUE TITLE
Causal forests giving the same result for X_test and X_train

### ISSUE THREAD

**Issue by yuhsienliu** [grf-labs/grf#839]
**Description of the bug**
Hi all! I'm trying to estimate causal effects for the training data and new/holdout testing data. However, it turns out that the ATE and ATETs are identical between my training and testing set, up until at least the 5th decimal point.

**Steps to reproduce**
I estimated the forest on the training set as per the codes below:

```
tau.forest = causal_forest(X_train, Y_train, W_train,
                           W.hat = W.hat, Y.hat = Y.hat,
                           tune.parameters = "all",
                           seed = 1,
                           num.threads = 3  
                           )
```
And then my ATE's and ATET's are estimated on `X_train` and `X_test` respectively.
```
# estimate on X_train
tau.hat.oob = predict(tau.forest)
hist(tau.hat.oob$predictions)
average_treatment_effect(tau.forest, target.sample = "all")
average_treatment_effect(tau.forest, target.sample = "treated")
```

```
# prediction on X_test
tau.hat<- predict(tau.forest, X_test)
hist(tau.hat$predictions)
average_treatment_effect(tau.forest, target.sample = "all")
average_treatment_effect(tau.forest, target.sample = "treated")
```
It turns out that the two pairs of ATE's and ATET's are identical. The X’s are indeed different across the training and testing sets, so it seems that in the prediction phase using X_test, the program is actually pointing back at X_train, thereby producing exactly the same results.  However, I cannot see any issues in the code. 

Any insights/ideas would be greatly appreciated!

Thank you!

**GRF version**
`1.2.0`

**Comment by erikcs** [comment]
Hi @yuhsienliu, sorry, from your code example I don't understand what you are asking for, you have pasted the same `average_treatment_effect` command two times (`average_treatment_effect` does currently not take take a test sample input).

**Comment by yuhsienliu** [comment]
Thanks for checking it out! Yes, it seems that my codes incorrectly used `average_treatment_effect` on the test sample input.

Would the correct way be using `predict()` on the test sample?

**Comment by erikcs** [comment]
Awaiting support for this (#129) you could take a mean of `predict()` on a test sample, but note that you won't get valid SEs
