### ISSUE TITLE
Standard errors for GATE using average_treatment_effects

### ISSUE THREAD

**Issue by lauremolina** [grf-labs/grf#842]
Does the average_treatment_effect function implements the GATE procedure described by Chernozhukov et.al. 2018?
Specifically, I wonder if the standard errors are calculated analytically, or thorough the multi-sample splitting procedure described by Chernozhukov et.al. 2018 for calculating a GATE. For example, Davis and Heller 2020 (page 673)  implement the estimation procedure proposed by Chernozhikov et.al. 2018, to address potential issues with the standard errors. I just wonder if the average_treatment_effect function already incorporates that, or if it calculates the standard errors analytically.
I've been able to find enough documentation about the procedure to calculate the ATE itself, but not so much about its standard errors.

Generic Machine Learning Inference on Heterogenous Treatment Effects in Randomized Experiments
Victor Chernozhukov, Mert Demirer, Esther Duflo, Iván Fernández-Val

Rethinking the Benefits of Youth Employment Programs: The Heterogeneous Effects of Summer Jobs 
Jonathan M.V. Davis , Sara B. Heller

**Comment by davidahirshberg** [comment]
We do not use the standard errors from Chernozhukov et.al. 2018.  See the implementation of our standard errors [here](https://github.com/grf-labs/grf/blob/e6605265fdde44541354fa10561a2021ddd90958/r-package/grf/R/average_treatment_effect.R#L230).

**Comment by erikcs** [comment]
What that linked code is doing in practice is calculating the SE of a mean, where the mean is an average of doubly robust scores (for the treatment effects).

**Comment by lauremolina** [comment]
Thank you both so much. And am I right to assume that the best_linear_projection also calculates standard errors analytically, in a similar way. Thanks again.

**Comment by erikcs** [comment]
Yes
