### ISSUE TITLE
Ranger implementation 

### ISSUE THREAD

**Issue by zpunit331111111** [grf-labs/grf#845]
Hello, I am wondering if the quantile_regression() could be used in ranger()? If so, is there an example I can refer to? Thanks!

**Comment by halflearned** [comment]
Hi @zpunit331111111. Although grf began as a fork of ranger, it has since turned into an entirely different package. I believe ranger supports quantile forests, and you can direct questions about their implementation to their repo.

**Comment by zpunit331111111** [comment]
Thank you! I have about a billion data points, quantile_regression took about 5-6 days to run. I am just wondering if using ranger will use less time. Or if there are other ways? I used 40 cores to run the code and it’s the maximum number I can afford. Thanks!

**Comment by halflearned** [comment]
One billion! That's impressive. I think we don't have a good idea of whether `ranger` will be faster. Please let us know if you find out it is.
