### ISSUE TITLE
The examined of covariate balance

### ISSUE THREAD

**Issue by yang9198** [grf-labs/grf#851]
covariate balance can be examined by comparing the inverse-propensity weighted averages of the explanatory variables across the two groups. Specifically, the treatment observations are weighted by 1/e^(−i)(Xi) and control observations by 1 / (1-e^(−i)(Xi) ). But the results show that there is a big difference between the treated groups and control groups. How to solve this problem?

**code:**

Y1 <- data1$CAR
W1 <- data1$W
X1 <- data1[,3:12]
Y1.forest <- tune_regression_forest(X1, Y1, tune.parameters = "all", tune.num.reps = 300)
W1.forest <- tune_regression_forest(X1, W1, tune.parameters = "all", tune.num.reps = 300)
Y1forest <- regression_forest(X1, Y1, num.trees = 200, 
                              min.node.size = as.numeric(Y1.forest$params["min.node.size"]),
                              sample.fraction = as.numeric(Y1.forest$params["sample.fraction"]),
                              mtry = as.numeric(Y1.forest$params["mtry"]),
                              alpha = as.numeric(Y1.forest$params["alpha"]),
                              imbalance.penalty = as.numeric(Y1.forest$params["imbalance.penalty"]))
W1forest <- regression_forest(X1, W1, num.trees = 200, 
                              min.node.size = as.numeric(W1.forest$params["min.node.size"]),
                              sample.fraction = as.numeric(W1.forest$params["sample.fraction"]),
                              mtry = as.numeric(W1.forest$params["mtry"]),
                              alpha = as.numeric(W1.forest$params["alpha"]),
                              imbalance.penalty = as.numeric(W1.forest$params["imbalance.penalty"]))
forest.1 <- tune_causal_forest(X1, Y1, W1, Y.hat = Y1forest$predictions, W.hat = W1forest$predictions,  tune.parameters = "all", tune.num.reps = 300)
forest1 <- causal_forest(X1, Y1, W1, Y.hat = Y1forest$predictions, W.hat = W1forest$predictions,  num.trees = 3000,
                           min.node.size = as.numeric(forest.1$params["min.node.size"]),
                           sample.fraction = as.numeric(forest.1$params["sample.fraction"]),
                           mtry = as.numeric(forest.1$params["mtry"]),
                           alpha = as.numeric(forest.1$params["alpha"]),
                           imbalance.penalty = as.numeric(forest.1$params["imbalance.penalty"]))
treat_group <- data1$W==1
grf_treat <- (data1$Age / W1forest$predictions)[treat_group]
grf_control <- (data1$Age / (1 - W1forest$predictions))[!treat_group]
mean(grf_treat)
sd(grf_treat)
mean(grf_control)
sd(grf_control)

**Results:**
**> mean(grf_treat)
[1] 30.364
> sd(grf_treat)
[1] 13.16843
> mean(grf_control)
[1] 15.40941
> sd(grf_control)
[1] 10.58091**

**Comment by swager** [comment]
To get the propensity-weighted covariate means here, you'd need to do something like the following (either works)
```R
age_mean_treat <- mean(data1$W * data1$Age / W1forest$predictions)
age_mean_treat <- sum((data1$Age / W1forest$predictions)[treat_group]) / nrow(data1)
```
If this doesn't help, could you please share a reproducible example we could take a look at?

**Comment by yang9198** [comment]
> To get the propensity-weighted covariate means here, you'd need to do something like the following (either works)
> 
> ```r
> age_mean_treat <- mean(data1$W * data1$Age / W1forest$predictions)
> age_mean_treat <- sum((data1$Age / W1forest$predictions)[treat_group]) / nrow(data1)
> ```
> 
> If this doesn't help, could you please share a reproducible example we could take a look at?

This is very helpful for me. Thanks!
