### ISSUE TITLE
Efficient implemetion of CF with the same {X,W} but different outcome Y

### ISSUE THREAD

**Issue by HarryMayday** [grf-labs/grf#852]
Dear developers, 

I am running causal forest on a large dataset with the same set of covariates X and treatment W, but looking at the treatment effects on different outcome variables Y. For the moment, I'm running the whole causal_forest procedure for each Y each time, which takes a lot of time to go through all outcome variables. 

Since we are training CF based on the same set of X and W, not sure if I'm right that we just need to train the CF once to get the weights and then we can compute the treatment effect for other Ys without the need to run the whole procedure again? I searched into the manual and previous github requests but seem to only find the request for multi-arm ATE, which I guess is a more general case of my question. Could you please advise whether there can be a more efficient implementation of CF with the same set of {X,W} but to look at different Y. 

Many thanks!

**Comment by erikcs** [comment]
Hi @HarryMayday, the experimental [multi_arm_causal_forest](https://grf-labs.github.io/grf/reference/multi_arm_causal_forest.html) has support for multiple outcomes `Y` in the form of a matrix with one column for each outcome. Note this is currently only available in the development version and you'd have to install GRF from source to try it out.

**Comment by HarryMayday** [comment]
Hi Erikcs, many thanks for your prompt reply! Will definitely have a try on the multi-arm function

**Comment by erikcs** [comment]
Note that you'd want the outcomes Y to be on the same scale when using this approach

**Comment by HarryMayday** [comment]
@erikcs Hi Erikcs, sorry to bother with a follow-up question. I tried the multi_arm_causal_forest function. I have 28 outcome variables, and I can indeed get OOB predictions of 28 columns. However, when I use average_treatment_effect to compute the average treatment effect, the result only returns a single row of estimate and standard error, rather than for all 28 outcomes.

Just would like to confirm, if average_treatment_effect is not yet adapted to the multi_arm_causal_forest yet?

**Comment by erikcs** [comment]
You have to specify outcome: `average_treatment_effect(forest, outcome=1...28)`

**Comment by HarryMayday** [comment]
@erikcs Thanks a lot! This well solves my problem!

**Comment by erikcs** [comment]
FYI if you are using the development version of `multi_arm_causal_forest`: we simplified the API for multiple outcomes here https://github.com/grf-labs/grf/pull/982
