### ISSUE TITLE
Support for Continuous Treatment in Causal Survival Forest

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#861]
I was wondering if it is possible to add support for continous treatment for causal survival forest, as the current [documentation](https://grf-labs.github.io/grf/reference/causal_survival_forest.html) indicates that the treatment `W` can only be binary. 

It might be also helpful to add something similar to average_partial_effect for continuous treatment for causal survival forest, too.

**Comment by erikcs** [comment]
Hi @ginward, `causal_survival_forest` only supports binary `W`. If you really want to get a forest based estimate for a continuous `W` you can do inverse probability of censoring weighting (IPCW) with `causal_forest`: estimate censoring probabilities P(Ci) with a `survival_forest`, then pass 1/P(Ci) to `causal_forest` using the `sample.weights` argument.

The latest causal survival paper draft has details on this, it will hopefully be uploaded to arxiv within this month, I can ping you in this issue once it is (together with example replication code).

**Comment by ginward** [comment]
Ok thanks!

**Comment by ginward** [comment]
> Hi @ginward, `causal_survival_forest` only supports binary `W`. If you really want to get a forest based estimate for a continuous `W` you can do inverse probability of censoring weighting (IPCW) with `causal_forest`: estimate censoring probabilities P(Ci) with a `survival_forest`, then pass 1/P(Ci) to `causal_forest` using the `sample.weights` argument.
> 
> The latest causal survival paper draft has details on this, it will hopefully be uploaded to arxiv within this month, I can ping you in this issue once it is (together with example replication code).

Sorry, I have another follow-up question related to this issue. Because the survival forest prediction contains the predicted survival probabilities with different survival times, so when I generate P(Ci), which survival time am I expected to use?

**Comment by ginward** [comment]
Do i simply calculate the expected survival time ([similar to the function here](https://github.com/grf-labs/grf/blob/508397fa5ba21a9ae0b3d6035c905b6b8d2c15d1/r-package/grf/R/causal_survival_forest.R#L602)), and then take the inverse of that as the weight to the sample.weights input to the average_treatment_effect function? @erikcs

**Comment by erikcs** [comment]
Hi @ginward, see section 2.2 in https://arxiv.org/pdf/2001.09887.pdf for a description and https://github.com/grf-labs/grf/blob/master/experiments/csf/comparison_estimators.R#L68 for an example

**Comment by ginward** [comment]
> Hi @ginward, see section 2.2 in https://arxiv.org/pdf/2001.09887.pdf for a description and https://github.com/grf-labs/grf/blob/master/experiments/csf/comparison_estimators.R#L68 for an example

Thanks @erikcs 

In [this line](https://github.com/grf-labs/grf/blob/a3382b9af5e35414c7a0478e8e928c578b89d517/experiments/csf/comparison_estimators.R#L69), did you write 1` - data$D`, as in D is the event type `(0: censored, 1: failure)`? 

Did you effectively change the event type to `(1: censored, 0: failure)`, because you are estimating the probability of censoring, not the probability of failure?

**Comment by erikcs** [comment]
Yes, it is estimating (5) in https://arxiv.org/pdf/2001.09887.pdf

**Comment by ginward** [comment]
> Yes, it is estimating (5) in https://arxiv.org/pdf/2001.09887.pdf

I am sorry, I still don't get why [this line](https://github.com/grf-labs/grf/blob/a3382b9af5e35414c7a0478e8e928c578b89d517/experiments/csf/comparison_estimators.R#L69) writes it as `1 - data$D`. 

Equation (5) in the paper you were referring to seems to say that we are using the inverse weight of the probability of **not-censoring** to weight the causal forest estimates, which is equivalent to the probability of not-surviving, or the probability of failure. 

If we use `data$D` instead of `1 - data$D`, `predict` is already giving us the probability of failure. Why do we need to do `1 - data$D` then? @swager @erikcs

**Comment by ginward** [comment]
Or rather, is it because survival forests only give us the probability of survival time T>t, but what we want instead is the probability of T<t, and hence using `1 - data$D`?

**Comment by yifan-cui** [comment]
Hello @ginward, please see Eq (10) in the pdf. As we need to estimate $S_C$, we swap the censoring indicator to do so.

**Comment by ginward** [comment]
> Hello @ginward, please see Eq (10) in the pdf. As we need to estimate $S_C$, we swap the censoring indicator to do so.

I see. Thank you!
