### ISSUE TITLE
Statistical test between subset average treatment effects

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#871]
In the `average_treatment_effect` function, there is a `subset` parameter which you can set to estimate the ATE over the subsample. 

Suppose I have two subsamples, A and B, and two subsample treatment effects estimated, ATE_A and ATE_B. 

I was wondering if it is possible to perform a one-sided or two-sided p-test/t-test of ATE_A and ATE_B, so that I can compare the significance of their difference? 

Thanks!

**Comment by halflearned** [comment]
Hi @ginward. Assuming the definition of subsets A and B happened before you looked at the data, and that they are non-overlapping, this should work in large iid samples:
```{r}
cf <- causal_forest(X, Y, W)
ate.a <- average_treatment_effect(cf, subset = subset.A)
ate.b <- average_treatment_effect(cf, subset = subset.B)
ate.diff.t.stat <- (ate.a[1] - ate.b[1]) / sqrt(ate.a[2]^2 + ate.b[2]^2)
ate.diff.p.value <- 2*(1 - pnorm(abs(ate.diff.t.stat)))
```

**Comment by ginward** [comment]
Ok thanks!

**Comment by ginward** [comment]
> Hi @ginward. Assuming the definition of subsets A and B happened before you looked at the data, and that they are non-overlapping, this should work in large iid samples:
> 
> ```r
> cf <- causal_forest(X, Y, W)
> ate.a <- average_treatment_effect(cf, subset = subset.A)
> ate.b <- average_treatment_effect(cf, subset = subset.B)
> ate.diff.t.stat <- (ate.a[1] - ate.b[1]) / sqrt(ate.a[2]^2 + ate.b[2]^2)
> ate.diff.p.value <- 2*(1 - pnorm(abs(ate.diff.t.stat)))  # two-sided
> ```

Does this mean that, when defining subsets, I am not supposed to use the covariates `X `used in `causal_forest(X, Y, W)`?  Otherwise the two samples won't be independent, right?

**Comment by halflearned** [comment]
Yes, that's correct. 

Closing this for now as the question seems to have been answered. Feel free to re-open if you have follow-up questions!

**Comment by lennartseizer** [comment]
Hi @halflearned ,

can you please elaborate on not to use the covariates X from casual_forest(Y,W,X) to define subsets in causal_average_effects()?

The vignette for this function reads "For valid statistical performance, the subset should be defined only using features Xi, not using the treatment Wi or the outcome Yi." https://grf-labs.github.io/grf/reference/average_treatment_effect.html

Thanks!
