### ISSUE TITLE
Use survival forest with survreg? 

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#877]
I was wondering if it is possible to substitute the survival forest predictions for the `Surv` object when using `survreg` in the `survival` package? 

Normally, you use the `survreg` as follows: 

```
library(survival)
data("aids", package = "JM")
data("aids.id", package = "JM")
fit_weib <- survreg(Surv(Time, death) ~ drug * gender, data = aids.id)

```

Since `Surv(Time, death)`, from my limited understanding, is similar to the `S(t,x)` object that survival forests estimate, I was wondering if it is possible to substitue the survival forest object somehow to the `survreg` regression?

**Comment by erikcs** [comment]
Hi @ginward, sorry I don't understand the question, `Surv(Y, death)` is just `survival`'s formula for right censored data, it's the same as the `(Y, D)` tuple in grf's `survival_forest`.

`S(t,x)` is the Kaplan-Meier curve estimated for sample x.

```R
n <- 100
p <- 5
X <- matrix(rnorm(n * p), n, p)
failure.time <- exp(0.5 * X[, 1]) * rexp(n)
censor.time <- 2 * rexp(n)
Y <- pmin(failure.time, censor.time)
D <- as.integer(failure.time <= censor.time)
sf <- survival_forest(X, Y, D, min.node.size = n) # min.node.size =n for no splits, i.e. survival curve not conditioning on x

sfit <- survival::survfit(survival::Surv(Y, D) ~ 1,  data = data.frame(Y, D))
plot(sfit$time, sfit$surv, type = "l")
# Same as (~ numerical compounding):
lines(sfit$time, predict(sf, X[1,,drop=F], failure.times = sfit$time)$predictions[,], col = "red")
```
