### ISSUE TITLE
How do I use the function average_treatment_effect() with subset to obtain CATE with test data set?

### ISSUE THREAD

**Issue by sssh307** [grf-labs/grf#883]
Hi! I am a newcomer for the package grf, which is very useful for my research! 

However, I do not how to use average_treatment_effect() with subset to get CATE with "test data set".

I read some issues and the paper "Estimating Treatment Effects with Causal Forests- An Application". However, it seems that the examples are just using the "whole" data set to get CATE with this function. 

If I subset the data (for example, named as df_test), this function cannot give me the estimation of CATE and its S.E. (but with errors), how could I solve this issue? THANKS!

**Comment by erikcs** [comment]
Hi @sssh307, `average_treatment_effect` does currently not take a `X.test` argument (existing issue: #129). 

If you just want to predict treatment effects at a new set of points `X.test`, you can call `predict(forest, X.test)`. A rough but simple estimate of the average effect over `X.test` could just average those predictions.

**Comment by erikcs** [comment]
Closing for now, please let us know if the suggested resolution is not clear.
