### ISSUE TITLE
Add support for parallelizing across multiple shards.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#90]
A user expressed interest in running an experiment involving ~20 million samples and ~100 features. We should consider supporting growing trees + predicting across multiple machines, likely by splitting the data across these shards.

**Comment by halflearned** [comment]
We now have some support for this functionality via `merge_forests`. This is explained in the ([docs](https://github.com/grf-labs/grf/blob/master/REFERENCE.md#merging-forests)). Closing this for now, re-open as appropriate.
