### ISSUE TITLE
Causal forest always fits even number of trees

### ISSUE THREAD

**Issue by pbrehill** [grf-labs/grf#908]
I have noticed that when I set `num.trees` to an odd number, the number of trees fitted by `causal_forest()` is rounded up by one to the nearest even number. I'm currently looking to fit additional trees one at a time in order to evaluate the effect of a marginal tree (i.e. a forest with one tree so I can use `merge_forests()`. I am relatively new to the package so there might be a theoretical reason for this that I'm missing (and I can just increment by two trees at a time if needed), but I can't find a reason for this behaviour in the documentation so I thought it was worth raising.

**Comment by erikcs** [comment]
The number of trees has to be an even number for variance estimates, you can disable this by setting [`ci.group.size=1`](https://grf-labs.github.io/grf/REFERENCE.html#variance-estimates).

**Comment by pbrehill** [comment]
Thanks for your help!
