### ISSUE TITLE
Prediction comparison 

### ISSUE THREAD

**Issue by zpunit331111111** [grf-labs/grf#915]
Hello, I used the GRF algorithm and the quantile random forests introduced by Meinshausen (2006) on the same set of input variables to estimate three percentiles 50th, 85th and 95th. The prediction error measured by MAPE showed that GRF performed better on 50th and 85th, but not on 95th. I tried tune the mtry parameter to get the best performance from both algorithms and then compare. For GRF, I tried both with and without honest sampling. Theoretically, I would expect the performance to be consistent, since GRF provide a better way to separate heterogeneity. I tried to explained this observation, but couldn’t figure out.

**Comment by erikcs** [comment]
Hi @zpunit331111111, it is very rare that some method A outperform all other methods on all kinds of data sets. See section 5 in https://arxiv.org/pdf/1610.01271.pdf: 
>  The purpose of this example is not to claim that our variant of quantile
regression forests built using gradient trees is always superior to the method of
Meinshausen (2006) that uses regression-based splitting to obtain the weights αi(x);
rather, we found that, our splitting rule is specifically sensitive to quantile shifts in
a way that regression splits are not—

**Comment by zpunit331111111** [comment]
Hi, I used the SAME data set to predict 50th, 85th and 95th percentile using Meinshausen’s method and QRF. I would expect the prediction accuracy for 50th wound be similar for these two methods and GRF started to show advantage on 85th and 95th. However, the results are quit the opposite. GRF has better predictions on 50th and 85th with the 50th has the highest accuracy. The 95th percentile has lower prediction accuracy than Meinshausen’s method. I am confused with the results since GRF should be more suitable to separate quantiles, and was trying to explain such results. 

Also, I did not quit get the sentence “rather, we found that, our splitting rule is specifically sensitive to quantile shifts in
a way that regression splits are not—”, especially what is quantile shifts mean? Thanks!

**Comment by halflearned** [comment]
As @erikcs pointed out, it's not the case that GRF should outperform other methods in every dataset. There doesn't seem to be something actionable here, so I'll close this issue for now, but  @zpunit331111111  please feel free to re-open if you have follow-up questions.
