### ISSUE TITLE
local linear forests (LLF) extrapolation

### ISSUE THREAD

**Issue by Shafi2016** [grf-labs/grf#931]
@swager I found, LLF performs pretty well on the data with extreme outlier, probably due to fitting local trend, compared to XGBoost, RF, and GBM. It is well known the decision tree-based models can not extrapolate i.e., to forecast beyond the maximum value of the data. What do you think about extrapolating with LLF? Can we reliably use it to forecast into the future.?

**Comment by rinafriedberg** [comment]
Hi @Shafi2016 , glad LLF is performing well on data with extreme outliers! In general, we cannot expect LLF to extrapolate well into the future; it should be considered as primarily an interpolation model. That said, it should do a good job of fitting predictions at the boundary of a dataset! If you're interested in forecasting models, I'd suggest to use other algorithms specifically designed for time-series data.

**Comment by Shafi2016** [comment]
@rinafriedberg  Thanks for the valuable input !!!
