### ISSUE TITLE
GATES with causal forest and bootstrapping?

### ISSUE THREAD

**Issue by robert702** [grf-labs/grf#955]
Hi everyone, I understand that the discussion in[ Chernozhukov et al ](https://arxiv.org/pdf/1712.04802.pdf) about GATES is based on a k-fold prediction, which is less natural than out-of-bag predictions, as discussed by swager [here](https://github.com/grf-labs/grf/issues/339).

But I am wondering if it is at all possible to use the grf package to implement Chernozhukov 's approach.

Specifically, suppose I take a say 100 bootstrap samples, and in each sample I train a causal forest, with 1000 trees, and for each of the 100 forests I calculate the average_tratment_effect for the subset of observations with tauhat> median(tau.hat). Then I take the average and standard deviation of the 100 estimates for the average_treatment effects to do inference on individuals with the largest predicted treatment effect.

This would obviously be computationally intensive, but I wonder if this is a valid way to implement the estimation procedure of Chernozhukov et.al. using the grf package.

**Comment by halflearned** [comment]
There's already a discussion about GATES (and CLAN) in #339, so closing this issue.
