### ISSUE TITLE
Regular tarball for development version (Windows)

### ISSUE THREAD

**Issue by beau2005** [grf-labs/grf#965]
Hi all,

would it be possible to regularly add a tarball (or link to one) to install the development version of grf on Windows? I managed to do this with the tarball provided in #838. Since not everyone has administrator privileges on their machines the solution https://grf-labs.github.io/grf/DEVELOPING.html#note-for-windows-users is not always helpful.

Thanks in advance!

**Comment by erikcs** [comment]
Hi @beau2005, here is tarball of the latest version [grf_1.2.0.0a77064b.tar.gz](https://github.com/grf-labs/grf/files/6488688/grf_1.2.0.0a77064b.tar.gz) (we don't anticipate automating tarball publishing for the small user base that do not have symlink write rights on their windows account)

**Comment by beau2005** [comment]
Thank you!
