### ISSUE TITLE
RCT with staggered treatment 

### ISSUE THREAD

**Issue by beau2005** [grf-labs/grf#973]
Hi all,

I am trying to train a causal forest on data from a randomised control trial field experiment, where there are two treatments and adoption was staggered. E.g. Person i joined the study at time t and was treated with binary treatment W at time t+10, whereas Person j joined at time t+5 and was treated with binary treatment V at time t+15.  

I would like to control for calendar date, day of study, and individual "fixed effects" as I would do in a standard fixed effects model. I understand that fixed effects is a concept that does not directly translate to causal forests, however, I have tried to train a causal forest where I one-hot encode the individual IDs as well as add the date and day of study as vectors in the feature matrix. I have also tried to reduce the feature dimension using the sufrep package. I have also tried residualising the outcome by regressing it on the three "fixed effect" dimensions. 

All these approaches do not yield the same estimated average treatment effect as estimated with the linear model, with quite large differences in some cases. Is this expected when comparing causal forests to reduced from fixed effects models?

If the effects should be similar (as I would intuitively/naively expect), what is the recommended approach for this type of problem?

Thanks in advance!

**Comment by swager** [comment]
Fixed effects models encode an invariance that adding a constant offset to the measurements for any given unit does not change the resulting inference about treatment effects. At least to me, the first thing I'd look to do in trying to generalize panel methods to a machine learning context is to make sure this invariance continues to hold.

One nice way to enforce this invariance is to redefine your outcomes. For example, if you have "pre" and "post" data for the same units, you could just redefine "post - pre" as your outcome and run a regular causal forest on that.

In contrast, I wouldn't recommend one-hot encoding the FEs. Forests aren't good at using sparse binary features, so the FEs are likely to just get ignored. The approach in sufrep is likely better, but still doesn't enforce the exact invariance you get from classical fixed effects modeling, so I wouldn't use it if canceling out unit offsets is key for controlling selection bias. (I'd be more likely to use sufrep if I wanted to develop a model that can capture and express heterogeneity across a categorical variable; and not just cancel it out.)

Finally -- regarding time, often it's OK to just include time as-is in the forest. This allows the forest to non-parametrically control for time via something that looks like a mixture of step functions, which is probably not too far from what one wants conceptually.

**Comment by beau2005** [comment]
Thank you very much for the detailed answer and apologies for the late reply!
