### ISSUE TITLE
average_treatment_effect gamma weighting

### ISSUE THREAD

**Issue by samkodes** [grf-labs/grf#996]
Not sure if this is a bug, or a problem with my understanding. I'm attempting to reproduce the AIPW CATE treatment effect algorithm as described in the documentation here [https://grf-labs.github.io/grf/articles/muhats.html].

I'm getting inconsistent results with the `average_treatment_effect` function, and after inspecting the code and removing this reweighting I've identified the issue as the following snippet:
`      gamma[control.idx] <- gamma.control.raw/sum(subset.weights[control.idx] * 
            gamma.control.raw) * sum(subset.weights)
        gamma[treated.idx] <- gamma.treated.raw/sum(subset.weights[treated.idx] * 
            gamma.treated.raw) * sum(subset.weights)`

Is this reweighting implied in the Athey/Wager paper cited in the docs, or is it justified for some other reason? It seems to me to be normalizing inappropriately but I'm not sure. 

Thanks for any clarification you can provide.

**Comment by erikcs** [comment]
Hi @samkodes, the `average_treatment_effect` has been revised in #723 for the upcoming 2.0 release and for a causal forest ATE you should get consistent results with the latest GRF version. For ATT and ATC `average_treatment_effect` still does renormalization.
