### ISSUE TITLE
can reduce model's size?

### ISSUE THREAD

**Issue by bianchenhao** [grf-labs/grf#997]
I trained a causual forest with 1 million * 115 samples, then I saved model with `saveRDS`. However, the model file's size is about 5G.When I predicted, reading modelfile and predicting needed 20G memory.

Is there any wan to reduce the size of model which can support forecast?
> grf_1.2.0

**Comment by erikcs** [comment]
Hi @bianchenhao, when predicting on a test set the entire the forest is copied (#187). This can be become very expensive on large datasets. At the moment we have no workaround, except to try out @crflynn's [Python wrapper](https://github.com/crflynn/skgrf) for GRF where this step is avoided. (Hopefully we will make improvements to forest sizes in the future, #746).

**Comment by erikcs** [comment]
You can also reduce the `num.trees` argument, the forest size scales roughly linearly with this.
