### ISSUE TITLE
Cannot install the development version 

### ISSUE THREAD

**Issue by NeveTong** [grf-labs/grf#998]
**Description of the bug**
Compilation error

**Steps to reproduce**
R version 4.0.2, 4.0.3, 4.0.5
R studio
the first time to install grf; install using local file grf_1.2.0_develop_121b94d.tar.gz
Linux system

**GRF version**
development

**Error message**
/usr/bin/ld.gold: error: src/commons/DefaultData.o:1:1: invalid character
/usr/bin/ld.gold: error: src/commons/Data.o:1:1: invalid character
/usr/bin/ld.gold: error: src/commons/SparseData.o:1:1: invalid character
/usr/bin/ld.gold: error: src/commons/utility.o:1:1: invalid character
/usr/bin/ld.gold: error: src/analysis/SplitFrequencyComputer.o:1:1: invalid character
/usr/bin/ld.gold: error: src/forest/ForestPredictor.o:1:1: invalid character
/usr/bin/ld.gold: error: src/forest/ForestTrainers.o:1:1: invalid character
/usr/bin/ld.gold: error: src/forest/ForestTrainer.o:1:1: invalid character
/usr/bin/ld.gold: error: src/forest/ForestOptions.o:1:1: invalid character
/usr/bin/ld.gold: error: src/forest/ForestPredictors.o:1:1: invalid character
/usr/bin/ld.gold: error: src/forest/Forest.o:1:1: invalid character
/usr/bin/ld.gold: error: src/relabeling/LLRegressionRelabelingStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/relabeling/NoopRelabelingStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/relabeling/CausalSurvivalRelabelingStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/relabeling/QuantileRelabelingStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/relabeling/CustomRelabelingStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/relabeling/InstrumentalRelabelingStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/sampling/RandomSampler.o:1:1: invalid character
/usr/bin/ld.gold: error: src/sampling/SamplingOptions.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/ObjectiveBayesDebiaser.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/PredictionValues.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/Prediction.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/InstrumentalPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/LLCausalPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/CausalSurvivalPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/ProbabilityPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/SurvivalPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/RegressionPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/LocalLinearPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/QuantilePredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/CustomPredictionStrategy.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/RegressionSplittingRule.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/SurvivalSplittingRule.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/ProbabilitySplittingRule.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/InstrumentalSplittingRule.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/CausalSurvivalSplittingRule.o:1:1: invalid character
/usr/bin/ld.gold: error: src/tree/Tree.o:1:1: invalid character
/usr/bin/ld.gold: error: src/tree/TreeTrainer.o:1:1: invalid character
/usr/bin/ld.gold: error: src/tree/TreeOptions.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/collector/TreeTraverser.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/collector/DefaultPredictionCollector.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/collector/OptimizedPredictionCollector.o:1:1: invalid character
/usr/bin/ld.gold: error: src/prediction/collector/SampleWeightComputer.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/factory/InstrumentalSplittingRuleFactory.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/factory/CausalSurvivalSplittingRuleFactory.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/factory/RegressionSplittingRuleFactory.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/factory/SurvivalSplittingRuleFactory.o:1:1: invalid character
/usr/bin/ld.gold: error: src/splitting/factory/ProbabilitySplittingRuleFactory.o:1:1: invalid character
collect2: error: ld returned 1 exit status
make: *** [grf.so] Error 1
ERROR: compilation failed for package ‘grf’

**Comment by erikcs** [comment]
Hi @NeveTong, this looks like something that may be an issue with your custom [ld.gold](https://llvm.org/docs/GoldPlugin.html) linker, what happens if you tell Linux to use the default linker?

**Comment by erikcs** [comment]
Closing pending further info
