### ISSUE TITLE
Variance estimates for conditional mean estimates 

### ISSUE THREAD

**Issue by austindenteh** [grf-labs/grf#999]
This is a follow-up question based on @swager's comment on getting the conditional mean estimates: https://github.com/grf-labs/grf/pull/411#issuecomment-525582725. I understand that we can obtain conditional means, for instance, as described in the function `est_counterfactual_outcomes` based on https://github.com/grf-labs/grf/issues/403#issuecomment-486915981. However, how do we get variance estimates of these conditional means? Any help is much appreciated. Thanks for your time.

**Comment by erikcs** [comment]
Hi @austindenteh, sorry, this is currently not possible to do natively with GRF. FYI a brief vignette on just the conditional means is here: https://grf-labs.github.io/grf/articles/muhats.html
